# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.unit.docs.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".auditor_budgets_tests": ("TestLoadAuditBudgets",),
    ".auditor_docstring_tests": ("TestsDocstringCoverage",),
    ".auditor_links_tests": (
        "TestAuditorBrokenLinks",
        "TestAuditorToMarkdown",
    ),
    ".auditor_scope_tests": (
        "TestAuditorForbiddenTerms",
        "TestAuditorScope",
    ),
    ".auditor_tests": (
        "TestAuditorCore",
        "TestAuditorNormalize",
    ),
    ".builder_tests": ("TestBuilderCore",),
    ".render_tests": ("TestsDocsRenderExcludeDocs",),
    ".server_tests": ("TestsFlextInfraDocServer",),
    ".shared_iter_tests": (
        "TestIterMarkdownFiles",
        "TestSelectedProjectNames",
    ),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "TestAuditorBrokenLinks",
    "TestAuditorCore",
    "TestAuditorForbiddenTerms",
    "TestAuditorNormalize",
    "TestAuditorScope",
    "TestAuditorToMarkdown",
    "TestBuilderCore",
    "TestIterMarkdownFiles",
    "TestLoadAuditBudgets",
    "TestSelectedProjectNames",
    "TestsDocsRenderExcludeDocs",
    "TestsDocstringCoverage",
    "TestsFlextInfraDocServer",
    "auditor_cli_tests",
    "auditor_codeblocks_tests",
    "auditor_stale_symbols_tests",
    "builder_scope_tests",
    "c",
    "d",
    "e",
    "fixer_internals_tests",
    "fixer_tests",
    "generator_internals_tests",
    "generator_tests",
    "h",
    "m",
    "main_commands_tests",
    "main_entry_tests",
    "main_tests",
    "p",
    "r",
    "s",
    "shared_tests",
    "shared_write_tests",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "validator_internals_tests",
    "validator_tests",
    "x",
)
