# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.transformers.smells.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".base": (
        "FlextInfraSmellFixer",
        "auto_fixable_smell_tags",
        "register_smell_fixer",
        "smell_fixer_for",
    ),
    ".boolean_logic": ("FlextInfraBooleanLogicFixer",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraBooleanLogicFixer",
    "FlextInfraSmellFixer",
    "auto_fixable_smell_tags",
    "register_smell_fixer",
    "smell_fixer_for",
)
