"""Tests for FlextInfraWorkflowSyncer and SyncOperation.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from pathlib import Path

from flext_tests import tm

from flext_core import r
from flext_infra.github.workflows import FlextInfraWorkflowSyncer, SyncOperation
from tests.infra.unit.github._stubs import StubJsonIo, StubSelector, StubTemplates


def _syncer(
    selector: StubSelector | None = None,
    json_io: StubJsonIo | None = None,
    templates: StubTemplates | None = None,
) -> FlextInfraWorkflowSyncer:
    return FlextInfraWorkflowSyncer(
        selector=selector or StubSelector(),
        json_io=json_io or StubJsonIo(),
        templates=templates or StubTemplates(),
    )


class TestSyncOperation:
    """Test suite for SyncOperation data class."""

    def test_creation(self) -> None:
        op = SyncOperation(
            project="flext-core",
            path=".github/workflows/ci.yml",
            action="create",
            reason="New workflow file",
        )
        tm.that(op.project, eq="flext-core")
        tm.that(op.action, eq="create")

    def test_frozen(self) -> None:
        tm.that(SyncOperation.model_config.get("frozen"), eq=True)


class TestFlextInfraWorkflowSyncer:
    """Test suite for FlextInfraWorkflowSyncer."""

    def test_resolve_absolute_path(self, tmp_path: Path) -> None:
        wf = tmp_path / "source.yml"
        wf.write_text("name: CI")
        value = tm.ok(_syncer().resolve_source_workflow(tmp_path, wf))
        tm.that(str(value), eq=str(wf))

    def test_resolve_relative_path(self, tmp_path: Path) -> None:
        wf = tmp_path / "source.yml"
        wf.write_text("name: CI")
        value = tm.ok(_syncer().resolve_source_workflow(tmp_path, Path("source.yml")))
        tm.that(str(value), eq=str(wf))

    def test_resolve_not_found(self, tmp_path: Path) -> None:
        tm.fail(_syncer().resolve_source_workflow(tmp_path, Path("nonexistent.yml")))

    def test_default_initialization(self) -> None:
        syncer = FlextInfraWorkflowSyncer()
        tm.that(getattr(syncer, "_selector", None), none=False)
        tm.that(getattr(syncer, "_json", None), none=False)
        tm.that(getattr(syncer, "_templates", None), none=False)

    def test_resolve_default_source(self, tmp_path: Path) -> None:
        wf = tmp_path / ".github" / "workflows"
        wf.mkdir(parents=True)
        (wf / "ci.yml").write_text("name: CI")
        tm.ok(_syncer().resolve_source_workflow(tmp_path))

    def test_resolve_default_source_missing(self, tmp_path: Path) -> None:
        tm.fail(_syncer().resolve_source_workflow(tmp_path))


class TestRenderTemplate:
    """Test render_template method."""

    def test_adds_header(self, tmp_path: Path) -> None:
        t = tmp_path / "ci.yml"
        t.write_text("name: CI\n")
        value = tm.ok(_syncer().render_template(t))
        tm.that(value, starts="# GENERATED by")

    def test_already_has_header(self, tmp_path: Path) -> None:
        header = "# GENERATED by flext_infra.github.workflows\n"
        t = tmp_path / "ci.yml"
        t.write_text(header + "name: CI\n")
        value = tm.ok(_syncer().render_template(t))
        tm.that(value, starts=header)

    def test_read_failure(self, tmp_path: Path) -> None:
        tm.fail(_syncer().render_template(tmp_path / "nonexistent.yml"))


def _sync(
    root: Path,
    template: str,
    *,
    apply: bool = False,
    prune: bool = False,
) -> r[list[SyncOperation]]:
    """Helper to call sync_project with defaults."""
    return _syncer().sync_project(
        project_name="proj",
        project_root=root,
        rendered_template=template,
        apply=apply,
        prune=prune,
    )


class TestSyncProject:
    """Test sync_project method."""

    def test_update_existing(self, tmp_path: Path) -> None:
        proj, wf = tmp_path / "proj", tmp_path / "proj/.github/workflows"
        wf.mkdir(parents=True)
        (wf / "ci.yml").write_text("old content")
        ops = tm.ok(_sync(proj, "new content", apply=True))
        tm.that(len(ops), eq=1)
        tm.that(ops[0].action, eq="update")
        tm.that((wf / "ci.yml").read_text(), eq="new content")

    def test_noop_same_content(self, tmp_path: Path) -> None:
        proj, wf = tmp_path / "proj", tmp_path / "proj/.github/workflows"
        wf.mkdir(parents=True)
        (wf / "ci.yml").write_text("same content")
        ops = tm.ok(_sync(proj, "same content"))
        tm.that(ops[0].action, eq="noop")

    def test_create_missing(self, tmp_path: Path) -> None:
        proj = tmp_path / "proj"
        proj.mkdir()
        ops = tm.ok(_sync(proj, "new content", apply=True))
        tm.that(ops[0].action, eq="create")
        tm.that((proj / ".github" / "workflows" / "ci.yml").exists(), eq=True)

    def test_create_dry_run(self, tmp_path: Path) -> None:
        proj = tmp_path / "proj"
        proj.mkdir()
        ops = tm.ok(_sync(proj, "new content", apply=False))
        tm.that(ops[0].action, eq="create")
        tm.that((proj / ".github" / "workflows" / "ci.yml").exists(), eq=False)

    def test_prune_extra_workflows(self, tmp_path: Path) -> None:
        proj, wf = tmp_path / "proj", tmp_path / "proj/.github/workflows"
        wf.mkdir(parents=True)
        (wf / "ci.yml").write_text("content")
        (wf / "extra.yml").write_text("old")
        ops = tm.ok(_sync(proj, "content", apply=True, prune=True))
        tm.that([o.action for o in ops], has="prune")
        tm.that((wf / "extra.yml").exists(), eq=False)

    def test_prune_skips_managed(self, tmp_path: Path) -> None:
        proj, wf = tmp_path / "proj", tmp_path / "proj/.github/workflows"
        wf.mkdir(parents=True)
        (wf / "ci.yml").write_text("content")
        ops = tm.ok(_sync(proj, "content", apply=True, prune=True))
        tm.that(all(o.action != "prune" for o in ops), eq=True)

    def test_update_dry_run(self, tmp_path: Path) -> None:
        proj, wf = tmp_path / "proj", tmp_path / "proj/.github/workflows"
        wf.mkdir(parents=True)
        (wf / "ci.yml").write_text("old content")
        ops = tm.ok(_sync(proj, "new content", apply=False))
        tm.that(ops[0].action, eq="update")
        tm.that((wf / "ci.yml").read_text(), eq="old content")

    def test_sync_project_oserror(self, tmp_path: Path) -> None:
        """Test sync_project handles OSError via read-only directory."""
        proj, wf = tmp_path / "proj", tmp_path / "proj/.github/workflows"
        wf.mkdir(parents=True)
        wf.chmod(0o444)
        result = _sync(proj, "new content", apply=True)
        wf.chmod(0o755)
        tm.fail(result, has="sync error")
