"""Public direnv gate behavior: static contracts plus activation smoke."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_tests import tm

from flext_infra import c, m
from flext_infra.gates.direnv import FlextInfraDirenvGate
from flext_infra.workspace.environment_contracts import (
    FlextInfraWorkspaceEnvironmentContracts,
)
from tests import TestsFlextInfraUtilities as u

if TYPE_CHECKING:
    from pathlib import Path

    from tests import t


class TestsFlextInfraDirenvGate:
    @staticmethod
    def allowed_check(root: Path) -> m.Infra.GateExecution:
        """Check one workspace whose ``.envrc`` the real direnv approved."""
        allow = (c.Infra.CLI_DIRENV, "allow", str(root))
        tm.ok(u.Cli.run_checked(allow, cwd=root))
        execution = FlextInfraDirenvGate(root).check(root, u.Tests.gate_context(root))
        tm.ok(u.Cli.run_checked((c.Infra.CLI_DIRENV, "deny", str(root)), cwd=root))
        return execution

    @staticmethod
    def issue_codes(execution: m.Infra.GateExecution) -> t.StrSequence:
        """Return the issue codes one gate execution reported, in order."""
        return [issue.code for issue in execution.issues]

    class TestsDirenvContractLint:
        """Pure-lint contracts for managed environment files."""

        def test_unguarded_direnv_dir_reads_fail(self, tmp_path: Path) -> None:
            """strict_env does not export DIRENV_DIR; unguarded reads violate."""
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_contract_violations(
                    'checkout_root="${DIRENV_DIR#-}"\n'
                    'other="${DIRENV_DIR}"\n'
                    "bare=$DIRENV_DIR\n",
                    root=tmp_path,
                )
            )
            tm.that(len(violations), eq=3)

        def test_guarded_direnv_dir_reads_pass(self, tmp_path: Path) -> None:
            """Guarded reads keep working under strict_env."""
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_contract_violations(
                    'fallback="${DIRENV_DIR:-missing}"\noptional="${DIRENV_DIR-}"\n',
                    root=tmp_path,
                )
            )
            tm.that(violations, eq=())

        def test_missing_literal_target_fails(self, tmp_path: Path) -> None:
            """Literal source_env and watch_file targets must exist."""
            (tmp_path / "present.envrc").write_text("export OK=1\n", encoding="utf-8")
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_contract_violations(
                    'source_env "present.envrc"\nwatch_file "absent.envrc"\n',
                    root=tmp_path,
                )
            )
            tm.that(len(violations), eq=1)
            tm.that("absent.envrc" in violations[0], eq=True)

        def test_dynamic_targets_are_skipped(self, tmp_path: Path) -> None:
            """Runtime-derived targets cannot be validated statically."""
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_contract_violations(
                    'watch_file "$some_var/relstate.json"\n', root=tmp_path
                )
            )
            tm.that(violations, eq=())

        def test_home_targets_validated_only_when_resolving(
            self, tmp_path: Path
        ) -> None:
            """resolve_home=False skips $HOME targets (generation-time lint)."""
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_contract_violations(
                    'source_env "$HOME/.config/environment.d/projects/absent.envrc"\n',
                    root=tmp_path,
                    resolve_home=False,
                )
            )
            tm.that(violations, eq=())

        def test_home_targets_resolve_against_the_real_home(
            self, tmp_path: Path
        ) -> None:
            """resolve_home=True substitutes the real home for the prefix.

            Regression: the prefix used to be stripped without substitution,
            probing a bogus absolute path (``/.``) that never exists.
            """
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_contract_violations(
                    'source_env "$HOME"\n'
                    'watch_file "$HOME/.flext-infra-contract-absent-marker"\n',
                    root=tmp_path,
                )
            )
            tm.that(len(violations), eq=1)
            tm.that(".flext-infra-contract-absent-marker" in violations[0], eq=True)
            tm.that("/./" not in violations[0], eq=True)

    class TestsEnvrcLocalContracts:
        """Local overrides never carry generated activation residue."""

        stale_section = (
            "# Generated by `flext-infra codegen conform`.\n"
            "# === SECTION: Gas City Beads activation (managed) ===\n"
            "unset GT_ROOT\n"
            "# End SECTION: Gas City Beads activation\n"
        )

        def test_normalizer_keeps_custom_and_strips_generated(self) -> None:
            """Custom operator content survives; generated content is removed."""
            normalized = FlextInfraWorkspaceEnvironmentContracts.envrc_local_normalized(
                self.stale_section + "export CUSTOM_OVERRIDE=1\n"
            )
            tm.that(normalized, eq="export CUSTOM_OVERRIDE=1\n")

        def test_normalizer_removes_residue_only_file(self) -> None:
            """A file carrying only generated residue normalizes to empty."""
            normalized = FlextInfraWorkspaceEnvironmentContracts.envrc_local_normalized(
                self.stale_section
            )
            tm.that(normalized, eq="")

        def test_normalizer_removes_unterminated_section(self) -> None:
            """A truncated managed section never leaks its body."""
            normalized = FlextInfraWorkspaceEnvironmentContracts.envrc_local_normalized(
                "# === SECTION: Gas City Beads activation (managed) ===\n"
                "unset GT_ROOT\n"
                "export CUSTOM_OVERRIDE=1\n"
            )
            tm.that(normalized, eq="")

        def test_normalizer_keeps_clean_content_verbatim(self) -> None:
            """Already-clean overrides round-trip unchanged."""
            normalized = FlextInfraWorkspaceEnvironmentContracts.envrc_local_normalized(
                "export CUSTOM_OVERRIDE=1\nPATH_add bin\n"
            )
            tm.that(normalized, eq="export CUSTOM_OVERRIDE=1\nPATH_add bin\n")

        def test_violations_flag_activation_residue(self) -> None:
            """Markers and Beads variables are named per line."""
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_local_contract_violations(
                    self.stale_section + "export BEADS_DOLT_AUTO_START=0\n"
                )
            )
            tm.that(len(violations), eq=5)

        def test_clean_local_content_passes(self) -> None:
            """Custom overrides carry no violations."""
            violations = (
                FlextInfraWorkspaceEnvironmentContracts.envrc_local_contract_violations(
                    "export CUSTOM_OVERRIDE=1\nPATH_add bin\n"
                )
            )
            tm.that(violations, eq=())

        def test_gate_fails_on_local_residue(self, tmp_path: Path) -> None:
            """The direnv gate fails a workspace whose overrides carry residue."""
            _ = (tmp_path / c.Infra.ENVRC_FILENAME).write_text(
                "export OK=1\n", encoding="utf-8"
            )
            _ = (tmp_path / c.Infra.ENVRC_LOCAL_RELPATH).write_text(
                self.stale_section, encoding="utf-8"
            )
            execution = FlextInfraDirenvGate(tmp_path).check(
                tmp_path, u.Tests.gate_context(tmp_path)
            )
            tm.that(execution.result.passed, eq=False)
            tm.that(
                set(TestsFlextInfraDirenvGate.issue_codes(execution)),
                eq={"DIRENV_CONTRACT"},
            )

        def test_gate_passes_clean_local_overrides(self, tmp_path: Path) -> None:
            """Clean local overrides keep the gate green."""
            _ = (tmp_path / c.Infra.ENVRC_FILENAME).write_text(
                "export OK=1\n", encoding="utf-8"
            )
            _ = (tmp_path / c.Infra.ENVRC_LOCAL_RELPATH).write_text(
                "export CUSTOM_OVERRIDE=1\n", encoding="utf-8"
            )
            execution = TestsFlextInfraDirenvGate.allowed_check(tmp_path)
            tm.that(execution.result.passed, eq=True)

    class TestsDirenvGate:
        """Fail-closed gate behavior over the two enforcement stages."""

        def test_workspace_without_envrc_cannot_pass(self, tmp_path: Path) -> None:
            """A selected gate with no inputs cannot establish acceptance."""
            execution = FlextInfraDirenvGate(tmp_path).check(
                tmp_path, u.Tests.gate_context(tmp_path)
            )
            tm.that(execution.result.passed, eq=False)
            tm.that(
                execution.result.errors, eq=["direnv: no check targets were collected"]
            )

        def test_contract_violation_fails_before_smoke(self, tmp_path: Path) -> None:
            """The static lint fails the gate before the unapproved smoke runs."""
            _ = (tmp_path / c.Infra.ENVRC_FILENAME).write_text(
                'checkout_root="${DIRENV_DIR#-}"\n', encoding="utf-8"
            )
            execution = FlextInfraDirenvGate(tmp_path).check(
                tmp_path, u.Tests.gate_context(tmp_path)
            )
            tm.that(execution.result.passed, eq=False)
            tm.that(
                TestsFlextInfraDirenvGate.issue_codes(execution), eq=["DIRENV_CONTRACT"]
            )

        def test_activation_smoke_passes(self, tmp_path: Path) -> None:
            """An approved clean envrc passes through a real direnv exec."""
            _ = (tmp_path / c.Infra.ENVRC_FILENAME).write_text(
                "export OK=1\n", encoding="utf-8"
            )
            execution = TestsFlextInfraDirenvGate.allowed_check(tmp_path)
            tm.that(execution.result.passed, eq=True)
            tm.that(execution.issues, eq=())

        def test_activation_smoke_fails_loud(self, tmp_path: Path) -> None:
            """An unapproved envrc fails real activation with direnv's own error."""
            _ = (tmp_path / c.Infra.ENVRC_FILENAME).write_text(
                "export OK=1\n", encoding="utf-8"
            )
            execution = FlextInfraDirenvGate(tmp_path).check(
                tmp_path, u.Tests.gate_context(tmp_path)
            )
            tm.that(execution.result.passed, eq=False)
            tm.that(
                TestsFlextInfraDirenvGate.issue_codes(execution), eq=["DIRENV_ACTIVATE"]
            )
            tm.that(execution.issues[0].message, ne="")



