# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.unit.refactor.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".test_declarative_enforcement": (
        "TestsFlextInfraRefactorDeclarativeEnforcement",
        "TestsFlextInfraRefactorDeclarativeEnforcementInCensus",
    ),
    ".test_infra_refactor_census_preview_cache": (
        "TestsFlextInfraRefactorCensusPreviewCache",
    ),
    ".test_infra_refactor_class_and_propagation": (
        "TestsFlextInfraRefactorInfraRefactorClassAndPropagation",
    ),
    ".test_infra_refactor_class_placement": (
        "TestsFlextInfraRefactorInfraRefactorClassPlacement",
    ),
    ".test_infra_refactor_cli_models_workflow": (
        "TestsFlextInfraRefactorInfraRefactorCliModelsWorkflow",
    ),
    ".test_infra_refactor_import_modernizer": (
        "TestsFlextInfraRefactorInfraRefactorImportModernizer",
    ),
    ".test_infra_refactor_legacy_and_annotations": (
        "TestsFlextInfraRefactorInfraRefactorLegacyAndAnnotations",
    ),
    ".test_infra_refactor_migrate_to_class_mro": (
        "TestsFlextInfraRefactorInfraRefactorMigrateToClassMro",
    ),
    ".test_infra_refactor_mro_completeness": (
        "TestsFlextInfraRefactorInfraRefactorMroCompleteness",
    ),
    ".test_infra_refactor_mro_shape": ("TestsFlextInfraRefactorInfraRefactorMroShape",),
    ".test_infra_refactor_namespace_aliases": (
        "TestsFlextInfraRefactorInfraRefactorNamespaceAliases",
    ),
    ".test_infra_refactor_namespace_enforcer": (
        "TestsFlextInfraRefactorInfraRefactorNamespaceEnforcer",
    ),
    ".test_infra_refactor_namespace_moves": (
        "TestsFlextInfraRefactorInfraRefactorNamespaceMoves",
    ),
    ".test_infra_refactor_pattern_corrections": (
        "TestsFlextInfraRefactorInfraRefactorPatternCorrections",
    ),
    ".test_infra_refactor_policy_family_rules": (
        "TestsFlextInfraRefactorInfraRefactorPolicyFamilyRules",
    ),
    ".test_infra_refactor_project_classifier": (
        "TestsFlextInfraRefactorInfraRefactorProjectClassifier",
    ),
    ".test_infra_refactor_safety": (
        "RefactorSafetyStub",
        "TestsFlextInfraRefactorInfraRefactorSafety",
    ),
    ".test_infra_refactor_service": ("TestsFlextInfraRefactorInfraRefactorService",),
    ".test_infra_refactor_typing_unifier": (
        "FlextInfraRefactorTypingUnificationRule",
        "TestsFlextInfraRefactorInfraRefactorTypingUnifier",
    ),
    ".test_main_cli": ("TestsFlextInfraRefactorMainCli",),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraRefactorTypingUnificationRule",
    "RefactorSafetyStub",
    "TestsFlextInfraRefactorCensusPreviewCache",
    "TestsFlextInfraRefactorDeclarativeEnforcement",
    "TestsFlextInfraRefactorDeclarativeEnforcementInCensus",
    "TestsFlextInfraRefactorInfraRefactorClassAndPropagation",
    "TestsFlextInfraRefactorInfraRefactorClassPlacement",
    "TestsFlextInfraRefactorInfraRefactorCliModelsWorkflow",
    "TestsFlextInfraRefactorInfraRefactorImportModernizer",
    "TestsFlextInfraRefactorInfraRefactorLegacyAndAnnotations",
    "TestsFlextInfraRefactorInfraRefactorMigrateToClassMro",
    "TestsFlextInfraRefactorInfraRefactorMroCompleteness",
    "TestsFlextInfraRefactorInfraRefactorMroShape",
    "TestsFlextInfraRefactorInfraRefactorNamespaceAliases",
    "TestsFlextInfraRefactorInfraRefactorNamespaceEnforcer",
    "TestsFlextInfraRefactorInfraRefactorNamespaceMoves",
    "TestsFlextInfraRefactorInfraRefactorPatternCorrections",
    "TestsFlextInfraRefactorInfraRefactorPolicyFamilyRules",
    "TestsFlextInfraRefactorInfraRefactorProjectClassifier",
    "TestsFlextInfraRefactorInfraRefactorSafety",
    "TestsFlextInfraRefactorInfraRefactorService",
    "TestsFlextInfraRefactorInfraRefactorTypingUnifier",
    "TestsFlextInfraRefactorMainCli",
    "c",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "t",
    "td",
    "test_infra_refactor_mro_import_rewriter",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
