# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.unit._utilities.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".test_discovery_consolidated": ("TestsFlextInfraUtilitiesdiscoveryconsolidated",),
    ".test_formatting": ("TestsFlextInfraUtilitiesformatting",),
    ".test_protected_edit": ("TestsFlextInfraUtilitiesProtectedEdit",),
    ".test_rope_analysis": ("TestsFlextInfraRopeAnalysis",),
    ".test_rope_hooks": ("TestsFlextInfraUtilitiesRopeHooks",),
    ".test_safety": ("TestsFlextInfraUtilitiessafety",),
    ".test_scanning": ("TestsFlextInfraUtilitiesscanning",),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "TestsFlextInfraRopeAnalysis",
    "TestsFlextInfraUtilitiesProtectedEdit",
    "TestsFlextInfraUtilitiesRopeHooks",
    "TestsFlextInfraUtilitiesdiscoveryconsolidated",
    "TestsFlextInfraUtilitiesformatting",
    "TestsFlextInfraUtilitiessafety",
    "TestsFlextInfraUtilitiesscanning",
    "c",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
