"""Project Makefile generator for workspace sync.

Fully generates project Makefiles from pyproject.toml metadata and the
base bootstrap template. Custom targets live in ``custom.mk`` alongside
the generated ``Makefile``.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import hashlib
import tomllib
from pathlib import Path
from typing import NamedTuple

from flext_infra import FlextInfraBaseMkGenerator, c, r, u


class _ProjectMeta(NamedTuple):
    """Extracted project metadata from pyproject.toml."""

    name: str
    python_version: str
    description: str


class FlextInfraProjectMakefileUpdater:
    """Fully generate project Makefiles from pyproject.toml metadata.

    The generated ``Makefile`` is 100% managed — do not edit it.  Put any
    project-specific Make targets in ``custom.mk`` next to the ``Makefile``;
    it is automatically included via ``-include custom.mk`` at the end.

    Idempotency:
      - SHA-256 comparison skips the write if the generated content is
        identical to the file already on disk.
    """

    def update(self, project_root: Path, *, canonical_root: Path) -> r[bool]:
        """Regenerate project Makefile from pyproject.toml.

        Args:
            project_root: Root directory of the project.
            canonical_root: Workspace canonical root (reserved for future use).

        Returns:
            r with True if Makefile was written, False if unchanged,
            failure with error message on I/O or parse error.

        """
        _ = canonical_root  # reserved for future cross-project dependency resolution
        pyproject = project_root / c.Infra.Files.PYPROJECT_FILENAME
        if not pyproject.exists():
            return r[bool].ok(False)

        meta_result = self._read_pyproject(pyproject)
        if meta_result.is_failure:
            return r[bool].fail(meta_result.error or "pyproject.toml parse failed")
        meta = meta_result.value

        bootstrap_result = FlextInfraBaseMkGenerator.render_bootstrap_include()
        if bootstrap_result.is_failure:
            return r[bool].fail(
                bootstrap_result.error or "bootstrap template read failed",
            )
        bootstrap = bootstrap_result.value

        new_content = self._build_makefile(meta, bootstrap)
        makefile_path = project_root / c.Infra.Files.MAKEFILE_FILENAME

        if makefile_path.exists():
            try:
                existing = makefile_path.read_text(encoding=c.Infra.Encoding.DEFAULT)
            except OSError as exc:
                return r[bool].fail(f"Makefile read failed: {exc}")

            existing_hash = hashlib.sha256(
                existing.encode(c.Infra.Encoding.DEFAULT)
            ).hexdigest()
            new_hash = hashlib.sha256(
                new_content.encode(c.Infra.Encoding.DEFAULT)
            ).hexdigest()
            if existing_hash == new_hash:
                return r[bool].ok(False)

        return u.Infra.atomic_write_file(makefile_path, new_content)

    @staticmethod
    def _read_pyproject(pyproject: Path) -> r[_ProjectMeta]:
        """Parse pyproject.toml and extract name, python_version, description."""
        try:
            with pyproject.open("rb") as fh:
                data = tomllib.load(fh)
        except (OSError, tomllib.TOMLDecodeError) as exc:
            return r[_ProjectMeta].fail(f"pyproject.toml read failed: {exc}")

        try:
            project = data["project"]
            name: str = project["name"]
            requires_python: str = project.get("requires-python", ">=3.13")
            # Extract "3.13" from ">=3.13,<3.14" or ">=3.13"
            version_str = requires_python.lstrip(">= ")
            python_version = version_str.split(",")[0].split("<")[0].strip()
            description: str = project.get("description", "")
        except (KeyError, AttributeError) as exc:
            return r[_ProjectMeta].fail(
                f"pyproject.toml missing required fields: {exc}",
            )

        return r[_ProjectMeta].ok(
            _ProjectMeta(
                name=name,
                python_version=python_version,
                description=description,
            ),
        )

    @staticmethod
    def _build_makefile(meta: _ProjectMeta, bootstrap: str) -> str:
        """Build the fully-generated Makefile content."""
        title = f"# {meta.name}"
        if meta.description:
            title += f" - {meta.description}"
        sep = "# " + "=" * 77
        lines = [
            sep,
            title,
            sep,
            "# @generated by: flext_infra workspace sync",
            "# Run 'make sync' from workspace root to regenerate this file.",
            "# DO NOT EDIT — put custom targets in custom.mk instead.",
            sep,
            "",
            f"PROJECT_NAME := {meta.name}",
            f"PYTHON_VERSION ?= {meta.python_version}",
            f"SRC_DIR ?= {c.Infra.Paths.DEFAULT_SRC_DIR}",
            f"TESTS_DIR ?= {c.Infra.Directories.TESTS}",
            bootstrap,
            "",
            "# Project-specific targets (optional, never overwritten by sync)",
            "-include custom.mk",
        ]
        return "\n".join(lines) + "\n"


__all__ = ["FlextInfraProjectMakefileUpdater"]
