"""Project Makefile generator for workspace sync.

Fully generates project Makefiles from pyproject.toml metadata and the
base bootstrap template. Custom targets live in ``custom.mk`` alongside
the generated ``Makefile``.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from pathlib import Path

from flext_infra import (
    FlextInfraBaseMkTemplateEngine,
    c,
    m,
    p,
    r,
    u,
)


class FlextInfraProjectMakefileUpdater:
    """Fully generate project Makefiles from pyproject.toml metadata.

    The generated ``Makefile`` is 100% managed — do not edit it.  Put any
    project-specific Make targets in ``custom.mk`` next to the ``Makefile``;
    it is automatically included via ``-include custom.mk`` at the end.

    Idempotency:
      - SHA-256 comparison skips the write if the generated content is
        identical to the file already on disk.
    """

    def update(self, project_root: Path, *, canonical_root: Path) -> p.Result[bool]:
        """Regenerate project Makefile from pyproject.toml.

        Args:
            project_root: Root directory of the project.
            canonical_root: Workspace canonical root (reserved for future use).

        Returns:
            r with True if Makefile was written, False if unchanged,
            failure with error message on I/O or parse error.

        """
        _ = canonical_root  # reserved for future cross-project dependency resolution
        pyproject = project_root / c.Infra.PYPROJECT_FILENAME
        if not pyproject.exists():
            return r[bool].ok(False)

        try:
            meta = u.read_project_metadata(project_root)
        except (FileNotFoundError, ValueError) as exc:
            return r[bool].fail(f"pyproject.toml parse failed: {exc}")

        bootstrap_result = FlextInfraBaseMkTemplateEngine.render_bootstrap_include()
        if bootstrap_result.failure:
            return r[bool].fail(
                bootstrap_result.error or "bootstrap template read failed",
            )
        bootstrap = bootstrap_result.value

        new_content = self._build_makefile(meta, bootstrap)
        makefile_path = project_root / c.Infra.MAKEFILE_FILENAME

        if makefile_path.exists():
            try:
                existing = makefile_path.read_text(encoding=c.Infra.ENCODING_DEFAULT)
            except OSError as exc:
                return r[bool].fail(f"Makefile read failed: {exc}")

            if u.Cli.sha256_content(existing) == u.Cli.sha256_content(new_content):
                return r[bool].ok(False)

        return u.Cli.atomic_write_text_file(makefile_path, new_content)

    @staticmethod
    def _build_makefile(meta: m.ProjectMetadata, bootstrap: str) -> str:
        """Build the fully-generated Makefile content."""
        title = f"# {meta.name}"
        if meta.description:
            title += f" - {meta.description}"
        sep = "# " + "=" * 77
        lines = [
            sep,
            title,
            sep,
            "# @generated by: flext_infra workspace sync",
            "# Run 'make sync' from workspace root to regenerate this file.",
            "# DO NOT EDIT — put custom targets in custom.mk instead.",
            sep,
            "",
            f"PROJECT_NAME := {meta.name}",
            f"PYTHON_VERSION ?= {meta.requires_python}",
            f"SRC_DIR ?= {c.Infra.DEFAULT_SRC_DIR}",
            f"TESTS_DIR ?= {c.Infra.DIR_TESTS}",
            bootstrap,
            "",
            "# Project-specific targets (optional, never overwritten by sync)",
            "-include custom.mk",
        ]
        return "\n".join(lines) + "\n"


__all__: list[str] = ["FlextInfraProjectMakefileUpdater"]
