"""Workspace root Makefile generator.

Manages the root ``Makefile`` in a FLEXT workspace.  The file is
100% generated from a Jinja2 template stored inside ``flext_infra``.
Custom workspace targets go in ``workspace_custom.mk`` (auto-included).

Bootstrap flow (first run, no template yet):
  - Reads the current ``Makefile`` and registers it as the canonical template.
  - Adds ``@generated`` header and ``-include workspace_custom.mk``.
  - Parameterises ``PR_BRANCH`` from the current git branch.

Subsequent runs:
  - Reads the stored template, renders ``{{ pr_branch }}``.
  - SHA-256 idempotency skips writes when content is unchanged.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import hashlib
import tomllib
from collections.abc import MutableSequence
from pathlib import Path

from flext_infra import FlextInfraUtilitiesSubprocess, c, r, u

_TEMPLATE_NAME = "workspace_makefile.mk.j2"
_GENERATED_MARKER = "# @generated by: flext_infra workspace sync"
_CUSTOM_INCLUDE = "-include workspace_custom.mk"

# Relative path from this file to the templates directory
_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"


class FlextInfraWorkspaceMakefileGenerator:
    """Generate and keep the workspace root Makefile in sync with flext_infra.

    The canonical source of truth is
    ``flext_infra/templates/workspace_makefile.mk.j2``.  Edit that file
    to change workspace-level verbs; then run ``make sync`` to propagate.
    """

    @property
    def template_path(self) -> Path:
        """Path to the Makefile Jinja2 template used for workspace generation."""
        return _TEMPLATES_DIR / _TEMPLATE_NAME

    def generate(self, workspace_root: Path) -> r[bool]:
        """Regenerate the workspace root Makefile from the stored template.

        Args:
            workspace_root: Path to the workspace root (contains Makefile).

        Returns:
            r with True if Makefile was written, False if unchanged,
            failure on I/O error.

        """
        makefile = workspace_root / "Makefile"

        if not self.template_path.exists():
            return self._bootstrap_template(makefile)

        try:
            template_text = self.template_path.read_text(
                encoding=c.Infra.Encoding.DEFAULT
            )
        except OSError as exc:
            return r[bool].fail(f"template read failed: {exc}")

        pr_branch = self._current_branch(workspace_root)
        content = template_text.replace("{{ pr_branch }}", pr_branch)

        if makefile.exists():
            try:
                existing = makefile.read_text(encoding=c.Infra.Encoding.DEFAULT)
            except OSError as exc:
                return r[bool].fail(f"Makefile read failed: {exc}")
            if (
                hashlib.sha256(existing.encode(c.Infra.Encoding.DEFAULT)).hexdigest()
                == hashlib.sha256(content.encode(c.Infra.Encoding.DEFAULT)).hexdigest()
            ):
                return r[bool].ok(False)

        return self._atomic_write(makefile, content)

    def _bootstrap_template(self, makefile: Path) -> r[bool]:
        """Create the template from the current Makefile (one-time bootstrap)."""
        if not makefile.exists():
            return r[bool].ok(False)

        try:
            content = makefile.read_text(encoding=c.Infra.Encoding.DEFAULT)
        except OSError as exc:
            return r[bool].fail(f"Makefile read failed: {exc}")

        # Skip if already generated (avoid re-bootstrapping)
        if _GENERATED_MARKER in content:
            return r[bool].ok(False)

        pr_branch = self._current_branch(makefile.parent)

        # Build template: replace header, parameterise PR_BRANCH, add custom include
        lines = content.splitlines(keepends=True)
        out: MutableSequence[str] = []
        header_done = False
        custom_include_done = _CUSTOM_INCLUDE in content

        for line in lines:
            # Replace first non-comment/non-empty block with @generated header
            if not header_done and line.startswith("#"):
                out.extend((
                    "# =============================================================================\n",
                    "# FLEXT Workspace Makefile\n",
                    "# =============================================================================\n",
                    f"{_GENERATED_MARKER}\n",
                    "# Run 'make sync' from workspace root to regenerate this file.\n",
                    "# DO NOT EDIT — put custom targets in workspace_custom.mk instead.\n",
                    "# =============================================================================\n",
                ))
                # Skip original header lines
                header_done = True
                continue
            if not header_done and not line.strip():
                continue
            # Parameterise PR_BRANCH
            if line.startswith("PR_BRANCH ?="):
                out.append("PR_BRANCH ?= {{ pr_branch }}\n")
                continue
            out.append(line)

        template_content = "".join(out)

        # Append custom include if not already present
        if not custom_include_done:
            if not template_content.endswith("\n"):
                template_content += "\n"
            template_content += f"\n# Workspace-specific custom targets (optional, never overwritten by sync)\n{_CUSTOM_INCLUDE}\n"

        # Write template to flext_infra
        try:
            _TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
            template_write = self._atomic_write(self.template_path, template_content)
            if template_write.is_failure:
                return template_write
        except OSError as exc:
            return r[bool].fail(f"template bootstrap failed: {exc}")

        # Now generate the Makefile from the newly created template
        rendered = template_content.replace("{{ pr_branch }}", pr_branch)
        return self._atomic_write(makefile, rendered)

    @staticmethod
    def _current_branch(workspace_root: Path) -> str:
        """Return current git branch or version from pyproject.toml."""
        capture_result = FlextInfraUtilitiesSubprocess.capture(
            ["git", "-C", str(workspace_root), "rev-parse", "--abbrev-ref", "HEAD"],
            timeout=5,
        )
        if capture_result.is_success:
            branch = capture_result.value
            if branch and branch != "HEAD":
                return branch

        # Fallback: read version from pyproject.toml
        pyproject = workspace_root / "pyproject.toml"
        if pyproject.exists():
            try:
                with pyproject.open("rb") as fh:
                    data = tomllib.load(fh)
                version: str = data.get("project", {}).get("version", "main")
                return version
            except (OSError, tomllib.TOMLDecodeError, KeyError):
                pass
        return "main"

    @staticmethod
    def _atomic_write(target: Path, content: str) -> r[bool]:
        """Write content to target via atomic temp-file rename."""
        return u.Infra.atomic_write_file(target, content)


__all__ = ["FlextInfraWorkspaceMakefileGenerator"]
