# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.codegen.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".census": ("FlextInfraCodegenCensus",),
    ".codegen_generation": ("FlextInfraCodegenGeneration",),
    ".conform": ("FlextInfraCodegenConform",),
    ".consolidator": ("FlextInfraCodegenConsolidator",),
    ".constants_quality_gate": ("FlextInfraCodegenQualityGate",),
    ".fixer": ("FlextInfraCodegenFixer",),
    ".lazy_init": ("FlextInfraCodegenLazyInit",),
    ".lazy_init_planner": ("FlextInfraCodegenLazyInitPlanner",),
    ".pipeline": ("FlextInfraCodegenPipeline",),
    ".project_new": ("FlextInfraCodegenProjectNew",),
    ".py_typed": ("FlextInfraCodegenPyTyped",),
    ".scaffolder": ("FlextInfraCodegenScaffolder",),
    ".version_file": ("FlextInfraCodegenVersionFile",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraCodegenCensus",
    "FlextInfraCodegenConform",
    "FlextInfraCodegenConsolidator",
    "FlextInfraCodegenFixer",
    "FlextInfraCodegenGeneration",
    "FlextInfraCodegenLazyInit",
    "FlextInfraCodegenLazyInitPlanner",
    "FlextInfraCodegenPipeline",
    "FlextInfraCodegenProjectNew",
    "FlextInfraCodegenPyTyped",
    "FlextInfraCodegenQualityGate",
    "FlextInfraCodegenScaffolder",
    "FlextInfraCodegenVersionFile",
)
