"""Package/module entry and name-resolution caches for the lazy-init planner."""

from __future__ import annotations

from collections.abc import MutableMapping
from typing import TYPE_CHECKING

from flext_infra import c, m, u

if TYPE_CHECKING:
    from pathlib import Path

    from flext_infra import p, t


class FlextInfraCodegenLazyInitPlannerCacheMixin:
    if TYPE_CHECKING:
        rope_workspace: p.Infra.RopeWorkspaceDsl
        _package_exports_cache: MutableMapping[str, frozenset[str]]
        _source_exports_cache: MutableMapping[str, frozenset[str]]
        _source_plan_cache: MutableMapping[str, m.Infra.LazyInitPlan]
        _module_file_by_name: MutableMapping[str, Path]

        def build_plan(
            self, pkg_dir: Path, *, dir_exports: t.MappingKV[str, t.LazyAliasMap]
        ) -> m.Infra.LazyInitPlan: ...

    def _export_names_for_package(self, package_name: str) -> frozenset[str]:
        """Return all export names for a package (init + source plans)."""
        cached = self._package_exports_cache.get(package_name)
        if cached is not None:
            return cached
        exports = frozenset((
            *self._package_init_exports(package_name),
            *self._source_export_names_for_package(package_name),
        ))
        self._package_exports_cache[package_name] = exports
        return exports

    def _package_init_exports(self, package_name: str) -> frozenset[str]:
        """Return names exported from the package __init__.py."""
        index = self.rope_workspace.workspace_index
        package_dir = index.package_dir_by_name.get(package_name)
        if package_dir is not None:
            init_path = package_dir / c.Infra.INIT_PY
            if self.rope_workspace.resource(init_path) is None:
                return frozenset()
            if init_path.read_text(encoding=c.Cli.ENCODING_DEFAULT).startswith(
                c.Infra.AUTOGEN_HEADERS
            ):
                return frozenset()
            return frozenset(
                self.rope_workspace.exports(
                    init_path,
                    export_options=m.Infra.ExportOptions(allow_assignments=True),
                )
            )
        # Why (flext-b3xmn/R32): a parent outside the scan scope is read by
        # path from the one package the active environment declares; a name
        # that resolves nowhere raises in the resolver. A module (not a
        # package) can never have been accepted as a facade parent.
        package_dir = u.Infra.declared_package_dir(package_name)
        if package_dir is None:
            msg = (
                f"lazy-init facade parent '{package_name}' resolves to a module,"
                " not a package, in the active environment"
            )
            raise ValueError(msg)
        init_path = package_dir / c.Infra.INIT_PY
        if not init_path.is_file():
            return frozenset()
        # An external parent's generated __init__ is its published ABI (it is
        # not regenerated by this run), so its export manifest is read as-is.
        source = init_path.read_text(encoding=c.Cli.ENCODING_DEFAULT)
        return frozenset(u.Infra.public_export_names_source(source))

    def _source_export_names_for_package(self, package_name: str) -> frozenset[str]:
        """Return a package's published export names, read from disk.

        This answers one question for the alias resolver: which names does this
        package publish? It is deliberately disk-bound. Planning the package to
        answer it re-entered the walker with an empty export accumulator, so the
        plan it produced described a package with no children — and that plan,
        or the names taken from it, then stood in for the real one. The scan
        collapsed from 624 names to 49 whenever alias inheritance was active,
        which is what made the inherited facade letters look impossible to
        restore and got them prohibited instead of repaired.

        The published initializer is the right source: it is what an importer
        actually sees, this run does not regenerate the package being probed,
        and reading it costs nothing and cannot recurse.
        """
        cached = self._source_exports_cache.get(package_name)
        if cached is not None:
            return cached
        package_dir = self.rope_workspace.workspace_index.package_dir_by_name.get(
            package_name
        )
        if package_dir is None:
            return frozenset()
        init_path = package_dir / c.Infra.INIT_PY
        if not init_path.is_file():
            return frozenset()
        source = init_path.read_text(encoding=c.Cli.ENCODING_DEFAULT)
        exports = frozenset(u.Infra.public_export_names_source(source))
        self._source_exports_cache[package_name] = exports
        return exports

    def _source_package_name(self, pkg_dir: Path, inherited_key: str) -> str:
        """Return the project-root package name for the given directory."""
        if inherited_key == "src":
            return ""
        package_entry = self._package_entry(pkg_dir)
        if package_entry is None or package_entry.project_root is None:
            return ""
        project_pkg: str = (
            self.rope_workspace.workspace_index.project_package_by_root.get(
                str(package_entry.project_root), ""
            )
        )
        return project_pkg

    def _package_entry(self, pkg_dir: Path) -> m.Infra.RopePackageIndexEntry | None:
        """Return the workspace index entry for a package directory."""
        return self.rope_workspace.package(pkg_dir)

    def _module_file(self, module_path: str) -> Path | None:
        """Resolve a dotted module path to its source file (lazy index build)."""
        resolved = self._module_file_by_name.get(module_path)
        if resolved is not None:
            return resolved
        if not self._module_file_by_name:
            index = self.rope_workspace.workspace_index
            self._module_file_by_name = {
                entry.module_name: entry.file_path
                for entry in index.modules_by_path.values()
                if entry.module_name
            }
            resolved = self._module_file_by_name.get(module_path)
        return resolved
