# AUTO-GENERATED FILE — Regenerate with: make gen
"""Utilities package."""

from __future__ import annotations

from flext_core.lazy import build_lazy_import_map, install_lazy_exports

_LAZY_IMPORTS = build_lazy_import_map(
    {
        "._docs_audit_detectors": ("FlextInfraUtilitiesDocsAuditDetectorsMixin",),
        "._github_pr_single": ("FlextInfraUtilitiesGithubPrSingleMixin",),
        "._github_sync": ("FlextInfraUtilitiesGithubSyncMixin",),
        "._rope_bracket_balance": ("FlextInfraUtilitiesRopeBracketBalanceMixin",),
        "._rope_core_pymodule": ("FlextInfraUtilitiesRopeCorePyModuleMixin",),
        "._rope_method_order": ("FlextInfraUtilitiesRopeMethodOrderMixin",),
        ".base": ("FlextInfraUtilitiesBase",),
        ".census": ("FlextInfraUtilitiesRefactorCensus",),
        ".codegen": ("FlextInfraUtilitiesCodegen",),
        ".deps_path_sync": ("FlextInfraUtilitiesDependencyPathSync",),
        ".deps_repos": ("FlextInfraInternalSyncRepoMixin",),
        ".discovery": ("FlextInfraUtilitiesDiscovery",),
        ".docs": ("FlextInfraUtilitiesDocs",),
        ".docs_api": ("FlextInfraUtilitiesDocsApi",),
        ".docs_audit": ("FlextInfraUtilitiesDocsAudit",),
        ".docs_build": ("FlextInfraUtilitiesDocsBuild",),
        ".docs_contract": ("FlextInfraUtilitiesDocsContract",),
        ".docs_fix": ("FlextInfraUtilitiesDocsFix",),
        ".docs_generate": ("FlextInfraUtilitiesDocsGenerate",),
        ".docs_render": ("FlextInfraUtilitiesDocsRender",),
        ".docs_scope": ("FlextInfraUtilitiesDocsScope",),
        ".docs_validate": ("FlextInfraUtilitiesDocsValidate",),
        ".engine": ("FlextInfraUtilitiesRefactorEngine",),
        ".github": ("FlextInfraUtilitiesGithub",),
        ".github_pr": ("FlextInfraUtilitiesGithubPr",),
        ".dependencies": ("FlextInfraUtilitiesDependencies",),
        ".file_iteration": ("FlextInfraUtilitiesFileIteration",),
        ".git_scope": ("FlextInfraUtilitiesGitScope",),
        ".log_parser": ("FlextInfraUtilitiesLogParser",),
        ".namespace_config": ("FlextInfraUtilitiesNamespaceConfig",),
        ".project_discovery": ("FlextInfraUtilitiesProjectDiscovery",),
        ".pyproject": ("FlextInfraUtilitiesPyproject",),
        ".mro_scan": ("FlextInfraUtilitiesRefactorMroScan",),
        ".namespace": ("FlextInfraUtilitiesCodegenNamespace",),
        ".namespace_analysis": ("FlextInfraUtilitiesRefactorNamespaceMro",),
        ".namespace_common": ("FlextInfraUtilitiesRefactorNamespaceCommon",),
        ".namespace_facades": ("FlextInfraUtilitiesRefactorNamespaceFacades",),
        ".namespace_moves": ("FlextInfraUtilitiesRefactorNamespaceMoves",),
        ".policy": ("FlextInfraUtilitiesRefactorPolicy",),
        ".protected_edit": ("FlextInfraUtilitiesProtectedEdit",),
        ".protected_edit_apply": ("FlextInfraUtilitiesProtectedEditApply",),
        ".protected_edit_linting": ("FlextInfraUtilitiesProtectedEditLinting",),
        ".protected_edit_preview": ("FlextInfraUtilitiesProtectedEditPreview",),
        ".protected_edit_writes": ("FlextInfraUtilitiesProtectedEditWrites",),
        ".refactor": ("FlextInfraUtilitiesRefactor",),
        ".release": ("FlextInfraUtilitiesRelease",),
        ".rope_analysis": ("FlextInfraUtilitiesRopeAnalysis",),
        ".rope_analysis_introspection": (
            "FlextInfraUtilitiesRopeAnalysisIntrospection",
        ),
        ".rope_analysis_workspace": ("FlextInfraUtilitiesRopeAnalysisWorkspace",),
        ".rope_core": ("FlextInfraUtilitiesRopeCore",),
        ".rope_helpers": ("FlextInfraUtilitiesRopeHelpers",),
        ".rope_imports": ("FlextInfraUtilitiesRopeImports",),
        ".rope_inventory": ("FlextInfraUtilitiesRopeInventory",),
        ".rope_module_patch": ("FlextInfraUtilitiesRopeModulePatch",),
        ".rope_mro_transform": ("FlextInfraUtilitiesRopeMroTransform",),
        ".rope_pep695_patch": ("FlextInfraUtilitiesRopePep695Patch",),
        ".rope_source": ("FlextInfraUtilitiesRopeSource",),
        ".safety": ("FlextInfraUtilitiesSafety",),
        ".snapshot": ("FlextInfraUtilitiesSnapshot",),
        ".versioning": ("FlextInfraUtilitiesVersioning",),
    },
)


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, publish_all=False)
