# AUTO-GENERATED FILE — Regenerate with: make gen
"""Utilities package."""

from __future__ import annotations

from flext_core.lazy import install_lazy_exports

_LAZY_IMPORTS = {
    "FlextInfraExtraPathsResolutionMixin": ".deps_paths",
    "FlextInfraInternalSyncRepoMixin": ".deps_repos",
    "FlextInfraNormalizerContext": ".normalizer",
    "FlextInfraUtilitiesBase": ".base",
    "FlextInfraUtilitiesCli": ".cli",
    "FlextInfraUtilitiesCliShared": ".cli_shared",
    "FlextInfraUtilitiesCliSubcommand": ".cli_subcommand",
    "FlextInfraUtilitiesCodegen": ".codegen",
    "FlextInfraUtilitiesCodegenConstantAnalysis": ".codegen_constants",
    "FlextInfraUtilitiesCodegenConstantDetection": ".codegen_constants",
    "FlextInfraUtilitiesCodegenConstantTransformation": ".codegen_constants",
    "FlextInfraUtilitiesCodegenExecution": ".codegen_execution",
    "FlextInfraUtilitiesCodegenGeneration": ".codegen_generation",
    "FlextInfraUtilitiesCodegenGovernance": ".codegen_constants",
    "FlextInfraUtilitiesCodegenImportCycles": ".codegen_import_cycles",
    "FlextInfraUtilitiesCodegenLazyAliases": ".lazy",
    "FlextInfraUtilitiesCodegenLazyMerging": ".lazy",
    "FlextInfraUtilitiesCodegenLazyScanning": ".lazy",
    "FlextInfraUtilitiesCodegenNamespace": ".namespace",
    "FlextInfraUtilitiesDiscovery": ".discovery",
    "FlextInfraUtilitiesDiscoveryScanning": ".discovery_scanning",
    "FlextInfraUtilitiesDocs": ".docs",
    "FlextInfraUtilitiesDocsApi": ".docs_api",
    "FlextInfraUtilitiesDocsAudit": ".docs_audit",
    "FlextInfraUtilitiesDocsBuild": ".docs_build",
    "FlextInfraUtilitiesDocsContract": ".docs_contract",
    "FlextInfraUtilitiesDocsFix": ".docs_fix",
    "FlextInfraUtilitiesDocsGenerate": ".docs_generate",
    "FlextInfraUtilitiesDocsRender": ".docs_render",
    "FlextInfraUtilitiesDocsScope": ".docs_scope",
    "FlextInfraUtilitiesDocsValidate": ".docs_validate",
    "FlextInfraUtilitiesFormatting": ".formatting",
    "FlextInfraUtilitiesGit": ".git",
    "FlextInfraUtilitiesGithub": ".github",
    "FlextInfraUtilitiesGithubPr": ".github_pr",
    "FlextInfraUtilitiesImportNormalizer": ".normalizer",
    "FlextInfraUtilitiesIteration": ".iteration",
    "FlextInfraUtilitiesLogParser": ".log_parser",
    "FlextInfraUtilitiesOutput": ".output",
    "FlextInfraUtilitiesOutputFailureSummary": ".output_failure_summary",
    "FlextInfraUtilitiesOutputReporting": ".output_reporting",
    "FlextInfraUtilitiesParsing": ".parsing",
    "FlextInfraUtilitiesPaths": ".paths",
    "FlextInfraUtilitiesPatterns": ".patterns",
    "FlextInfraUtilitiesProtectedEdit": ".protected_edit",
    "FlextInfraUtilitiesRefactor": "._utilities",
    "FlextInfraUtilitiesRefactorCensus": ".census",
    "FlextInfraUtilitiesRefactorCli": "._utilities_cli",
    "FlextInfraUtilitiesRefactorEngine": ".engine",
    "FlextInfraUtilitiesRefactorMroScan": ".mro_scan",
    "FlextInfraUtilitiesRefactorMroTransform": "._utilities_mro_transform",
    "FlextInfraUtilitiesRefactorNamespace": "._utilities_namespace",
    "FlextInfraUtilitiesRefactorNamespaceCommon": "._utilities_namespace_analysis",
    "FlextInfraUtilitiesRefactorNamespaceFacades": "._utilities_namespace_facades",
    "FlextInfraUtilitiesRefactorNamespaceMoves": "._utilities_namespace_moves",
    "FlextInfraUtilitiesRefactorNamespaceMro": "._utilities_namespace_analysis",
    "FlextInfraUtilitiesRefactorNamespaceRuntime": "._utilities_namespace_runtime",
    "FlextInfraUtilitiesRefactorPolicy": "._utilities_policy",
    "FlextInfraUtilitiesRefactorPydantic": "._utilities_pydantic",
    "FlextInfraUtilitiesRefactorPydanticAnalysis": "._utilities_pydantic_analysis",
    "FlextInfraUtilitiesRefactorTransformerPolicy": ".transformer_policy",
    "FlextInfraUtilitiesRelease": ".release",
    "FlextInfraUtilitiesReporting": ".reporting",
    "FlextInfraUtilitiesRope": ".rope",
    "FlextInfraUtilitiesRopeAnalysis": ".rope_analysis",
    "FlextInfraUtilitiesRopeAnalysisIntrospection": ".rope_analysis_introspection",
    "FlextInfraUtilitiesRopeCore": ".rope_core",
    "FlextInfraUtilitiesRopeHelpers": ".rope_helpers",
    "FlextInfraUtilitiesRopeImports": ".rope_imports",
    "FlextInfraUtilitiesRopeSource": ".rope_source",
    "FlextInfraUtilitiesSafety": ".safety",
    "FlextInfraUtilitiesSelection": ".selection",
    "FlextInfraUtilitiesTerminal": ".terminal",
    "FlextInfraUtilitiesToml": ".toml",
    "FlextInfraUtilitiesTomlParse": ".toml_parse",
    "FlextInfraUtilitiesVersioning": ".versioning",
    "FlextInfraUtilitiesYaml": ".yaml",
}


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, publish_all=False)
