"""Project scanning and introspection utilities."""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from pathlib import Path

from flext_core import r
from flext_infra import c, t


class FlextInfraUtilitiesDiscoveryScanning:
    """Mixin for project alias discovery, package introspection, and file scanning."""

    @staticmethod
    def discover_project_aliases(project_root: Path) -> t.StrMapping:
        """Discover all single-char aliases in a project."""
        src_package = FlextInfraUtilitiesDiscoveryScanning.discover_src_package_dir(
            project_root,
        )
        if src_package is None:
            return {}
        _package_name, package_dir = src_package
        alias_to_facade: t.MutableStrMapping = {}
        facades = [
            c.Infra.Files.MODELS_PY,
            c.Infra.Files.UTILITIES_PY,
            c.Infra.Files.CONSTANTS_PY,
            c.Infra.Files.TYPINGS_PY,
            c.Infra.Files.PROTOCOLS_PY,
        ]
        for facade_name in facades:
            facade_path = package_dir / facade_name
            if not facade_path.is_file():
                continue
            alias = (
                FlextInfraUtilitiesDiscoveryScanning.extract_declared_alias_from_facade(
                    facade_path,
                )
            )
            if len(alias) == 1 and alias.islower():
                alias_to_facade[alias] = facade_name
        return alias_to_facade

    @staticmethod
    def extract_declared_alias_from_facade(file_path: Path) -> str:
        """Extract the single-char alias defined in a facade file."""
        if not file_path.is_file():
            return ""
        try:
            content = file_path.read_text(encoding=c.Infra.Encoding.DEFAULT)
            match = re.search(
                r"^\s*([a-z])\s*=\s*[A-Z][a-zA-Z0-9_]+\s*$", content, re.MULTILINE
            )
            return match.group(1) if match else ""
        except OSError:
            return ""

    @staticmethod
    def extract_lazy_import_map(init_path: Path) -> t.StrMapping:
        """Extract PEP 562 lazy import map from an __init__.py file."""
        targets = FlextInfraUtilitiesDiscoveryScanning.extract_lazy_import_targets(
            init_path,
        )
        return {
            alias_name: module_name.split(".")[-1]
            for alias_name, module_name in targets.items()
            if len(alias_name) == 1 and alias_name.islower()
        }

    @staticmethod
    def extract_lazy_import_targets(init_path: Path) -> t.StrMapping:
        """Extract `_LAZY_IMPORTS` targets from an autogenerated package init."""
        if not init_path.is_file():
            return {}
        try:
            content = init_path.read_text(encoding=c.Infra.Encoding.DEFAULT)
            targets: t.MutableStrMapping = {}
            dict_match = re.search(
                r"_LAZY_IMPORTS\s*(?::\s*[^=]+)?\s*=\s*(?:merge_lazy_imports\s*\(\s*(?:\([^)]*\)\s*,\s*)?)?\{(.*?)\}\s*(?:,\s*\))?",
                content,
                re.DOTALL,
            )
            if dict_match:
                for match in re.finditer(
                    r"""["']([a-zA-Z0-9_]+)["']\s*:\s*(?:\(\s*)?["']([a-zA-Z0-9_\.]+)["']""",
                    dict_match.group(1),
                ):
                    targets[match.group(1)] = match.group(2)
            return targets
        except OSError:
            return {}

    @staticmethod
    def discover_python_dirs(
        project_dir: Path,
        *,
        skip_dirs: frozenset[str] | None = None,
    ) -> t.StrSequence:
        """Discover all directories containing Python files in a project.

        SSOT discovery function used by all tool config phases
        (pyright, ruff, pyrefly, mypy, extra_paths) and codegen.

        Args:
            project_dir: Project root directory to scan.
            skip_dirs: Directory names to skip. Defaults to c.Infra.SKIP_DIRS.

        Returns:
            Sorted list of directory names that contain at least one .py file.

        """
        if not project_dir.is_dir():
            return []
        effective_skip = skip_dirs if skip_dirs is not None else c.Infra.SKIP_DIRS
        return [
            subdir.name
            for subdir in sorted(project_dir.iterdir())
            if subdir.is_dir()
            and not subdir.name.startswith(".")
            and subdir.name not in effective_skip
            and any(subdir.rglob(c.Infra.Extensions.PYTHON_GLOB))
        ]

    @staticmethod
    def discover_src_package_dir(project_root: Path) -> t.Infra.Pair[str, Path] | None:
        """Find the main package directory inside src/."""
        src_dir = project_root / c.Infra.Paths.DEFAULT_SRC_DIR
        if not src_dir.is_dir():
            return None
        for child in sorted(src_dir.iterdir()):
            if child.is_dir() and (child / c.Infra.Files.INIT_PY).is_file():
                return child.name, child
        return None

    @staticmethod
    def find_all_pyproject_files(
        workspace_root: Path,
        *,
        skip_dirs: frozenset[str] | None = None,
        project_paths: Sequence[Path] | None = None,
    ) -> r[Sequence[Path]]:
        """Find all pyproject.toml files in the workspace.

        Args:
            workspace_root: Root directory to search
            skip_dirs: Directory names to skip during traversal (defaults to c.Infra.SKIP_DIRS)
            project_paths: If provided, only include files within these paths

        Returns:
            r[Sequence[Path]]: Result with list of pyproject.toml paths, or failure

        """
        if not workspace_root.exists():
            return r[Sequence[Path]].ok([])
        effective_skip = skip_dirs if skip_dirs is not None else c.Infra.SKIP_DIRS
        try:
            all_files = [
                p
                for p in workspace_root.rglob(c.Infra.Files.PYPROJECT_FILENAME)
                if not any(
                    part in effective_skip
                    for part in p.relative_to(workspace_root).parts[:-1]
                )
            ]
        except OSError as exc:
            return r[Sequence[Path]].fail(f"pyproject file scan failed: {exc}")
        if project_paths is not None:
            all_files = [
                f
                for f in all_files
                if any(f.is_relative_to(pp) for pp in project_paths)
            ]
        return r[Sequence[Path]].ok(all_files)

    @staticmethod
    def resolve_parent_constants(
        pkg_dir_or_file: Path,
        *,
        return_module: bool = False,
    ) -> str:
        """Find the parent constants class or module from constants.py imports.

        Unified helper replacing 3 near-identical implementations.
        If return_module=True returns the dotted module (e.g. "flext_core").
        Otherwise returns the class name (e.g. "FlextCoreConstants").
        Falls back to "flext_core" (module) or "" (class) if not found.
        """
        constants_file = (
            pkg_dir_or_file
            if pkg_dir_or_file.name == c.Infra.Files.CONSTANTS_PY
            else pkg_dir_or_file / c.Infra.Files.CONSTANTS_PY
        )
        if not constants_file.is_file():
            return c.Infra.Packages.CORE_UNDERSCORE if return_module else ""
        try:
            source = constants_file.read_text(c.Infra.Encoding.DEFAULT)
        except (OSError, UnicodeDecodeError):
            return c.Infra.Packages.CORE_UNDERSCORE if return_module else ""
        match = c.Infra.Detection.IMPORT_CONSTANTS_RE.search(source)
        if not match:
            return c.Infra.Packages.CORE_UNDERSCORE if return_module else ""
        module = match.group(1)
        class_name = match.group(2)
        if return_module:
            return module
        return class_name

    @staticmethod
    def discover_project_package_name(*, project_root: Path) -> str:
        """Discover the Python package name under ``src/`` for a project root."""
        result = FlextInfraUtilitiesDiscoveryScanning.discover_src_package_dir(
            project_root,
        )
        return result[0] if result is not None else ""

    @staticmethod
    def find_package_dir(project_root: Path) -> Path | None:
        """Find the first package directory under ``src/`` for a project root."""
        result = FlextInfraUtilitiesDiscoveryScanning.discover_src_package_dir(
            project_root,
        )
        return result[1] if result is not None else None

    @staticmethod
    def discover_parent_package(project_root: Path) -> str:
        """Resolve the direct parent FLEXT package for a project."""
        package_dir = FlextInfraUtilitiesDiscoveryScanning.find_package_dir(
            project_root
        )
        if package_dir is None:
            return c.Infra.Packages.CORE_UNDERSCORE
        return FlextInfraUtilitiesDiscoveryScanning.resolve_parent_constants(
            package_dir,
            return_module=True,
        )

    @staticmethod
    def contextual_runtime_alias_sources(
        *,
        project_root: Path,
        file_path: Path,
    ) -> Mapping[str, frozenset[str]]:
        """Return allowed foreign-package runtime alias sources for a file."""
        package_dir = FlextInfraUtilitiesDiscoveryScanning.find_package_dir(
            project_root
        )
        if package_dir is None:
            return {}
        utilities_dir = package_dir / c.Infra.FAMILY_DIRECTORIES["u"]
        if not file_path.is_relative_to(utilities_dir):
            return {}
        parent_package = FlextInfraUtilitiesDiscoveryScanning.discover_parent_package(
            project_root,
        )
        if not parent_package:
            return {}
        return {"u": frozenset({parent_package})}


__all__ = ["FlextInfraUtilitiesDiscoveryScanning"]
