"""Template engine service for text rendering.

Consolidates shared text templates used by infrastructure scripts
into a service class with r error handling.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from typing import ClassVar

from flext_core import r


class FlextInfraUtilitiesTemplates:
    """Infrastructure service for text template rendering.

    Centralizes template constants and provides safe rendering
    with r error handling.
    """

    TOC_START: ClassVar[str] = "<!-- TOC START -->"
    TOC_END: ClassVar[str] = "<!-- TOC END -->"
    GENERATED_SHELL_HEADER: ClassVar[str] = "# Generated by {source} - DO NOT EDIT\n"

    @staticmethod
    def render(template: str, **kwargs: str) -> r[str]:
        """Render a template string with keyword arguments.

        Args:
            template: Template string with {key} placeholders.
            **kwargs: Values to substitute into the template.

        Returns:
            r[str] with the rendered string.

        """
        try:
            rendered = template.format(**kwargs)
            return r[str].ok(rendered)
        except KeyError as exc:
            return r[str].fail(f"missing template key: {exc}")
        except (IndexError, ValueError) as exc:
            return r[str].fail(f"template render error: {exc}")


__all__ = ["FlextInfraUtilitiesTemplates"]
