# Generated by `flext-infra codegen conform` for flext_infra.
# Clean-machine proof: project bootstrap + canonical make verbs on Alpine
# (musl, POSIX /bin/sh at runtime; bash installed for the project scripts).
FROM alpine:3.21

RUN apk add --no-cache \
      bash ca-certificates coreutils curl git make build-base nodejs util-linux-misc

WORKDIR /workspace
COPY . .

RUN make setup

ENTRYPOINT []
CMD ["/bin/bash", "-lc", "make help"]
