# Generated by `flext_infra codegen conform` for flext_infra.
# === SECTION: header (managed) ===
# Source: template (base/ci/docker/alpine.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Alpine
# (musl, POSIX /bin/sh at runtime; bash installed for the project scripts).
FROM alpine:3.21

# === SECTION: base packages (managed) ===
# Source: template (distro-specific package list)
RUN apk add --no-cache \
      bash ca-certificates curl git make build-base icu-dev icu-libs
# End SECTION: base packages

# === SECTION: managed tool bootstrap (managed) ===
# Source: config:python_version, template (installer URLs)
# mise installs the supported Python 3.13 family.
# uv is supplied by the managed environment without a project patch pin.
RUN curl -fsSL https://mise.run | MISE_VERSION="v2026.7.16" sh
# uv is intentionally supplied by the caller environment; install it explicitly
# in clean-machine images so the project bootstrap can resolve dependencies.
RUN curl -fsSL https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:/root/.local/share/mise/shims:${PATH}"
# End SECTION: managed tool bootstrap

WORKDIR /workspace
COPY . .

# === SECTION: mise install (managed) ===
# Source: computed (reads .mise.toml from copied workspace)
RUN mise trust .mise.toml && mise install --yes
# End SECTION: mise install

# === SECTION: bootstrap (managed) ===
# Source: canonical Make setup; every failure stops the image build.
RUN make setup CI=Y
# End SECTION: bootstrap

ENTRYPOINT []
CMD ["/bin/bash", "-lc", "make help"]
