# Generated by `flext-infra codegen conform` for flext_infra.
# Clean-machine proof: project bootstrap + canonical make verbs on Debian.
FROM debian:bookworm-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       bash ca-certificates curl git make build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY . .

RUN make setup

ENTRYPOINT []
CMD ["make", "help"]
