# Generated by `flext-infra codegen conform` for flext_infra.
# Clean-machine proof: project bootstrap + canonical make verbs on Debian.
FROM debian:bookworm-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       bash ca-certificates curl git make build-essential \
    && rm -rf /var/lib/apt/lists/*

# mise installs the supported Python 3.13 family.
# uv is supplied by the managed environment without a project patch pin.
RUN curl -fsSL https://mise.run | sh
ENV PATH="/root/.local/bin:/root/.local/share/mise/shims:${PATH}"

WORKDIR /workspace
COPY . .

RUN mise trust .mise.toml && mise install --yes

# uv is an environment-provided executable, intentionally without a project
# patch pin. The official installer places it on the declared runtime PATH.
RUN curl -LsSf https://astral.sh/uv/install.sh \
    | env UV_UNMANAGED_INSTALL=/usr/local/bin sh

RUN make setup

ENTRYPOINT []
CMD ["make", "help"]
