# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.refactor.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".accessor_migration": ("FlextInfraAccessorMigrationOrchestrator",),
    ".census": ("FlextInfraRefactorCensus",),
    ".class_nesting_analyzer": ("FlextInfraRefactorClassNestingAnalyzer",),
    ".classvar_constant_autofix": ("FlextInfraRefactorClassvarConstantAutofix",),
    ".declarative_enforcement": ("FlextInfraRefactorDeclarativeEnforcement",),
    ".file_executor": (
        "FlextInfraClassNestingPostCheckGate",
        "FlextInfraRefactorFileExecutor",
    ),
    ".legacy_text_ops": ("FlextInfraRefactorLegacyTextOps",),
    ".loader": ("FlextInfraRefactorRuleLoader",),
    ".migrate_to_class_mro": ("FlextInfraRefactorMigrateToClassMRO",),
    ".modernize_orchestrator": ("FlextInfraModernizeOrchestrator",),
    ".mro_import_rewriter": ("FlextInfraRefactorMROImportRewriter",),
    ".mro_migration_validator": ("FlextInfraRefactorMROMigrationValidator",),
    ".mro_resolver": ("FlextInfraRefactorMROResolver",),
    ".namespace_enforcer": ("FlextInfraNamespaceEnforcer",),
    ".namespace_enforcer_phases": ("FlextInfraNamespaceEnforcerPhasesMixin",),
    ".orchestrator": ("FlextInfraRefactorOrchestrator",),
    ".project_classifier": ("FlextInfraProjectClassifier",),
    ".safety": ("FlextInfraRefactorSafetyManager",),
    ".scanner": ("FlextInfraRefactorLooseClassScanner",),
    ".service": ("FlextInfraRefactorService",),
    ".text_executor": ("FlextInfraRefactorTextExecutor",),
    ".violation_analyzer": ("FlextInfraRefactorViolationAnalyzer",),
    ".wrapper_root_namespace": ("FlextInfraWrapperRootNamespaceRefactor",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraAccessorMigrationOrchestrator",
    "FlextInfraClassNestingPostCheckGate",
    "FlextInfraModernizeOrchestrator",
    "FlextInfraNamespaceEnforcer",
    "FlextInfraNamespaceEnforcerPhasesMixin",
    "FlextInfraProjectClassifier",
    "FlextInfraRefactorCensus",
    "FlextInfraRefactorClassNestingAnalyzer",
    "FlextInfraRefactorClassvarConstantAutofix",
    "FlextInfraRefactorDeclarativeEnforcement",
    "FlextInfraRefactorFileExecutor",
    "FlextInfraRefactorLegacyTextOps",
    "FlextInfraRefactorLooseClassScanner",
    "FlextInfraRefactorMROImportRewriter",
    "FlextInfraRefactorMROMigrationValidator",
    "FlextInfraRefactorMROResolver",
    "FlextInfraRefactorMigrateToClassMRO",
    "FlextInfraRefactorOrchestrator",
    "FlextInfraRefactorRuleLoader",
    "FlextInfraRefactorSafetyManager",
    "FlextInfraRefactorService",
    "FlextInfraRefactorTextExecutor",
    "FlextInfraRefactorViolationAnalyzer",
    "FlextInfraWrapperRootNamespaceRefactor",
)
