# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.integration.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".docs_serve_e2e_tests": ("TestsFlextInfraIntegrationDocsServeE2e",),
    ".test_infra_integration": ("TestsFlextInfraIntegrationInfraIntegration",),
    ".test_refactor_nesting_file": ("TestsFlextInfraIntegrationRefactorNestingFile",),
    ".test_refactor_nesting_idempotency": (
        "TestsFlextInfraIntegrationRefactorNestingIdempotency",
    ),
    ".test_refactor_nesting_performance": (
        "TestsFlextInfraIntegrationRefactorNestingPerformance",
    ),
    ".test_refactor_nesting_project": (
        "TestsFlextInfraIntegrationRefactorNestingProject",
    ),
    ".test_refactor_nesting_workspace": (
        "TestsFlextInfraIntegrationRefactorNestingWorkspace",
    ),
    ".test_refactor_policy_mro": ("TestsFlextInfraIntegrationRefactorPolicyMro",),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "TestsFlextInfraIntegrationDocsServeE2e",
    "TestsFlextInfraIntegrationInfraIntegration",
    "TestsFlextInfraIntegrationRefactorNestingFile",
    "TestsFlextInfraIntegrationRefactorNestingIdempotency",
    "TestsFlextInfraIntegrationRefactorNestingPerformance",
    "TestsFlextInfraIntegrationRefactorNestingProject",
    "TestsFlextInfraIntegrationRefactorNestingWorkspace",
    "TestsFlextInfraIntegrationRefactorPolicyMro",
    "c",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
