"""Lazy-init planning and quality-gate models.

Copyright (c) 2026 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

from flext_cli import m

from flext_infra import c, t
from flext_infra._models.mixins import FlextInfraModelsMixins


class FlextInfraModelsCodegenLazyInitModels:
    """Lazy-init planning and quality-gate models."""

    class LazyInitPackageContext(m.ArbitraryTypesModel):
        """Declarative package context for one lazy-init directory."""

        pkg_dir: Path = m.Field(description="Directory being processed.")
        init_path: Path = m.Field(description="Target __init__.py path.")
        current_pkg: str = m.Field(description="Importable package name.")
        surface: str = m.Field(description="Root surface for wrapper alias resolution.")
        generated_init: Annotated[
            bool,
            m.Field(
                description=(
                    "Whether the current __init__.py is generated by lazy-init."
                ),
            ),
        ] = False
        importable: Annotated[
            bool,
            m.Field(
                description="Whether the directory resolves to an importable package.",
            ),
        ] = False

    class LazyInitPlan(m.ArbitraryTypesModel):
        """Fully resolved lazy-init action and render payload.

        Enforcement exemption: internal tooling model with intentional
        mutable state.
        """

        context: FlextInfraModelsCodegenLazyInitModels.LazyInitPackageContext = m.Field(
            description="Discovered package context.",
        )
        action: Annotated[
            c.Infra.LazyInitAction,
            m.Field(description="Action selected for this package."),
        ] = c.Infra.LazyInitAction.SKIP
        exports: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Public exports for generated __init__.py.",
        )
        lazy_map: t.LazyAliasMap = m.Field(
            description="Lazy import map: export name to module/attribute target.",
        )
        eager_dunders: t.LazyAliasMap = m.Field(
            description=(
                "Dunder exports that must be eagerly imported at __init__.py "
                "load time. Required for the ``__version__.py`` submodule case "
                "where the submodule name collides with the dunder string it "
                "exports — eager binding pins the canonical string in the "
                "package dict before any submodule re-import can shadow it."
            ),
        )
        inline_constants: t.StrMapping = m.Field(
            description="Inline constants emitted directly into __init__.py.",
        )
        wildcard_runtime_modules: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Runtime wildcard import modules.",
        )
        child_packages_for_lazy: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Direct child package imports merged at runtime.",
        )
        excluded_lazy_names: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Names excluded from runtime child lazy import merges.",
        )

    class QualityGateCheck(m.ArbitraryTypesModel):
        """A single quality gate check result entry."""

        name: Annotated[t.NonEmptyStr, m.Field(description="Check identifier")]
        passed: Annotated[bool, m.Field(description="Whether check passed")]
        detail: Annotated[str, m.Field(description="Human-readable check detail")] = ""
        critical: Annotated[bool, m.Field(description="Whether failure is critical")]

    class QualityGateProjectFinding(
        FlextInfraModelsMixins.ProjectNameMixin,
        m.ArbitraryTypesModel,
    ):
        """Per-project quality gate findings."""

        violations_total: Annotated[
            t.NonNegativeInt,
            m.Field(description="Total violations"),
        ]
        validator_passed: Annotated[
            bool,
            m.Field(description="Whether validator passed"),
        ]
