"""Namespace policy and lazy-init plan models for the codegen governance domain."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, ClassVar

from flext_cli import m

from ... import c, p, t
from .. import ImmutableEmptyMapping
from .census import FlextInfraModelsCodegenCensus
from .results import FlextInfraModelsCodegenResults


class FlextInfraModelsCodegenPolicy:
    """Private codegen policy and pipeline model domain partial."""

    class NamespaceModulePolicy(m.ArbitraryTypesModel):
        """Derived gen-init policy for one governed module."""

        enforce_contract: Annotated[
            bool, m.Field(description="Whether gen-init must enforce namespace shape.")
        ] = False
        export_symbols: Annotated[
            bool,
            m.Field(description="Whether gen-init should discover public symbols."),
        ] = False
        include_in_lazy_init: Annotated[
            bool,
            m.Field(description="Whether lazy-init should index this module at all."),
        ] = True
        project_prefix: Annotated[
            str, m.Field(description="Canonical class prefix expected for the module.")
        ] = ""
        expected_alias: Annotated[
            str | None,
            m.Field(description="Canonical module-level alias allowed for the file."),
        ] = None
        expected_family: Annotated[
            str | None,
            m.Field(description="Canonical namespace family suffix for the file."),
        ] = None
        family_tokens: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Accepted family markers for private namespace modules.",
        )
        accepted_suffixes: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Accepted class suffixes for governed facade classes.",
        )
        allow_main_export: Annotated[
            bool,
            m.Field(description="Whether the file may export a module-level main()."),
        ] = False
        allow_type_alias: Annotated[
            bool,
            m.Field(description="Whether the module may keep TypeAlias declarations."),
        ] = False
        is_fixture_module: Annotated[
            bool,
            m.Field(
                description="Whether the module belongs to a private fixtures package."
            ),
        ] = False
        type_checking_imports: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Canonical root names allowed inside TYPE_CHECKING imports.",
        )

    class LazyInitPackageContext(m.ArbitraryTypesModel):
        """Declarative package context for one lazy-init directory."""

        pkg_dir: Path = m.Field(description="Directory being processed.")
        init_path: Path = m.Field(description="Target __init__.py path.")
        current_pkg: str = m.Field(description="Importable package name.")
        surface: str = m.Field(description="Root surface for wrapper alias resolution.")
        generated_init: Annotated[
            bool,
            m.Field(
                description="Whether the current __init__.py is generated by lazy-init."
            ),
        ] = False
        importable: Annotated[
            bool,
            m.Field(
                description="Whether the directory resolves to an importable package."
            ),
        ] = False

    class LazyInitPlan(m.ArbitraryTypesModel):
        """Fully resolved lazy-init action and render payload.

        Enforcement exemption: internal tooling model with intentional
        mutable state.
        """

        context: FlextInfraModelsCodegenPolicy.LazyInitPackageContext = m.Field(
            description="Discovered package context."
        )
        action: Annotated[
            c.Infra.LazyInitAction,
            m.Field(description="Action selected for this package."),
        ] = c.Infra.LazyInitAction.SKIP
        exports: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Public exports for generated __init__.py.",
        )
        lazy_map: t.LazyAliasMap = m.Field(
            default_factory=ImmutableEmptyMapping,
            description="Lazy import map: export name to module/attribute target.",
        )
        type_checking_map: t.LazyAliasMap = m.Field(
            default_factory=ImmutableEmptyMapping,
            description=(
                "Type-checking import map used to publish static package attributes "
                "without widening the runtime/public lazy export surface."
            ),
        )
        eager_dunders: t.LazyAliasMap = m.Field(
            default_factory=ImmutableEmptyMapping,
            description=(
                "Dunder exports that must be eagerly imported at __init__.py "
                "load time. Required for the ``__version__.py`` submodule case "
                "where the submodule name collides with the dunder string it "
                "exports — eager binding pins the canonical string in the "
                "package dict before any submodule re-import can shadow it."
            ),
        )
        inline_constants: t.StrMapping = m.Field(
            default_factory=ImmutableEmptyMapping,
            description="Inline constants emitted directly into __init__.py.",
        )
        wildcard_runtime_modules: t.StrSequence = m.Field(
            default_factory=tuple, description="Runtime wildcard import modules."
        )
        child_packages_for_lazy: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Direct child package imports merged at runtime.",
        )
        excluded_lazy_names: t.StrSequence = m.Field(
            default_factory=tuple,
            description="Names excluded from runtime child lazy import merges.",
        )

    class CodegenPipelineState(m.ArbitraryTypesModel):
        """Typed inter-stage state for the codegen pipeline — Pydantic v2 model."""

        model_config: ClassVar[m.ConfigDict] = m.ConfigDict(
            extra="forbid", arbitrary_types_allowed=True
        )

        discovered_projects: Annotated[
            t.SequenceOf[p.Infra.ProjectInfo],
            m.Field(description="Projects discovered at pipeline start"),
        ] = ()
        census_service: Annotated[
            p.Infra.CodegenCensusService | None,
            m.Field(description="Cached census service for reuse across stages"),
        ] = None
        reports_before: Annotated[
            t.SequenceOf[FlextInfraModelsCodegenCensus.CensusReport],
            m.Field(description="Census reports collected before fixes"),
        ] = ()
        reports_after: Annotated[
            t.SequenceOf[FlextInfraModelsCodegenCensus.CensusReport],
            m.Field(description="Census reports collected after fixes"),
        ] = ()
        scaffold_results: Annotated[
            t.SequenceOf[FlextInfraModelsCodegenResults.ScaffoldResult],
            m.Field(description="Scaffolding stage results"),
        ] = ()
        fix_results: Annotated[
            t.SequenceOf[FlextInfraModelsCodegenResults.AutoFixResult],
            m.Field(description="Auto-fix stage results"),
        ] = ()
