id: ban-latest-tag
language: yaml
rule:
  kind: block_mapping_pair
  all:
  - has:
      field: key
      regex: "^image$"
  - has:
      field: value
      regex: ":latest$"
message: "Docker image uses :latest tag - pin specific version"
severity: error
