# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra._models.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".base": ("FlextInfraModelsBase",),
    ".basemk": ("FlextInfraModelsBasemk",),
    ".census": ("FlextInfraModelsCensus",),
    ".check": ("FlextInfraModelsCheck",),
    ".codegen": ("FlextInfraModelsCodegen",),
    ".codegen_render": ("FlextInfraModelsCodegenRender",),
    ".config": ("FlextInfraConfigModels",),
    ".deps": ("FlextInfraModelsDeps",),
    ".deps_toml": ("FlextInfraModelsDepsToml",),
    ".deps_tool_config": ("FlextInfraModelsDepsToolSettings",),
    ".deps_tool_config_linters": ("FlextInfraModelsDepsToolConfigLinters",),
    ".deps_tool_config_type_checkers": ("FlextInfraModelsDepsToolConfigTypeCheckers",),
    ".docs": ("FlextInfraModelsDocs",),
    ".enforcement": ("FlextInfraModelsEnforcement",),
    ".gates": ("FlextInfraModelsGates",),
    ".github": ("FlextInfraModelsGithub",),
    ".mixins": ("FlextInfraModelsMixins",),
    ".mro_scan": ("FlextInfraModelsMroScan",),
    ".refactor": ("FlextInfraModelsRefactor",),
    ".refactor_ast_grep": ("FlextInfraModelsRefactorGrep",),
    ".refactor_census": ("FlextInfraModelsRefactorCensus",),
    ".refactor_namespace_enforcer": ("FlextInfraModelsNamespaceEnforcer",),
    ".refactor_violations": ("FlextInfraModelsRefactorViolations",),
    ".release": ("FlextInfraModelsRelease",),
    ".rope": ("FlextInfraModelsRope",),
    ".scan": ("FlextInfraModelsScan",),
    ".settings": ("FlextInfraSettingsModels",),
    ".transformers": ("FlextInfraModelsTransformers",),
    ".validate": ("FlextInfraModelsCore",),
    ".workspace": ("FlextInfraModelsWorkspace",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraConfigModels",
    "FlextInfraModelsBase",
    "FlextInfraModelsBasemk",
    "FlextInfraModelsCensus",
    "FlextInfraModelsCheck",
    "FlextInfraModelsCodegen",
    "FlextInfraModelsCodegenRender",
    "FlextInfraModelsCore",
    "FlextInfraModelsDeps",
    "FlextInfraModelsDepsToml",
    "FlextInfraModelsDepsToolConfigLinters",
    "FlextInfraModelsDepsToolConfigTypeCheckers",
    "FlextInfraModelsDepsToolSettings",
    "FlextInfraModelsDocs",
    "FlextInfraModelsEnforcement",
    "FlextInfraModelsGates",
    "FlextInfraModelsGithub",
    "FlextInfraModelsMixins",
    "FlextInfraModelsMroScan",
    "FlextInfraModelsNamespaceEnforcer",
    "FlextInfraModelsRefactor",
    "FlextInfraModelsRefactorCensus",
    "FlextInfraModelsRefactorGrep",
    "FlextInfraModelsRefactorViolations",
    "FlextInfraModelsRelease",
    "FlextInfraModelsRope",
    "FlextInfraModelsScan",
    "FlextInfraModelsTransformers",
    "FlextInfraModelsWorkspace",
    "FlextInfraSettingsModels",
)
