# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.detectors.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".class_placement_detector": ("FlextInfraClassPlacementDetector",),
    ".compatibility_alias_detector": ("FlextInfraCompatibilityAliasDetector",),
    ".cyclic_import_detector": ("FlextInfraCyclicImportDetector",),
    ".facade_scanner": ("FlextInfraScanner",),
    ".future_annotations_detector": ("FlextInfraFutureAnnotationsDetector",),
    ".import_alias_detector": ("FlextInfraImportAliasDetector",),
    ".inline_import_detector": ("FlextInfraInlineImportDetector",),
    ".internal_import_detector": ("FlextInfraInternalImportDetector",),
    ".loose_object_detector": ("FlextInfraLooseObjectDetector",),
    ".loose_test_function_detector": ("FlextInfraLooseTestFunctionDetector",),
    ".manual_protocol_detector": ("FlextInfraManualProtocolDetector",),
    ".manual_typing_alias_detector": ("FlextInfraManualTypingAliasDetector",),
    ".mro_completeness_detector": ("FlextInfraMROCompletenessDetector",),
    ".mro_shape_detector": ("FlextInfraMROShapeDetector",),
    ".namespace_source_detector": ("FlextInfraNamespaceSourceDetector",),
    ".pattern_smell_detector": ("FlextInfraPatternSmellDetector",),
    ".private_import_bypass_detector": ("FlextInfraPrivateImportBypassDetector",),
    ".runtime_alias_detector": ("FlextInfraRuntimeAliasDetector",),
    ".silent_failure_detector": ("FlextInfraSilentFailureDetector",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraClassPlacementDetector",
    "FlextInfraCompatibilityAliasDetector",
    "FlextInfraCyclicImportDetector",
    "FlextInfraFutureAnnotationsDetector",
    "FlextInfraImportAliasDetector",
    "FlextInfraInlineImportDetector",
    "FlextInfraInternalImportDetector",
    "FlextInfraLooseObjectDetector",
    "FlextInfraLooseTestFunctionDetector",
    "FlextInfraMROCompletenessDetector",
    "FlextInfraMROShapeDetector",
    "FlextInfraManualProtocolDetector",
    "FlextInfraManualTypingAliasDetector",
    "FlextInfraNamespaceSourceDetector",
    "FlextInfraPatternSmellDetector",
    "FlextInfraPrivateImportBypassDetector",
    "FlextInfraRuntimeAliasDetector",
    "FlextInfraScanner",
    "FlextInfraSilentFailureDetector",
)
