# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.unit.transformers.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".test_infra_transformer_cast_remover": ("TestsFlextInfraTransformersCastRemover",),
    ".test_infra_transformer_class_nesting": (
        "TestsFlextInfraTransformersInfraTransformerClassNesting",
    ),
    ".test_infra_transformer_cli_modernizer": (
        "TestsFlextInfraTransformersCliModernizer",
    ),
    ".test_infra_transformer_enforcement_fixers": (
        "TestsFlextInfraTransformersCompatibilityAlias",
        "TestsFlextInfraTransformersFutureImport",
        "TestsFlextInfraTransformersHardcodedVersion",
        "TestsFlextInfraTransformersOpenEncoding",
        "TestsFlextInfraTransformersPattern",
        "TestsFlextInfraTransformersPatternList",
        "TestsFlextInfraTransformersPatternStructlog",
        "TestsFlextInfraTransformersTypingDictAttr",
        "TestsFlextInfraTransformersTypingDictImport",
        "TestsFlextInfraTransformersTypingUnifier",
    ),
    ".test_infra_transformer_helper_consolidation": (
        "TestsFlextInfraTransformersInfraTransformerHelperConsolidation",
    ),
    ".test_infra_transformer_logging_modernizer": (
        "TestsFlextInfraTransformersLoggingModernizer",
    ),
    ".test_infra_transformer_nested_class_propagation": (
        "TestsFlextInfraTransformersInfraTransformerNestedClassPropagation",
    ),
    ".test_infra_transformer_pattern_modernizer": (
        "TestsFlextInfraTransformersPatternModernizer",
    ),
    ".test_infra_transformer_pydantic_modernizer": (
        "TestsFlextInfraTransformersPydanticModernizer",
    ),
    ".test_infra_transformer_result_di_modernizer": (
        "TestsFlextInfraTransformersResultDiModernizer",
    ),
    ".test_infra_transformer_tests_modernizer": (
        "TestsFlextInfraTransformersTestsModernizer",
    ),
    ".test_project_alias_migrator": ("TestsFlextInfraRefactorProjectAliasMigrator",),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "TestsFlextInfraRefactorProjectAliasMigrator",
    "TestsFlextInfraTransformersCastRemover",
    "TestsFlextInfraTransformersCliModernizer",
    "TestsFlextInfraTransformersCompatibilityAlias",
    "TestsFlextInfraTransformersFutureImport",
    "TestsFlextInfraTransformersHardcodedVersion",
    "TestsFlextInfraTransformersInfraTransformerClassNesting",
    "TestsFlextInfraTransformersInfraTransformerHelperConsolidation",
    "TestsFlextInfraTransformersInfraTransformerNestedClassPropagation",
    "TestsFlextInfraTransformersLoggingModernizer",
    "TestsFlextInfraTransformersOpenEncoding",
    "TestsFlextInfraTransformersPattern",
    "TestsFlextInfraTransformersPatternList",
    "TestsFlextInfraTransformersPatternModernizer",
    "TestsFlextInfraTransformersPatternStructlog",
    "TestsFlextInfraTransformersPydanticModernizer",
    "TestsFlextInfraTransformersResultDiModernizer",
    "TestsFlextInfraTransformersTestsModernizer",
    "TestsFlextInfraTransformersTypingDictAttr",
    "TestsFlextInfraTransformersTypingDictImport",
    "TestsFlextInfraTransformersTypingUnifier",
    "c",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "t",
    "td",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
