# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.transformers.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".base": ("FlextInfraChangeTrackingTransformer", "FlextInfraRopeTransformer"),
    ".cast_remover": ("FlextInfraRefactorCastRemover",),
    ".census_visitors": (
        "FlextInfraCensusImportDiscoveryVisitor",
        "FlextInfraCensusUsageCollector",
    ),
    ".class_nesting": ("FlextInfraRefactorClassNestingTransformer",),
    ".class_reconstructor": ("FlextInfraRefactorClassReconstructor",),
    ".cli_modernizer": ("FlextInfraRefactorCliModernizer",),
    ".compatibility_alias": ("FlextInfraRefactorCompatibilityAlias",),
    ".deprecated_remover": ("FlextInfraRefactorDeprecatedRemover",),
    ".future_import": ("FlextInfraRefactorFutureImport",),
    ".hardcoded_version": ("FlextInfraRefactorHardcodedVersion",),
    ".helper_consolidation": ("FlextInfraHelperConsolidationTransformer",),
    ".import_bypass_remover": ("FlextInfraRefactorImportBypassRemover",),
    ".import_modernizer": ("FlextInfraRefactorImportModernizer",),
    ".lazy_import_fixer": ("FlextInfraRefactorLazyImportFixer",),
    ".logging_modernizer": ("FlextInfraRefactorLoggingModernizer",),
    ".mro_remover": ("FlextInfraRefactorMRORemover",),
    ".mro_symbol_propagator": ("FlextInfraRefactorMROSymbolPropagator",),
    ".nested_class_propagation": ("FlextInfraNestedClassPropagationTransformer",),
    ".open_encoding": ("FlextInfraRefactorOpenEncoding",),
    ".pattern": ("FlextInfraRefactorPatternTransformer",),
    ".pattern_modernizer": ("FlextInfraRefactorPatternModernizer",),
    ".project_alias_migrator": ("FlextInfraRefactorProjectAliasMigrator",),
    ".pydantic_modernizer": ("FlextInfraRefactorPydanticModernizer",),
    ".result_di_modernizer": ("FlextInfraRefactorResultDiModernizer",),
    ".signature_propagator": ("FlextInfraRefactorSignaturePropagator",),
    ".smells.base": (
        "FlextInfraSmellFixer",
        "auto_fixable_smell_tags",
        "register_smell_fixer",
        "smell_fixer_for",
    ),
    ".smells.boolean_logic": ("FlextInfraBooleanLogicFixer",),
    ".symbol_propagator": ("FlextInfraRefactorSymbolPropagator",),
    ".tier0_import_fixer": ("FlextInfraTransformerTier0ImportFixer",),
    ".typing_dict_attr": ("FlextInfraRefactorTypingDictAttr",),
    ".typing_dict_import": ("FlextInfraRefactorTypingDictImport",),
    ".typing_unifier": ("FlextInfraRefactorTypingUnifier",),
    ".violation_census_visitor": ("FlextInfraViolationCensusVisitor",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = (".smells",)
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraBooleanLogicFixer",
    "FlextInfraCensusImportDiscoveryVisitor",
    "FlextInfraCensusUsageCollector",
    "FlextInfraChangeTrackingTransformer",
    "FlextInfraHelperConsolidationTransformer",
    "FlextInfraNestedClassPropagationTransformer",
    "FlextInfraRefactorCastRemover",
    "FlextInfraRefactorClassNestingTransformer",
    "FlextInfraRefactorClassReconstructor",
    "FlextInfraRefactorCliModernizer",
    "FlextInfraRefactorCompatibilityAlias",
    "FlextInfraRefactorDeprecatedRemover",
    "FlextInfraRefactorFutureImport",
    "FlextInfraRefactorHardcodedVersion",
    "FlextInfraRefactorImportBypassRemover",
    "FlextInfraRefactorImportModernizer",
    "FlextInfraRefactorLazyImportFixer",
    "FlextInfraRefactorLoggingModernizer",
    "FlextInfraRefactorMRORemover",
    "FlextInfraRefactorMROSymbolPropagator",
    "FlextInfraRefactorOpenEncoding",
    "FlextInfraRefactorPatternModernizer",
    "FlextInfraRefactorPatternTransformer",
    "FlextInfraRefactorProjectAliasMigrator",
    "FlextInfraRefactorPydanticModernizer",
    "FlextInfraRefactorResultDiModernizer",
    "FlextInfraRefactorSignaturePropagator",
    "FlextInfraRefactorSymbolPropagator",
    "FlextInfraRefactorTypingDictAttr",
    "FlextInfraRefactorTypingDictImport",
    "FlextInfraRefactorTypingUnifier",
    "FlextInfraRopeTransformer",
    "FlextInfraSmellFixer",
    "FlextInfraTransformerTier0ImportFixer",
    "FlextInfraViolationCensusVisitor",
    "auto_fixable_smell_tags",
    "register_smell_fixer",
    "smell_fixer_for",
    "smells",
)
