# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.fixers.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".base": ("FlextInfraFixerAdapter",),
    ".gate_fixer": ("FlextInfraGateFixerAdapter",),
    ".manual_fixer": ("FlextInfraManualFixerAdapter",),
    ".orchestrator": ("FlextInfraEnforcementFixerOrchestrator",),
    ".result": ("FlextInfraFixersResult",),
    ".rope_fixer": ("FlextInfraRopeFixerAdapter",),
    ".transformer_fixer": ("FlextInfraTransformerFixerAdapter",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraEnforcementFixerOrchestrator",
    "FlextInfraFixerAdapter",
    "FlextInfraFixersResult",
    "FlextInfraGateFixerAdapter",
    "FlextInfraManualFixerAdapter",
    "FlextInfraRopeFixerAdapter",
    "FlextInfraTransformerFixerAdapter",
)
