# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.gates.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".abstraction_boundary": ("FlextInfraAbstractionBoundaryGate",),
    ".bandit": ("FlextInfraBanditGate",),
    ".base_gate": ("FlextInfraGate",),
    ".canonical_alias": ("FlextInfraCanonicalAliasGate",),
    ".loc_cap": ("FlextInfraLocCapGate",),
    ".markdown": ("FlextInfraMarkdownGate",),
    ".mypy": ("FlextInfraMypyGate",),
    ".namespace": ("FlextInfraNamespaceGate",),
    ".pyrefly": ("FlextInfraPyreflyGate",),
    ".pyright": ("FlextInfraPyrightGate",),
    ".ruff_format": ("FlextInfraRuffFormatGate",),
    ".ruff_lint": ("FlextInfraRuffLintGate",),
    ".runtime_census": ("FlextInfraRuntimeCensusGate",),
    ".silent_failure": ("FlextInfraSilentFailureGate",),
    ".smells": ("FlextInfraSmellsGate",),
    ".tier_whitelist": ("FlextInfraTierWhitelistGate",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraAbstractionBoundaryGate",
    "FlextInfraBanditGate",
    "FlextInfraCanonicalAliasGate",
    "FlextInfraGate",
    "FlextInfraLocCapGate",
    "FlextInfraMarkdownGate",
    "FlextInfraMypyGate",
    "FlextInfraNamespaceGate",
    "FlextInfraPyreflyGate",
    "FlextInfraPyrightGate",
    "FlextInfraRuffFormatGate",
    "FlextInfraRuffLintGate",
    "FlextInfraRuntimeCensusGate",
    "FlextInfraSilentFailureGate",
    "FlextInfraSmellsGate",
    "FlextInfraTierWhitelistGate",
)
