# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.unit.codegen.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".lazy_init_fixture_settings_tests": (
        "TestsFlextInfraLazyInitFixtureSettingsCollision",
    ),
    ".lazy_init_generation_tests": ("TestsFlextInfraCodegenGeneration",),
    ".lazy_init_helpers_tests": ("TestsFlextInfraLazyInitHelpers",),
    ".lazy_init_process_tests": ("TestsFlextInfraLazyInitProcessing",),
    ".lazy_init_registry_wrapper_tests": ("TestsFlextInfraLazyInitCleanup",),
    ".lazy_init_service_tests": ("TestsFlextInfraCodegenLazyInitService",),
    ".lazy_init_tests": (
        "TestAllDirectoriesScanned",
        "TestCheckOnlyMode",
        "TestEdgeCases",
        "TestExcludedDirectories",
    ),
    ".lazy_init_transforms_tests": ("TestsFlextInfraLazyInitTransforms",),
    ".scaffolder_naming_tests": (
        "TestGeneratedClassNamingConvention",
        "TestGeneratedFilesAreValidPython",
    ),
    ".test_codegen_pyproject_conform": ("TestsFlextInfraCodegenPyprojectConform",),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "TestAllDirectoriesScanned",
    "TestCheckOnlyMode",
    "TestEdgeCases",
    "TestExcludedDirectories",
    "TestGeneratedClassNamingConvention",
    "TestGeneratedFilesAreValidPython",
    "TestsFlextInfraCodegenGeneration",
    "TestsFlextInfraCodegenLazyInitService",
    "TestsFlextInfraCodegenPyprojectConform",
    "TestsFlextInfraLazyInitCleanup",
    "TestsFlextInfraLazyInitFixtureSettingsCollision",
    "TestsFlextInfraLazyInitHelpers",
    "TestsFlextInfraLazyInitProcessing",
    "TestsFlextInfraLazyInitTransforms",
    "autofix_workspace_tests",
    "c",
    "census_models_tests",
    "census_tests",
    "consolidator_tests",
    "constants_quality_gate_tests",
    "d",
    "e",
    "h",
    "init_tests",
    "m",
    "main_tests",
    "p",
    "pipeline_tests",
    "r",
    "s",
    "scaffolder_tests",
    "t",
    "td",
    "test_codegen_conform",
    "test_codegen_py_typed",
    "test_codegen_version_file",
    "test_violation_key",
    "tf",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
