"""Conform owns the workspace Makefile and its declared_repository fan-out.

The workspace profile must be generated by ``codegen conform`` (the single
Makefile owner for every profile) and its generic gate verbs must fan out across
declared subprojects through the generic ``flext-infra workspace orchestrate``
primitive, never through hardcoded per-project logic.
"""

from __future__ import annotations

from pathlib import Path

from flext_infra import c, config, m
from flext_infra.codegen.conform import FlextInfraCodegenConform
from flext_tests import tm
from tests import u


class TestsCodegenRepositoryRootFanout:
    def test_conform_owns_repository_root_makefile(self) -> None:
        """The single Makefile render entry includes the workspace profile."""
        makefile_entries = tuple(
            entry
            for entry in config.Infra.codegen.templates.entries
            if entry.destination == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_entries, len=1)
        tm.that(makefile_entries[0].profiles, has=c.Infra.MakeProfile.WORKSPACE)

    def test_repository_root_gate_verbs_fan_out_via_orchestrator(
        self, tmp_path: Path
    ) -> None:
        """Generated workspace check/test route through workspace orchestrate."""
        repository_root = _render_root_makefile(tmp_path)
        for verb in (c.Infra.VERB_CHECK, c.Infra.VERB_TEST):
            execution = tm.ok(
                u.Cli.run_raw(
                    [c.Infra.MAKE, "--dry-run", verb, "APPLY=Y"],
                    cwd=repository_root,
                    remove_env_keys=("MAKEFLAGS",),
                )
            )
            tm.that(u.Cli.process_succeeded(execution.outcome), eq=True)
            tm.that(execution.stdout + execution.stderr, has=f"--verb {verb}")

    def test_repository_root_deps_dispatches_into_the_managed_lock(
        self, tmp_path: Path
    ) -> None:
        """A dry run descends into the verb and shows the work it would do.

        Profiling is opt-in and therefore absent from a gate-path verb; what the
        dispatcher must prove is that `-n` reaches the builtin recipe at all,
        which it does only because the recursive line is marked with `+`.
        """
        repository_root = _render_root_makefile(tmp_path)

        execution = tm.ok(
            u.Cli.run_raw(
                [c.Infra.MAKE, "--dry-run", c.Infra.VERB_DEPS, "APPLY=Y"],
                cwd=repository_root,
                remove_env_keys=("MAKEFLAGS",),
            )
        )

        tm.that(u.Cli.process_succeeded(execution.outcome), eq=True)
        rendered = execution.stdout + execution.stderr
        tm.that(rendered, has="_builtin-deps")
        tm.that(rendered, has="lock --project")
        tm.that(rendered, lacks="-m cProfile")


def _render_root_makefile(tmp_path: Path) -> Path:
    """Render base/Makefile.j2 from a typed workspace fixture."""
    repository = u.Tests.repository_ref("workspace-fixture")
    workspace = m.Infra.WorkspaceSpec(
        name=repository.name,
        beads=m.Infra.BeadsProjectSpec(
            version=1,
            workspace=repository.name,
            database=repository.name,
            issue_prefix=repository.name,
        ),
        repository=repository,
        project=u.Tests.project_spec(repository.name),
    )
    repository_root = tmp_path / "workspace"
    # The bootstrap projection refreshes the dispatcher of an existing checkout:
    # the root is present, even when it carries no metadata or topology yet.
    repository_root.mkdir()
    request = m.Infra.CodegenConformRequest(
        root=repository_root,
        what=c.Infra.CodegenConformSurface.MAKEFILE,
        scope=c.Infra.CodegenConformScope.SELF,
        mode=c.Infra.CodegenConformMode.CHECK,
    )
    plan: m.Infra.CodegenPlan = tm.ok(
        FlextInfraCodegenConform(
            repository_root=repository_root,
            request=request,
            initial_workspace=workspace,
        ).plan(request)
    )
    makefile_plans = tuple(
        fp for fp in plan.files if Path(fp.path).name == c.Infra.MAKEFILE_FILENAME
    )
    tm.that(makefile_plans, len=1)
    makefile_path = repository_root / c.Infra.MAKEFILE_FILENAME
    makefile_path.write_text(
        u.Tests.codegen_file_text(makefile_plans[0]), encoding=c.Infra.ENCODING_DEFAULT
    )
    return repository_root


__all__: tuple[str, ...] = ()
