"""Conform owns the workspace Makefile and its declared subproject fan-out.

The workspace profile must be generated by ``codegen conform`` (the single
Makefile owner for every profile) and its generic gate verbs must fan out across
declared subprojects through the generic ``flext-infra workspace orchestrate``
primitive, never through hardcoded per-project logic.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from flext_tests import tm

from flext_infra import c, config, m
from flext_infra.codegen.conform import FlextInfraCodegenConform
from tests import u, u as test_u


class TestsFlextInfraCodegenRepositoryRootFanout:
    def test_conform_owns_repository_root_makefile(self) -> None:
        """The single Makefile render entry includes the workspace profile."""
        makefile_entries = tuple(
            entry
            for entry in config.Infra.codegen.templates.entries
            if entry.destination == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_entries, len=1)
        tm.that(makefile_entries[0].profiles, has=c.Infra.MakeProfile.WORKSPACE)

    def test_repository_root_projection_uses_workspace_profile(
        self, tmp_path: Path
    ) -> None:
        """The workspace projection exposes both gate routes and the CLI owner."""
        repository_root = self._render_root_makefile(tmp_path)
        rendered = (repository_root / c.Infra.MAKEFILE_FILENAME).read_text(
            encoding=c.Infra.ENCODING_DEFAULT
        )
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb check")
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb test")
        tm.that(rendered, has="MAKE_PROFILE := workspace")
        tm.that(
            rendered, has="PROJECT_FLEXT_INFRA := $(PROJECT_INFRA_RUN) -m flext_infra"
        )

    def test_repository_root_gate_verbs_fan_out_via_orchestrator(
        self, tmp_path: Path
    ) -> None:
        """Generated workspace check/test route through workspace orchestrate."""
        repository_root = self._render_root_makefile(tmp_path)
        for verb in (c.Infra.VERB_CHECK, c.Infra.VERB_TEST):
            execution = tm.ok(
                test_u.Cli.run_raw(
                    [c.Infra.MAKE, "--dry-run", f"_builtin-{verb}"],
                    cwd=repository_root,
                    remove_env_keys=("MAKEFLAGS",),
                )
            )
            tm.that(u.Cli.process_succeeded(execution.outcome), eq=True)
            tm.that(execution.stdout + execution.stderr, has=f"--verb {verb}")

    def test_repository_root_declares_member_propagation(self, tmp_path: Path) -> None:
        """The workspace profile declares propagate through the workspace CLI."""
        repository_root = self._render_root_makefile(tmp_path)
        execution = tm.ok(
            test_u.Cli.run_raw(
                [c.Infra.MAKE, "--dry-run", "_builtin-propagate"],
                cwd=repository_root,
                remove_env_keys=("MAKEFLAGS",),
            )
        )
        tm.that(u.Cli.process_succeeded(execution.outcome), eq=True)
        tm.that(
            execution.stdout + execution.stderr,
            has=f"{c.Infra.CLI_GROUP_WORKSPACE} propagate",
        )

    def test_repository_root_upg_profiles_canonical_modernization(
        self, tmp_path: Path
    ) -> None:
        """Generated upg renders the exact lock-upgrade and modernizer invocation.

        ``upg`` bootstraps Mise (network) and then dispatches its lifecycle with
        the Mise-resolved direnv handoff; the dry run enters that lifecycle with
        the same handoff contract, so its recursive ``+`` activation still runs.
        """
        repository_root = self._render_root_makefile(tmp_path)

        execution = tm.ok(
            u.Tests.run_isolated_make(
                ["--dry-run", "_upg_lifecycle"],
                cwd=repository_root,
                env={
                    "SETUP_DIRENV": tm.not_none(shutil.which("direnv")),
                    "SETUP_DIRENV_XDG_DATA_HOME": str(tmp_path / "direnv-data"),
                },
            )
        )

        tm.that(
            u.Cli.process_succeeded(execution.outcome),
            eq=True,
            msg=execution.stdout + execution.stderr,
        )
        rendered = execution.stdout + execution.stderr
        tm.that(rendered, has="deps modernize")
        tm.that(rendered, has="--apply --rewrite-constraints")
        tm.that(rendered, has="lock --project")
        tm.that(rendered, has="--upgrade --refresh")

    def test_repository_root_upg_locks_tools_from_the_rendered_manifest(
        self, tmp_path: Path
    ) -> None:
        """One ``make upg`` converges: every final lock follows ``gen``.

        ``gen`` renders the tool manifests of the upgraded generator, so the
        first half ends at ``gen`` and hands off to a fresh make invocation of
        the regenerated Makefile. That second half locks the tools again from
        the rendered manifest (without re-resolving the Mise release), then
        re-resolves, reprovisions and checks uv.lock before post-upg.
        """
        repository_root = self._render_root_makefile(tmp_path)
        handoff = {
            "SETUP_DIRENV": tm.not_none(shutil.which("direnv")),
            "SETUP_DIRENV_XDG_DATA_HOME": str(tmp_path / "direnv-data"),
        }
        first, second, database = (
            tm.ok(
                u.Tests.run_isolated_make(arguments, cwd=repository_root, env=handoff)
            )
            for arguments in (
                ["--dry-run", "_upg_lifecycle"],
                ["--dry-run", "_upg_converge"],
                ["--dry-run", "--print-data-base", "help"],
            )
        )
        for execution in (first, second, database):
            tm.that(
                u.Cli.process_succeeded(execution.outcome),
                eq=True,
                msg=execution.stdout + execution.stderr,
            )
        steps = first.stdout.splitlines()
        positions = [
            next(i for i, step in enumerate(steps) if needle in step)
            for needle in (
                "--upgrade --refresh",
                "deps modernize",
                " gen",
                "_upg_relock",
            )
        ]
        tm.that(positions, eq=sorted(positions))
        tm.that(steps[positions[-1] :], len=1)
        tm.that(sum("lock --project" in step for step in steps), eq=1)
        converge = second.stdout.splitlines()
        final_lock = next(i for i, s in enumerate(converge) if "lock --project" in s)
        # The staged lock step verifies its own mirror; the final check is the
        # separate step that validates the published uv.lock after it.
        lock_check = max(i for i, s in enumerate(converge) if "lock --check" in s)
        tm.that(final_lock < lock_check, eq=True)
        tm.that(second.stdout + second.stderr, has="_upg_activated")
        variables = {
            line
            for line in database.stdout.splitlines()
            if line.startswith(("upg: TOOL_BOOTSTRAP_", "_upg_relock: TOOL_BOOTSTRAP_"))
        }
        tm.that(
            variables,
            eq={
                "upg: TOOL_BOOTSTRAP_LIFECYCLE := _upg_lifecycle",
                "upg: TOOL_BOOTSTRAP_RESOLVE := 1",
                "upg: TOOL_BOOTSTRAP_LOCK := 1",
                "_upg_relock: TOOL_BOOTSTRAP_LIFECYCLE := _upg_converge",
                "_upg_relock: TOOL_BOOTSTRAP_LOCK := 1",
            },
        )

    def _render_root_makefile(self, tmp_path: Path) -> Path:
        """Render base/Makefile.j2 from a typed workspace fixture."""
        repository = u.Tests.repository_ref("workspace-fixture")
        workspace = u.Tests.workspace_spec(
            repository, project=u.Tests.project_spec(repository.name)
        )
        # The bootstrap projection refreshes the dispatcher of an existing
        # checkout: the root is a Git repository (the workspace profile resolves
        # itself through Git), even when it carries no topology yet.
        repository_root = u.Tests.git_repository(tmp_path, "workspace")
        request = u.Tests.conform_request(
            repository_root,
            what=c.Infra.CodegenConformSurface.MAKEFILE,
            scope=c.Infra.CodegenConformScope.SELF,
            mode=c.Infra.CodegenConformMode.CHECK,
        )
        plan: m.Infra.CodegenPlan = tm.ok(
            FlextInfraCodegenConform(
                repository_root=repository_root,
                request=request,
                initial_workspace=workspace,
            ).plan(request)
        )
        makefile_plans = tuple(
            fp for fp in plan.files if Path(fp.path).name == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_plans, len=1)
        makefile_path = repository_root / c.Infra.MAKEFILE_FILENAME
        tm.not_none(makefile_plans[0].desired_content)
        makefile_path.write_text(
            u.Tests.codegen_file_text(makefile_plans[0]),
            encoding=c.Infra.ENCODING_DEFAULT,
        )
        return repository_root
