"""Behavioral contracts for generated Git-hook conformance."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from flext_infra import c, m, u
from flext_infra.codegen.conform import FlextInfraCodegenConform
from flext_infra.codegen.project_new import FlextInfraCodegenProjectNew
from flext_tests import tm

if TYPE_CHECKING:
    from flext_infra import p


class TestGitHookConformance:
    """Prove generated hook configs and installed shims converge together."""

    @staticmethod
    def _scaffold(root: Path) -> m.Infra.WorkspaceSpec:
        """Materialize a governed project so the hook config exists on disk."""
        created = tm.ok(
            FlextInfraCodegenProjectNew(
                name="flext-demo",
                kind=c.Infra.ProjectKind.EXTERNAL,
                output_root=root,
                provider="flext-sh",
                license="MIT",
                author_name="FLEXT Team",
                author_email="team@flext.dev",
                upstream="flext_cli",
                year=2026,
                apply_changes=True,
            ).execute()
        )
        return created.plan.workspace

    @staticmethod
    def _check(
        root: Path, workspace: m.Infra.WorkspaceSpec
    ) -> p.Result[m.Infra.CodegenResult]:
        return FlextInfraCodegenConform.execute_request(
            m.Infra.CodegenConformRequest(
                root=root,
                what=c.Infra.CodegenConformSurface.MAKEFILE,
                scope=c.Infra.CodegenConformScope.SELF,
                mode=c.Infra.CodegenConformMode.CHECK,
            ),
            initial_workspace=workspace,
        )

    def test_check_fails_when_declared_hooks_are_not_installed(
        self, infra_git_repo: Path
    ) -> None:
        """An emitted hook config that was never activated is drift."""
        root = infra_git_repo
        workspace = self._scaffold(root)
        hooks_dir = root / ".git" / "hooks"
        for stage in ("pre-commit", "pre-push"):
            tm.ok(u.Cli.files_delete(hooks_dir / stage))

        result = self._check(root, workspace)

        tm.fail(result)
        tm.that(result.error, has="git hook is not installed")
        tm.that(result.error, has="pre-commit")
        tm.that(result.error, has="pre-push")

    def test_apply_installs_every_declared_hook(self, infra_git_repo: Path) -> None:
        """Apply activates the hooks it emits, so the next check is green."""
        root = infra_git_repo
        workspace = self._scaffold(root)
        hooks_dir = root / ".git" / "hooks"
        for stage in ("pre-commit", "pre-push"):
            tm.ok(u.Cli.files_delete(hooks_dir / stage))

        tm.ok(
            FlextInfraCodegenConform.execute_request(
                m.Infra.CodegenConformRequest(
                    root=root,
                    what=c.Infra.CodegenConformSurface.MAKEFILE,
                    scope=c.Infra.CodegenConformScope.SELF,
                    mode=c.Infra.CodegenConformMode.APPLY,
                ),
                initial_workspace=workspace,
            )
        )

        for stage in ("pre-commit", "pre-push"):
            hook = hooks_dir / stage
            tm.that(hook.is_file(), eq=True)
            tm.that(hook.read_text(encoding="utf-8"), has=f"--hook-type={stage}")
        tm.ok(self._check(root, workspace))

    def test_member_hook_config_is_retired_by_conform(self, tmp_path: Path) -> None:
        """A workspace member carries no hook config, and conform removes one."""
        root = tmp_path / "flext-member"
        root.mkdir()
        hook_config = root / ".pre-commit-config.yaml"
        hook_config.write_text(
            "# Generated by flext_infra codegen for flext-member — DO NOT EDIT\n"
            "repos: []\n",
            encoding="utf-8",
        )

        planned = FlextInfraCodegenConform.retired_projection_plans(
            root, c.Infra.MakeProfile.WORKSPACE_MEMBER
        )

        retired = {plan.path for plan in tm.ok(planned) if plan.absent}
        tm.that(hook_config in retired, eq=True)


__all__: list[str] = ["TestGitHookConformance"]
