"""Conform owns the workspace Makefile and its subproject fan-out.

The workspace profile must be generated by ``codegen conform`` (the single
Makefile owner for every profile) and its generic gate verbs must fan out across
declared subprojects through the generic ``flext-infra workspace orchestrate``
primitive, never through hardcoded per-project logic.
"""

from __future__ import annotations

from pathlib import Path

from flext_infra import c, config, m
from flext_infra.codegen.conform import FlextInfraCodegenConform
from flext_tests import tm
from tests import u as test_u


class TestsCodegenWorkspaceRootFanout:
    def test_conform_owns_workspace_root_makefile(self) -> None:
        """The single Makefile render entry includes the workspace profile."""
        makefile_entries = tuple(
            entry
            for entry in config.Infra.codegen.templates.entries
            if entry.destination == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_entries, len=1)
        tm.that(makefile_entries[0].profiles, has=c.Infra.MakeProfile.WORKSPACE)

    def test_workspace_root_gate_verbs_fan_out_via_orchestrator(
        self, tmp_path: Path
    ) -> None:
        """Generated workspace check/test route through workspace orchestrate."""
        rendered = _render_root_makefile(tmp_path)
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb check")
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb test")
        tm.that(rendered, has="MAKE_PROFILE := workspace")
        tm.that(rendered, has="$(FLEXT_INFRA_PYTHON) -m flext_infra")


def _render_root_makefile(tmp_path: Path) -> str:
    """Render base/Makefile.j2 from a typed workspace fixture."""
    repository = test_u.Tests.repository_ref("workspace-fixture")
    workspace = m.Infra.WorkspaceSpec(
        name=repository.name,
        beads=m.Infra.BeadsProjectSpec(
            version=1,
            workspace=repository.name,
            database=repository.name,
            issue_prefix=repository.name,
        ),
        repository=repository,
        project=test_u.Tests.project_spec(repository.name),
    )
    workspace_root = tmp_path / "workspace"
    request = m.Infra.CodegenConformRequest(
        root=workspace_root,
        what=c.Infra.CodegenConformSurface.MAKEFILE,
        scope=c.Infra.CodegenConformScope.SELF,
        mode=c.Infra.CodegenConformMode.CHECK,
    )
    plan: m.Infra.CodegenPlan = tm.ok(
        FlextInfraCodegenConform(
            workspace_root=workspace_root, request=request, initial_workspace=workspace
        ).plan(request)
    )
    makefile_plans = tuple(
        fp for fp in plan.files if Path(fp.path).name == c.Infra.MAKEFILE_FILENAME
    )
    tm.that(makefile_plans, len=1)
    rendered: str = makefile_plans[0].rendered
    return rendered


__all__: tuple[str, ...] = ()
