"""Conform owns the workspace Makefile; the workspace root evaluates only itself.

The workspace profile is generated by ``codegen conform`` (the single Makefile
owner for every profile) and its gate verbs run the same local bodies as every
repository: a workspace root consumes its declared members as libraries and
never fans a verb out across them, locally exactly as in CI (operator ruling
2026-09-29).

Copyright (c) 2026 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import shutil
from pathlib import Path

from flext_tests import tm

from flext_infra import c, config, m
from flext_infra.codegen.conform import FlextInfraCodegenConform
from tests import u, u as test_u


class TestsFlextInfraCodegenRepositoryRootScope:
    """Tests for ``FlextInfraCodegenRepositoryRootScope``."""

    @staticmethod
    def test_conform_owns_repository_root_makefile() -> None:
        """The single Makefile render entry includes the workspace profile."""
        makefile_entries = tuple(
            entry
            for entry in config.Infra.codegen.templates.entries
            if entry.destination == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_entries, len=1)
        tm.that(makefile_entries[0].profiles, has=c.Infra.MakeProfile.WORKSPACE)

    def test_repository_root_projection_uses_workspace_profile(
        self,
        tmp_path: Path,
    ) -> None:
        """The workspace projection has one local body per verb and no fan-out."""
        repository_root = self._render_root_makefile(tmp_path)
        rendered = (repository_root / c.Infra.MAKEFILE_FILENAME).read_text(
            encoding=c.Infra.ENCODING_DEFAULT,
        )
        tm.that(rendered, lacks=["orchestrate", "GITHUB_ACTIONS", "_builtin-self-"])
        tm.that(rendered, has="MAKE_PROFILE := workspace")
        tm.that(
            rendered,
            has="PROJECT_FLEXT_INFRA := $(PROJECT_INFRA_RUN) -m flext_infra",
        )
        tm.that(rendered.endswith("\n"), eq=True)
        tm.that(rendered.endswith("\n\n"), eq=False)

    def test_repository_root_gate_verbs_evaluate_only_the_root(
        self,
        tmp_path: Path,
    ) -> None:
        """Generated workspace check/test run the root's own gates and tests."""
        repository_root = self._render_root_makefile(tmp_path)
        expected = {
            c.Infra.VERB_CHECK: "check run --repository-root",
            c.Infra.VERB_TEST: "_pytest_entry",
        }
        for verb, local_body in expected.items():
            execution = tm.ok(
                test_u.Cli.run_raw(
                    [c.Infra.MAKE, "--dry-run", f"_builtin-{verb}"],
                    cwd=repository_root,
                    remove_env_keys=("MAKEFLAGS",),
                ),
            )
            tm.that(u.Cli.process_succeeded(execution.outcome), eq=True)
            output = execution.stdout + execution.stderr
            tm.that(output, has=local_body)
            tm.that(output, lacks="--verb")

    def test_repository_root_declares_member_propagation(self, tmp_path: Path) -> None:
        """The workspace profile declares propagate through the workspace CLI."""
        repository_root = self._render_root_makefile(tmp_path)
        execution = tm.ok(
            test_u.Cli.run_raw(
                [c.Infra.MAKE, "--dry-run", "_builtin-propagate"],
                cwd=repository_root,
                remove_env_keys=("MAKEFLAGS",),
            ),
        )
        tm.that(u.Cli.process_succeeded(execution.outcome), eq=True)
        tm.that(
            execution.stdout + execution.stderr,
            has=f"{c.Infra.CLI_GROUP_WORKSPACE} propagate",
        )

    def test_repository_root_upg_profiles_canonical_modernization(
        self,
        tmp_path: Path,
    ) -> None:
        """Generated upg renders the exact lock-upgrade and modernizer invocation.

        ``upg`` bootstraps Mise (network) and then dispatches its lifecycle with
        the Mise-resolved direnv handoff; the dry run enters that lifecycle with
        the same handoff contract, so its recursive ``+`` activation still runs.
        """
        repository_root = self._render_root_makefile(tmp_path)

        execution = tm.ok(
            u.Tests.run_isolated_make(
                ["--dry-run", "_upg_lifecycle"],
                cwd=repository_root,
                env={
                    "SETUP_DIRENV": tm.not_none(shutil.which("direnv")),
                    "SETUP_DIRENV_XDG_DATA_HOME": str(tmp_path / "direnv-data"),
                },
            ),
        )

        tm.that(
            u.Cli.process_succeeded(execution.outcome),
            eq=True,
            msg=execution.stdout + execution.stderr,
        )
        rendered = execution.stdout + execution.stderr
        tm.that(rendered, has="deps modernize")
        tm.that(rendered, has="--apply --rewrite-constraints")
        tm.that(rendered, has="lock --project")
        tm.that(rendered, has="--upgrade --refresh")

    def test_repository_root_upg_locks_tools_from_the_rendered_manifest(
        self,
        tmp_path: Path,
    ) -> None:
        """One ``make upg`` converges: every final lock follows ``gen``.

        ``gen`` renders the tool manifests of the upgraded generator, so the
        first half ends at ``gen`` and hands off to a fresh make invocation of
        the regenerated Makefile. That second half locks the tools again from
        the rendered manifest (without re-resolving the Mise release), then
        re-resolves, reprovisions and checks uv.lock before post-upg.
        """
        repository_root = self._render_root_makefile(tmp_path)
        handoff = {
            "SETUP_DIRENV": tm.not_none(shutil.which("direnv")),
            "SETUP_DIRENV_XDG_DATA_HOME": str(tmp_path / "direnv-data"),
        }
        first, second = (
            tm.ok(
                u.Tests.run_isolated_make(arguments, cwd=repository_root, env=handoff),
            )
            for arguments in (
                ["--dry-run", "_upg_lifecycle"],
                ["--dry-run", "_upg_converge"],
            )
        )
        for execution in (first, second):
            tm.that(
                u.Cli.process_succeeded(execution.outcome),
                eq=True,
                msg=execution.stdout + execution.stderr,
            )
        steps = first.stdout.splitlines()
        positions = [
            next(i for i, step in enumerate(steps) if needle in step)
            for needle in (
                "--upgrade --refresh",
                "deps modernize",
                " gen",
                "_upg_relock",
            )
        ]
        tm.that(positions, eq=sorted(positions))
        tm.that(sum("lock --project" in step for step in steps), eq=1)
        converge = second.stdout.splitlines()
        final_lock = next(i for i, s in enumerate(converge) if "lock --project" in s)
        # The staged lock step verifies its own mirror; the final check is the
        # separate step that validates the published uv.lock after it.
        lock_check = max(i for i, s in enumerate(converge) if "lock --check" in s)
        tm.that(final_lock < lock_check, eq=True)
        tm.that(second.stdout + second.stderr, has="_upg_activated")

    @staticmethod
    def _render_root_makefile(tmp_path: Path) -> Path:
        """Render base/Makefile.j2 from a typed workspace fixture.

        Returns:
            The resulting ``Path``.

        """
        repository = u.Tests.repository_ref("workspace-fixture")
        workspace = u.Tests.workspace_spec(
            repository,
            project=u.Tests.project_spec(repository.name),
        )
        # The bootstrap projection refreshes the dispatcher of an existing
        # checkout: the root is a Git repository (the workspace profile resolves
        # itself through Git), even when it carries no topology yet.
        repository_root = u.Tests.git_repository(tmp_path, "workspace")
        request = u.Tests.conform_request(
            repository_root,
            what=c.Infra.CodegenConformSurface.MAKEFILE,
            scope=c.Infra.CodegenConformScope.SELF,
            mode=c.Infra.CodegenConformMode.CHECK,
        )
        plan: m.Infra.CodegenPlan = tm.ok(
            FlextInfraCodegenConform(
                repository_root=repository_root,
                request=request,
                initial_workspace=workspace,
            ).plan(request),
        )
        makefile_plans = tuple(
            fp for fp in plan.files if Path(fp.path).name == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_plans, len=1)
        makefile_path = repository_root / c.Infra.MAKEFILE_FILENAME
        tm.not_none(makefile_plans[0].desired_content)
        makefile_path.write_text(
            u.Tests.codegen_file_text(makefile_plans[0]),
            encoding=c.Infra.ENCODING_DEFAULT,
        )
        return repository_root
