"""Conform is the single owner of the workspace-root Makefile with member fan-out.

The workspace-root profile must be generated by ``codegen conform`` (the single
Makefile owner for every profile) and its generic gate verbs must fan out across
declared members through the generic ``flext-infra workspace orchestrate``
primitive, never through hardcoded per-project logic.
"""

from __future__ import annotations

from pathlib import Path

from flext_infra import c, config, m, u
from flext_infra.codegen.conform import FlextInfraCodegenConform
from flext_tests import tm


class TestsCodegenWorkspaceRootFanout:
    def test_conform_owns_workspace_root_makefile(self) -> None:
        """The single Makefile render entry includes the workspace-root profile."""
        makefile_entries = tuple(
            entry
            for entry in config.Infra.codegen.templates.entries
            if entry.destination == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_entries, len=1)
        tm.that(makefile_entries[0].profiles, has=c.Infra.MakeProfile.WORKSPACE_ROOT)

    def test_workspace_root_gate_verbs_fan_out_via_orchestrator(
        self, tmp_path: Path
    ) -> None:
        """Generated workspace-root check/test route through workspace orchestrate."""
        rendered = _render_root_makefile(tmp_path)
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb check")
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb test")
        tm.that(rendered, has="MAKE_PROFILE := workspace-root")
        tm.that(rendered, lacks="python -m flext_infra")


def _render_root_makefile(tmp_path: Path) -> str:
    """Render the workspace-root profile from an isolated manifest consumer."""
    provider = config.Infra.codegen.providers[0]
    root_repository = next(
        repository
        for repository in config.Infra.codegen.repositories
        if repository.role is c.Infra.RepositoryRole.WORKSPACE_ROOT
        and repository.provider == provider.name
    )
    members = tuple(
        repository
        for repository in config.Infra.codegen.repositories
        if repository.role is c.Infra.RepositoryRole.WORKSPACE_MEMBER
        and repository.provider == root_repository.provider
    )
    workspace_root = tmp_path / root_repository.name
    workspace_root.mkdir()
    tm.ok(
        u.Cli.atomic_write_text_file(
            workspace_root / c.Infra.PYPROJECT_FILENAME,
            (
                "[project]\n"
                f'name = "{root_repository.distribution}"\n'
                'version = "0.1.0"\n'
            ),
        )
    )
    workspace = m.Infra.WorkspaceSpec(
        version=c.Infra.WORKSPACE_MANIFEST_VERSION,
        name=root_repository.name,
        repository=root_repository,
        members=members,
    )
    tm.ok(
        u.Cli.yaml_dump(
            workspace_root / c.CONFIG_DIR_NAME / c.Infra.WORKSPACE_MANIFEST_FILENAME,
            workspace.model_dump(mode="json", exclude_none=True),
        )
    )
    plan = (
        FlextInfraCodegenConform()
        .plan(
            m.Infra.CodegenConformRequest(
                root=workspace_root,
                what=c.Infra.CodegenConformSurface.MAKEFILE,
                scope=c.Infra.CodegenConformScope.SELF,
                mode=c.Infra.CodegenConformMode.CHECK,
            )
        )
        .unwrap()
    )
    makefile_plans = tuple(
        fp for fp in plan.files if Path(fp.path).name == c.Infra.MAKEFILE_FILENAME
    )
    tm.that(makefile_plans, len=1)
    rendered: str = makefile_plans[0].rendered
    return rendered


__all__: tuple[str, ...] = ()
