"""Conform is the single owner of the workspace-root Makefile with member fan-out.

The workspace-root profile must be generated by ``codegen conform`` (the single
Makefile owner for every profile) and its generic gate verbs must fan out across
declared members through the generic ``flext-infra workspace orchestrate``
primitive, never through hardcoded per-project logic.
"""

from __future__ import annotations

from pathlib import Path

from flext_tests import tm

from flext_infra import c, config, m
from flext_infra.codegen.conform import FlextInfraCodegenConform


class TestsCodegenWorkspaceRootFanout:
    def test_conform_owns_workspace_root_makefile(self) -> None:
        """The single Makefile render entry includes the workspace-root profile."""
        makefile_entries = tuple(
            entry
            for entry in config.Infra.codegen.templates.entries
            if entry.destination == c.Infra.MAKEFILE_FILENAME
        )
        tm.that(makefile_entries, len=1)
        tm.that(makefile_entries[0].profiles, has=c.Infra.MakeProfile.WORKSPACE_ROOT)

    def test_workspace_root_gate_verbs_fan_out_via_orchestrator(self) -> None:
        """Generated workspace-root check/test route through workspace orchestrate."""
        rendered = _render_root_makefile()
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb check")
        tm.that(rendered, has="$(WORKSPACE_ORCHESTRATE) --verb test")
        tm.that(rendered, has="MAKE_PROFILE := workspace-root")


def _render_root_makefile() -> str:
    """Render base/Makefile.j2 for the real workspace-root profile via conform."""
    workspace_root = Path(__file__).resolve().parents[3].parent
    plan = (
        FlextInfraCodegenConform()
        .plan(
            m.Infra.CodegenConformRequest(
                root=workspace_root,
                what=c.Infra.CodegenConformSurface.MAKEFILE,
                scope=c.Infra.CodegenConformScope.SELF,
                mode=c.Infra.CodegenConformMode.CHECK,
            )
        )
        .unwrap()
    )
    makefile_plans = tuple(
        fp for fp in plan.files if Path(fp.path).name == c.Infra.MAKEFILE_FILENAME
    )
    tm.that(makefile_plans, len=1)
    rendered: str = makefile_plans[0].rendered
    return rendered


__all__: tuple[str, ...] = ()
