# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Flext infra package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import install_lazy_exports, merge_lazy_imports
from flext_infra.__version__ import *

if _t.TYPE_CHECKING:
    import flext_infra._constants as _flext_infra__constants

    _constants = _flext_infra__constants
    import flext_infra._models as _flext_infra__models
    from flext_infra._constants import (
        FlextInfraBasemkConstants,
        FlextInfraCheckConstants,
        FlextInfraCodegenConstants,
        FlextInfraConstantsBase,
        FlextInfraConstantsCensus,
        FlextInfraConstantsMake,
        FlextInfraConstantsRope,
        FlextInfraConstantsSourceCode,
        FlextInfraCoreConstants,
        FlextInfraDepsConstants,
        FlextInfraDocsConstants,
        FlextInfraGithubConstants,
        FlextInfraRefactorConstants,
        FlextInfraReleaseConstants,
        FlextInfraSharedInfraConstants,
        FlextInfraWorkspaceConstants,
        basemk,
        census,
        check,
        codegen,
        deps,
        docs,
        github,
        make,
        refactor,
        release,
        rope,
        source_code,
        validate,
        workspace,
    )

    _models = _flext_infra__models
    import flext_infra._protocols as _flext_infra__protocols
    from flext_infra._models import (
        FlextInfraBasemkModels,
        FlextInfraCheckModels,
        FlextInfraCodegenDeduplicationModels,
        FlextInfraCodegenModels,
        FlextInfraCoreModels,
        FlextInfraDepsModels,
        FlextInfraDepsModelsToolConfig,
        FlextInfraDepsModelsToolConfigLinters,
        FlextInfraDepsModelsToolConfigTypeCheckers,
        FlextInfraDocsModels,
        FlextInfraEngineModels,
        FlextInfraGatesModels,
        FlextInfraGithubModels,
        FlextInfraModelsBase,
        FlextInfraModelsCensus,
        FlextInfraModelsCliInputs,
        FlextInfraModelsCliInputsCodegen,
        FlextInfraModelsCliInputsOps,
        FlextInfraModelsMixins,
        FlextInfraModelsRope,
        FlextInfraModelsScan,
        FlextInfraNamespaceEnforcerModels,
        FlextInfraRefactorGrepModels,
        FlextInfraRefactorModels,
        FlextInfraRefactorModelsCensus,
        FlextInfraRefactorModelsViolations,
        FlextInfraReleaseModels,
        FlextInfraWorkspaceModels,
        cli_inputs,
        cli_inputs_codegen,
        cli_inputs_ops,
        codegen_deduplication,
        deps_tool_config,
        deps_tool_config_linters,
        deps_tool_config_type_checkers,
        engine,
        gates,
        mixins,
        refactor_ast_grep,
        refactor_census,
        refactor_namespace_enforcer,
        refactor_violations,
        scan,
    )

    _protocols = _flext_infra__protocols
    import flext_infra._typings as _flext_infra__typings
    from flext_infra._protocols import (
        FlextInfraChangeTracker,
        FlextInfraProtocolsBase,
        FlextInfraProtocolsCheck,
        FlextInfraProtocolsRefactor,
        FlextInfraProtocolsRope,
        WorkspaceLoopOutcome,
    )

    _typings = _flext_infra__typings
    import flext_infra._utilities as _flext_infra__utilities
    from flext_infra._typings import (
        FlextInfraTypesAdapters,
        FlextInfraTypesBase,
        FlextInfraTypesRope,
        adapters,
    )

    _utilities = _flext_infra__utilities
    import flext_infra.api as _flext_infra_api
    from flext_infra._utilities import (
        FlextInfraExtraPathsResolutionMixin,
        FlextInfraInternalSyncRepoMixin,
        FlextInfraUtilitiesBase,
        FlextInfraUtilitiesCli,
        FlextInfraUtilitiesCliShared,
        FlextInfraUtilitiesCliSubcommand,
        FlextInfraUtilitiesCodegenConstantAnalysis,
        FlextInfraUtilitiesCodegenConstantDetection,
        FlextInfraUtilitiesCodegenConstantTransformation,
        FlextInfraUtilitiesCodegenExecution,
        FlextInfraUtilitiesCodegenGeneration,
        FlextInfraUtilitiesCodegenGovernance,
        FlextInfraUtilitiesCodegenImportCycles,
        FlextInfraUtilitiesCodegenLazyAliases,
        FlextInfraUtilitiesCodegenLazyMerging,
        FlextInfraUtilitiesCodegenLazyScanning,
        FlextInfraUtilitiesDiscovery,
        FlextInfraUtilitiesDiscoveryScanning,
        FlextInfraUtilitiesDocs,
        FlextInfraUtilitiesDocsApi,
        FlextInfraUtilitiesDocsAudit,
        FlextInfraUtilitiesDocsBuild,
        FlextInfraUtilitiesDocsContract,
        FlextInfraUtilitiesDocsFix,
        FlextInfraUtilitiesDocsGenerate,
        FlextInfraUtilitiesDocsRender,
        FlextInfraUtilitiesDocsScope,
        FlextInfraUtilitiesDocsValidate,
        FlextInfraUtilitiesFormatting,
        FlextInfraUtilitiesGit,
        FlextInfraUtilitiesGithub,
        FlextInfraUtilitiesGithubPr,
        FlextInfraUtilitiesIo,
        FlextInfraUtilitiesIteration,
        FlextInfraUtilitiesLogParser,
        FlextInfraUtilitiesOutput,
        FlextInfraUtilitiesOutputReporting,
        FlextInfraUtilitiesParsing,
        FlextInfraUtilitiesPaths,
        FlextInfraUtilitiesPatterns,
        FlextInfraUtilitiesRelease,
        FlextInfraUtilitiesReporting,
        FlextInfraUtilitiesRope,
        FlextInfraUtilitiesRopeAnalysis,
        FlextInfraUtilitiesRopeAnalysisIntrospection,
        FlextInfraUtilitiesRopeCore,
        FlextInfraUtilitiesRopeHelpers,
        FlextInfraUtilitiesRopeImports,
        FlextInfraUtilitiesRopeSource,
        FlextInfraUtilitiesSafety,
        FlextInfraUtilitiesSelection,
        FlextInfraUtilitiesSubprocess,
        FlextInfraUtilitiesTemplates,
        FlextInfraUtilitiesTerminal,
        FlextInfraUtilitiesToml,
        FlextInfraUtilitiesTomlParse,
        FlextInfraUtilitiesVersioning,
        FlextInfraUtilitiesYaml,
        cli_shared,
        cli_subcommand,
        codegen_constants,
        codegen_execution,
        codegen_generation,
        codegen_import_cycles,
        codegen_lazy,
        deps_paths,
        deps_repos,
        discovery,
        discovery_scanning,
        docs_api,
        docs_audit,
        docs_build,
        docs_contract,
        docs_fix,
        docs_generate,
        docs_render,
        docs_scope,
        docs_validate,
        formatting,
        git,
        github_pr,
        io,
        iteration,
        log_parser,
        parsing,
        paths,
        patterns,
        reporting,
        rope_analysis,
        rope_analysis_introspection,
        rope_core,
        rope_helpers,
        rope_imports,
        rope_source,
        safety,
        selection,
        subprocess,
        templates,
        terminal,
        toml,
        toml_parse,
        versioning,
        yaml,
    )

    api = _flext_infra_api
    import flext_infra.base as _flext_infra_base
    from flext_infra.api import FlextInfra

    base = _flext_infra_base
    import flext_infra.cli as _flext_infra_cli
    from flext_infra.base import FlextInfraCommandContext, FlextInfraServiceBase, s
    from flext_infra.basemk import (
        FlextInfraBaseMkGenerator,
        FlextInfraBaseMkTemplateEngine,
        FlextInfraCliBasemk,
        generator,
    )
    from flext_infra.check import (
        FlextInfraCliCheck,
        FlextInfraConfigFixer,
        FlextInfraGateRegistry,
        FlextInfraWorkspaceChecker,
        FlextInfraWorkspaceCheckerCli,
        FlextInfraWorkspaceCheckGatesMixin,
        build_parser,
        main,
        run_cli,
        services,
        workspace_check,
        workspace_check_cli,
    )

    cli = _flext_infra_cli
    import flext_infra.constants as _flext_infra_constants
    from flext_infra.cli import FlextInfraCli
    from flext_infra.codegen import (
        FlextInfraCliCodegen,
        FlextInfraCodegenCensus,
        FlextInfraCodegenConstantsQualityGate,
        FlextInfraCodegenFixer,
        FlextInfraCodegenGeneration,
        FlextInfraCodegenLazyInit,
        FlextInfraCodegenPyTyped,
        FlextInfraCodegenScaffolder,
        FlextInfraUtilitiesCodegen,
        constants_quality_gate,
        fixer,
        lazy_init,
        py_typed,
        scaffolder,
    )

    constants = _flext_infra_constants
    import flext_infra.detectors as _flext_infra_detectors
    from flext_infra.constants import FlextInfraConstants, FlextInfraConstants as c
    from flext_infra.deps import (
        FlextInfraCliDeps,
        FlextInfraDependencyDetectionAnalysis,
        FlextInfraDependencyDetectionService,
        FlextInfraDependencyDetectorRuntime,
        FlextInfraDependencyPathSync,
        FlextInfraDependencyPathSyncRewrite,
        FlextInfraExtraPathsManager,
        FlextInfraExtraPathsPyrefly,
        FlextInfraInternalDependencySyncService,
        FlextInfraPyprojectModernizer,
        FlextInfraRuntimeDevDependencyDetector,
        detection,
        detection_analysis,
        detector,
        extra_paths,
        extra_paths_pyrefly,
        fix_pyrefly_config,
        internal_sync,
        modernizer,
        path_sync,
        path_sync_rewrite,
    )
    from flext_infra.deps._phases import (
        FlextInfraConsolidateGroupsPhase,
        FlextInfraEnsureCoverageConfigPhase,
        FlextInfraEnsureExtraPathsPhase,
        FlextInfraEnsureFormattingToolingPhase,
        FlextInfraEnsureMypyConfigPhase,
        FlextInfraEnsureNamespaceToolingPhase,
        FlextInfraEnsurePydanticMypyConfigPhase,
        FlextInfraEnsurePyreflyConfigPhase,
        FlextInfraEnsurePyrightConfigPhase,
        FlextInfraEnsurePyrightEnvs,
        FlextInfraEnsurePytestConfigPhase,
        FlextInfraEnsureRuffConfigPhase,
        FlextInfraInjectCommentsPhase,
        consolidate_groups,
        ensure_coverage,
        ensure_extra_paths,
        ensure_formatting,
        ensure_mypy,
        ensure_namespace,
        ensure_pydantic_mypy,
        ensure_pyrefly,
        ensure_pyright,
        ensure_pyright_envs,
        ensure_pytest,
        ensure_ruff,
        inject_comments,
    )

    detectors = _flext_infra_detectors
    import flext_infra.models as _flext_infra_models
    from flext_infra.detectors import (
        DetectorContext,
        FlextInfraClassPlacementDetector,
        FlextInfraCompatibilityAliasDetector,
        FlextInfraCyclicImportDetector,
        FlextInfraFutureAnnotationsDetector,
        FlextInfraImportAliasDetector,
        FlextInfraInternalImportDetector,
        FlextInfraLooseObjectDetector,
        FlextInfraManualProtocolDetector,
        FlextInfraManualTypingAliasDetector,
        FlextInfraMROCompletenessDetector,
        FlextInfraNamespaceFacadeScanner,
        FlextInfraNamespaceSourceDetector,
        FlextInfraRuntimeAliasDetector,
        FlextInfraScanFileMixin,
        class_placement_detector,
        compatibility_alias_detector,
        cyclic_import_detector,
        future_annotations_detector,
        import_alias_detector,
        internal_import_detector,
        loose_object_detector,
        manual_protocol_detector,
        manual_typing_alias_detector,
        mro_completeness_detector,
        namespace_facade_scanner,
        namespace_source_detector,
        runtime_alias_detector,
    )
    from flext_infra.docs import (
        FlextInfraCliDocs,
        FlextInfraDocAuditor,
        FlextInfraDocAuditorMixin,
        FlextInfraDocBuilder,
        FlextInfraDocFixer,
        FlextInfraDocGenerator,
        FlextInfraDocValidator,
        auditor,
        builder,
        validator,
    )
    from flext_infra.gates import (
        FlextInfraBanditGate,
        FlextInfraGate,
        FlextInfraGoGate,
        FlextInfraMarkdownGate,
        FlextInfraMypyGate,
        FlextInfraPyreflyGate,
        FlextInfraPyrightGate,
        FlextInfraRuffFormatGate,
        FlextInfraRuffLintGate,
        bandit,
        go,
        markdown,
        mypy,
        pyrefly,
        pyright,
        ruff_format,
        ruff_lint,
    )
    from flext_infra.github import FlextInfraCliGithub, FlextInfraGithubService, service

    models = _flext_infra_models
    import flext_infra.protocols as _flext_infra_protocols
    from flext_infra.models import FlextInfraModels, FlextInfraModels as m

    protocols = _flext_infra_protocols
    import flext_infra.rules as _flext_infra_rules
    from flext_infra.protocols import FlextInfraProtocols, FlextInfraProtocols as p
    from flext_infra.refactor import (
        FlextInfraCliRefactor,
        FlextInfraGenericTransformerRule,
        FlextInfraNamespaceEnforcer,
        FlextInfraNamespaceEnforcerPhasesMixin,
        FlextInfraProjectClassifier,
        FlextInfraRefactorCensus,
        FlextInfraRefactorClassNestingAnalyzer,
        FlextInfraRefactorClassReconstructorRule,
        FlextInfraRefactorEngine,
        FlextInfraRefactorEngineHelpersMixin,
        FlextInfraRefactorLegacyRemovalTextRule,
        FlextInfraRefactorLooseClassScanner,
        FlextInfraRefactorMigrateToClassMRO,
        FlextInfraRefactorMROClassMigrationTextRule,
        FlextInfraRefactorMROImportRewriter,
        FlextInfraRefactorMROMigrationValidator,
        FlextInfraRefactorMRORedundancyChecker,
        FlextInfraRefactorMROResolver,
        FlextInfraRefactorPatternCorrectionsTextRule,
        FlextInfraRefactorRule,
        FlextInfraRefactorRuleDefinitionValidator,
        FlextInfraRefactorRuleLoader,
        FlextInfraRefactorSafetyManager,
        FlextInfraRefactorSignaturePropagationRule,
        FlextInfraRefactorSymbolPropagationRule,
        FlextInfraRefactorTier0ImportFixRule,
        FlextInfraRefactorTypingAnnotationFixRule,
        FlextInfraRefactorTypingUnificationRule,
        FlextInfraRefactorViolationAnalyzer,
        FlextInfraUtilitiesRefactor,
        FlextInfraUtilitiesRefactorCensus,
        FlextInfraUtilitiesRefactorCli,
        FlextInfraUtilitiesRefactorEngine,
        FlextInfraUtilitiesRefactorMroScan,
        FlextInfraUtilitiesRefactorMroTransform,
        FlextInfraUtilitiesRefactorNamespace,
        FlextInfraUtilitiesRefactorNamespaceCommon,
        FlextInfraUtilitiesRefactorNamespaceFacades,
        FlextInfraUtilitiesRefactorNamespaceMoves,
        FlextInfraUtilitiesRefactorNamespaceMro,
        FlextInfraUtilitiesRefactorNamespaceRuntime,
        FlextInfraUtilitiesRefactorPolicy,
        FlextInfraUtilitiesRefactorPydantic,
        FlextInfraUtilitiesRefactorPydanticAnalysis,
        class_nesting_analyzer,
        migrate_to_class_mro,
        mro_import_rewriter,
        mro_migration_validator,
        mro_resolver,
        namespace_enforcer,
        project_classifier,
        rule,
        rule_definition_validator,
        scanner,
        violation_analyzer,
    )
    from flext_infra.release import (
        FlextInfraCliRelease,
        FlextInfraReleaseOrchestrator,
        FlextInfraReleaseOrchestratorPhases,
        orchestrator,
        orchestrator_phases,
    )

    rules = _flext_infra_rules
    import flext_infra.transformers as _flext_infra_transformers
    from flext_infra.rules import (
        FlextInfraClassNestingRefactorRule,
        FlextInfraRefactorEnsureFutureAnnotationsRule,
        FlextInfraRefactorImportModernizerRule,
        FlextInfraRefactorLegacyRemovalRule,
        FlextInfraRefactorMROClassMigrationRule,
        FlextInfraRefactorPatternCorrectionsRule,
        class_nesting,
        ensure_future_annotations,
        import_modernizer,
        legacy_removal,
        mro_class_migration,
        pattern_corrections,
    )
    from flext_infra.services import (
        FlextInfraCodegenConsolidator,
        FlextInfraCodegenDeduplicator,
        FlextInfraCodegenPipeline,
        FlextInfraToml,
        consolidator,
        deduplicator,
        pipeline,
        toml_engine,
    )

    transformers = _flext_infra_transformers
    import flext_infra.typings as _flext_infra_typings
    from flext_infra.transformers import (
        FlextInfraCensusImportDiscoveryVisitor,
        FlextInfraCensusUsageCollector,
        FlextInfraChangeTrackingTransformer,
        FlextInfraHelperConsolidationTransformer,
        FlextInfraNestedClassPropagationTransformer,
        FlextInfraNormalizerContext,
        FlextInfraRefactorAliasRemover,
        FlextInfraRefactorClassNestingTransformer,
        FlextInfraRefactorClassReconstructor,
        FlextInfraRefactorDeprecatedRemover,
        FlextInfraRefactorImportBypassRemover,
        FlextInfraRefactorImportModernizer,
        FlextInfraRefactorLazyImportFixer,
        FlextInfraRefactorMRORemover,
        FlextInfraRefactorMROSymbolPropagator,
        FlextInfraRefactorSignaturePropagator,
        FlextInfraRefactorSymbolPropagator,
        FlextInfraRefactorTransformerPolicyUtilities,
        FlextInfraRefactorTypingUnifier,
        FlextInfraRopeTransformer,
        FlextInfraTransformerTier0ImportFixer,
        FlextInfraTypingAnnotationReplacer,
        FlextInfraUtilitiesImportNormalizer,
        FlextInfraViolationCensusVisitor,
        alias_remover,
        census_visitors,
        class_reconstructor,
        deprecated_remover,
        helper_consolidation,
        import_bypass_remover,
        lazy_import_fixer,
        mro_remover,
        mro_symbol_propagator,
        nested_class_propagation,
        policy,
        signature_propagator,
        symbol_propagator,
        tier0_import_fixer,
        typing_annotation_replacer,
        typing_unifier,
        violation_census_visitor,
    )

    typings = _flext_infra_typings
    import flext_infra.utilities as _flext_infra_utilities
    from flext_infra.typings import FlextInfraTypes, FlextInfraTypes as t

    utilities = _flext_infra_utilities
    import flext_infra.workspace.maintenance as _flext_infra_workspace_maintenance
    from flext_infra.utilities import FlextInfraUtilities, FlextInfraUtilities as u
    from flext_infra.validate import (
        FlextInfraBaseMkValidator,
        FlextInfraCliValidate,
        FlextInfraInventoryService,
        FlextInfraNamespaceRules,
        FlextInfraNamespaceValidator,
        FlextInfraPytestDiagExtractor,
        FlextInfraSkillValidator,
        FlextInfraStubSupplyChain,
        FlextInfraTextPatternScanner,
        basemk_validator,
        inventory,
        namespace_rules,
        namespace_validator,
        pytest_diag,
        skill_validator,
        stub_chain,
    )
    from flext_infra.workspace import (
        FlextInfraCliWorkspace,
        FlextInfraOrchestratorService,
        FlextInfraProjectMakefileUpdater,
        FlextInfraProjectMigrator,
        FlextInfraSyncService,
        FlextInfraWorkspaceDetector,
        FlextInfraWorkspaceMakefileGenerator,
        migrator,
        project_makefile,
        sync,
        workspace_makefile,
    )

    maintenance = _flext_infra_workspace_maintenance
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.result import FlextResult as r
    from flext_infra.workspace.maintenance import (
        FlextInfraCliMaintenance,
        FlextInfraPythonVersionEnforcer,
        logger,
        python_version,
    )
_LAZY_IMPORTS = merge_lazy_imports(
    (
        "flext_infra._constants",
        "flext_infra._models",
        "flext_infra._protocols",
        "flext_infra._typings",
        "flext_infra._utilities",
        "flext_infra.basemk",
        "flext_infra.check",
        "flext_infra.codegen",
        "flext_infra.deps",
        "flext_infra.detectors",
        "flext_infra.docs",
        "flext_infra.gates",
        "flext_infra.github",
        "flext_infra.refactor",
        "flext_infra.release",
        "flext_infra.rules",
        "flext_infra.services",
        "flext_infra.transformers",
        "flext_infra.validate",
        "flext_infra.workspace",
    ),
    {
        "FlextInfra": "flext_infra.api",
        "FlextInfraCli": "flext_infra.cli",
        "FlextInfraCommandContext": "flext_infra.base",
        "FlextInfraConstants": "flext_infra.constants",
        "FlextInfraModels": "flext_infra.models",
        "FlextInfraProtocols": "flext_infra.protocols",
        "FlextInfraServiceBase": "flext_infra.base",
        "FlextInfraTypes": "flext_infra.typings",
        "FlextInfraUtilities": "flext_infra.utilities",
        "FlextInfraVersion": "flext_infra.__version__",
        "__author__": "flext_infra.__version__",
        "__author_email__": "flext_infra.__version__",
        "__description__": "flext_infra.__version__",
        "__license__": "flext_infra.__version__",
        "__title__": "flext_infra.__version__",
        "__url__": "flext_infra.__version__",
        "__version__": "flext_infra.__version__",
        "__version_info__": "flext_infra.__version__",
        "_constants": "flext_infra._constants",
        "_models": "flext_infra._models",
        "_protocols": "flext_infra._protocols",
        "_typings": "flext_infra._typings",
        "_utilities": "flext_infra._utilities",
        "api": "flext_infra.api",
        "base": "flext_infra.base",
        "c": ("flext_infra.constants", "FlextInfraConstants"),
        "cli": "flext_infra.cli",
        "constants": "flext_infra.constants",
        "d": ("flext_core.decorators", "FlextDecorators"),
        "detectors": "flext_infra.detectors",
        "e": ("flext_core.exceptions", "FlextExceptions"),
        "h": ("flext_core.handlers", "FlextHandlers"),
        "m": ("flext_infra.models", "FlextInfraModels"),
        "models": "flext_infra.models",
        "p": ("flext_infra.protocols", "FlextInfraProtocols"),
        "protocols": "flext_infra.protocols",
        "r": ("flext_core.result", "FlextResult"),
        "rules": "flext_infra.rules",
        "s": "flext_infra.base",
        "t": ("flext_infra.typings", "FlextInfraTypes"),
        "transformers": "flext_infra.transformers",
        "typings": "flext_infra.typings",
        "u": ("flext_infra.utilities", "FlextInfraUtilities"),
        "utilities": "flext_infra.utilities",
        "x": ("flext_core.mixins", "FlextMixins"),
    },
)
_ = _LAZY_IMPORTS.pop("cleanup_submodule_namespace", None)
_ = _LAZY_IMPORTS.pop("install_lazy_exports", None)
_ = _LAZY_IMPORTS.pop("lazy_getattr", None)
_ = _LAZY_IMPORTS.pop("merge_lazy_imports", None)
_ = _LAZY_IMPORTS.pop("output", None)
_ = _LAZY_IMPORTS.pop("output_reporting", None)

__all__ = [
    "DetectorContext",
    "FlextInfra",
    "FlextInfraBanditGate",
    "FlextInfraBaseMkGenerator",
    "FlextInfraBaseMkTemplateEngine",
    "FlextInfraBaseMkValidator",
    "FlextInfraBasemkConstants",
    "FlextInfraBasemkModels",
    "FlextInfraCensusImportDiscoveryVisitor",
    "FlextInfraCensusUsageCollector",
    "FlextInfraChangeTracker",
    "FlextInfraChangeTrackingTransformer",
    "FlextInfraCheckConstants",
    "FlextInfraCheckModels",
    "FlextInfraClassNestingRefactorRule",
    "FlextInfraClassPlacementDetector",
    "FlextInfraCli",
    "FlextInfraCliBasemk",
    "FlextInfraCliCheck",
    "FlextInfraCliCodegen",
    "FlextInfraCliDeps",
    "FlextInfraCliDocs",
    "FlextInfraCliGithub",
    "FlextInfraCliMaintenance",
    "FlextInfraCliRefactor",
    "FlextInfraCliRelease",
    "FlextInfraCliValidate",
    "FlextInfraCliWorkspace",
    "FlextInfraCodegenCensus",
    "FlextInfraCodegenConsolidator",
    "FlextInfraCodegenConstants",
    "FlextInfraCodegenConstantsQualityGate",
    "FlextInfraCodegenDeduplicationModels",
    "FlextInfraCodegenDeduplicator",
    "FlextInfraCodegenFixer",
    "FlextInfraCodegenGeneration",
    "FlextInfraCodegenLazyInit",
    "FlextInfraCodegenModels",
    "FlextInfraCodegenPipeline",
    "FlextInfraCodegenPyTyped",
    "FlextInfraCodegenScaffolder",
    "FlextInfraCommandContext",
    "FlextInfraCompatibilityAliasDetector",
    "FlextInfraConfigFixer",
    "FlextInfraConsolidateGroupsPhase",
    "FlextInfraConstants",
    "FlextInfraConstantsBase",
    "FlextInfraConstantsCensus",
    "FlextInfraConstantsMake",
    "FlextInfraConstantsRope",
    "FlextInfraConstantsSourceCode",
    "FlextInfraCoreConstants",
    "FlextInfraCoreModels",
    "FlextInfraCyclicImportDetector",
    "FlextInfraDependencyDetectionAnalysis",
    "FlextInfraDependencyDetectionService",
    "FlextInfraDependencyDetectorRuntime",
    "FlextInfraDependencyPathSync",
    "FlextInfraDependencyPathSyncRewrite",
    "FlextInfraDepsConstants",
    "FlextInfraDepsModels",
    "FlextInfraDepsModelsToolConfig",
    "FlextInfraDepsModelsToolConfigLinters",
    "FlextInfraDepsModelsToolConfigTypeCheckers",
    "FlextInfraDocAuditor",
    "FlextInfraDocAuditorMixin",
    "FlextInfraDocBuilder",
    "FlextInfraDocFixer",
    "FlextInfraDocGenerator",
    "FlextInfraDocValidator",
    "FlextInfraDocsConstants",
    "FlextInfraDocsModels",
    "FlextInfraEngineModels",
    "FlextInfraEnsureCoverageConfigPhase",
    "FlextInfraEnsureExtraPathsPhase",
    "FlextInfraEnsureFormattingToolingPhase",
    "FlextInfraEnsureMypyConfigPhase",
    "FlextInfraEnsureNamespaceToolingPhase",
    "FlextInfraEnsurePydanticMypyConfigPhase",
    "FlextInfraEnsurePyreflyConfigPhase",
    "FlextInfraEnsurePyrightConfigPhase",
    "FlextInfraEnsurePyrightEnvs",
    "FlextInfraEnsurePytestConfigPhase",
    "FlextInfraEnsureRuffConfigPhase",
    "FlextInfraExtraPathsManager",
    "FlextInfraExtraPathsPyrefly",
    "FlextInfraExtraPathsResolutionMixin",
    "FlextInfraFutureAnnotationsDetector",
    "FlextInfraGate",
    "FlextInfraGateRegistry",
    "FlextInfraGatesModels",
    "FlextInfraGenericTransformerRule",
    "FlextInfraGithubConstants",
    "FlextInfraGithubModels",
    "FlextInfraGithubService",
    "FlextInfraGoGate",
    "FlextInfraHelperConsolidationTransformer",
    "FlextInfraImportAliasDetector",
    "FlextInfraInjectCommentsPhase",
    "FlextInfraInternalDependencySyncService",
    "FlextInfraInternalImportDetector",
    "FlextInfraInternalSyncRepoMixin",
    "FlextInfraInventoryService",
    "FlextInfraLooseObjectDetector",
    "FlextInfraMROCompletenessDetector",
    "FlextInfraManualProtocolDetector",
    "FlextInfraManualTypingAliasDetector",
    "FlextInfraMarkdownGate",
    "FlextInfraModels",
    "FlextInfraModelsBase",
    "FlextInfraModelsCensus",
    "FlextInfraModelsCliInputs",
    "FlextInfraModelsCliInputsCodegen",
    "FlextInfraModelsCliInputsOps",
    "FlextInfraModelsMixins",
    "FlextInfraModelsRope",
    "FlextInfraModelsScan",
    "FlextInfraMypyGate",
    "FlextInfraNamespaceEnforcer",
    "FlextInfraNamespaceEnforcerModels",
    "FlextInfraNamespaceEnforcerPhasesMixin",
    "FlextInfraNamespaceFacadeScanner",
    "FlextInfraNamespaceRules",
    "FlextInfraNamespaceSourceDetector",
    "FlextInfraNamespaceValidator",
    "FlextInfraNestedClassPropagationTransformer",
    "FlextInfraNormalizerContext",
    "FlextInfraOrchestratorService",
    "FlextInfraProjectClassifier",
    "FlextInfraProjectMakefileUpdater",
    "FlextInfraProjectMigrator",
    "FlextInfraProtocols",
    "FlextInfraProtocolsBase",
    "FlextInfraProtocolsCheck",
    "FlextInfraProtocolsRefactor",
    "FlextInfraProtocolsRope",
    "FlextInfraPyprojectModernizer",
    "FlextInfraPyreflyGate",
    "FlextInfraPyrightGate",
    "FlextInfraPytestDiagExtractor",
    "FlextInfraPythonVersionEnforcer",
    "FlextInfraRefactorAliasRemover",
    "FlextInfraRefactorCensus",
    "FlextInfraRefactorClassNestingAnalyzer",
    "FlextInfraRefactorClassNestingTransformer",
    "FlextInfraRefactorClassReconstructor",
    "FlextInfraRefactorClassReconstructorRule",
    "FlextInfraRefactorConstants",
    "FlextInfraRefactorDeprecatedRemover",
    "FlextInfraRefactorEngine",
    "FlextInfraRefactorEngineHelpersMixin",
    "FlextInfraRefactorEnsureFutureAnnotationsRule",
    "FlextInfraRefactorGrepModels",
    "FlextInfraRefactorImportBypassRemover",
    "FlextInfraRefactorImportModernizer",
    "FlextInfraRefactorImportModernizerRule",
    "FlextInfraRefactorLazyImportFixer",
    "FlextInfraRefactorLegacyRemovalRule",
    "FlextInfraRefactorLegacyRemovalTextRule",
    "FlextInfraRefactorLooseClassScanner",
    "FlextInfraRefactorMROClassMigrationRule",
    "FlextInfraRefactorMROClassMigrationTextRule",
    "FlextInfraRefactorMROImportRewriter",
    "FlextInfraRefactorMROMigrationValidator",
    "FlextInfraRefactorMRORedundancyChecker",
    "FlextInfraRefactorMRORemover",
    "FlextInfraRefactorMROResolver",
    "FlextInfraRefactorMROSymbolPropagator",
    "FlextInfraRefactorMigrateToClassMRO",
    "FlextInfraRefactorModels",
    "FlextInfraRefactorModelsCensus",
    "FlextInfraRefactorModelsViolations",
    "FlextInfraRefactorPatternCorrectionsRule",
    "FlextInfraRefactorPatternCorrectionsTextRule",
    "FlextInfraRefactorRule",
    "FlextInfraRefactorRuleDefinitionValidator",
    "FlextInfraRefactorRuleLoader",
    "FlextInfraRefactorSafetyManager",
    "FlextInfraRefactorSignaturePropagationRule",
    "FlextInfraRefactorSignaturePropagator",
    "FlextInfraRefactorSymbolPropagationRule",
    "FlextInfraRefactorSymbolPropagator",
    "FlextInfraRefactorTier0ImportFixRule",
    "FlextInfraRefactorTransformerPolicyUtilities",
    "FlextInfraRefactorTypingAnnotationFixRule",
    "FlextInfraRefactorTypingUnificationRule",
    "FlextInfraRefactorTypingUnifier",
    "FlextInfraRefactorViolationAnalyzer",
    "FlextInfraReleaseConstants",
    "FlextInfraReleaseModels",
    "FlextInfraReleaseOrchestrator",
    "FlextInfraReleaseOrchestratorPhases",
    "FlextInfraRopeTransformer",
    "FlextInfraRuffFormatGate",
    "FlextInfraRuffLintGate",
    "FlextInfraRuntimeAliasDetector",
    "FlextInfraRuntimeDevDependencyDetector",
    "FlextInfraScanFileMixin",
    "FlextInfraServiceBase",
    "FlextInfraSharedInfraConstants",
    "FlextInfraSkillValidator",
    "FlextInfraStubSupplyChain",
    "FlextInfraSyncService",
    "FlextInfraTextPatternScanner",
    "FlextInfraToml",
    "FlextInfraTransformerTier0ImportFixer",
    "FlextInfraTypes",
    "FlextInfraTypesAdapters",
    "FlextInfraTypesBase",
    "FlextInfraTypesRope",
    "FlextInfraTypingAnnotationReplacer",
    "FlextInfraUtilities",
    "FlextInfraUtilitiesBase",
    "FlextInfraUtilitiesCli",
    "FlextInfraUtilitiesCliShared",
    "FlextInfraUtilitiesCliSubcommand",
    "FlextInfraUtilitiesCodegen",
    "FlextInfraUtilitiesCodegenConstantAnalysis",
    "FlextInfraUtilitiesCodegenConstantDetection",
    "FlextInfraUtilitiesCodegenConstantTransformation",
    "FlextInfraUtilitiesCodegenExecution",
    "FlextInfraUtilitiesCodegenGeneration",
    "FlextInfraUtilitiesCodegenGovernance",
    "FlextInfraUtilitiesCodegenImportCycles",
    "FlextInfraUtilitiesCodegenLazyAliases",
    "FlextInfraUtilitiesCodegenLazyMerging",
    "FlextInfraUtilitiesCodegenLazyScanning",
    "FlextInfraUtilitiesDiscovery",
    "FlextInfraUtilitiesDiscoveryScanning",
    "FlextInfraUtilitiesDocs",
    "FlextInfraUtilitiesDocsApi",
    "FlextInfraUtilitiesDocsAudit",
    "FlextInfraUtilitiesDocsBuild",
    "FlextInfraUtilitiesDocsContract",
    "FlextInfraUtilitiesDocsFix",
    "FlextInfraUtilitiesDocsGenerate",
    "FlextInfraUtilitiesDocsRender",
    "FlextInfraUtilitiesDocsScope",
    "FlextInfraUtilitiesDocsValidate",
    "FlextInfraUtilitiesFormatting",
    "FlextInfraUtilitiesGit",
    "FlextInfraUtilitiesGithub",
    "FlextInfraUtilitiesGithubPr",
    "FlextInfraUtilitiesImportNormalizer",
    "FlextInfraUtilitiesIo",
    "FlextInfraUtilitiesIteration",
    "FlextInfraUtilitiesLogParser",
    "FlextInfraUtilitiesOutput",
    "FlextInfraUtilitiesOutputReporting",
    "FlextInfraUtilitiesParsing",
    "FlextInfraUtilitiesPaths",
    "FlextInfraUtilitiesPatterns",
    "FlextInfraUtilitiesRefactor",
    "FlextInfraUtilitiesRefactorCensus",
    "FlextInfraUtilitiesRefactorCli",
    "FlextInfraUtilitiesRefactorEngine",
    "FlextInfraUtilitiesRefactorMroScan",
    "FlextInfraUtilitiesRefactorMroTransform",
    "FlextInfraUtilitiesRefactorNamespace",
    "FlextInfraUtilitiesRefactorNamespaceCommon",
    "FlextInfraUtilitiesRefactorNamespaceFacades",
    "FlextInfraUtilitiesRefactorNamespaceMoves",
    "FlextInfraUtilitiesRefactorNamespaceMro",
    "FlextInfraUtilitiesRefactorNamespaceRuntime",
    "FlextInfraUtilitiesRefactorPolicy",
    "FlextInfraUtilitiesRefactorPydantic",
    "FlextInfraUtilitiesRefactorPydanticAnalysis",
    "FlextInfraUtilitiesRelease",
    "FlextInfraUtilitiesReporting",
    "FlextInfraUtilitiesRope",
    "FlextInfraUtilitiesRopeAnalysis",
    "FlextInfraUtilitiesRopeAnalysisIntrospection",
    "FlextInfraUtilitiesRopeCore",
    "FlextInfraUtilitiesRopeHelpers",
    "FlextInfraUtilitiesRopeImports",
    "FlextInfraUtilitiesRopeSource",
    "FlextInfraUtilitiesSafety",
    "FlextInfraUtilitiesSelection",
    "FlextInfraUtilitiesSubprocess",
    "FlextInfraUtilitiesTemplates",
    "FlextInfraUtilitiesTerminal",
    "FlextInfraUtilitiesToml",
    "FlextInfraUtilitiesTomlParse",
    "FlextInfraUtilitiesVersioning",
    "FlextInfraUtilitiesYaml",
    "FlextInfraVersion",
    "FlextInfraViolationCensusVisitor",
    "FlextInfraWorkspaceCheckGatesMixin",
    "FlextInfraWorkspaceChecker",
    "FlextInfraWorkspaceCheckerCli",
    "FlextInfraWorkspaceConstants",
    "FlextInfraWorkspaceDetector",
    "FlextInfraWorkspaceMakefileGenerator",
    "FlextInfraWorkspaceModels",
    "WorkspaceLoopOutcome",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "_constants",
    "_models",
    "_protocols",
    "_typings",
    "_utilities",
    "adapters",
    "alias_remover",
    "api",
    "auditor",
    "bandit",
    "base",
    "basemk",
    "basemk_validator",
    "build_parser",
    "builder",
    "c",
    "census",
    "census_visitors",
    "check",
    "class_nesting",
    "class_nesting_analyzer",
    "class_placement_detector",
    "class_reconstructor",
    "cli",
    "cli_inputs",
    "cli_inputs_codegen",
    "cli_inputs_ops",
    "cli_shared",
    "cli_subcommand",
    "codegen",
    "codegen_constants",
    "codegen_deduplication",
    "codegen_execution",
    "codegen_generation",
    "codegen_import_cycles",
    "codegen_lazy",
    "compatibility_alias_detector",
    "consolidate_groups",
    "consolidator",
    "constants",
    "constants_quality_gate",
    "cyclic_import_detector",
    "d",
    "deduplicator",
    "deprecated_remover",
    "deps",
    "deps_paths",
    "deps_repos",
    "deps_tool_config",
    "deps_tool_config_linters",
    "deps_tool_config_type_checkers",
    "detection",
    "detection_analysis",
    "detector",
    "detectors",
    "discovery",
    "discovery_scanning",
    "docs",
    "docs_api",
    "docs_audit",
    "docs_build",
    "docs_contract",
    "docs_fix",
    "docs_generate",
    "docs_render",
    "docs_scope",
    "docs_validate",
    "e",
    "engine",
    "ensure_coverage",
    "ensure_extra_paths",
    "ensure_formatting",
    "ensure_future_annotations",
    "ensure_mypy",
    "ensure_namespace",
    "ensure_pydantic_mypy",
    "ensure_pyrefly",
    "ensure_pyright",
    "ensure_pyright_envs",
    "ensure_pytest",
    "ensure_ruff",
    "extra_paths",
    "extra_paths_pyrefly",
    "fix_pyrefly_config",
    "fixer",
    "formatting",
    "future_annotations_detector",
    "gates",
    "generator",
    "git",
    "github",
    "github_pr",
    "go",
    "h",
    "helper_consolidation",
    "import_alias_detector",
    "import_bypass_remover",
    "import_modernizer",
    "inject_comments",
    "internal_import_detector",
    "internal_sync",
    "inventory",
    "io",
    "iteration",
    "lazy_import_fixer",
    "lazy_init",
    "legacy_removal",
    "log_parser",
    "logger",
    "loose_object_detector",
    "m",
    "main",
    "maintenance",
    "make",
    "manual_protocol_detector",
    "manual_typing_alias_detector",
    "markdown",
    "migrate_to_class_mro",
    "migrator",
    "mixins",
    "models",
    "modernizer",
    "mro_class_migration",
    "mro_completeness_detector",
    "mro_import_rewriter",
    "mro_migration_validator",
    "mro_remover",
    "mro_resolver",
    "mro_symbol_propagator",
    "mypy",
    "namespace_enforcer",
    "namespace_facade_scanner",
    "namespace_rules",
    "namespace_source_detector",
    "namespace_validator",
    "nested_class_propagation",
    "orchestrator",
    "orchestrator_phases",
    "p",
    "parsing",
    "path_sync",
    "path_sync_rewrite",
    "paths",
    "pattern_corrections",
    "patterns",
    "pipeline",
    "policy",
    "project_classifier",
    "project_makefile",
    "protocols",
    "py_typed",
    "pyrefly",
    "pyright",
    "pytest_diag",
    "python_version",
    "r",
    "refactor",
    "refactor_ast_grep",
    "refactor_census",
    "refactor_namespace_enforcer",
    "refactor_violations",
    "release",
    "reporting",
    "rope",
    "rope_analysis",
    "rope_analysis_introspection",
    "rope_core",
    "rope_helpers",
    "rope_imports",
    "rope_source",
    "ruff_format",
    "ruff_lint",
    "rule",
    "rule_definition_validator",
    "rules",
    "run_cli",
    "runtime_alias_detector",
    "s",
    "safety",
    "scaffolder",
    "scan",
    "scanner",
    "selection",
    "service",
    "services",
    "signature_propagator",
    "skill_validator",
    "source_code",
    "stub_chain",
    "subprocess",
    "symbol_propagator",
    "sync",
    "t",
    "templates",
    "terminal",
    "tier0_import_fixer",
    "toml",
    "toml_engine",
    "toml_parse",
    "transformers",
    "typing_annotation_replacer",
    "typing_unifier",
    "typings",
    "u",
    "utilities",
    "validate",
    "validator",
    "versioning",
    "violation_analyzer",
    "violation_census_visitor",
    "workspace",
    "workspace_check",
    "workspace_check_cli",
    "workspace_makefile",
    "x",
    "yaml",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
