# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Public API for flext-infra.

Provides access to infrastructure services for workspace management, validation,
dependency handling, and build orchestration in the FLEXT ecosystem.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core import d, e, h, r, s, x
    from flext_core.typings import FlextTypes
    from flext_infra import (
        _utilities,
        basemk,
        check,
        codegen,
        deps,
        docs,
        gates,
        refactor,
        release,
        rules,
        transformers,
        validate,
        workspace,
    )
    from flext_infra.__version__ import (
        __all__,
        __author__,
        __author_email__,
        __description__,
        __license__,
        __title__,
        __url__,
        __version__,
        __version_info__,
    )
    from flext_infra._utilities import (
        FlextInfraUtilitiesCli,
        FlextInfraUtilitiesDiscovery,
        FlextInfraUtilitiesFormatting,
        FlextInfraUtilitiesGit,
        FlextInfraUtilitiesGithub,
        FlextInfraUtilitiesIo,
        FlextInfraUtilitiesIteration,
        FlextInfraUtilitiesOutput,
        FlextInfraUtilitiesParsing,
        FlextInfraUtilitiesPaths,
        FlextInfraUtilitiesPatterns,
        FlextInfraUtilitiesReporting,
        FlextInfraUtilitiesSafety,
        FlextInfraUtilitiesScanning,
        FlextInfraUtilitiesSelection,
        FlextInfraUtilitiesSubprocess,
        FlextInfraUtilitiesTemplates,
        FlextInfraUtilitiesTerminal,
        FlextInfraUtilitiesToml,
        FlextInfraUtilitiesTomlParse,
        FlextInfraUtilitiesVersioning,
        FlextInfraUtilitiesYaml,
        OutputBackend,
        output,
    )
    from flext_infra.basemk import (
        FlextInfraBaseMkGenerator,
        FlextInfraBaseMkTemplateEngine,
    )
    from flext_infra.check import (
        CheckIssue,
        FlextInfraConfigFixer,
        FlextInfraWorkspaceChecker,
        GateExecution,
        ProjectResult,
        build_parser,
        run_cli,
    )
    from flext_infra.codegen import (
        FlextInfraCodegenCensus,
        FlextInfraCodegenConstantsQualityGate,
        FlextInfraCodegenFixer,
        FlextInfraCodegenLazyInit,
        FlextInfraCodegenPyTyped,
        FlextInfraCodegenScaffolder,
        FlextInfraCodegenTransforms,
    )
    from flext_infra.constants import FlextInfraConstants, FlextInfraConstants as c
    from flext_infra.deps import (
        ConsolidateGroupsPhase,
        EnsureCoverageConfigPhase,
        EnsureExtraPathsPhase,
        EnsureFormattingToolingPhase,
        EnsureMypyConfigPhase,
        EnsureNamespaceToolingPhase,
        EnsurePydanticMypyConfigPhase,
        EnsurePyreflyConfigPhase,
        EnsurePyrightConfigPhase,
        EnsurePytestConfigPhase,
        EnsureRuffConfigPhase,
        FlextInfraDependencyDetectionHelpers,
        FlextInfraDependencyDetectionService,
        FlextInfraDependencyPathSync,
        FlextInfraDependencyToolConfig,
        FlextInfraExtraPathsManager,
        FlextInfraInternalDependencySyncService,
        FlextInfraPyprojectModernizer,
        FlextInfraRuntimeDevDependencyDetector,
        InjectCommentsPhase,
        dm,
        shutil,
    )
    from flext_infra.docs import (
        FlextInfraDocAuditor,
        FlextInfraDocBuilder,
        FlextInfraDocFixer,
        FlextInfraDocGenerator,
        FlextInfraDocsShared,
        FlextInfraDocValidator,
    )
    from flext_infra.gates import (
        FlextInfraBanditGate,
        FlextInfraGoGate,
        FlextInfraMarkdownGate,
        FlextInfraMypyGate,
        FlextInfraPyreflyGate,
        FlextInfraPyrightGate,
        FlextInfraRuffFormatGate,
        FlextInfraRuffLintGate,
    )
    from flext_infra.models import FlextInfraModels, FlextInfraModels as m
    from flext_infra.protocols import FlextInfraProtocols, FlextInfraProtocols as p
    from flext_infra.refactor import (
        ClassPlacementDetector,
        CompatibilityAliasDetector,
        CyclicImportDetector,
        DependencyAnalyzer,
        DetectorScanResultBuilder,
        FlextInfraNamespaceEnforcer,
        FlextInfraRefactorCensus,
        FlextInfraRefactorClassNestingAnalyzer,
        FlextInfraRefactorCliSupport,
        FlextInfraRefactorDependencyAnalyzerFacade,
        FlextInfraRefactorDetectorModuleLoader,
        FlextInfraRefactorDetectorPythonModuleLoaderMixin,
        FlextInfraRefactorEngine,
        FlextInfraRefactorLooseClassScanner,
        FlextInfraRefactorMigrateToClassMRO,
        FlextInfraRefactorMROImportRewriter,
        FlextInfraRefactorMROMigrationScanner,
        FlextInfraRefactorMROMigrationTransformer,
        FlextInfraRefactorMROMigrationValidator,
        FlextInfraRefactorMROResolver,
        FlextInfraRefactorOutputRenderer,
        FlextInfraRefactorPydanticCentralizer,
        FlextInfraRefactorPydanticCentralizerAnalysis,
        FlextInfraRefactorRule,
        FlextInfraRefactorRuleDefinitionValidator,
        FlextInfraRefactorRuleLoader,
        FlextInfraRefactorSafetyManager,
        FlextInfraRefactorViolationAnalyzer,
        FutureAnnotationsDetector,
        ImportAliasDetector,
        ImportCollector,
        InternalImportDetector,
        LooseObjectDetector,
        ManualProtocolDetector,
        ManualTypingAliasDetector,
        MROCompletenessDetector,
        NamespaceEnforcementRewriter,
        NamespaceFacadeScanner,
        NamespaceSourceDetector,
        PostCheckGate,
        ProjectClassifier,
        RuntimeAliasDetector,
    )
    from flext_infra.release import FlextInfraReleaseOrchestrator
    from flext_infra.rules import (
        ClassNestingRefactorRule,
        FlextInfraRefactorClassNestingReconstructor,
        FlextInfraRefactorClassReconstructorRule,
        FlextInfraRefactorEnsureFutureAnnotationsRule,
        FlextInfraRefactorImportModernizerRule,
        FlextInfraRefactorLegacyRemovalRule,
        FlextInfraRefactorMROClassMigrationRule,
        FlextInfraRefactorMRORedundancyChecker,
        FlextInfraRefactorPatternCorrectionsRule,
        FlextInfraRefactorSignaturePropagationRule,
        FlextInfraRefactorSignaturePropagator,
        FlextInfraRefactorSymbolPropagationRule,
        FlextInfraRefactorTier0ImportFixRule,
        FlextInfraRefactorTypingAnnotationFixRule,
        FlextInfraRefactorTypingUnificationRule,
        PreCheckGate,
    )
    from flext_infra.transformers import (
        CensusImportDiscoveryVisitor,
        CensusUsageCollector,
        FlextInfraRefactorAliasRemover,
        FlextInfraRefactorClassNestingTransformer,
        FlextInfraRefactorClassReconstructor,
        FlextInfraRefactorDeprecatedRemover,
        FlextInfraRefactorImportBypassRemover,
        FlextInfraRefactorImportModernizer,
        FlextInfraRefactorLazyImportFixer,
        FlextInfraRefactorMROPrivateInlineTransformer,
        FlextInfraRefactorMROQualifiedReferenceTransformer,
        FlextInfraRefactorMROReferenceRewriter,
        FlextInfraRefactorMRORemover,
        FlextInfraRefactorSymbolPropagator,
        FlextInfraRefactorTransformerPolicyUtilities,
        FlextInfraRefactorTypingUnifier,
        FlextInfraTransformerImportInsertion,
        FlextInfraTransformerImportNormalizer,
        FlextInfraTransformerTier0ImportFixer,
        HelperConsolidationTransformer,
        ModelDefinitionCollector,
        ModelReferenceCollector,
        NestedClassPropagationTransformer,
        ProjectAliasDiscovery,
        Tier0ImportAnalysis,
        Tier0ImportAnalyzer,
        Tier0ImportContextDiscovery,
        Tier0ImportFixer,
        TypingAnnotationCensusVisitor,
        TypingAnnotationReplacer,
        UnusedModelRemover,
        ViolationCensusVisitor,
    )
    from flext_infra.typings import FlextInfraTypes, FlextInfraTypes as t
    from flext_infra.utilities import FlextInfraUtilities, FlextInfraUtilities as u
    from flext_infra.validate import (
        FlextInfraBaseMkValidator,
        FlextInfraInventoryService,
        FlextInfraNamespaceValidator,
        FlextInfraPytestDiagExtractor,
        FlextInfraSkillValidator,
        FlextInfraStubSupplyChain,
        FlextInfraTextPatternScanner,
    )
    from flext_infra.workspace import (
        FlextInfraOrchestratorService,
        FlextInfraProjectMigrator,
        FlextInfraPythonVersionEnforcer,
        FlextInfraSyncService,
        FlextInfraWorkspaceDetector,
        WorkspaceMode,
        logger,
        maintenance,
    )

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "CensusImportDiscoveryVisitor": (
        "flext_infra.transformers",
        "CensusImportDiscoveryVisitor",
    ),
    "CensusUsageCollector": ("flext_infra.transformers", "CensusUsageCollector"),
    "CheckIssue": ("flext_infra.check", "CheckIssue"),
    "ClassNestingRefactorRule": ("flext_infra.rules", "ClassNestingRefactorRule"),
    "ClassPlacementDetector": ("flext_infra.refactor", "ClassPlacementDetector"),
    "CompatibilityAliasDetector": (
        "flext_infra.refactor",
        "CompatibilityAliasDetector",
    ),
    "ConsolidateGroupsPhase": ("flext_infra.deps", "ConsolidateGroupsPhase"),
    "CyclicImportDetector": ("flext_infra.refactor", "CyclicImportDetector"),
    "DependencyAnalyzer": ("flext_infra.refactor", "DependencyAnalyzer"),
    "DetectorScanResultBuilder": ("flext_infra.refactor", "DetectorScanResultBuilder"),
    "EnsureCoverageConfigPhase": ("flext_infra.deps", "EnsureCoverageConfigPhase"),
    "EnsureExtraPathsPhase": ("flext_infra.deps", "EnsureExtraPathsPhase"),
    "EnsureFormattingToolingPhase": (
        "flext_infra.deps",
        "EnsureFormattingToolingPhase",
    ),
    "EnsureMypyConfigPhase": ("flext_infra.deps", "EnsureMypyConfigPhase"),
    "EnsureNamespaceToolingPhase": ("flext_infra.deps", "EnsureNamespaceToolingPhase"),
    "EnsurePydanticMypyConfigPhase": (
        "flext_infra.deps",
        "EnsurePydanticMypyConfigPhase",
    ),
    "EnsurePyreflyConfigPhase": ("flext_infra.deps", "EnsurePyreflyConfigPhase"),
    "EnsurePyrightConfigPhase": ("flext_infra.deps", "EnsurePyrightConfigPhase"),
    "EnsurePytestConfigPhase": ("flext_infra.deps", "EnsurePytestConfigPhase"),
    "EnsureRuffConfigPhase": ("flext_infra.deps", "EnsureRuffConfigPhase"),
    "FlextInfraBanditGate": ("flext_infra.gates", "FlextInfraBanditGate"),
    "FlextInfraBaseMkGenerator": ("flext_infra.basemk", "FlextInfraBaseMkGenerator"),
    "FlextInfraBaseMkTemplateEngine": (
        "flext_infra.basemk",
        "FlextInfraBaseMkTemplateEngine",
    ),
    "FlextInfraBaseMkValidator": ("flext_infra.validate", "FlextInfraBaseMkValidator"),
    "FlextInfraCodegenCensus": ("flext_infra.codegen", "FlextInfraCodegenCensus"),
    "FlextInfraCodegenConstantsQualityGate": (
        "flext_infra.codegen",
        "FlextInfraCodegenConstantsQualityGate",
    ),
    "FlextInfraCodegenFixer": ("flext_infra.codegen", "FlextInfraCodegenFixer"),
    "FlextInfraCodegenLazyInit": ("flext_infra.codegen", "FlextInfraCodegenLazyInit"),
    "FlextInfraCodegenPyTyped": ("flext_infra.codegen", "FlextInfraCodegenPyTyped"),
    "FlextInfraCodegenScaffolder": (
        "flext_infra.codegen",
        "FlextInfraCodegenScaffolder",
    ),
    "FlextInfraCodegenTransforms": (
        "flext_infra.codegen",
        "FlextInfraCodegenTransforms",
    ),
    "FlextInfraConfigFixer": ("flext_infra.check", "FlextInfraConfigFixer"),
    "FlextInfraConstants": ("flext_infra.constants", "FlextInfraConstants"),
    "FlextInfraDependencyDetectionHelpers": (
        "flext_infra.deps",
        "FlextInfraDependencyDetectionHelpers",
    ),
    "FlextInfraDependencyDetectionService": (
        "flext_infra.deps",
        "FlextInfraDependencyDetectionService",
    ),
    "FlextInfraDependencyPathSync": (
        "flext_infra.deps",
        "FlextInfraDependencyPathSync",
    ),
    "FlextInfraDependencyToolConfig": (
        "flext_infra.deps",
        "FlextInfraDependencyToolConfig",
    ),
    "FlextInfraDocAuditor": ("flext_infra.docs", "FlextInfraDocAuditor"),
    "FlextInfraDocBuilder": ("flext_infra.docs", "FlextInfraDocBuilder"),
    "FlextInfraDocFixer": ("flext_infra.docs", "FlextInfraDocFixer"),
    "FlextInfraDocGenerator": ("flext_infra.docs", "FlextInfraDocGenerator"),
    "FlextInfraDocValidator": ("flext_infra.docs", "FlextInfraDocValidator"),
    "FlextInfraDocsShared": ("flext_infra.docs", "FlextInfraDocsShared"),
    "FlextInfraExtraPathsManager": ("flext_infra.deps", "FlextInfraExtraPathsManager"),
    "FlextInfraGoGate": ("flext_infra.gates", "FlextInfraGoGate"),
    "FlextInfraInternalDependencySyncService": (
        "flext_infra.deps",
        "FlextInfraInternalDependencySyncService",
    ),
    "FlextInfraInventoryService": (
        "flext_infra.validate",
        "FlextInfraInventoryService",
    ),
    "FlextInfraMarkdownGate": ("flext_infra.gates", "FlextInfraMarkdownGate"),
    "FlextInfraModels": ("flext_infra.models", "FlextInfraModels"),
    "FlextInfraMypyGate": ("flext_infra.gates", "FlextInfraMypyGate"),
    "FlextInfraNamespaceEnforcer": (
        "flext_infra.refactor",
        "FlextInfraNamespaceEnforcer",
    ),
    "FlextInfraNamespaceValidator": (
        "flext_infra.validate",
        "FlextInfraNamespaceValidator",
    ),
    "FlextInfraOrchestratorService": (
        "flext_infra.workspace",
        "FlextInfraOrchestratorService",
    ),
    "FlextInfraProjectMigrator": ("flext_infra.workspace", "FlextInfraProjectMigrator"),
    "FlextInfraProtocols": ("flext_infra.protocols", "FlextInfraProtocols"),
    "FlextInfraPyprojectModernizer": (
        "flext_infra.deps",
        "FlextInfraPyprojectModernizer",
    ),
    "FlextInfraPyreflyGate": ("flext_infra.gates", "FlextInfraPyreflyGate"),
    "FlextInfraPyrightGate": ("flext_infra.gates", "FlextInfraPyrightGate"),
    "FlextInfraPytestDiagExtractor": (
        "flext_infra.validate",
        "FlextInfraPytestDiagExtractor",
    ),
    "FlextInfraPythonVersionEnforcer": (
        "flext_infra.workspace",
        "FlextInfraPythonVersionEnforcer",
    ),
    "FlextInfraRefactorAliasRemover": (
        "flext_infra.transformers",
        "FlextInfraRefactorAliasRemover",
    ),
    "FlextInfraRefactorCensus": ("flext_infra.refactor", "FlextInfraRefactorCensus"),
    "FlextInfraRefactorClassNestingAnalyzer": (
        "flext_infra.refactor",
        "FlextInfraRefactorClassNestingAnalyzer",
    ),
    "FlextInfraRefactorClassNestingReconstructor": (
        "flext_infra.rules",
        "FlextInfraRefactorClassNestingReconstructor",
    ),
    "FlextInfraRefactorClassNestingTransformer": (
        "flext_infra.transformers",
        "FlextInfraRefactorClassNestingTransformer",
    ),
    "FlextInfraRefactorClassReconstructor": (
        "flext_infra.transformers",
        "FlextInfraRefactorClassReconstructor",
    ),
    "FlextInfraRefactorClassReconstructorRule": (
        "flext_infra.rules",
        "FlextInfraRefactorClassReconstructorRule",
    ),
    "FlextInfraRefactorCliSupport": (
        "flext_infra.refactor",
        "FlextInfraRefactorCliSupport",
    ),
    "FlextInfraRefactorDependencyAnalyzerFacade": (
        "flext_infra.refactor",
        "FlextInfraRefactorDependencyAnalyzerFacade",
    ),
    "FlextInfraRefactorDeprecatedRemover": (
        "flext_infra.transformers",
        "FlextInfraRefactorDeprecatedRemover",
    ),
    "FlextInfraRefactorDetectorModuleLoader": (
        "flext_infra.refactor",
        "FlextInfraRefactorDetectorModuleLoader",
    ),
    "FlextInfraRefactorDetectorPythonModuleLoaderMixin": (
        "flext_infra.refactor",
        "FlextInfraRefactorDetectorPythonModuleLoaderMixin",
    ),
    "FlextInfraRefactorEngine": ("flext_infra.refactor", "FlextInfraRefactorEngine"),
    "FlextInfraRefactorEnsureFutureAnnotationsRule": (
        "flext_infra.rules",
        "FlextInfraRefactorEnsureFutureAnnotationsRule",
    ),
    "FlextInfraRefactorImportBypassRemover": (
        "flext_infra.transformers",
        "FlextInfraRefactorImportBypassRemover",
    ),
    "FlextInfraRefactorImportModernizer": (
        "flext_infra.transformers",
        "FlextInfraRefactorImportModernizer",
    ),
    "FlextInfraRefactorImportModernizerRule": (
        "flext_infra.rules",
        "FlextInfraRefactorImportModernizerRule",
    ),
    "FlextInfraRefactorLazyImportFixer": (
        "flext_infra.transformers",
        "FlextInfraRefactorLazyImportFixer",
    ),
    "FlextInfraRefactorLegacyRemovalRule": (
        "flext_infra.rules",
        "FlextInfraRefactorLegacyRemovalRule",
    ),
    "FlextInfraRefactorLooseClassScanner": (
        "flext_infra.refactor",
        "FlextInfraRefactorLooseClassScanner",
    ),
    "FlextInfraRefactorMROClassMigrationRule": (
        "flext_infra.rules",
        "FlextInfraRefactorMROClassMigrationRule",
    ),
    "FlextInfraRefactorMROImportRewriter": (
        "flext_infra.refactor",
        "FlextInfraRefactorMROImportRewriter",
    ),
    "FlextInfraRefactorMROMigrationScanner": (
        "flext_infra.refactor",
        "FlextInfraRefactorMROMigrationScanner",
    ),
    "FlextInfraRefactorMROMigrationTransformer": (
        "flext_infra.refactor",
        "FlextInfraRefactorMROMigrationTransformer",
    ),
    "FlextInfraRefactorMROMigrationValidator": (
        "flext_infra.refactor",
        "FlextInfraRefactorMROMigrationValidator",
    ),
    "FlextInfraRefactorMROPrivateInlineTransformer": (
        "flext_infra.transformers",
        "FlextInfraRefactorMROPrivateInlineTransformer",
    ),
    "FlextInfraRefactorMROQualifiedReferenceTransformer": (
        "flext_infra.transformers",
        "FlextInfraRefactorMROQualifiedReferenceTransformer",
    ),
    "FlextInfraRefactorMRORedundancyChecker": (
        "flext_infra.rules",
        "FlextInfraRefactorMRORedundancyChecker",
    ),
    "FlextInfraRefactorMROReferenceRewriter": (
        "flext_infra.transformers",
        "FlextInfraRefactorMROReferenceRewriter",
    ),
    "FlextInfraRefactorMRORemover": (
        "flext_infra.transformers",
        "FlextInfraRefactorMRORemover",
    ),
    "FlextInfraRefactorMROResolver": (
        "flext_infra.refactor",
        "FlextInfraRefactorMROResolver",
    ),
    "FlextInfraRefactorMigrateToClassMRO": (
        "flext_infra.refactor",
        "FlextInfraRefactorMigrateToClassMRO",
    ),
    "FlextInfraRefactorOutputRenderer": (
        "flext_infra.refactor",
        "FlextInfraRefactorOutputRenderer",
    ),
    "FlextInfraRefactorPatternCorrectionsRule": (
        "flext_infra.rules",
        "FlextInfraRefactorPatternCorrectionsRule",
    ),
    "FlextInfraRefactorPydanticCentralizer": (
        "flext_infra.refactor",
        "FlextInfraRefactorPydanticCentralizer",
    ),
    "FlextInfraRefactorPydanticCentralizerAnalysis": (
        "flext_infra.refactor",
        "FlextInfraRefactorPydanticCentralizerAnalysis",
    ),
    "FlextInfraRefactorRule": ("flext_infra.refactor", "FlextInfraRefactorRule"),
    "FlextInfraRefactorRuleDefinitionValidator": (
        "flext_infra.refactor",
        "FlextInfraRefactorRuleDefinitionValidator",
    ),
    "FlextInfraRefactorRuleLoader": (
        "flext_infra.refactor",
        "FlextInfraRefactorRuleLoader",
    ),
    "FlextInfraRefactorSafetyManager": (
        "flext_infra.refactor",
        "FlextInfraRefactorSafetyManager",
    ),
    "FlextInfraRefactorSignaturePropagationRule": (
        "flext_infra.rules",
        "FlextInfraRefactorSignaturePropagationRule",
    ),
    "FlextInfraRefactorSignaturePropagator": (
        "flext_infra.rules",
        "FlextInfraRefactorSignaturePropagator",
    ),
    "FlextInfraRefactorSymbolPropagationRule": (
        "flext_infra.rules",
        "FlextInfraRefactorSymbolPropagationRule",
    ),
    "FlextInfraRefactorSymbolPropagator": (
        "flext_infra.transformers",
        "FlextInfraRefactorSymbolPropagator",
    ),
    "FlextInfraRefactorTier0ImportFixRule": (
        "flext_infra.rules",
        "FlextInfraRefactorTier0ImportFixRule",
    ),
    "FlextInfraRefactorTransformerPolicyUtilities": (
        "flext_infra.transformers",
        "FlextInfraRefactorTransformerPolicyUtilities",
    ),
    "FlextInfraRefactorTypingAnnotationFixRule": (
        "flext_infra.rules",
        "FlextInfraRefactorTypingAnnotationFixRule",
    ),
    "FlextInfraRefactorTypingUnificationRule": (
        "flext_infra.rules",
        "FlextInfraRefactorTypingUnificationRule",
    ),
    "FlextInfraRefactorTypingUnifier": (
        "flext_infra.transformers",
        "FlextInfraRefactorTypingUnifier",
    ),
    "FlextInfraRefactorViolationAnalyzer": (
        "flext_infra.refactor",
        "FlextInfraRefactorViolationAnalyzer",
    ),
    "FlextInfraReleaseOrchestrator": (
        "flext_infra.release",
        "FlextInfraReleaseOrchestrator",
    ),
    "FlextInfraRuffFormatGate": ("flext_infra.gates", "FlextInfraRuffFormatGate"),
    "FlextInfraRuffLintGate": ("flext_infra.gates", "FlextInfraRuffLintGate"),
    "FlextInfraRuntimeDevDependencyDetector": (
        "flext_infra.deps",
        "FlextInfraRuntimeDevDependencyDetector",
    ),
    "FlextInfraSkillValidator": ("flext_infra.validate", "FlextInfraSkillValidator"),
    "FlextInfraStubSupplyChain": ("flext_infra.validate", "FlextInfraStubSupplyChain"),
    "FlextInfraSyncService": ("flext_infra.workspace", "FlextInfraSyncService"),
    "FlextInfraTextPatternScanner": (
        "flext_infra.validate",
        "FlextInfraTextPatternScanner",
    ),
    "FlextInfraTransformerImportInsertion": (
        "flext_infra.transformers",
        "FlextInfraTransformerImportInsertion",
    ),
    "FlextInfraTransformerImportNormalizer": (
        "flext_infra.transformers",
        "FlextInfraTransformerImportNormalizer",
    ),
    "FlextInfraTransformerTier0ImportFixer": (
        "flext_infra.transformers",
        "FlextInfraTransformerTier0ImportFixer",
    ),
    "FlextInfraTypes": ("flext_infra.typings", "FlextInfraTypes"),
    "FlextInfraUtilities": ("flext_infra.utilities", "FlextInfraUtilities"),
    "FlextInfraUtilitiesCli": ("flext_infra._utilities", "FlextInfraUtilitiesCli"),
    "FlextInfraUtilitiesDiscovery": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesDiscovery",
    ),
    "FlextInfraUtilitiesFormatting": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesFormatting",
    ),
    "FlextInfraUtilitiesGit": ("flext_infra._utilities", "FlextInfraUtilitiesGit"),
    "FlextInfraUtilitiesGithub": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesGithub",
    ),
    "FlextInfraUtilitiesIo": ("flext_infra._utilities", "FlextInfraUtilitiesIo"),
    "FlextInfraUtilitiesIteration": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesIteration",
    ),
    "FlextInfraUtilitiesOutput": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesOutput",
    ),
    "FlextInfraUtilitiesParsing": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesParsing",
    ),
    "FlextInfraUtilitiesPaths": ("flext_infra._utilities", "FlextInfraUtilitiesPaths"),
    "FlextInfraUtilitiesPatterns": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesPatterns",
    ),
    "FlextInfraUtilitiesReporting": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesReporting",
    ),
    "FlextInfraUtilitiesSafety": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesSafety",
    ),
    "FlextInfraUtilitiesScanning": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesScanning",
    ),
    "FlextInfraUtilitiesSelection": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesSelection",
    ),
    "FlextInfraUtilitiesSubprocess": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesSubprocess",
    ),
    "FlextInfraUtilitiesTemplates": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesTemplates",
    ),
    "FlextInfraUtilitiesTerminal": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesTerminal",
    ),
    "FlextInfraUtilitiesToml": ("flext_infra._utilities", "FlextInfraUtilitiesToml"),
    "FlextInfraUtilitiesTomlParse": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesTomlParse",
    ),
    "FlextInfraUtilitiesVersioning": (
        "flext_infra._utilities",
        "FlextInfraUtilitiesVersioning",
    ),
    "FlextInfraUtilitiesYaml": ("flext_infra._utilities", "FlextInfraUtilitiesYaml"),
    "FlextInfraWorkspaceChecker": ("flext_infra.check", "FlextInfraWorkspaceChecker"),
    "FlextInfraWorkspaceDetector": (
        "flext_infra.workspace",
        "FlextInfraWorkspaceDetector",
    ),
    "FutureAnnotationsDetector": ("flext_infra.refactor", "FutureAnnotationsDetector"),
    "GateExecution": ("flext_infra.check", "GateExecution"),
    "HelperConsolidationTransformer": (
        "flext_infra.transformers",
        "HelperConsolidationTransformer",
    ),
    "ImportAliasDetector": ("flext_infra.refactor", "ImportAliasDetector"),
    "ImportCollector": ("flext_infra.refactor", "ImportCollector"),
    "InjectCommentsPhase": ("flext_infra.deps", "InjectCommentsPhase"),
    "InternalImportDetector": ("flext_infra.refactor", "InternalImportDetector"),
    "LooseObjectDetector": ("flext_infra.refactor", "LooseObjectDetector"),
    "MROCompletenessDetector": ("flext_infra.refactor", "MROCompletenessDetector"),
    "ManualProtocolDetector": ("flext_infra.refactor", "ManualProtocolDetector"),
    "ManualTypingAliasDetector": ("flext_infra.refactor", "ManualTypingAliasDetector"),
    "ModelDefinitionCollector": (
        "flext_infra.transformers",
        "ModelDefinitionCollector",
    ),
    "ModelReferenceCollector": ("flext_infra.transformers", "ModelReferenceCollector"),
    "NamespaceEnforcementRewriter": (
        "flext_infra.refactor",
        "NamespaceEnforcementRewriter",
    ),
    "NamespaceFacadeScanner": ("flext_infra.refactor", "NamespaceFacadeScanner"),
    "NamespaceSourceDetector": ("flext_infra.refactor", "NamespaceSourceDetector"),
    "NestedClassPropagationTransformer": (
        "flext_infra.transformers",
        "NestedClassPropagationTransformer",
    ),
    "OutputBackend": ("flext_infra._utilities", "OutputBackend"),
    "PostCheckGate": ("flext_infra.refactor", "PostCheckGate"),
    "PreCheckGate": ("flext_infra.rules", "PreCheckGate"),
    "ProjectAliasDiscovery": ("flext_infra.transformers", "ProjectAliasDiscovery"),
    "ProjectClassifier": ("flext_infra.refactor", "ProjectClassifier"),
    "ProjectResult": ("flext_infra.check", "ProjectResult"),
    "RuntimeAliasDetector": ("flext_infra.refactor", "RuntimeAliasDetector"),
    "Tier0ImportAnalysis": ("flext_infra.transformers", "Tier0ImportAnalysis"),
    "Tier0ImportAnalyzer": ("flext_infra.transformers", "Tier0ImportAnalyzer"),
    "Tier0ImportContextDiscovery": (
        "flext_infra.transformers",
        "Tier0ImportContextDiscovery",
    ),
    "Tier0ImportFixer": ("flext_infra.transformers", "Tier0ImportFixer"),
    "TypingAnnotationCensusVisitor": (
        "flext_infra.transformers",
        "TypingAnnotationCensusVisitor",
    ),
    "TypingAnnotationReplacer": (
        "flext_infra.transformers",
        "TypingAnnotationReplacer",
    ),
    "UnusedModelRemover": ("flext_infra.transformers", "UnusedModelRemover"),
    "ViolationCensusVisitor": ("flext_infra.transformers", "ViolationCensusVisitor"),
    "WorkspaceMode": ("flext_infra.workspace", "WorkspaceMode"),
    "__all__": ("flext_infra.__version__", "__all__"),
    "__author__": ("flext_infra.__version__", "__author__"),
    "__author_email__": ("flext_infra.__version__", "__author_email__"),
    "__description__": ("flext_infra.__version__", "__description__"),
    "__license__": ("flext_infra.__version__", "__license__"),
    "__title__": ("flext_infra.__version__", "__title__"),
    "__url__": ("flext_infra.__version__", "__url__"),
    "__version__": ("flext_infra.__version__", "__version__"),
    "__version_info__": ("flext_infra.__version__", "__version_info__"),
    "_utilities": ("flext_infra._utilities", ""),
    "basemk": ("flext_infra.basemk", ""),
    "build_parser": ("flext_infra.check", "build_parser"),
    "c": ("flext_infra.constants", "FlextInfraConstants"),
    "check": ("flext_infra.check", ""),
    "codegen": ("flext_infra.codegen", ""),
    "d": ("flext_core", "d"),
    "deps": ("flext_infra.deps", ""),
    "dm": ("flext_infra.deps", "dm"),
    "docs": ("flext_infra.docs", ""),
    "e": ("flext_core", "e"),
    "gates": ("flext_infra.gates", ""),
    "h": ("flext_core", "h"),
    "logger": ("flext_infra.workspace", "logger"),
    "m": ("flext_infra.models", "FlextInfraModels"),
    "maintenance": ("flext_infra.workspace", "maintenance"),
    "output": ("flext_infra._utilities", "output"),
    "p": ("flext_infra.protocols", "FlextInfraProtocols"),
    "r": ("flext_core", "r"),
    "refactor": ("flext_infra.refactor", ""),
    "release": ("flext_infra.release", ""),
    "rules": ("flext_infra.rules", ""),
    "run_cli": ("flext_infra.check", "run_cli"),
    "s": ("flext_core", "s"),
    "shutil": ("flext_infra.deps", "shutil"),
    "t": ("flext_infra.typings", "FlextInfraTypes"),
    "transformers": ("flext_infra.transformers", ""),
    "u": ("flext_infra.utilities", "FlextInfraUtilities"),
    "validate": ("flext_infra.validate", ""),
    "workspace": ("flext_infra.workspace", ""),
    "x": ("flext_core", "x"),
}

__all__ = [
    "CensusImportDiscoveryVisitor",
    "CensusUsageCollector",
    "CheckIssue",
    "ClassNestingRefactorRule",
    "ClassPlacementDetector",
    "CompatibilityAliasDetector",
    "ConsolidateGroupsPhase",
    "CyclicImportDetector",
    "DependencyAnalyzer",
    "DetectorScanResultBuilder",
    "EnsureCoverageConfigPhase",
    "EnsureExtraPathsPhase",
    "EnsureFormattingToolingPhase",
    "EnsureMypyConfigPhase",
    "EnsureNamespaceToolingPhase",
    "EnsurePydanticMypyConfigPhase",
    "EnsurePyreflyConfigPhase",
    "EnsurePyrightConfigPhase",
    "EnsurePytestConfigPhase",
    "EnsureRuffConfigPhase",
    "FlextInfraBanditGate",
    "FlextInfraBaseMkGenerator",
    "FlextInfraBaseMkTemplateEngine",
    "FlextInfraBaseMkValidator",
    "FlextInfraCodegenCensus",
    "FlextInfraCodegenConstantsQualityGate",
    "FlextInfraCodegenFixer",
    "FlextInfraCodegenLazyInit",
    "FlextInfraCodegenPyTyped",
    "FlextInfraCodegenScaffolder",
    "FlextInfraCodegenTransforms",
    "FlextInfraConfigFixer",
    "FlextInfraConstants",
    "FlextInfraDependencyDetectionHelpers",
    "FlextInfraDependencyDetectionService",
    "FlextInfraDependencyPathSync",
    "FlextInfraDependencyToolConfig",
    "FlextInfraDocAuditor",
    "FlextInfraDocBuilder",
    "FlextInfraDocFixer",
    "FlextInfraDocGenerator",
    "FlextInfraDocValidator",
    "FlextInfraDocsShared",
    "FlextInfraExtraPathsManager",
    "FlextInfraGoGate",
    "FlextInfraInternalDependencySyncService",
    "FlextInfraInventoryService",
    "FlextInfraMarkdownGate",
    "FlextInfraModels",
    "FlextInfraMypyGate",
    "FlextInfraNamespaceEnforcer",
    "FlextInfraNamespaceValidator",
    "FlextInfraOrchestratorService",
    "FlextInfraProjectMigrator",
    "FlextInfraProtocols",
    "FlextInfraPyprojectModernizer",
    "FlextInfraPyreflyGate",
    "FlextInfraPyrightGate",
    "FlextInfraPytestDiagExtractor",
    "FlextInfraPythonVersionEnforcer",
    "FlextInfraRefactorAliasRemover",
    "FlextInfraRefactorCensus",
    "FlextInfraRefactorClassNestingAnalyzer",
    "FlextInfraRefactorClassNestingReconstructor",
    "FlextInfraRefactorClassNestingTransformer",
    "FlextInfraRefactorClassReconstructor",
    "FlextInfraRefactorClassReconstructorRule",
    "FlextInfraRefactorCliSupport",
    "FlextInfraRefactorDependencyAnalyzerFacade",
    "FlextInfraRefactorDeprecatedRemover",
    "FlextInfraRefactorDetectorModuleLoader",
    "FlextInfraRefactorDetectorPythonModuleLoaderMixin",
    "FlextInfraRefactorEngine",
    "FlextInfraRefactorEnsureFutureAnnotationsRule",
    "FlextInfraRefactorImportBypassRemover",
    "FlextInfraRefactorImportModernizer",
    "FlextInfraRefactorImportModernizerRule",
    "FlextInfraRefactorLazyImportFixer",
    "FlextInfraRefactorLegacyRemovalRule",
    "FlextInfraRefactorLooseClassScanner",
    "FlextInfraRefactorMROClassMigrationRule",
    "FlextInfraRefactorMROImportRewriter",
    "FlextInfraRefactorMROMigrationScanner",
    "FlextInfraRefactorMROMigrationTransformer",
    "FlextInfraRefactorMROMigrationValidator",
    "FlextInfraRefactorMROPrivateInlineTransformer",
    "FlextInfraRefactorMROQualifiedReferenceTransformer",
    "FlextInfraRefactorMRORedundancyChecker",
    "FlextInfraRefactorMROReferenceRewriter",
    "FlextInfraRefactorMRORemover",
    "FlextInfraRefactorMROResolver",
    "FlextInfraRefactorMigrateToClassMRO",
    "FlextInfraRefactorOutputRenderer",
    "FlextInfraRefactorPatternCorrectionsRule",
    "FlextInfraRefactorPydanticCentralizer",
    "FlextInfraRefactorPydanticCentralizerAnalysis",
    "FlextInfraRefactorRule",
    "FlextInfraRefactorRuleDefinitionValidator",
    "FlextInfraRefactorRuleLoader",
    "FlextInfraRefactorSafetyManager",
    "FlextInfraRefactorSignaturePropagationRule",
    "FlextInfraRefactorSignaturePropagator",
    "FlextInfraRefactorSymbolPropagationRule",
    "FlextInfraRefactorSymbolPropagator",
    "FlextInfraRefactorTier0ImportFixRule",
    "FlextInfraRefactorTransformerPolicyUtilities",
    "FlextInfraRefactorTypingAnnotationFixRule",
    "FlextInfraRefactorTypingUnificationRule",
    "FlextInfraRefactorTypingUnifier",
    "FlextInfraRefactorViolationAnalyzer",
    "FlextInfraReleaseOrchestrator",
    "FlextInfraRuffFormatGate",
    "FlextInfraRuffLintGate",
    "FlextInfraRuntimeDevDependencyDetector",
    "FlextInfraSkillValidator",
    "FlextInfraStubSupplyChain",
    "FlextInfraSyncService",
    "FlextInfraTextPatternScanner",
    "FlextInfraTransformerImportInsertion",
    "FlextInfraTransformerImportNormalizer",
    "FlextInfraTransformerTier0ImportFixer",
    "FlextInfraTypes",
    "FlextInfraUtilities",
    "FlextInfraUtilitiesCli",
    "FlextInfraUtilitiesDiscovery",
    "FlextInfraUtilitiesFormatting",
    "FlextInfraUtilitiesGit",
    "FlextInfraUtilitiesGithub",
    "FlextInfraUtilitiesIo",
    "FlextInfraUtilitiesIteration",
    "FlextInfraUtilitiesOutput",
    "FlextInfraUtilitiesParsing",
    "FlextInfraUtilitiesPaths",
    "FlextInfraUtilitiesPatterns",
    "FlextInfraUtilitiesReporting",
    "FlextInfraUtilitiesSafety",
    "FlextInfraUtilitiesScanning",
    "FlextInfraUtilitiesSelection",
    "FlextInfraUtilitiesSubprocess",
    "FlextInfraUtilitiesTemplates",
    "FlextInfraUtilitiesTerminal",
    "FlextInfraUtilitiesToml",
    "FlextInfraUtilitiesTomlParse",
    "FlextInfraUtilitiesVersioning",
    "FlextInfraUtilitiesYaml",
    "FlextInfraWorkspaceChecker",
    "FlextInfraWorkspaceDetector",
    "FutureAnnotationsDetector",
    "GateExecution",
    "HelperConsolidationTransformer",
    "ImportAliasDetector",
    "ImportCollector",
    "InjectCommentsPhase",
    "InternalImportDetector",
    "LooseObjectDetector",
    "MROCompletenessDetector",
    "ManualProtocolDetector",
    "ManualTypingAliasDetector",
    "ModelDefinitionCollector",
    "ModelReferenceCollector",
    "NamespaceEnforcementRewriter",
    "NamespaceFacadeScanner",
    "NamespaceSourceDetector",
    "NestedClassPropagationTransformer",
    "OutputBackend",
    "PostCheckGate",
    "PreCheckGate",
    "ProjectAliasDiscovery",
    "ProjectClassifier",
    "ProjectResult",
    "RuntimeAliasDetector",
    "Tier0ImportAnalysis",
    "Tier0ImportAnalyzer",
    "Tier0ImportContextDiscovery",
    "Tier0ImportFixer",
    "TypingAnnotationCensusVisitor",
    "TypingAnnotationReplacer",
    "UnusedModelRemover",
    "ViolationCensusVisitor",
    "WorkspaceMode",
    "__all__",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "_utilities",
    "basemk",
    "build_parser",
    "c",
    "check",
    "codegen",
    "d",
    "deps",
    "dm",
    "docs",
    "e",
    "gates",
    "h",
    "logger",
    "m",
    "maintenance",
    "output",
    "p",
    "r",
    "refactor",
    "release",
    "rules",
    "run_cli",
    "s",
    "shutil",
    "t",
    "transformers",
    "u",
    "validate",
    "workspace",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
