# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Flext infra package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING as _TYPE_CHECKING

from flext_core.lazy import install_lazy_exports, merge_lazy_imports
from flext_infra.__version__ import (
    FlextInfraVersion,
    __author__,
    __author_email__,
    __description__,
    __license__,
    __title__,
    __url__,
    __version__,
    __version_info__,
)

if _TYPE_CHECKING:
    from flext_cli import d, e, h, r, s, x
    from flext_core import FlextTypes
    from flext_infra import (
        _constants,
        _models,
        _protocols,
        _typings,
        _utilities,
        basemk,
        check,
        cli,
        codegen,
        constants,
        deps,
        detectors,
        gates,
        models,
        protocols,
        refactor,
        rules,
        transformers,
        typings,
        utilities,
        validate,
        workspace,
    )
    from flext_infra._constants import (
        FlextInfraConstantsBase,
        FlextInfraConstantsCensus,
        FlextInfraConstantsRope,
        base,
        census,
        rope,
    )
    from flext_infra._models import (
        FlextInfraModelsBase,
        FlextInfraModelsCensus,
        FlextInfraModelsCliInputs,
        FlextInfraModelsRope,
        FlextInfraModelsScan,
        cli_inputs,
        scan,
    )
    from flext_infra._protocols import FlextInfraProtocolsBase, FlextInfraProtocolsRope
    from flext_infra._typings import (
        FlextInfraTypesAdapters,
        FlextInfraTypesBase,
        FlextInfraTypesCst,
        FlextInfraTypesRope,
        adapters,
        cst,
    )
    from flext_infra._utilities import (
        FlextInfraUtilitiesBase,
        FlextInfraUtilitiesCli,
        FlextInfraUtilitiesDiscovery,
        FlextInfraUtilitiesDocs,
        FlextInfraUtilitiesFormatting,
        FlextInfraUtilitiesGit,
        FlextInfraUtilitiesGithub,
        FlextInfraUtilitiesIo,
        FlextInfraUtilitiesIteration,
        FlextInfraUtilitiesLogParser,
        FlextInfraUtilitiesOutput,
        FlextInfraUtilitiesParsing,
        FlextInfraUtilitiesPaths,
        FlextInfraUtilitiesPatterns,
        FlextInfraUtilitiesRelease,
        FlextInfraUtilitiesReporting,
        FlextInfraUtilitiesRope,
        FlextInfraUtilitiesSafety,
        FlextInfraUtilitiesSelection,
        FlextInfraUtilitiesSubprocess,
        FlextInfraUtilitiesTemplates,
        FlextInfraUtilitiesTerminal,
        FlextInfraUtilitiesToml,
        FlextInfraUtilitiesTomlParse,
        FlextInfraUtilitiesVersioning,
        FlextInfraUtilitiesYaml,
        discovery,
        docs,
        formatting,
        git,
        github,
        io,
        iteration,
        log_parser,
        output,
        parsing,
        paths,
        patterns,
        release,
        reporting,
        safety,
        selection,
        subprocess,
        templates,
        terminal,
        toml,
        toml_parse,
        versioning,
        yaml,
    )
    from flext_infra.basemk import (
        FlextInfraBasemkConstants,
        FlextInfraBaseMkGenerator,
        FlextInfraBasemkModels,
        FlextInfraBaseMkTemplateEngine,
        FlextInfraCliBasemk,
        engine,
        generator,
    )
    from flext_infra.check import (
        FlextInfraCheckConstants,
        FlextInfraCheckModels,
        FlextInfraCliCheck,
        FlextInfraConfigFixer,
        FlextInfraWorkspaceChecker,
        build_parser,
        run_cli,
        services,
        workspace_check,
    )
    from flext_infra.cli import FlextInfraCli, main
    from flext_infra.codegen import (
        FlextInfraCliCodegen,
        FlextInfraCodegenCensus,
        FlextInfraCodegenCoercion,
        FlextInfraCodegenConstants,
        FlextInfraCodegenConstantsQualityGate,
        FlextInfraCodegenExecutionTools,
        FlextInfraCodegenFixer,
        FlextInfraCodegenGeneration,
        FlextInfraCodegenLazyInit,
        FlextInfraCodegenMetrics,
        FlextInfraCodegenMetricsChecks,
        FlextInfraCodegenModels,
        FlextInfraCodegenPyTyped,
        FlextInfraCodegenScaffolder,
        FlextInfraCodegenSnapshot,
        FlextInfraUtilitiesCodegen,
        FlextInfraUtilitiesCodegenAstParsing,
        FlextInfraUtilitiesCodegenConstantDetection,
        FlextInfraUtilitiesCodegenConstantTransformation,
        FlextInfraUtilitiesCodegenExecution,
        FlextInfraUtilitiesCodegenGovernance,
        FlextInfraUtilitiesCodegenTransforms,
        constants_quality_gate,
        fixer,
        lazy_init,
        py_typed,
        scaffolder,
    )
    from flext_infra.constants import FlextInfraConstants, FlextInfraConstants as c
    from flext_infra.deps import (
        FlextInfraCliDeps,
        FlextInfraDependencyDetectionService,
        FlextInfraDependencyDetectorRuntime,
        FlextInfraDependencyPathSync,
        FlextInfraDepsConstants,
        FlextInfraDepsModels,
        FlextInfraExtraPathsManager,
        FlextInfraInternalDependencySyncService,
        FlextInfraPyprojectModernizer,
        FlextInfraRuntimeDevDependencyDetector,
        detection,
        detector,
        extra_paths,
        fix_pyrefly_config,
        internal_sync,
        modernizer,
        path_sync,
    )
    from flext_infra.deps._phases import (
        FlextInfraConsolidateGroupsPhase,
        FlextInfraEnsureCoverageConfigPhase,
        FlextInfraEnsureExtraPathsPhase,
        FlextInfraEnsureFormattingToolingPhase,
        FlextInfraEnsureMypyConfigPhase,
        FlextInfraEnsureNamespaceToolingPhase,
        FlextInfraEnsurePydanticMypyConfigPhase,
        FlextInfraEnsurePyreflyConfigPhase,
        FlextInfraEnsurePyrightConfigPhase,
        FlextInfraEnsurePytestConfigPhase,
        FlextInfraEnsureRuffConfigPhase,
        FlextInfraInjectCommentsPhase,
        consolidate_groups,
        ensure_coverage,
        ensure_extra_paths,
        ensure_formatting,
        ensure_mypy,
        ensure_namespace,
        ensure_pydantic_mypy,
        ensure_pyrefly,
        ensure_pyright,
        ensure_pytest,
        ensure_ruff,
        inject_comments,
    )
    from flext_infra.detectors import (
        DetectorContext,
        FlextInfraClassPlacementDetector,
        FlextInfraCompatibilityAliasDetector,
        FlextInfraCyclicImportDetector,
        FlextInfraDependencyAnalyzer,
        FlextInfraFutureAnnotationsDetector,
        FlextInfraImportAliasDetector,
        FlextInfraInternalImportDetector,
        FlextInfraLooseObjectDetector,
        FlextInfraManualProtocolDetector,
        FlextInfraManualTypingAliasDetector,
        FlextInfraMROCompletenessDetector,
        FlextInfraNamespaceFacadeScanner,
        FlextInfraNamespaceSourceDetector,
        FlextInfraRuntimeAliasDetector,
        FlextInfraScanFileMixin,
        class_placement_detector,
        compatibility_alias_detector,
        cyclic_import_detector,
        dependency_analyzer_base,
        future_annotations_detector,
        import_alias_detector,
        internal_import_detector,
        loose_object_detector,
        manual_protocol_detector,
        manual_typing_alias_detector,
        mro_completeness_detector,
        namespace_facade_scanner,
        namespace_source_detector,
        runtime_alias_detector,
    )
    from flext_infra.docs import (
        FlextInfraCliDocs,
        FlextInfraDocAuditor,
        FlextInfraDocBuilder,
        FlextInfraDocFixer,
        FlextInfraDocGenerator,
        FlextInfraDocsCli,
        FlextInfraDocsConstants,
        FlextInfraDocsModels,
        FlextInfraDocValidator,
        auditor,
        builder,
        validator,
    )
    from flext_infra.gates import (
        FlextInfraBanditGate,
        FlextInfraGate,
        FlextInfraGateRegistry,
        FlextInfraGatesModels,
        FlextInfraGoGate,
        FlextInfraMarkdownGate,
        FlextInfraMypyGate,
        FlextInfraPyreflyGate,
        FlextInfraPyrightGate,
        FlextInfraRuffFormatGate,
        FlextInfraRuffLintGate,
        bandit,
        go,
        markdown,
        mypy,
        pyrefly,
        pyright,
        ruff_format,
        ruff_lint,
    )
    from flext_infra.github import (
        FlextInfraCliGithub,
        FlextInfraGithubConstants,
        FlextInfraGithubModels,
    )
    from flext_infra.models import FlextInfraModels, FlextInfraModels as m
    from flext_infra.protocols import FlextInfraProtocols, FlextInfraProtocols as p
    from flext_infra.refactor import (
        CONTAINER_DICT_SEQ_ADAPTER,
        INFRA_MAPPING_ADAPTER,
        INFRA_SEQ_ADAPTER,
        STR_MAPPING_ADAPTER,
        FlextInfraChangeTracker,
        FlextInfraCliRefactor,
        FlextInfraGenericTransformerRule,
        FlextInfraNamespaceEnforcer,
        FlextInfraNamespaceEnforcerModels,
        FlextInfraPostCheckGate,
        FlextInfraProjectClassifier,
        FlextInfraRefactorAstGrepModels,
        FlextInfraRefactorCensus,
        FlextInfraRefactorClassNestingAnalyzer,
        FlextInfraRefactorClassReconstructorRule,
        FlextInfraRefactorConstants,
        FlextInfraRefactorEngine,
        FlextInfraRefactorLooseClassScanner,
        FlextInfraRefactorMigrateToClassMRO,
        FlextInfraRefactorModels,
        FlextInfraRefactorMROImportRewriter,
        FlextInfraRefactorMROMigrationValidator,
        FlextInfraRefactorMRORedundancyChecker,
        FlextInfraRefactorMROResolver,
        FlextInfraRefactorRule,
        FlextInfraRefactorRuleDefinitionValidator,
        FlextInfraRefactorRuleLoader,
        FlextInfraRefactorSafetyManager,
        FlextInfraRefactorSignaturePropagationRule,
        FlextInfraRefactorSymbolPropagationRule,
        FlextInfraRefactorTier0ImportFixRule,
        FlextInfraRefactorTypingAnnotationFixRule,
        FlextInfraRefactorTypingUnificationRule,
        FlextInfraRefactorViolationAnalyzer,
        FlextInfraUtilitiesRefactor,
        FlextInfraUtilitiesRefactorCli,
        FlextInfraUtilitiesRefactorLoader,
        FlextInfraUtilitiesRefactorMroScan,
        FlextInfraUtilitiesRefactorMroTransform,
        FlextInfraUtilitiesRefactorNamespace,
        FlextInfraUtilitiesRefactorPydantic,
        FlextInfraUtilitiesRefactorPydanticAnalysis,
        class_nesting_analyzer,
        migrate_to_class_mro,
        mro_import_rewriter,
        mro_migration_validator,
        mro_resolver,
        namespace_enforcer,
        project_classifier,
        rule,
        rule_definition_validator,
        scanner,
        violation_analyzer,
    )
    from flext_infra.release import (
        FlextInfraCliRelease,
        FlextInfraReleaseConstants,
        FlextInfraReleaseModels,
        FlextInfraReleaseOrchestrator,
        orchestrator,
    )
    from flext_infra.rules import (
        FlextInfraClassNestingRefactorRule,
        FlextInfraPreCheckGate,
        FlextInfraRefactorClassNestingReconstructor,
        FlextInfraRefactorEnsureFutureAnnotationsRule,
        FlextInfraRefactorImportModernizerRule,
        FlextInfraRefactorLegacyRemovalRule,
        FlextInfraRefactorMROClassMigrationRule,
        FlextInfraRefactorPatternCorrectionsRule,
        class_nesting,
        class_reconstructor,
        ensure_future_annotations,
        import_modernizer,
        legacy_removal,
        mro_class_migration,
        pattern_corrections,
    )
    from flext_infra.transformers import (
        FlextInfraCensusImportDiscoveryVisitor,
        FlextInfraCensusUsageCollector,
        FlextInfraChangeTrackingTransformer,
        FlextInfraDictToMappingTransformer,
        FlextInfraHelperConsolidationTransformer,
        FlextInfraNestedClassPropagationTransformer,
        FlextInfraNormalizerContext,
        FlextInfraRedundantCastRemover,
        FlextInfraRefactorAliasRemover,
        FlextInfraRefactorClassNestingTransformer,
        FlextInfraRefactorClassReconstructor,
        FlextInfraRefactorDeprecatedRemover,
        FlextInfraRefactorImportBypassRemover,
        FlextInfraRefactorImportModernizer,
        FlextInfraRefactorLazyImportFixer,
        FlextInfraRefactorMROPrivateInlineTransformer,
        FlextInfraRefactorMROQualifiedReferenceTransformer,
        FlextInfraRefactorMRORemover,
        FlextInfraRefactorMROSymbolPropagator,
        FlextInfraRefactorSignaturePropagator,
        FlextInfraRefactorSymbolPropagator,
        FlextInfraRefactorTransformerPolicyUtilities,
        FlextInfraRefactorTypingUnifier,
        FlextInfraTransformerTier0ImportFixer,
        FlextInfraTypingAnnotationReplacer,
        FlextInfraUtilitiesImportNormalizer,
        FlextInfraViolationCensusVisitor,
        alias_remover,
        census_visitors,
        deprecated_remover,
        dict_to_mapping,
        helper_consolidation,
        import_bypass_remover,
        lazy_import_fixer,
        mro_private_inline,
        mro_remover,
        mro_symbol_propagator,
        nested_class_propagation,
        policy,
        redundant_cast_remover,
        signature_propagator,
        symbol_propagator,
        tier0_import_fixer,
        typing_annotation_replacer,
        typing_unifier,
        violation_census_visitor,
    )
    from flext_infra.typings import FlextInfraTypes, FlextInfraTypes as t
    from flext_infra.utilities import FlextInfraUtilities, FlextInfraUtilities as u
    from flext_infra.validate import (
        FlextInfraBaseMkValidator,
        FlextInfraCliValidate,
        FlextInfraCoreConstants,
        FlextInfraCoreModels,
        FlextInfraInventoryService,
        FlextInfraNamespaceValidator,
        FlextInfraPytestDiagExtractor,
        FlextInfraSharedInfraConstants,
        FlextInfraSkillValidator,
        FlextInfraStubSupplyChain,
        FlextInfraTextPatternScanner,
        basemk_validator,
        inventory,
        namespace_validator,
        pytest_diag,
        skill_validator,
        stub_chain,
    )
    from flext_infra.workspace import (
        FlextInfraCliWorkspace,
        FlextInfraOrchestratorService,
        FlextInfraProjectMakefileUpdater,
        FlextInfraProjectMigrator,
        FlextInfraSyncService,
        FlextInfraWorkspaceConstants,
        FlextInfraWorkspaceDetector,
        FlextInfraWorkspaceMakefileGenerator,
        FlextInfraWorkspaceMode,
        FlextInfraWorkspaceModels,
        maintenance,
        migrator,
        project_makefile,
        sync,
        workspace_makefile,
    )
    from flext_infra.workspace.maintenance import (
        FlextInfraCliMaintenance,
        FlextInfraPythonVersionEnforcer,
        logger,
        python_version,
    )

_LAZY_IMPORTS: FlextTypes.LazyImportIndex = merge_lazy_imports(
    (
        "flext_infra._constants",
        "flext_infra._models",
        "flext_infra._protocols",
        "flext_infra._typings",
        "flext_infra._utilities",
        "flext_infra.basemk",
        "flext_infra.check",
        "flext_infra.codegen",
        "flext_infra.deps",
        "flext_infra.detectors",
        "flext_infra.docs",
        "flext_infra.gates",
        "flext_infra.github",
        "flext_infra.refactor",
        "flext_infra.release",
        "flext_infra.rules",
        "flext_infra.transformers",
        "flext_infra.validate",
        "flext_infra.workspace",
    ),
    {
        "FlextInfraCli": "flext_infra.cli",
        "FlextInfraConstants": "flext_infra.constants",
        "FlextInfraModels": "flext_infra.models",
        "FlextInfraProtocols": "flext_infra.protocols",
        "FlextInfraTypes": "flext_infra.typings",
        "FlextInfraUtilities": "flext_infra.utilities",
        "_constants": "flext_infra._constants",
        "_models": "flext_infra._models",
        "_protocols": "flext_infra._protocols",
        "_typings": "flext_infra._typings",
        "_utilities": "flext_infra._utilities",
        "basemk": "flext_infra.basemk",
        "c": ("flext_infra.constants", "FlextInfraConstants"),
        "check": "flext_infra.check",
        "cli": "flext_infra.cli",
        "codegen": "flext_infra.codegen",
        "constants": "flext_infra.constants",
        "d": "flext_cli",
        "deps": "flext_infra.deps",
        "detectors": "flext_infra.detectors",
        "e": "flext_cli",
        "gates": "flext_infra.gates",
        "h": "flext_cli",
        "m": ("flext_infra.models", "FlextInfraModels"),
        "main": "flext_infra.cli",
        "models": "flext_infra.models",
        "p": ("flext_infra.protocols", "FlextInfraProtocols"),
        "protocols": "flext_infra.protocols",
        "r": "flext_cli",
        "refactor": "flext_infra.refactor",
        "rules": "flext_infra.rules",
        "s": "flext_cli",
        "t": ("flext_infra.typings", "FlextInfraTypes"),
        "transformers": "flext_infra.transformers",
        "typings": "flext_infra.typings",
        "u": ("flext_infra.utilities", "FlextInfraUtilities"),
        "utilities": "flext_infra.utilities",
        "validate": "flext_infra.validate",
        "workspace": "flext_infra.workspace",
        "x": "flext_cli",
    },
)


install_lazy_exports(
    __name__,
    globals(),
    _LAZY_IMPORTS,
    [
        "FlextInfraVersion",
        "__author__",
        "__author_email__",
        "__description__",
        "__license__",
        "__title__",
        "__url__",
        "__version__",
        "__version_info__",
    ],
)
