# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    "._config": ("config",),
    "._settings": ("settings",),
    ".api": ("FlextInfra", "infra"),
    ".base": ("FlextInfraServiceBase", "s"),
    ".base_selection": ("FlextInfraProjectSelectionServiceBase",),
    ".cli": ("FlextInfraCli", "docs_main", "main"),
    ".constants": ("FlextInfraConstants", "c"),
    ".models": ("FlextInfraModels", "m"),
    ".protocols": ("FlextInfraProtocols", "FlextInfraProtocolsBase", "p"),
    ".typings": ("FlextInfraTypes", "t"),
    ".utilities": ("FlextInfraUtilities", "u"),
    "flext_cli": ("d", "e", "h", "r", "x"),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfra",
    "FlextInfraCli",
    "FlextInfraConstants",
    "FlextInfraModels",
    "FlextInfraProjectSelectionServiceBase",
    "FlextInfraProtocols",
    "FlextInfraProtocolsBase",
    "FlextInfraServiceBase",
    "FlextInfraTypes",
    "FlextInfraUtilities",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "basemk",
    "c",
    "config",
    "d",
    "docs_main",
    "e",
    "h",
    "infra",
    "m",
    "main",
    "p",
    "r",
    "s",
    "settings",
    "t",
    "u",
    "x",
)
