"""Generated public lightweight CLI registry. Do not edit."""

from __future__ import annotations

from types import MappingProxyType
from typing import Final

CLI_OPTION_ARITIES: Final = MappingProxyType({
    "-h": 0,
    "--help": 0,
    "--apply": 0,
    "--check": 0,
    "--check-only": 0,
    "--dry-run": 0,
    "--fail-fast": 0,
    "--verbose": 0,
    "--quiet": 0,
    "--no-fail": 0,
    "--typings": 0,
    "--apply-typings": 0,
    "--no-pip-check": 0,
    "--skip-check": 0,
    "--skip-comments": 0,
    "--audit": 0,
    "--rewrite-constraints": 0,
    "--checks": 1,
    "--docstring-min": 1,
    "--workspace": 1,
    "--projects": 1,
    "--project": 1,
    "--module": 1,
    "--namespace": 1,
    "--gates": 1,
    "--what": 1,
    "--format": 1,
    "--output": 1,
    "--report": 1,
    "--output-dir": 1,
    "--json-output": 1,
    "--reports-dir": 1,
    "--root": 1,
    "--ruff-args": 1,
    "--pyright-args": 1,
    "--operation": 1,
    "--branch": 1,
    "--base": 1,
    "--profile-module": 1,
    "--arguments": 1,
    "--profile": 1,
    "--sort": 1,
    "--limit": 1,
    "--timeout-seconds": 1,
})
CLI_GROUP_DESCRIPTIONS: Final = MappingProxyType({
    "basemk": "Base.mk template generation",
    "check": "Lint gates and pyrefly settings management",
    "codegen": "Code generation and workspace standardization",
    "deps": "Dependency detection and modernization",
    "docs": "Documentation audit, fix, build, generate, validate",
    "github": "GitHub workflows, linting, and PR automation",
    "maintenance": "Python version enforcement",
    "validate": "Infrastructure validators and diagnostics",
    "refactor": "Declarative refactoring and modernization",
    "release": "Release orchestration",
    "workspace": "Workspace detection, sync, orchestration, migration",
})
CLI_GROUP_WHAT_STRATEGIES: Final = MappingProxyType({
    "basemk": "none",
    "check": "check-run",
    "codegen": "none",
    "deps": "none",
    "docs": "none",
    "github": "none",
    "maintenance": "none",
    "validate": "validate-command",
    "refactor": "none",
    "release": "none",
    "workspace": "none",
})
CLI_COMMAND_DESCRIPTIONS: Final = MappingProxyType({
    "basemk": MappingProxyType({
        "generate": "Generate base.mk content from the canonical template"
    }),
    "check": MappingProxyType({
        "run": "Run workspace quality gates",
        "fix-pyrefly-settings": "Repair [tool.pyrefly] blocks",
        "fix-enforcement": "Auto-fix enforcement-catalog violations",
    }),
    "codegen": MappingProxyType({
        "conform": "Conform generated project and workspace files",
        "new": "Create a new FLEXT project from the canonical templates",
        "init": "Generate/refresh PEP 562 lazy-import __init__.py files",
        "census": "Count namespace violations across workspace projects",
        "scaffold": "Generate missing base modules in src/ and tests/",
        "auto-fix": "Auto-fix namespace violations (move Finals/TypeVars)",
        "py-typed": "Create/remove PEP 561 py.typed markers",
        "pipeline": "Run full codegen pipeline",
        "constants-quality-gate": "Run constants migration quality gate",
        "consolidate": "Consolidate inline constants into c.Infra.* references",
        "version-file": "Generate __version__.py from project-metadata SSOT",
    }),
    "deps": MappingProxyType({
        "detect": "Detect runtime vs dev dependencies",
        "extra-paths": "Synchronize pyright/mypy extraPaths",
        "modernize": "Modernize workspace pyproject files",
    }),
    "docs": MappingProxyType({
        "audit": "Audit documentation for broken links and forbidden terms",
        "fix": "Fix documentation issues",
        "build": "Build MkDocs sites",
        "generate": "Generate project docs",
        "serve": "Serve one MkDocs site in dev mode (blocking preview)",
        "validate": "Validate documentation",
    }),
    "github": MappingProxyType({
        "workflows": "Sync GitHub workflow files across workspace",
        "lint": "Lint GitHub workflow files",
        "pr": "Manage pull requests for a single project",
        "pr-workspace": "Manage pull requests across workspace projects",
    }),
    "maintenance": MappingProxyType({"run": "Enforce Python version constraints"}),
    "validate": MappingProxyType({
        "basemk-validate": "Validate base.mk sync",
        "inventory": "Generate scripts inventory",
        "runtime-census": "Post-import Beartype enforcement census for flext_* modules",
        "pytest-diag": "Extract pytest diagnostics",
        "cprofile-report": "Render a bounded report from a cProfile artifact",
        "cprofile-run": "Run a module under portable cProfile supervision",
        "scan": "Scan text files for patterns",
        "skill-validate": "Validate a skill",
        "silent-failure": "Validate silent failure sentinel returns",
        "stub-validate": "Validate stub supply chain",
        "fresh-import": "Guard 7: fresh-process import smoke test",
        "import-cycles": "Guard 1: ROPE-backed import cycle detector",
        "lazy-map-freshness": "Guard 2/3: lazy-map freshness validator",
        "namespace": "Guard: static namespace rules (NS-000..003) via rope",
        "tier-whitelist": "Guard 5: tier-whitelist/abstraction-boundary enforcer",
        "metadata-discipline": "Guard 8: centralized metadata parser discipline",
        "manual-cmd": "Manual-command blocker (\u00a75): pre-commit config drift gate",
    }),
    "refactor": MappingProxyType({
        "apply-renames": "Check or apply an old,new CSV rename list",
        "migrate-mro": "Migrate loose declarations into MRO facade classes",
        "namespace-enforce": "Scan workspace for namespace governance violations",
        "census": "Run a Rope-only workspace census for Python objects",
        "accessor-migrate": "Preview or apply automated get_/set_/is_ migration",
        "wrapper-root-namespace": "Normalize wrapper alias imports to wrapper root and flatten *.Core.Tests paths",
        "modernize-patterns": "Fix u.Cli.print(), pdb, bare except and open() encoding in library code",
        "modernize-pydantic": "Migrate Pydantic v1/legacy patterns to Pydantic v2",
        "modernize-logging": "Migrate logging usage to u.fetch_logger",
        "modernize-result-di": "Migrate result-flow and dependency-injector patterns to FLEXT canonical forms",
        "modernize-cli": "Remove banned CLI helper imports and route u.Cli.print() to cli.display_text()",
    }),
    "release": MappingProxyType({"run": "Run release orchestration CLI flow"}),
    "workspace": MappingProxyType({
        "verify-environment": "Verify live workspace editable provenance",
        "detect": "Detect workspace or standalone mode",
        "sync": "Sync base.mk to project root",
        "orchestrate": "Run make verb across projects",
        "serialize-make": "Run one state-sensitive Make verb under its checkout lock",
        "migrate": "Migrate workspace projects to flext_infra tooling",
        "worktree": "Manage repository-local development worktrees",
    }),
})
CLI_COMMAND_LOADERS: Final = MappingProxyType({
    "basemk": MappingProxyType({
        "generate": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_generate"
    }),
    "check": MappingProxyType({
        "run": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_run",
        "fix-pyrefly-settings": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_fix_pyrefly_settings",
        "fix-enforcement": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_fix_enforcement",
    }),
    "codegen": MappingProxyType({
        "conform": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_conform",
        "new": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_new",
        "init": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_init",
        "census": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_census",
        "scaffold": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_scaffold",
        "auto-fix": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_auto_fix",
        "py-typed": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_py_typed",
        "pipeline": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_pipeline",
        "constants-quality-gate": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_constants_quality_gate",
        "consolidate": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_consolidate",
        "version-file": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_version_file",
    }),
    "deps": MappingProxyType({
        "detect": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_detect",
        "extra-paths": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_extra_paths",
        "modernize": "flext_infra.services.cli_routes_codegen:CodegenRoutes.load_modernize",
    }),
    "docs": MappingProxyType({
        "audit": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_audit",
        "fix": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_fix",
        "build": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_build",
        "generate": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_generate",
        "serve": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_serve",
        "validate": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_validate",
    }),
    "github": MappingProxyType({
        "workflows": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_workflows",
        "lint": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_lint",
        "pr": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_pr",
        "pr-workspace": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_pr_workspace",
    }),
    "maintenance": MappingProxyType({
        "run": "flext_infra.services.cli_routes_validate:ValidationRoutes.load_run"
    }),
    "validate": MappingProxyType({
        "basemk-validate": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_basemk_validate",
        "inventory": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_inventory",
        "runtime-census": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_runtime_census",
        "pytest-diag": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_pytest_diag",
        "cprofile-report": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_cprofile_report",
        "cprofile-run": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_cprofile_run",
        "scan": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_scan",
        "skill-validate": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_skill_validate",
        "silent-failure": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_silent_failure",
        "stub-validate": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_stub_validate",
        "fresh-import": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_fresh_import",
        "import-cycles": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_import_cycles",
        "lazy-map-freshness": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_lazy_map_freshness",
        "namespace": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_namespace",
        "tier-whitelist": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_tier_whitelist",
        "metadata-discipline": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_metadata_discipline",
        "manual-cmd": "flext_infra.services.cli_routes_validate_commands:ValidationCommandRoutes.load_manual_cmd",
    }),
    "refactor": MappingProxyType({
        "apply-renames": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_apply_renames",
        "migrate-mro": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_migrate_mro",
        "namespace-enforce": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_namespace_enforce",
        "census": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_census",
        "accessor-migrate": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_accessor_migrate",
        "wrapper-root-namespace": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_wrapper_root_namespace",
        "modernize-patterns": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_modernize_patterns",
        "modernize-pydantic": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_modernize_pydantic",
        "modernize-logging": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_modernize_logging",
        "modernize-result-di": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_modernize_result_di",
        "modernize-cli": "flext_infra.services.cli_routes_refactor:RefactorRoutes.load_modernize_cli",
    }),
    "release": MappingProxyType({
        "run": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_run"
    }),
    "workspace": MappingProxyType({
        "verify-environment": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_verify_environment",
        "detect": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_detect",
        "sync": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_sync",
        "orchestrate": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_orchestrate",
        "serialize-make": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_serialize_make",
        "migrate": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_migrate",
        "worktree": "flext_infra.services.cli_routes_workspace:WorkspaceRoutes.load_worktree",
    }),
})

__all__: tuple[str, ...] = (
    "CLI_COMMAND_DESCRIPTIONS",
    "CLI_COMMAND_LOADERS",
    "CLI_GROUP_DESCRIPTIONS",
    "CLI_GROUP_WHAT_STRATEGIES",
    "CLI_OPTION_ARITIES",
)
