# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for tests.unit.validate.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".main_cli_tests": ("TestValidateCli",),
    ".namespace_validator_tests": ("TestFlextInfraNamespaceValidator",),
    "flext_tests": (
        "c",
        "d",
        "e",
        "h",
        "m",
        "p",
        "r",
        "s",
        "t",
        "td",
        "tf",
        "tk",
        "tm",
        "tv",
        "u",
        "x",
    ),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "TestFlextInfraNamespaceValidator",
    "TestValidateCli",
    "basemk_validator_tests",
    "c",
    "d",
    "e",
    "fresh_import_tests",
    "h",
    "import_cycles_tests",
    "init_tests",
    "inventory_tests",
    "lazy_map_freshness_tests",
    "loc_delta_tests",
    "m",
    "main_tests",
    "manual_command_tests",
    "metadata_discipline_tests",
    "p",
    "pytest_diag_tests",
    "r",
    "s",
    "scanner_helpers_tests",
    "scanner_tests",
    "silent_failure_tests",
    "skill_validator_tests",
    "stub_chain_tests",
    "t",
    "td",
    "tf",
    "tier_whitelist_tests",
    "tk",
    "tm",
    "tv",
    "u",
    "x",
)
