# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra.validate.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".basemk_validator": ("FlextInfraBaseMkValidator",),
    ".fresh_import": ("FlextInfraValidateFreshImport",),
    ".gate_contract": ("FlextInfraGateContractValidator",),
    ".gate_contract_checks": ("FlextInfraGateContractChecksMixin",),
    ".gate_contract_content": ("FlextInfraGateContractContentMixin",),
    ".gate_contract_models": ("FlextInfraGateContractModels",),
    ".gate_contract_report": ("FlextInfraGateContractReportMixin",),
    ".gate_contract_scan": ("FlextInfraGateContractScanMixin",),
    ".import_cycles": ("FlextInfraValidateImportCycles",),
    ".inventory": ("FlextInfraInventoryService",),
    ".lazy_map_freshness": ("FlextInfraValidateLazyMapFreshness",),
    ".loc_delta": ("FlextInfraLocDeltaValidator",),
    ".manual_command": ("FlextInfraManualCommandValidator",),
    ".metadata_discipline": ("FlextInfraValidateMetadataDiscipline",),
    ".namespace_rules": ("FlextInfraNamespaceRules",),
    ".namespace_validator": ("FlextInfraNamespaceValidator",),
    ".pytest_diag": ("FlextInfraPytestDiagExtractor",),
    ".runtime_census": ("FlextInfraRuntimeCensusValidator",),
    ".scanner": ("FlextInfraTextPatternScanner",),
    ".silent_failure": ("FlextInfraSilentFailureValidator",),
    ".skill_validator": ("FlextInfraSkillValidator",),
    ".stub_chain": ("FlextInfraStubSupplyChain",),
    ".tier_whitelist": ("FlextInfraValidateTierWhitelist",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextInfraBaseMkValidator",
    "FlextInfraGateContractChecksMixin",
    "FlextInfraGateContractContentMixin",
    "FlextInfraGateContractModels",
    "FlextInfraGateContractReportMixin",
    "FlextInfraGateContractScanMixin",
    "FlextInfraGateContractValidator",
    "FlextInfraInventoryService",
    "FlextInfraLocDeltaValidator",
    "FlextInfraManualCommandValidator",
    "FlextInfraNamespaceRules",
    "FlextInfraNamespaceValidator",
    "FlextInfraPytestDiagExtractor",
    "FlextInfraRuntimeCensusValidator",
    "FlextInfraSilentFailureValidator",
    "FlextInfraSkillValidator",
    "FlextInfraStubSupplyChain",
    "FlextInfraTextPatternScanner",
    "FlextInfraValidateFreshImport",
    "FlextInfraValidateImportCycles",
    "FlextInfraValidateLazyMapFreshness",
    "FlextInfraValidateMetadataDiscipline",
    "FlextInfraValidateTierWhitelist",
)
