# AUTO-GENERATED FILE — Regenerate with: make gen
"""Flext Infra package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import (
    build_lazy_import_map,
    install_lazy_exports,
    merge_lazy_imports,
)

if _t.TYPE_CHECKING:
    from _utilities.test_discovery_consolidated import (
        TestsFlextInfraUtilitiesDiscoveryConsolidated,
    )
    from _utilities.test_formatting import TestsFlextInfraUtilitiesFormattingRunRuffFix
    from _utilities.test_iteration import TestIterWorkspacePythonModules
    from _utilities.test_rope_hooks import (
        test_run_rope_post_hooks_applies_mro_migration,
        test_run_rope_post_hooks_dry_run_is_non_mutating,
    )
    from _utilities.test_safety import TestSafetyCheckpoint, TestSafetyRollback
    from _utilities.test_scanning import TestScanModels

    from flext_infra.autofix_workspace_tests import (
        test_files_modified_tracks_affected_files,
        test_flexcore_excluded_from_run,
        test_project_without_src_returns_empty,
    )
    from flext_infra.basemk_validator_tests import (
        TestBaseMkValidatorCore,
        TestBaseMkValidatorEdgeCases,
        TestBaseMkValidatorSha256,
        v,
    )
    from flext_infra.census_models_tests import (
        TestCensusReportModel,
        TestCensusViolationModel,
        TestExcludedProjects,
        TestViolationPattern,
    )
    from flext_infra.census_tests import (
        TestCensusExecute,
        TestFixabilityClassification,
        TestParseViolationInvalid,
        TestParseViolationValid,
    )
    from flext_infra.consolidator_tests import (
        test_execute_scans_real_package_layout,
        test_execute_uses_codegen_project_discovery_and_project_filter,
    )
    from flext_infra.constants_quality_gate_tests import (
        TestConstantsQualityGateCLIDispatch,
        TestConstantsQualityGateVerdict,
    )
    from flext_infra.extended_cli_entry_tests import TestWorkspaceCheckCLI
    from flext_infra.extended_config_fixer_errors_tests import (
        TestConfigFixerPublicBehavior,
    )
    from flext_infra.extended_config_fixer_tests import (
        TestConfigFixerEnsureProjectExcludes,
        TestConfigFixerExecute,
        TestConfigFixerFindPyprojectFiles,
        TestConfigFixerFixSearchPaths,
        TestConfigFixerProcessFile,
        TestConfigFixerRemoveIgnoreSubConfig,
        TestConfigFixerRun,
        TestConfigFixerToArray,
    )
    from flext_infra.extended_error_reporting_tests import (
        TestGateErrorReportingPublicBehavior,
    )
    from flext_infra.extended_gate_bandit_markdown_tests import (
        TestBanditAndMarkdownGates,
    )
    from flext_infra.extended_gate_go_cmd_tests import TestGoGate
    from flext_infra.extended_gate_mypy_pyright_tests import TestTypeGates
    from flext_infra.extended_models_tests import (
        TestCheckIssueFormatted,
        TestProjectResultProperties,
        TestWorkspaceCheckerErrorSummary,
    )
    from flext_infra.extended_project_runners_tests import TestsExtendedProjectRunners
    from flext_infra.extended_resolve_gates_tests import (
        TestWorkspaceCheckerParseGateCSV,
        TestWorkspaceCheckerResolveGates,
    )
    from flext_infra.extended_run_projects_tests import TestRunProjectsPublicBehavior
    from flext_infra.extended_runners_extra_tests import TestExtendedRunnerExtras
    from flext_infra.extended_runners_ruff_tests import TestRealGateRunners
    from flext_infra.extended_runners_tests import TestRunnerPublicBehavior
    from flext_infra.extended_workspace_init_tests import TestWorkspaceChecker
    from flext_infra.fix_pyrefly_config_tests import (
        test_fix_pyrefly_config_main_executes_real_cli_help,
    )
    from flext_infra.fixtures import (
        deptry_report_payload,
        modernizer_workspace,
        modernizer_workspace_with_projects,
        real_docs_project,
        real_makefile_project,
        real_python_package,
        real_toml_project,
        real_workspace,
        tool_config_document,
    )
    from flext_infra.fixtures_git import real_git_repo
    from flext_infra.init_tests import (
        TestCoreModuleInit,
        TestFlextInfraCheck,
        test_codegen_dir_returns_all_exports,
        test_codegen_getattr_raises_attribute_error,
        test_codegen_lazy_imports_work,
    )
    from flext_infra.inventory_tests import (
        TestInventoryServiceCore,
        TestInventoryServiceReports,
        TestInventoryServiceScripts,
    )
    from flext_infra.lazy_init_generation_tests import (
        TestGenerateFile,
        TestGenerateTypeChecking,
        TestResolveAliases,
        TestRunRuffFix,
        test_codegen_init_getattr_raises_attribute_error,
    )
    from flext_infra.lazy_init_helpers_tests import (
        TestBuildSiblingExportIndex,
        TestExtractExports,
        TestInferPackage,
    )
    from flext_infra.lazy_init_process_tests import TestProcessDirectory
    from flext_infra.lazy_init_service_tests import TestFlextInfraCodegenLazyInit
    from flext_infra.lazy_init_tests import (
        TestAllDirectoriesScanned,
        TestCheckOnlyMode,
        TestEdgeCases,
        TestExcludedDirectories,
    )
    from flext_infra.lazy_init_transforms_tests import (
        TestExtractVersionExports,
        TestMergeChildExports,
        TestScanPublicDefs,
        TestShouldBubbleUp,
    )
    from flext_infra.main_cli_tests import (
        TestValidateCli,
        test_main_returns_nonzero_on_unknown,
        test_main_returns_one_without_subcommand,
        test_main_returns_zero_on_help,
        test_pr_workspace_accepts_repeated_project_options,
    )
    from flext_infra.main_dispatch_tests import (
        test_run_github_workspace_pull_requests_aggregates_results,
        test_run_github_workspace_pull_requests_honors_fail_fast,
        test_run_github_workspace_pull_requests_respects_project_selection,
    )
    from flext_infra.main_integration_tests import (
        test_lint_subcommand_writes_report,
        test_pr_subcommand_returns_nonzero_for_minimal_repo,
        test_workflows_subcommand_applies_templates,
    )
    from flext_infra.main_tests import (
        TestHandleLazyInit,
        TestMainBaseMkValidate,
        TestMainCliRouting,
        TestMainCommandDispatch,
        TestMainEntryPoint,
        TestMainInventory,
        TestMainScan,
        test_check_main_executes_real_cli,
        test_lint_github_workflows_writes_report,
        test_run_github_pull_request_fails_for_minimal_repo,
        test_sync_github_workflows_apply_writes_ci_files_and_report,
        test_sync_github_workflows_prunes_noncanonical_files,
        test_sync_github_workflows_reports_create_operations,
    )
    from flext_infra.namespace_validator_tests import TestFlextInfraNamespaceValidator
    from flext_infra.pipeline_tests import test_codegen_pipeline_end_to_end
    from flext_infra.pyrefly_tests import TestFlextInfraConfigFixer
    from flext_infra.pytest_diag import TestPytestDiagExtractorBehavior
    from flext_infra.runner_service import RealSubprocessRunner
    from flext_infra.scaffolder_naming_tests import (
        TestGeneratedClassNamingConvention,
        TestGeneratedFilesAreValidPython,
    )
    from flext_infra.scaffolder_tests import (
        TestScaffoldProjectCreatesSrcModules,
        TestScaffoldProjectCreatesTestsModules,
        TestScaffoldProjectIdempotency,
        TestScaffoldProjectNoop,
    )
    from flext_infra.scanner_tests import (
        TestScannerCore,
        TestScannerHelpers,
        TestScannerMultiFile,
    )
    from flext_infra.scenarios import (
        DependencyScenario,
        DependencyScenarios,
        GitScenario,
        GitScenarios,
        SubprocessScenario,
        SubprocessScenarios,
        WorkspaceScenario,
        WorkspaceScenarios,
    )
    from flext_infra.silent_failure_gate_tests import TestSilentFailureGate
    from flext_infra.silent_failure_tests import (
        TestSilentFailureDetector,
        TestSilentFailureValidator,
    )
    from flext_infra.skill_validator_tests import (
        TestSafeLoadYaml,
        TestSkillValidatorAstGrepCount,
        TestSkillValidatorCore,
        TestSkillValidatorRenderTemplate,
        TestStringList,
    )
    from flext_infra.stub_chain_tests import TestStubChain
    from flext_infra.test_codegen_pipeline_dag import TestCodegenPipelineDag
    from flext_infra.test_infra_constants_core import (
        TestFlextInfraConstantsExcludedNamespace,
        TestFlextInfraConstantsFilesNamespace,
        TestFlextInfraConstantsGatesNamespace,
        TestFlextInfraConstantsPathsNamespace,
        TestFlextInfraConstantsStatusNamespace,
    )
    from flext_infra.test_infra_constants_extra import (
        TestFlextInfraConstantsAlias,
        TestFlextInfraConstantsCheckNamespace,
        TestFlextInfraConstantsConsistency,
        TestFlextInfraConstantsEncodingNamespace,
        TestFlextInfraConstantsGithubNamespace,
        TestFlextInfraConstantsImmutability,
    )
    from flext_infra.test_infra_container import (
        TestInfraContainerFunctions,
        TestInfraMroPattern,
        TestInfraServiceRetrieval,
    )
    from flext_infra.test_infra_discovery import TestFlextInfraDiscoveryService
    from flext_infra.test_infra_discovery_edge_cases import (
        TestFlextInfraDiscoveryServiceUncoveredLines,
    )
    from flext_infra.test_infra_init_lazy_core import TestFlextInfraInitLazyLoading
    from flext_infra.test_infra_main import (
        test_main_help_flag_returns_zero,
        test_main_help_lists_core_groups,
        test_main_returns_error_when_no_args,
        test_main_unknown_group_returns_error,
    )
    from flext_infra.test_infra_maintenance_cli import (
        test_maintenance_rejects_apply_flag,
    )
    from flext_infra.test_infra_maintenance_init import TestFlextInfraMaintenance
    from flext_infra.test_infra_maintenance_main import (
        TestMaintenanceMainEnforcer,
        TestMaintenanceMainSuccess,
    )
    from flext_infra.test_infra_maintenance_python_version import (
        TestDiscoverProjects,
        TestEnforcerExecute,
        TestEnsurePythonVersionFile,
        TestReadRequiredMinor,
        TestWorkspaceRoot,
    )
    from flext_infra.test_infra_paths import TestFlextInfraPathResolver
    from flext_infra.test_infra_patterns_core import (
        TestFlextInfraPatternsMarkdown,
        TestFlextInfraPatternsTooling,
    )
    from flext_infra.test_infra_patterns_extra import (
        TestFlextInfraPatternsEdgeCases,
        TestFlextInfraTypesPatternsPattern,
    )
    from flext_infra.test_infra_protocols import TestFlextInfraProtocolsImport
    from flext_infra.test_infra_refactor_class_and_propagation import (
        test_class_reconstructor_reorders_each_contiguous_method_block,
        test_class_reconstructor_reorders_methods_by_config,
        test_class_reconstructor_skips_interleaved_non_method_members,
        test_signature_propagation_removes_and_adds_keywords,
        test_signature_propagation_renames_call_keyword,
        test_symbol_propagation_keeps_alias_reference_when_asname_used,
        test_symbol_propagation_renames_import_and_local_references,
        test_symbol_propagation_updates_mro_base_references,
    )
    from flext_infra.test_infra_refactor_class_placement import (
        test_detects_attribute_base_class,
        test_detects_basemodel_in_non_model_file,
        test_detects_multiple_models,
        test_non_pydantic_class_not_flagged,
        test_skips_models_directory,
        test_skips_models_file,
        test_skips_private_class,
        test_skips_protected_files,
        test_skips_settings_file,
    )
    from flext_infra.test_infra_refactor_cli_models_workflow import (
        test_namespace_enforce_cli_fails_on_manual_protocol_violation,
    )
    from flext_infra.test_infra_refactor_engine import (
        BrokenRule,
        test_engine_always_enables_class_nesting_file_rule,
        test_refactor_file_rolls_back_invalid_output_and_preserves_backup,
        test_refactor_files_skips_non_python_inputs,
        test_refactor_project_scans_tests_and_scripts_dirs,
        test_rule_dispatch_fails_on_invalid_pattern_rule_config,
        test_rule_dispatch_fails_on_unknown_rule_mapping,
        test_rule_dispatch_keeps_legacy_id_fallback_mapping,
        test_rule_dispatch_prefers_fix_action_metadata,
    )
    from flext_infra.test_infra_refactor_import_modernizer import (
        test_import_modernizer_adds_c_when_existing_c_is_aliased,
        test_import_modernizer_does_not_rewrite_function_parameter_shadow,
        test_import_modernizer_does_not_rewrite_rebound_local_name_usage,
        test_import_modernizer_partial_import_keeps_unmapped_symbols,
        test_import_modernizer_partial_import_with_asname_keeps_unmapped_alias,
        test_import_modernizer_skips_rewrite_when_runtime_alias_shadowed_in_function,
        test_import_modernizer_skips_when_runtime_alias_name_is_blocked,
        test_import_modernizer_updates_aliased_symbol_usage,
        test_lazy_import_rule_hoists_import_to_module_level,
        test_lazy_import_rule_uses_fix_action_for_hoist,
    )
    from flext_infra.test_infra_refactor_legacy_and_annotations import (
        test_ensure_future_annotations_after_docstring,
        test_ensure_future_annotations_moves_existing_import_to_top,
        test_legacy_import_bypass_collapses_to_primary_import,
        test_legacy_rule_uses_fix_action_remove_for_aliases,
        test_legacy_wrapper_forwarding_keywords_is_inlined_as_alias,
        test_legacy_wrapper_forwarding_varargs_is_inlined_as_alias,
        test_legacy_wrapper_function_is_inlined_as_alias,
        test_legacy_wrapper_non_passthrough_is_not_inlined,
    )
    from flext_infra.test_infra_refactor_migrate_to_class_mro import (
        test_discover_project_roots_without_nested_git_dirs,
        test_migrate_protocols_rewrites_references_with_p_alias,
        test_migrate_to_mro_inlines_alias_constant_into_constants_class,
        test_migrate_to_mro_moves_constant_and_rewrites_reference,
        test_migrate_to_mro_moves_manual_uppercase_assignment,
        test_migrate_to_mro_normalizes_facade_alias_to_c,
        test_migrate_to_mro_rejects_unknown_target,
        test_migrate_typings_rewrites_references_with_t_alias,
        test_refactor_utilities_iter_python_files_includes_examples_and_scripts,
    )
    from flext_infra.test_infra_refactor_mro_completeness import (
        test_detects_missing_local_composition_base,
        test_rewriter_adds_missing_base_and_formats,
        test_skips_non_facade_files,
        test_skips_private_candidate_classes,
        test_skips_when_candidate_is_already_in_facade_bases,
    )
    from flext_infra.test_infra_refactor_mro_import_rewriter import (
        test_migrate_workspace_applies_consumer_rewrites,
        test_migrate_workspace_dry_run_preserves_files,
        test_migrate_workspace_reports_protected_write_failure,
    )
    from flext_infra.test_infra_refactor_namespace_aliases import (
        test_import_alias_detector_skips_facade_and_subclass_files,
        test_import_alias_detector_skips_nested_private_and_as_renames,
        test_import_alias_detector_skips_private_and_class_imports,
        test_namespace_rewriter_keeps_contextual_alias_subset,
        test_namespace_rewriter_only_rewrites_runtime_alias_imports,
        test_namespace_rewriter_skips_facade_and_subclass_files,
        test_namespace_rewriter_skips_nested_private_as_rename_and_duplicates,
    )
    from flext_infra.test_infra_refactor_namespace_enforcer import (
        test_loose_object_detector_detects_module_logger_assignment,
        test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring,
        test_namespace_enforcer_apply_keeps_autofixes_when_other_violations_remain,
        test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future,
        test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file,
        test_namespace_enforcer_creates_missing_facades_and_rewrites_imports,
        test_namespace_enforcer_detects_cyclic_imports_in_tests_directory,
        test_namespace_enforcer_detects_internal_private_imports,
        test_namespace_enforcer_detects_manual_protocol_outside_canonical_files,
        test_namespace_enforcer_detects_manual_typings_and_compat_aliases,
        test_namespace_enforcer_detects_missing_runtime_alias_outside_src,
        test_namespace_enforcer_does_not_rewrite_indented_import_aliases,
        test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks,
        test_namespace_enforcer_respects_tool_flext_namespace_scan_dirs,
        test_namespace_enforcer_skips_dynamic_dirs_by_default,
    )
    from flext_infra.test_infra_refactor_namespace_moves import (
        test_rewrite_compatibility_alias_violations_uses_public_runtime_api,
        test_rewrite_manual_protocol_violations_uses_public_runtime_api,
        test_rewrite_manual_typing_alias_violations_uses_public_runtime_api,
    )
    from flext_infra.test_infra_refactor_namespace_source import (
        test_detects_only_wrong_alias_in_mixed_import,
        test_detects_parent_u_import_in_private_utilities_module,
        test_detects_parent_u_import_outside_private_utilities_module,
        test_detects_same_project_submodule_alias_import,
        test_detects_wrong_source_m_import,
        test_detects_wrong_source_u_import,
        test_project_without_alias_facade_has_no_violation,
        test_rewriter_namespace_source_is_idempotent_with_ruff,
        test_rewriter_preserves_non_alias_symbols,
        test_rewriter_splits_mixed_imports_correctly,
        test_skips_facade_declaration_files,
        test_skips_import_as_rename,
        test_skips_init_file,
        test_skips_non_alias_symbols,
        test_skips_r_alias_universal_exception,
        test_skips_same_project_private_submodule,
        test_skips_same_project_submodule_class_import,
    )
    from flext_infra.test_infra_refactor_pattern_corrections import (
        test_pattern_rule_converts_dict_annotations_to_mapping,
        test_pattern_rule_keeps_dict_param_when_copy_used,
        test_pattern_rule_keeps_dict_param_when_subscript_mutated,
        test_pattern_rule_keeps_type_cast_when_not_nested_object_cast,
        test_pattern_rule_optionally_converts_return_annotations_to_mapping,
        test_pattern_rule_removes_configured_redundant_casts,
        test_pattern_rule_removes_nested_type_object_cast_chain,
        test_pattern_rule_skips_overload_signatures,
    )
    from flext_infra.test_infra_refactor_policy_family_rules import (
        test_decorators_family_blocks_dispatcher_target,
        test_dispatcher_family_blocks_models_target,
        test_helper_consolidation_is_prechecked,
        test_models_family_blocks_utilities_target,
        test_runtime_family_blocks_non_runtime_target,
        test_utilities_family_allows_utilities_target,
    )
    from flext_infra.test_infra_refactor_project_classifier import (
        test_read_project_metadata_preserves_pep621_dependency_order,
        test_read_project_metadata_preserves_poetry_dependency_order,
    )
    from flext_infra.test_infra_refactor_rope_migrations import (
        TestNestedClassPropagationRopeMigration,
        TestSymbolPropagatorRopeMigration,
    )
    from flext_infra.test_infra_refactor_safety import (
        EngineSafetyStub,
        exc,
        test_clear_checkpoint_preserves_requested_backups,
        test_refactor_project_integrates_safety_manager,
    )
    from flext_infra.test_infra_refactor_typing_unifier import (
        test_all_three_capabilities_in_one_pass,
        test_converts_multiple_aliases,
        test_converts_typealias_to_pep695,
        test_injects_t_import_when_needed,
        test_inserts_t_import_after_parenthesized_import_block,
        test_no_duplicate_t_import_when_t_from_project_package,
        test_noop_clean_module,
        test_preserves_annotated_in_function_params,
        test_preserves_non_matching_unions,
        test_preserves_override_in_method,
        test_preserves_protocol_and_runtime_checkable,
        test_preserves_type_checking_import,
        test_preserves_typealias_import_when_class_level_usage_exists,
        test_preserves_used_imports_when_import_precedes_usage,
        test_preserves_used_typing_imports,
        test_removes_all_imports_when_none_used_import_first,
        test_removes_all_unused_typing_imports,
        test_removes_dead_typealias_import,
        test_removes_typealias_import_only_when_all_usages_converted,
        test_removes_unused_preserves_used_when_import_precedes_usage,
        test_replaces_container_union,
        test_replaces_numeric_union,
        test_replaces_primitives_union,
        test_replaces_scalar_union,
        test_replaces_subset_union_with_none,
        test_rewrites_builtin_containers_to_canonical_t_aliases,
        test_rewrites_fixed_arity_four_tuple_to_quad,
        test_rewrites_tuple_variadics_and_any_annotations,
        test_skips_definition_files,
        test_skips_duplicate_t_import_in_parenthesized_import_block,
        test_typealias_conversion_preserves_used_typing_siblings,
    )
    from flext_infra.test_infra_reporting_core import TestFlextInfraReportingServiceCore
    from flext_infra.test_infra_reporting_extra import (
        TestFlextInfraReportingServiceExtra,
    )
    from flext_infra.test_infra_selection import TestFlextInfraUtilitiesSelection
    from flext_infra.test_infra_terminal_detection import (
        test_ci_variables_disable_color,
        test_force_color_enables_color,
        test_lc_all_takes_priority_over_lang,
        test_no_color_beats_force_color,
        test_no_color_env_disables_color,
        test_non_tty_disables_color,
        test_non_utf8_locale_disables_unicode,
        test_tty_with_dumb_or_empty_term_disables_color,
        test_tty_with_xterm_enables_color,
        test_utf8_locale_enables_unicode,
    )
    from flext_infra.test_infra_transformer_class_nesting import (
        test_class_nesting_appends_to_existing_namespace_and_removes_pass,
        test_class_nesting_keeps_unmapped_top_level_classes,
        test_class_nesting_moves_top_level_class_into_new_namespace,
    )
    from flext_infra.test_infra_transformer_helper_consolidation import (
        TestHelperConsolidationTransformer,
    )
    from flext_infra.test_infra_transformer_nested_class_propagation import (
        test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage,
        test_nested_class_propagation_updates_import_annotations_and_calls,
    )
    from flext_infra.test_infra_typings import (
        TestInfraTypingAdapters,
        TestInfraTypingGuards,
    )
    from flext_infra.test_infra_utilities import TestFlextInfraUtilitiesImport
    from flext_infra.test_infra_version_core import TestFlextInfraVersionClass
    from flext_infra.test_infra_version_extra import (
        TestFlextInfraVersionModuleLevel,
        TestFlextInfraVersionPackageInfo,
    )
    from flext_infra.test_infra_versioning import (
        service,
        test_bump_version_invalid,
        test_bump_version_result_type,
        test_bump_version_valid,
        test_current_workspace_version,
        test_parse_semver_invalid,
        test_parse_semver_result_type,
        test_parse_semver_valid,
        test_replace_project_version,
    )
    from flext_infra.test_infra_workspace_detector import TestWorkspaceDetector
    from flext_infra.test_infra_workspace_init import TestFlextInfraWorkspace
    from flext_infra.test_infra_workspace_migrator import (
        test_migrator_apply_updates_project_files,
        test_migrator_discovery_failure,
        test_migrator_dry_run_reports_changes_without_writes,
        test_migrator_execute_returns_failure,
        test_migrator_handles_missing_pyproject_gracefully,
        test_migrator_no_changes_needed,
        test_migrator_preserves_custom_makefile_content,
        test_migrator_workspace_root_not_exists,
        test_migrator_workspace_root_project_detection,
    )
    from flext_infra.test_infra_workspace_migrator_deps import (
        TestWorkspaceMigratorDependencyBehavior,
    )
    from flext_infra.test_infra_workspace_migrator_dryrun import (
        test_migrator_flext_core_dry_run,
        test_migrator_flext_core_project_skipped,
        test_migrator_gitignore_already_normalized_dry_run,
        test_migrator_makefile_not_found_dry_run,
        test_migrator_makefile_read_failure,
        test_migrator_pyproject_not_found_dry_run,
    )
    from flext_infra.test_infra_workspace_migrator_errors import (
        TestMigratorFailureScenarios,
    )
    from flext_infra.test_infra_workspace_migrator_internal import (
        TestMigratorPublicBehavior,
    )
    from flext_infra.test_infra_workspace_migrator_pyproject import (
        TestMigratorDryRun,
        TestMigratorFlextCore,
        TestMigratorPoetryDeps,
    )
    from flext_infra.test_infra_workspace_orchestrator import (
        TestOrchestratorBasic,
        TestOrchestratorFailures,
        TestOrchestratorGateNormalization,
        orchestrator,
    )
    from flext_infra.test_main import (
        test_detect_workspace_returns_workspace_mode,
        test_orchestrate_workspace_defaults_to_current_project,
        test_orchestrate_workspace_rejects_unknown_verb,
        test_sync_workspace_returns_sync_result,
        test_workspace_main_detect_accepts_explicit_workspace_root,
        test_workspace_main_orchestrate_returns_failure_for_unknown_verb,
        test_workspace_main_sync_runs_public_command,
        test_workspace_main_without_command_returns_failure,
        workspace_main,
    )
    from flext_infra.test_main_cli import TestFlextInfraRefactorMainCli
    from flext_infra.test_makefile_dry_run import (
        test_workspace_makefile_dry_run_fmt_respects_project_selection,
        test_workspace_makefile_dry_run_gen_forwards_selection,
        test_workspace_makefile_dry_run_mod_respects_project_selection,
        test_workspace_makefile_dry_run_mod_without_selection_uses_workspace_scope,
        test_workspace_makefile_dry_run_sync_respects_project_selection,
        test_workspace_makefile_dry_run_up_forwards_selection_to_mod,
    )
    from flext_infra.test_makefile_generator import (
        test_workspace_makefile_generator_declares_canonical_workspace_variables,
        test_workspace_makefile_generator_declares_workspace_boot_separation,
        test_workspace_makefile_generator_does_not_persist_external_project_names,
        test_workspace_makefile_generator_emits_parseable_discovery_commands,
        test_workspace_makefile_generator_limits_absolute_path_scan_to_sources,
        test_workspace_makefile_generator_reuses_mod_and_boot_feedback,
        test_workspace_makefile_generator_sanitizes_orchestrator_env,
        test_workspace_makefile_generator_uses_check_only_for_maintenance_validation,
    )
    from flext_infra.test_ssot_enforcement import (
        SSOT_METHODS,
        WORKSPACE,
        test_no_duplicate_utility_implementations,
        test_no_utility_method_shadows_parent,
    )
    from flext_infra.test_sync import (
        test_atomic_write_fails_when_parent_is_a_file,
        test_atomic_write_ok,
        test_sync_fails_when_generator_fails,
        test_sync_fails_when_gitignore_path_is_directory,
        test_sync_fails_when_workspace_root_is_missing,
        test_sync_generates_basemk_gitignore_and_makefile,
        test_sync_is_idempotent_on_second_run,
        test_sync_regenerates_project_makefile_without_legacy_passthrough,
        test_sync_workspace_root_also_syncs_child_projects,
    )
    from flext_infra.test_violation_key import TestViolationKeyFromViolation
    from flext_infra.tests_cli import TestWorkspaceCheckCli
    from flext_infra.tests_workspace_check import (
        test_workspace_check_main_returns_error_without_projects,
    )
    from flext_infra.workspace_factory import WorkspaceFactory
    from flext_infra.workspace_scenarios import (
        BrokenScenario,
        EmptyScenario,
        FullScenario,
        MinimalScenario,
    )
    from flext_infra.workspace_tests import TestFlextInfraWorkspaceChecker
_LAZY_IMPORTS = merge_lazy_imports(
    (
        "._utilities",
        ".check",
        ".codegen",
        ".container",
        ".discovery",
        ".github",
        ".io",
        ".refactor",
        ".transformers",
        ".validate",
        ".workspace",
    ),
    build_lazy_import_map(
        {
            ".autofix_workspace_tests": (
                "test_files_modified_tracks_affected_files",
                "test_flexcore_excluded_from_run",
                "test_project_without_src_returns_empty",
            ),
            ".basemk_validator_tests": (
                "TestBaseMkValidatorCore",
                "TestBaseMkValidatorEdgeCases",
                "TestBaseMkValidatorSha256",
                "v",
            ),
            ".census_models_tests": (
                "TestCensusReportModel",
                "TestCensusViolationModel",
                "TestExcludedProjects",
                "TestViolationPattern",
            ),
            ".census_tests": (
                "TestCensusExecute",
                "TestFixabilityClassification",
                "TestParseViolationInvalid",
                "TestParseViolationValid",
            ),
            ".consolidator_tests": (
                "test_execute_scans_real_package_layout",
                "test_execute_uses_codegen_project_discovery_and_project_filter",
            ),
            ".constants_quality_gate_tests": (
                "TestConstantsQualityGateCLIDispatch",
                "TestConstantsQualityGateVerdict",
            ),
            ".extended_cli_entry_tests": ("TestWorkspaceCheckCLI",),
            ".extended_config_fixer_errors_tests": ("TestConfigFixerPublicBehavior",),
            ".extended_config_fixer_tests": (
                "TestConfigFixerEnsureProjectExcludes",
                "TestConfigFixerExecute",
                "TestConfigFixerFindPyprojectFiles",
                "TestConfigFixerFixSearchPaths",
                "TestConfigFixerProcessFile",
                "TestConfigFixerRemoveIgnoreSubConfig",
                "TestConfigFixerRun",
                "TestConfigFixerToArray",
            ),
            ".extended_error_reporting_tests": (
                "TestGateErrorReportingPublicBehavior",
            ),
            ".extended_gate_bandit_markdown_tests": ("TestBanditAndMarkdownGates",),
            ".extended_gate_go_cmd_tests": ("TestGoGate",),
            ".extended_gate_mypy_pyright_tests": ("TestTypeGates",),
            ".extended_models_tests": (
                "TestCheckIssueFormatted",
                "TestProjectResultProperties",
                "TestWorkspaceCheckerErrorSummary",
            ),
            ".extended_project_runners_tests": ("TestsExtendedProjectRunners",),
            ".extended_resolve_gates_tests": (
                "TestWorkspaceCheckerParseGateCSV",
                "TestWorkspaceCheckerResolveGates",
            ),
            ".extended_run_projects_tests": ("TestRunProjectsPublicBehavior",),
            ".extended_runners_extra_tests": ("TestExtendedRunnerExtras",),
            ".extended_runners_ruff_tests": ("TestRealGateRunners",),
            ".extended_runners_tests": ("TestRunnerPublicBehavior",),
            ".extended_workspace_init_tests": ("TestWorkspaceChecker",),
            ".fix_pyrefly_config_tests": (
                "test_fix_pyrefly_config_main_executes_real_cli_help",
            ),
            ".fixtures": (
                "deptry_report_payload",
                "modernizer_workspace",
                "modernizer_workspace_with_projects",
                "real_docs_project",
                "real_makefile_project",
                "real_python_package",
                "real_toml_project",
                "real_workspace",
                "tool_config_document",
            ),
            ".fixtures_git": ("real_git_repo",),
            ".init_tests": (
                "TestCoreModuleInit",
                "TestFlextInfraCheck",
                "test_codegen_dir_returns_all_exports",
                "test_codegen_getattr_raises_attribute_error",
                "test_codegen_lazy_imports_work",
            ),
            ".inventory_tests": (
                "TestInventoryServiceCore",
                "TestInventoryServiceReports",
                "TestInventoryServiceScripts",
            ),
            ".lazy_init_generation_tests": (
                "TestGenerateFile",
                "TestGenerateTypeChecking",
                "TestResolveAliases",
                "TestRunRuffFix",
                "test_codegen_init_getattr_raises_attribute_error",
            ),
            ".lazy_init_helpers_tests": (
                "TestBuildSiblingExportIndex",
                "TestExtractExports",
                "TestInferPackage",
            ),
            ".lazy_init_process_tests": ("TestProcessDirectory",),
            ".lazy_init_service_tests": ("TestFlextInfraCodegenLazyInit",),
            ".lazy_init_tests": (
                "TestAllDirectoriesScanned",
                "TestCheckOnlyMode",
                "TestEdgeCases",
                "TestExcludedDirectories",
            ),
            ".lazy_init_transforms_tests": (
                "TestExtractVersionExports",
                "TestMergeChildExports",
                "TestScanPublicDefs",
                "TestShouldBubbleUp",
            ),
            ".main_cli_tests": (
                "TestValidateCli",
                "test_main_returns_nonzero_on_unknown",
                "test_main_returns_one_without_subcommand",
                "test_main_returns_zero_on_help",
                "test_pr_workspace_accepts_repeated_project_options",
            ),
            ".main_dispatch_tests": (
                "test_run_github_workspace_pull_requests_aggregates_results",
                "test_run_github_workspace_pull_requests_honors_fail_fast",
                "test_run_github_workspace_pull_requests_respects_project_selection",
            ),
            ".main_integration_tests": (
                "test_lint_subcommand_writes_report",
                "test_pr_subcommand_returns_nonzero_for_minimal_repo",
                "test_workflows_subcommand_applies_templates",
            ),
            ".main_tests": (
                "TestHandleLazyInit",
                "TestMainBaseMkValidate",
                "TestMainCliRouting",
                "TestMainCommandDispatch",
                "TestMainEntryPoint",
                "TestMainInventory",
                "TestMainScan",
                "test_check_main_executes_real_cli",
                "test_lint_github_workflows_writes_report",
                "test_run_github_pull_request_fails_for_minimal_repo",
                "test_sync_github_workflows_apply_writes_ci_files_and_report",
                "test_sync_github_workflows_prunes_noncanonical_files",
                "test_sync_github_workflows_reports_create_operations",
            ),
            ".namespace_validator_tests": ("TestFlextInfraNamespaceValidator",),
            ".pipeline_tests": ("test_codegen_pipeline_end_to_end",),
            ".pyrefly_tests": ("TestFlextInfraConfigFixer",),
            ".pytest_diag": ("TestPytestDiagExtractorBehavior",),
            ".runner_service": ("RealSubprocessRunner",),
            ".scaffolder_naming_tests": (
                "TestGeneratedClassNamingConvention",
                "TestGeneratedFilesAreValidPython",
            ),
            ".scaffolder_tests": (
                "TestScaffoldProjectCreatesSrcModules",
                "TestScaffoldProjectCreatesTestsModules",
                "TestScaffoldProjectIdempotency",
                "TestScaffoldProjectNoop",
            ),
            ".scanner_tests": (
                "TestScannerCore",
                "TestScannerHelpers",
                "TestScannerMultiFile",
            ),
            ".scenarios": (
                "DependencyScenario",
                "DependencyScenarios",
                "GitScenario",
                "GitScenarios",
                "SubprocessScenario",
                "SubprocessScenarios",
                "WorkspaceScenario",
                "WorkspaceScenarios",
            ),
            ".silent_failure_gate_tests": ("TestSilentFailureGate",),
            ".silent_failure_tests": (
                "TestSilentFailureDetector",
                "TestSilentFailureValidator",
            ),
            ".skill_validator_tests": (
                "TestSafeLoadYaml",
                "TestSkillValidatorAstGrepCount",
                "TestSkillValidatorCore",
                "TestSkillValidatorRenderTemplate",
                "TestStringList",
            ),
            ".stub_chain_tests": ("TestStubChain",),
            ".test_codegen_pipeline_dag": ("TestCodegenPipelineDag",),
            ".test_infra_constants_core": (
                "TestFlextInfraConstantsExcludedNamespace",
                "TestFlextInfraConstantsFilesNamespace",
                "TestFlextInfraConstantsGatesNamespace",
                "TestFlextInfraConstantsPathsNamespace",
                "TestFlextInfraConstantsStatusNamespace",
            ),
            ".test_infra_constants_extra": (
                "TestFlextInfraConstantsAlias",
                "TestFlextInfraConstantsCheckNamespace",
                "TestFlextInfraConstantsConsistency",
                "TestFlextInfraConstantsEncodingNamespace",
                "TestFlextInfraConstantsGithubNamespace",
                "TestFlextInfraConstantsImmutability",
            ),
            ".test_infra_container": (
                "TestInfraContainerFunctions",
                "TestInfraMroPattern",
                "TestInfraServiceRetrieval",
            ),
            ".test_infra_discovery": ("TestFlextInfraDiscoveryService",),
            ".test_infra_discovery_edge_cases": (
                "TestFlextInfraDiscoveryServiceUncoveredLines",
            ),
            ".test_infra_init_lazy_core": ("TestFlextInfraInitLazyLoading",),
            ".test_infra_main": (
                "test_main_help_flag_returns_zero",
                "test_main_help_lists_core_groups",
                "test_main_returns_error_when_no_args",
                "test_main_unknown_group_returns_error",
            ),
            ".test_infra_maintenance_cli": ("test_maintenance_rejects_apply_flag",),
            ".test_infra_maintenance_init": ("TestFlextInfraMaintenance",),
            ".test_infra_maintenance_main": (
                "TestMaintenanceMainEnforcer",
                "TestMaintenanceMainSuccess",
            ),
            ".test_infra_maintenance_python_version": (
                "TestDiscoverProjects",
                "TestEnforcerExecute",
                "TestEnsurePythonVersionFile",
                "TestReadRequiredMinor",
                "TestWorkspaceRoot",
            ),
            ".test_infra_paths": ("TestFlextInfraPathResolver",),
            ".test_infra_patterns_core": (
                "TestFlextInfraPatternsMarkdown",
                "TestFlextInfraPatternsTooling",
            ),
            ".test_infra_patterns_extra": (
                "TestFlextInfraPatternsEdgeCases",
                "TestFlextInfraTypesPatternsPattern",
            ),
            ".test_infra_protocols": ("TestFlextInfraProtocolsImport",),
            ".test_infra_refactor_class_and_propagation": (
                "test_class_reconstructor_reorders_each_contiguous_method_block",
                "test_class_reconstructor_reorders_methods_by_config",
                "test_class_reconstructor_skips_interleaved_non_method_members",
                "test_signature_propagation_removes_and_adds_keywords",
                "test_signature_propagation_renames_call_keyword",
                "test_symbol_propagation_keeps_alias_reference_when_asname_used",
                "test_symbol_propagation_renames_import_and_local_references",
                "test_symbol_propagation_updates_mro_base_references",
            ),
            ".test_infra_refactor_class_placement": (
                "test_detects_attribute_base_class",
                "test_detects_basemodel_in_non_model_file",
                "test_detects_multiple_models",
                "test_non_pydantic_class_not_flagged",
                "test_skips_models_directory",
                "test_skips_models_file",
                "test_skips_private_class",
                "test_skips_protected_files",
                "test_skips_settings_file",
            ),
            ".test_infra_refactor_cli_models_workflow": (
                "test_namespace_enforce_cli_fails_on_manual_protocol_violation",
            ),
            ".test_infra_refactor_engine": (
                "BrokenRule",
                "test_engine_always_enables_class_nesting_file_rule",
                "test_refactor_file_rolls_back_invalid_output_and_preserves_backup",
                "test_refactor_files_skips_non_python_inputs",
                "test_refactor_project_scans_tests_and_scripts_dirs",
                "test_rule_dispatch_fails_on_invalid_pattern_rule_config",
                "test_rule_dispatch_fails_on_unknown_rule_mapping",
                "test_rule_dispatch_keeps_legacy_id_fallback_mapping",
                "test_rule_dispatch_prefers_fix_action_metadata",
            ),
            ".test_infra_refactor_import_modernizer": (
                "test_import_modernizer_adds_c_when_existing_c_is_aliased",
                "test_import_modernizer_does_not_rewrite_function_parameter_shadow",
                "test_import_modernizer_does_not_rewrite_rebound_local_name_usage",
                "test_import_modernizer_partial_import_keeps_unmapped_symbols",
                "test_import_modernizer_partial_import_with_asname_keeps_unmapped_alias",
                "test_import_modernizer_skips_rewrite_when_runtime_alias_shadowed_in_function",
                "test_import_modernizer_skips_when_runtime_alias_name_is_blocked",
                "test_import_modernizer_updates_aliased_symbol_usage",
                "test_lazy_import_rule_hoists_import_to_module_level",
                "test_lazy_import_rule_uses_fix_action_for_hoist",
            ),
            ".test_infra_refactor_legacy_and_annotations": (
                "test_ensure_future_annotations_after_docstring",
                "test_ensure_future_annotations_moves_existing_import_to_top",
                "test_legacy_import_bypass_collapses_to_primary_import",
                "test_legacy_rule_uses_fix_action_remove_for_aliases",
                "test_legacy_wrapper_forwarding_keywords_is_inlined_as_alias",
                "test_legacy_wrapper_forwarding_varargs_is_inlined_as_alias",
                "test_legacy_wrapper_function_is_inlined_as_alias",
                "test_legacy_wrapper_non_passthrough_is_not_inlined",
            ),
            ".test_infra_refactor_migrate_to_class_mro": (
                "test_discover_project_roots_without_nested_git_dirs",
                "test_migrate_protocols_rewrites_references_with_p_alias",
                "test_migrate_to_mro_inlines_alias_constant_into_constants_class",
                "test_migrate_to_mro_moves_constant_and_rewrites_reference",
                "test_migrate_to_mro_moves_manual_uppercase_assignment",
                "test_migrate_to_mro_normalizes_facade_alias_to_c",
                "test_migrate_to_mro_rejects_unknown_target",
                "test_migrate_typings_rewrites_references_with_t_alias",
                "test_refactor_utilities_iter_python_files_includes_examples_and_scripts",
            ),
            ".test_infra_refactor_mro_completeness": (
                "test_detects_missing_local_composition_base",
                "test_rewriter_adds_missing_base_and_formats",
                "test_skips_non_facade_files",
                "test_skips_private_candidate_classes",
                "test_skips_when_candidate_is_already_in_facade_bases",
            ),
            ".test_infra_refactor_mro_import_rewriter": (
                "test_migrate_workspace_applies_consumer_rewrites",
                "test_migrate_workspace_dry_run_preserves_files",
                "test_migrate_workspace_reports_protected_write_failure",
            ),
            ".test_infra_refactor_namespace_aliases": (
                "test_import_alias_detector_skips_facade_and_subclass_files",
                "test_import_alias_detector_skips_nested_private_and_as_renames",
                "test_import_alias_detector_skips_private_and_class_imports",
                "test_namespace_rewriter_keeps_contextual_alias_subset",
                "test_namespace_rewriter_only_rewrites_runtime_alias_imports",
                "test_namespace_rewriter_skips_facade_and_subclass_files",
                "test_namespace_rewriter_skips_nested_private_as_rename_and_duplicates",
            ),
            ".test_infra_refactor_namespace_enforcer": (
                "test_loose_object_detector_detects_module_logger_assignment",
                "test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring",
                "test_namespace_enforcer_apply_keeps_autofixes_when_other_violations_remain",
                "test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future",
                "test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file",
                "test_namespace_enforcer_creates_missing_facades_and_rewrites_imports",
                "test_namespace_enforcer_detects_cyclic_imports_in_tests_directory",
                "test_namespace_enforcer_detects_internal_private_imports",
                "test_namespace_enforcer_detects_manual_protocol_outside_canonical_files",
                "test_namespace_enforcer_detects_manual_typings_and_compat_aliases",
                "test_namespace_enforcer_detects_missing_runtime_alias_outside_src",
                "test_namespace_enforcer_does_not_rewrite_indented_import_aliases",
                "test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks",
                "test_namespace_enforcer_respects_tool_flext_namespace_scan_dirs",
                "test_namespace_enforcer_skips_dynamic_dirs_by_default",
            ),
            ".test_infra_refactor_namespace_moves": (
                "test_rewrite_compatibility_alias_violations_uses_public_runtime_api",
                "test_rewrite_manual_protocol_violations_uses_public_runtime_api",
                "test_rewrite_manual_typing_alias_violations_uses_public_runtime_api",
            ),
            ".test_infra_refactor_namespace_source": (
                "test_detects_only_wrong_alias_in_mixed_import",
                "test_detects_parent_u_import_in_private_utilities_module",
                "test_detects_parent_u_import_outside_private_utilities_module",
                "test_detects_same_project_submodule_alias_import",
                "test_detects_wrong_source_m_import",
                "test_detects_wrong_source_u_import",
                "test_project_without_alias_facade_has_no_violation",
                "test_rewriter_namespace_source_is_idempotent_with_ruff",
                "test_rewriter_preserves_non_alias_symbols",
                "test_rewriter_splits_mixed_imports_correctly",
                "test_skips_facade_declaration_files",
                "test_skips_import_as_rename",
                "test_skips_init_file",
                "test_skips_non_alias_symbols",
                "test_skips_r_alias_universal_exception",
                "test_skips_same_project_private_submodule",
                "test_skips_same_project_submodule_class_import",
            ),
            ".test_infra_refactor_pattern_corrections": (
                "test_pattern_rule_converts_dict_annotations_to_mapping",
                "test_pattern_rule_keeps_dict_param_when_copy_used",
                "test_pattern_rule_keeps_dict_param_when_subscript_mutated",
                "test_pattern_rule_keeps_type_cast_when_not_nested_object_cast",
                "test_pattern_rule_optionally_converts_return_annotations_to_mapping",
                "test_pattern_rule_removes_configured_redundant_casts",
                "test_pattern_rule_removes_nested_type_object_cast_chain",
                "test_pattern_rule_skips_overload_signatures",
            ),
            ".test_infra_refactor_policy_family_rules": (
                "test_decorators_family_blocks_dispatcher_target",
                "test_dispatcher_family_blocks_models_target",
                "test_helper_consolidation_is_prechecked",
                "test_models_family_blocks_utilities_target",
                "test_runtime_family_blocks_non_runtime_target",
                "test_utilities_family_allows_utilities_target",
            ),
            ".test_infra_refactor_project_classifier": (
                "test_read_project_metadata_preserves_pep621_dependency_order",
                "test_read_project_metadata_preserves_poetry_dependency_order",
            ),
            ".test_infra_refactor_rope_migrations": (
                "TestNestedClassPropagationRopeMigration",
                "TestSymbolPropagatorRopeMigration",
            ),
            ".test_infra_refactor_safety": (
                "EngineSafetyStub",
                "exc",
                "test_clear_checkpoint_preserves_requested_backups",
                "test_refactor_project_integrates_safety_manager",
            ),
            ".test_infra_refactor_typing_unifier": (
                "test_all_three_capabilities_in_one_pass",
                "test_converts_multiple_aliases",
                "test_converts_typealias_to_pep695",
                "test_injects_t_import_when_needed",
                "test_inserts_t_import_after_parenthesized_import_block",
                "test_no_duplicate_t_import_when_t_from_project_package",
                "test_noop_clean_module",
                "test_preserves_annotated_in_function_params",
                "test_preserves_non_matching_unions",
                "test_preserves_override_in_method",
                "test_preserves_protocol_and_runtime_checkable",
                "test_preserves_type_checking_import",
                "test_preserves_typealias_import_when_class_level_usage_exists",
                "test_preserves_used_imports_when_import_precedes_usage",
                "test_preserves_used_typing_imports",
                "test_removes_all_imports_when_none_used_import_first",
                "test_removes_all_unused_typing_imports",
                "test_removes_dead_typealias_import",
                "test_removes_typealias_import_only_when_all_usages_converted",
                "test_removes_unused_preserves_used_when_import_precedes_usage",
                "test_replaces_container_union",
                "test_replaces_numeric_union",
                "test_replaces_primitives_union",
                "test_replaces_scalar_union",
                "test_replaces_subset_union_with_none",
                "test_rewrites_builtin_containers_to_canonical_t_aliases",
                "test_rewrites_fixed_arity_four_tuple_to_quad",
                "test_rewrites_tuple_variadics_and_any_annotations",
                "test_skips_definition_files",
                "test_skips_duplicate_t_import_in_parenthesized_import_block",
                "test_typealias_conversion_preserves_used_typing_siblings",
            ),
            ".test_infra_reporting_core": ("TestFlextInfraReportingServiceCore",),
            ".test_infra_reporting_extra": ("TestFlextInfraReportingServiceExtra",),
            ".test_infra_selection": ("TestFlextInfraUtilitiesSelection",),
            ".test_infra_terminal_detection": (
                "test_ci_variables_disable_color",
                "test_force_color_enables_color",
                "test_lc_all_takes_priority_over_lang",
                "test_no_color_beats_force_color",
                "test_no_color_env_disables_color",
                "test_non_tty_disables_color",
                "test_non_utf8_locale_disables_unicode",
                "test_tty_with_dumb_or_empty_term_disables_color",
                "test_tty_with_xterm_enables_color",
                "test_utf8_locale_enables_unicode",
            ),
            ".test_infra_transformer_class_nesting": (
                "test_class_nesting_appends_to_existing_namespace_and_removes_pass",
                "test_class_nesting_keeps_unmapped_top_level_classes",
                "test_class_nesting_moves_top_level_class_into_new_namespace",
            ),
            ".test_infra_transformer_helper_consolidation": (
                "TestHelperConsolidationTransformer",
            ),
            ".test_infra_transformer_nested_class_propagation": (
                "test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage",
                "test_nested_class_propagation_updates_import_annotations_and_calls",
            ),
            ".test_infra_typings": (
                "TestInfraTypingAdapters",
                "TestInfraTypingGuards",
            ),
            ".test_infra_utilities": ("TestFlextInfraUtilitiesImport",),
            ".test_infra_version_core": ("TestFlextInfraVersionClass",),
            ".test_infra_version_extra": (
                "TestFlextInfraVersionModuleLevel",
                "TestFlextInfraVersionPackageInfo",
            ),
            ".test_infra_versioning": (
                "service",
                "test_bump_version_invalid",
                "test_bump_version_result_type",
                "test_bump_version_valid",
                "test_current_workspace_version",
                "test_parse_semver_invalid",
                "test_parse_semver_result_type",
                "test_parse_semver_valid",
                "test_replace_project_version",
            ),
            ".test_infra_workspace_detector": ("TestWorkspaceDetector",),
            ".test_infra_workspace_init": ("TestFlextInfraWorkspace",),
            ".test_infra_workspace_migrator": (
                "test_migrator_apply_updates_project_files",
                "test_migrator_discovery_failure",
                "test_migrator_dry_run_reports_changes_without_writes",
                "test_migrator_execute_returns_failure",
                "test_migrator_handles_missing_pyproject_gracefully",
                "test_migrator_no_changes_needed",
                "test_migrator_preserves_custom_makefile_content",
                "test_migrator_workspace_root_not_exists",
                "test_migrator_workspace_root_project_detection",
            ),
            ".test_infra_workspace_migrator_deps": (
                "TestWorkspaceMigratorDependencyBehavior",
            ),
            ".test_infra_workspace_migrator_dryrun": (
                "test_migrator_flext_core_dry_run",
                "test_migrator_flext_core_project_skipped",
                "test_migrator_gitignore_already_normalized_dry_run",
                "test_migrator_makefile_not_found_dry_run",
                "test_migrator_makefile_read_failure",
                "test_migrator_pyproject_not_found_dry_run",
            ),
            ".test_infra_workspace_migrator_errors": ("TestMigratorFailureScenarios",),
            ".test_infra_workspace_migrator_internal": ("TestMigratorPublicBehavior",),
            ".test_infra_workspace_migrator_pyproject": (
                "TestMigratorDryRun",
                "TestMigratorFlextCore",
                "TestMigratorPoetryDeps",
            ),
            ".test_infra_workspace_orchestrator": (
                "TestOrchestratorBasic",
                "TestOrchestratorFailures",
                "TestOrchestratorGateNormalization",
                "orchestrator",
            ),
            ".test_main": (
                "test_detect_workspace_returns_workspace_mode",
                "test_orchestrate_workspace_defaults_to_current_project",
                "test_orchestrate_workspace_rejects_unknown_verb",
                "test_sync_workspace_returns_sync_result",
                "test_workspace_main_detect_accepts_explicit_workspace_root",
                "test_workspace_main_orchestrate_returns_failure_for_unknown_verb",
                "test_workspace_main_sync_runs_public_command",
                "test_workspace_main_without_command_returns_failure",
                "workspace_main",
            ),
            ".test_main_cli": ("TestFlextInfraRefactorMainCli",),
            ".test_makefile_dry_run": (
                "test_workspace_makefile_dry_run_fmt_respects_project_selection",
                "test_workspace_makefile_dry_run_gen_forwards_selection",
                "test_workspace_makefile_dry_run_mod_respects_project_selection",
                "test_workspace_makefile_dry_run_mod_without_selection_uses_workspace_scope",
                "test_workspace_makefile_dry_run_sync_respects_project_selection",
                "test_workspace_makefile_dry_run_up_forwards_selection_to_mod",
            ),
            ".test_makefile_generator": (
                "test_workspace_makefile_generator_declares_canonical_workspace_variables",
                "test_workspace_makefile_generator_declares_workspace_boot_separation",
                "test_workspace_makefile_generator_does_not_persist_external_project_names",
                "test_workspace_makefile_generator_emits_parseable_discovery_commands",
                "test_workspace_makefile_generator_limits_absolute_path_scan_to_sources",
                "test_workspace_makefile_generator_reuses_mod_and_boot_feedback",
                "test_workspace_makefile_generator_sanitizes_orchestrator_env",
                "test_workspace_makefile_generator_uses_check_only_for_maintenance_validation",
            ),
            ".test_ssot_enforcement": (
                "SSOT_METHODS",
                "WORKSPACE",
                "test_no_duplicate_utility_implementations",
                "test_no_utility_method_shadows_parent",
            ),
            ".test_sync": (
                "test_atomic_write_fails_when_parent_is_a_file",
                "test_atomic_write_ok",
                "test_sync_fails_when_generator_fails",
                "test_sync_fails_when_gitignore_path_is_directory",
                "test_sync_fails_when_workspace_root_is_missing",
                "test_sync_generates_basemk_gitignore_and_makefile",
                "test_sync_is_idempotent_on_second_run",
                "test_sync_regenerates_project_makefile_without_legacy_passthrough",
                "test_sync_workspace_root_also_syncs_child_projects",
            ),
            ".test_violation_key": ("TestViolationKeyFromViolation",),
            ".tests_cli": ("TestWorkspaceCheckCli",),
            ".tests_workspace_check": (
                "test_workspace_check_main_returns_error_without_projects",
            ),
            ".workspace_factory": ("WorkspaceFactory",),
            ".workspace_scenarios": (
                "BrokenScenario",
                "EmptyScenario",
                "FullScenario",
                "MinimalScenario",
            ),
            ".workspace_tests": ("TestFlextInfraWorkspaceChecker",),
            "_utilities.test_discovery_consolidated": (
                "TestsFlextInfraUtilitiesDiscoveryConsolidated",
            ),
            "_utilities.test_formatting": (
                "TestsFlextInfraUtilitiesFormattingRunRuffFix",
            ),
            "_utilities.test_iteration": ("TestIterWorkspacePythonModules",),
            "_utilities.test_rope_hooks": (
                "test_run_rope_post_hooks_applies_mro_migration",
                "test_run_rope_post_hooks_dry_run_is_non_mutating",
            ),
            "_utilities.test_safety": (
                "TestSafetyCheckpoint",
                "TestSafetyRollback",
            ),
            "_utilities.test_scanning": ("TestScanModels",),
        },
    ),
    exclude_names=(
        "cleanup_submodule_namespace",
        "install_lazy_exports",
        "lazy_getattr",
        "logger",
        "merge_lazy_imports",
        "output",
        "output_reporting",
    ),
    module_name=__name__,
)


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)

__all__ = [
    "SSOT_METHODS",
    "WORKSPACE",
    "BrokenRule",
    "BrokenScenario",
    "DependencyScenario",
    "DependencyScenarios",
    "EmptyScenario",
    "EngineSafetyStub",
    "FullScenario",
    "GitScenario",
    "GitScenarios",
    "MinimalScenario",
    "RealSubprocessRunner",
    "SubprocessScenario",
    "SubprocessScenarios",
    "TestAllDirectoriesScanned",
    "TestBanditAndMarkdownGates",
    "TestBaseMkValidatorCore",
    "TestBaseMkValidatorEdgeCases",
    "TestBaseMkValidatorSha256",
    "TestBuildSiblingExportIndex",
    "TestCensusExecute",
    "TestCensusReportModel",
    "TestCensusViolationModel",
    "TestCheckIssueFormatted",
    "TestCheckOnlyMode",
    "TestCodegenPipelineDag",
    "TestConfigFixerEnsureProjectExcludes",
    "TestConfigFixerExecute",
    "TestConfigFixerFindPyprojectFiles",
    "TestConfigFixerFixSearchPaths",
    "TestConfigFixerProcessFile",
    "TestConfigFixerPublicBehavior",
    "TestConfigFixerRemoveIgnoreSubConfig",
    "TestConfigFixerRun",
    "TestConfigFixerToArray",
    "TestConstantsQualityGateCLIDispatch",
    "TestConstantsQualityGateVerdict",
    "TestCoreModuleInit",
    "TestDiscoverProjects",
    "TestEdgeCases",
    "TestEnforcerExecute",
    "TestEnsurePythonVersionFile",
    "TestExcludedDirectories",
    "TestExcludedProjects",
    "TestExtendedRunnerExtras",
    "TestExtractExports",
    "TestExtractVersionExports",
    "TestFixabilityClassification",
    "TestFlextInfraCheck",
    "TestFlextInfraCodegenLazyInit",
    "TestFlextInfraConfigFixer",
    "TestFlextInfraConstantsAlias",
    "TestFlextInfraConstantsCheckNamespace",
    "TestFlextInfraConstantsConsistency",
    "TestFlextInfraConstantsEncodingNamespace",
    "TestFlextInfraConstantsExcludedNamespace",
    "TestFlextInfraConstantsFilesNamespace",
    "TestFlextInfraConstantsGatesNamespace",
    "TestFlextInfraConstantsGithubNamespace",
    "TestFlextInfraConstantsImmutability",
    "TestFlextInfraConstantsPathsNamespace",
    "TestFlextInfraConstantsStatusNamespace",
    "TestFlextInfraDiscoveryService",
    "TestFlextInfraDiscoveryServiceUncoveredLines",
    "TestFlextInfraInitLazyLoading",
    "TestFlextInfraMaintenance",
    "TestFlextInfraNamespaceValidator",
    "TestFlextInfraPathResolver",
    "TestFlextInfraPatternsEdgeCases",
    "TestFlextInfraPatternsMarkdown",
    "TestFlextInfraPatternsTooling",
    "TestFlextInfraProtocolsImport",
    "TestFlextInfraRefactorMainCli",
    "TestFlextInfraReportingServiceCore",
    "TestFlextInfraReportingServiceExtra",
    "TestFlextInfraTypesPatternsPattern",
    "TestFlextInfraUtilitiesImport",
    "TestFlextInfraUtilitiesSelection",
    "TestFlextInfraVersionClass",
    "TestFlextInfraVersionModuleLevel",
    "TestFlextInfraVersionPackageInfo",
    "TestFlextInfraWorkspace",
    "TestFlextInfraWorkspaceChecker",
    "TestGateErrorReportingPublicBehavior",
    "TestGenerateFile",
    "TestGenerateTypeChecking",
    "TestGeneratedClassNamingConvention",
    "TestGeneratedFilesAreValidPython",
    "TestGoGate",
    "TestHandleLazyInit",
    "TestHelperConsolidationTransformer",
    "TestInferPackage",
    "TestInfraContainerFunctions",
    "TestInfraMroPattern",
    "TestInfraServiceRetrieval",
    "TestInfraTypingAdapters",
    "TestInfraTypingGuards",
    "TestInventoryServiceCore",
    "TestInventoryServiceReports",
    "TestInventoryServiceScripts",
    "TestIterWorkspacePythonModules",
    "TestMainBaseMkValidate",
    "TestMainCliRouting",
    "TestMainCommandDispatch",
    "TestMainEntryPoint",
    "TestMainInventory",
    "TestMainScan",
    "TestMaintenanceMainEnforcer",
    "TestMaintenanceMainSuccess",
    "TestMergeChildExports",
    "TestMigratorDryRun",
    "TestMigratorFailureScenarios",
    "TestMigratorFlextCore",
    "TestMigratorPoetryDeps",
    "TestMigratorPublicBehavior",
    "TestNestedClassPropagationRopeMigration",
    "TestOrchestratorBasic",
    "TestOrchestratorFailures",
    "TestOrchestratorGateNormalization",
    "TestParseViolationInvalid",
    "TestParseViolationValid",
    "TestProcessDirectory",
    "TestProjectResultProperties",
    "TestPytestDiagExtractorBehavior",
    "TestReadRequiredMinor",
    "TestRealGateRunners",
    "TestResolveAliases",
    "TestRunProjectsPublicBehavior",
    "TestRunRuffFix",
    "TestRunnerPublicBehavior",
    "TestSafeLoadYaml",
    "TestSafetyCheckpoint",
    "TestSafetyRollback",
    "TestScaffoldProjectCreatesSrcModules",
    "TestScaffoldProjectCreatesTestsModules",
    "TestScaffoldProjectIdempotency",
    "TestScaffoldProjectNoop",
    "TestScanModels",
    "TestScanPublicDefs",
    "TestScannerCore",
    "TestScannerHelpers",
    "TestScannerMultiFile",
    "TestShouldBubbleUp",
    "TestSilentFailureDetector",
    "TestSilentFailureGate",
    "TestSilentFailureValidator",
    "TestSkillValidatorAstGrepCount",
    "TestSkillValidatorCore",
    "TestSkillValidatorRenderTemplate",
    "TestStringList",
    "TestStubChain",
    "TestSymbolPropagatorRopeMigration",
    "TestTypeGates",
    "TestValidateCli",
    "TestViolationKeyFromViolation",
    "TestViolationPattern",
    "TestWorkspaceCheckCLI",
    "TestWorkspaceCheckCli",
    "TestWorkspaceChecker",
    "TestWorkspaceCheckerErrorSummary",
    "TestWorkspaceCheckerParseGateCSV",
    "TestWorkspaceCheckerResolveGates",
    "TestWorkspaceDetector",
    "TestWorkspaceMigratorDependencyBehavior",
    "TestWorkspaceRoot",
    "TestsExtendedProjectRunners",
    "TestsFlextInfraUtilitiesDiscoveryConsolidated",
    "TestsFlextInfraUtilitiesFormattingRunRuffFix",
    "WorkspaceFactory",
    "WorkspaceScenario",
    "WorkspaceScenarios",
    "deptry_report_payload",
    "exc",
    "modernizer_workspace",
    "modernizer_workspace_with_projects",
    "orchestrator",
    "real_docs_project",
    "real_git_repo",
    "real_makefile_project",
    "real_python_package",
    "real_toml_project",
    "real_workspace",
    "service",
    "test_all_three_capabilities_in_one_pass",
    "test_atomic_write_fails_when_parent_is_a_file",
    "test_atomic_write_ok",
    "test_bump_version_invalid",
    "test_bump_version_result_type",
    "test_bump_version_valid",
    "test_check_main_executes_real_cli",
    "test_ci_variables_disable_color",
    "test_class_nesting_appends_to_existing_namespace_and_removes_pass",
    "test_class_nesting_keeps_unmapped_top_level_classes",
    "test_class_nesting_moves_top_level_class_into_new_namespace",
    "test_class_reconstructor_reorders_each_contiguous_method_block",
    "test_class_reconstructor_reorders_methods_by_config",
    "test_class_reconstructor_skips_interleaved_non_method_members",
    "test_clear_checkpoint_preserves_requested_backups",
    "test_codegen_dir_returns_all_exports",
    "test_codegen_getattr_raises_attribute_error",
    "test_codegen_init_getattr_raises_attribute_error",
    "test_codegen_lazy_imports_work",
    "test_codegen_pipeline_end_to_end",
    "test_converts_multiple_aliases",
    "test_converts_typealias_to_pep695",
    "test_current_workspace_version",
    "test_decorators_family_blocks_dispatcher_target",
    "test_detect_workspace_returns_workspace_mode",
    "test_detects_attribute_base_class",
    "test_detects_basemodel_in_non_model_file",
    "test_detects_missing_local_composition_base",
    "test_detects_multiple_models",
    "test_detects_only_wrong_alias_in_mixed_import",
    "test_detects_parent_u_import_in_private_utilities_module",
    "test_detects_parent_u_import_outside_private_utilities_module",
    "test_detects_same_project_submodule_alias_import",
    "test_detects_wrong_source_m_import",
    "test_detects_wrong_source_u_import",
    "test_discover_project_roots_without_nested_git_dirs",
    "test_dispatcher_family_blocks_models_target",
    "test_engine_always_enables_class_nesting_file_rule",
    "test_ensure_future_annotations_after_docstring",
    "test_ensure_future_annotations_moves_existing_import_to_top",
    "test_execute_scans_real_package_layout",
    "test_execute_uses_codegen_project_discovery_and_project_filter",
    "test_files_modified_tracks_affected_files",
    "test_fix_pyrefly_config_main_executes_real_cli_help",
    "test_flexcore_excluded_from_run",
    "test_force_color_enables_color",
    "test_helper_consolidation_is_prechecked",
    "test_import_alias_detector_skips_facade_and_subclass_files",
    "test_import_alias_detector_skips_nested_private_and_as_renames",
    "test_import_alias_detector_skips_private_and_class_imports",
    "test_import_modernizer_adds_c_when_existing_c_is_aliased",
    "test_import_modernizer_does_not_rewrite_function_parameter_shadow",
    "test_import_modernizer_does_not_rewrite_rebound_local_name_usage",
    "test_import_modernizer_partial_import_keeps_unmapped_symbols",
    "test_import_modernizer_partial_import_with_asname_keeps_unmapped_alias",
    "test_import_modernizer_skips_rewrite_when_runtime_alias_shadowed_in_function",
    "test_import_modernizer_skips_when_runtime_alias_name_is_blocked",
    "test_import_modernizer_updates_aliased_symbol_usage",
    "test_injects_t_import_when_needed",
    "test_inserts_t_import_after_parenthesized_import_block",
    "test_lazy_import_rule_hoists_import_to_module_level",
    "test_lazy_import_rule_uses_fix_action_for_hoist",
    "test_lc_all_takes_priority_over_lang",
    "test_legacy_import_bypass_collapses_to_primary_import",
    "test_legacy_rule_uses_fix_action_remove_for_aliases",
    "test_legacy_wrapper_forwarding_keywords_is_inlined_as_alias",
    "test_legacy_wrapper_forwarding_varargs_is_inlined_as_alias",
    "test_legacy_wrapper_function_is_inlined_as_alias",
    "test_legacy_wrapper_non_passthrough_is_not_inlined",
    "test_lint_github_workflows_writes_report",
    "test_lint_subcommand_writes_report",
    "test_loose_object_detector_detects_module_logger_assignment",
    "test_main_help_flag_returns_zero",
    "test_main_help_lists_core_groups",
    "test_main_returns_error_when_no_args",
    "test_main_returns_nonzero_on_unknown",
    "test_main_returns_one_without_subcommand",
    "test_main_returns_zero_on_help",
    "test_main_unknown_group_returns_error",
    "test_maintenance_rejects_apply_flag",
    "test_migrate_protocols_rewrites_references_with_p_alias",
    "test_migrate_to_mro_inlines_alias_constant_into_constants_class",
    "test_migrate_to_mro_moves_constant_and_rewrites_reference",
    "test_migrate_to_mro_moves_manual_uppercase_assignment",
    "test_migrate_to_mro_normalizes_facade_alias_to_c",
    "test_migrate_to_mro_rejects_unknown_target",
    "test_migrate_typings_rewrites_references_with_t_alias",
    "test_migrate_workspace_applies_consumer_rewrites",
    "test_migrate_workspace_dry_run_preserves_files",
    "test_migrate_workspace_reports_protected_write_failure",
    "test_migrator_apply_updates_project_files",
    "test_migrator_discovery_failure",
    "test_migrator_dry_run_reports_changes_without_writes",
    "test_migrator_execute_returns_failure",
    "test_migrator_flext_core_dry_run",
    "test_migrator_flext_core_project_skipped",
    "test_migrator_gitignore_already_normalized_dry_run",
    "test_migrator_handles_missing_pyproject_gracefully",
    "test_migrator_makefile_not_found_dry_run",
    "test_migrator_makefile_read_failure",
    "test_migrator_no_changes_needed",
    "test_migrator_preserves_custom_makefile_content",
    "test_migrator_pyproject_not_found_dry_run",
    "test_migrator_workspace_root_not_exists",
    "test_migrator_workspace_root_project_detection",
    "test_models_family_blocks_utilities_target",
    "test_namespace_enforce_cli_fails_on_manual_protocol_violation",
    "test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring",
    "test_namespace_enforcer_apply_keeps_autofixes_when_other_violations_remain",
    "test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future",
    "test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file",
    "test_namespace_enforcer_creates_missing_facades_and_rewrites_imports",
    "test_namespace_enforcer_detects_cyclic_imports_in_tests_directory",
    "test_namespace_enforcer_detects_internal_private_imports",
    "test_namespace_enforcer_detects_manual_protocol_outside_canonical_files",
    "test_namespace_enforcer_detects_manual_typings_and_compat_aliases",
    "test_namespace_enforcer_detects_missing_runtime_alias_outside_src",
    "test_namespace_enforcer_does_not_rewrite_indented_import_aliases",
    "test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks",
    "test_namespace_enforcer_respects_tool_flext_namespace_scan_dirs",
    "test_namespace_enforcer_skips_dynamic_dirs_by_default",
    "test_namespace_rewriter_keeps_contextual_alias_subset",
    "test_namespace_rewriter_only_rewrites_runtime_alias_imports",
    "test_namespace_rewriter_skips_facade_and_subclass_files",
    "test_namespace_rewriter_skips_nested_private_as_rename_and_duplicates",
    "test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage",
    "test_nested_class_propagation_updates_import_annotations_and_calls",
    "test_no_color_beats_force_color",
    "test_no_color_env_disables_color",
    "test_no_duplicate_t_import_when_t_from_project_package",
    "test_no_duplicate_utility_implementations",
    "test_no_utility_method_shadows_parent",
    "test_non_pydantic_class_not_flagged",
    "test_non_tty_disables_color",
    "test_non_utf8_locale_disables_unicode",
    "test_noop_clean_module",
    "test_orchestrate_workspace_defaults_to_current_project",
    "test_orchestrate_workspace_rejects_unknown_verb",
    "test_parse_semver_invalid",
    "test_parse_semver_result_type",
    "test_parse_semver_valid",
    "test_pattern_rule_converts_dict_annotations_to_mapping",
    "test_pattern_rule_keeps_dict_param_when_copy_used",
    "test_pattern_rule_keeps_dict_param_when_subscript_mutated",
    "test_pattern_rule_keeps_type_cast_when_not_nested_object_cast",
    "test_pattern_rule_optionally_converts_return_annotations_to_mapping",
    "test_pattern_rule_removes_configured_redundant_casts",
    "test_pattern_rule_removes_nested_type_object_cast_chain",
    "test_pattern_rule_skips_overload_signatures",
    "test_pr_subcommand_returns_nonzero_for_minimal_repo",
    "test_pr_workspace_accepts_repeated_project_options",
    "test_preserves_annotated_in_function_params",
    "test_preserves_non_matching_unions",
    "test_preserves_override_in_method",
    "test_preserves_protocol_and_runtime_checkable",
    "test_preserves_type_checking_import",
    "test_preserves_typealias_import_when_class_level_usage_exists",
    "test_preserves_used_imports_when_import_precedes_usage",
    "test_preserves_used_typing_imports",
    "test_project_without_alias_facade_has_no_violation",
    "test_project_without_src_returns_empty",
    "test_read_project_metadata_preserves_pep621_dependency_order",
    "test_read_project_metadata_preserves_poetry_dependency_order",
    "test_refactor_file_rolls_back_invalid_output_and_preserves_backup",
    "test_refactor_files_skips_non_python_inputs",
    "test_refactor_project_integrates_safety_manager",
    "test_refactor_project_scans_tests_and_scripts_dirs",
    "test_refactor_utilities_iter_python_files_includes_examples_and_scripts",
    "test_removes_all_imports_when_none_used_import_first",
    "test_removes_all_unused_typing_imports",
    "test_removes_dead_typealias_import",
    "test_removes_typealias_import_only_when_all_usages_converted",
    "test_removes_unused_preserves_used_when_import_precedes_usage",
    "test_replace_project_version",
    "test_replaces_container_union",
    "test_replaces_numeric_union",
    "test_replaces_primitives_union",
    "test_replaces_scalar_union",
    "test_replaces_subset_union_with_none",
    "test_rewrite_compatibility_alias_violations_uses_public_runtime_api",
    "test_rewrite_manual_protocol_violations_uses_public_runtime_api",
    "test_rewrite_manual_typing_alias_violations_uses_public_runtime_api",
    "test_rewriter_adds_missing_base_and_formats",
    "test_rewriter_namespace_source_is_idempotent_with_ruff",
    "test_rewriter_preserves_non_alias_symbols",
    "test_rewriter_splits_mixed_imports_correctly",
    "test_rewrites_builtin_containers_to_canonical_t_aliases",
    "test_rewrites_fixed_arity_four_tuple_to_quad",
    "test_rewrites_tuple_variadics_and_any_annotations",
    "test_rule_dispatch_fails_on_invalid_pattern_rule_config",
    "test_rule_dispatch_fails_on_unknown_rule_mapping",
    "test_rule_dispatch_keeps_legacy_id_fallback_mapping",
    "test_rule_dispatch_prefers_fix_action_metadata",
    "test_run_github_pull_request_fails_for_minimal_repo",
    "test_run_github_workspace_pull_requests_aggregates_results",
    "test_run_github_workspace_pull_requests_honors_fail_fast",
    "test_run_github_workspace_pull_requests_respects_project_selection",
    "test_run_rope_post_hooks_applies_mro_migration",
    "test_run_rope_post_hooks_dry_run_is_non_mutating",
    "test_runtime_family_blocks_non_runtime_target",
    "test_signature_propagation_removes_and_adds_keywords",
    "test_signature_propagation_renames_call_keyword",
    "test_skips_definition_files",
    "test_skips_duplicate_t_import_in_parenthesized_import_block",
    "test_skips_facade_declaration_files",
    "test_skips_import_as_rename",
    "test_skips_init_file",
    "test_skips_models_directory",
    "test_skips_models_file",
    "test_skips_non_alias_symbols",
    "test_skips_non_facade_files",
    "test_skips_private_candidate_classes",
    "test_skips_private_class",
    "test_skips_protected_files",
    "test_skips_r_alias_universal_exception",
    "test_skips_same_project_private_submodule",
    "test_skips_same_project_submodule_class_import",
    "test_skips_settings_file",
    "test_skips_when_candidate_is_already_in_facade_bases",
    "test_symbol_propagation_keeps_alias_reference_when_asname_used",
    "test_symbol_propagation_renames_import_and_local_references",
    "test_symbol_propagation_updates_mro_base_references",
    "test_sync_fails_when_generator_fails",
    "test_sync_fails_when_gitignore_path_is_directory",
    "test_sync_fails_when_workspace_root_is_missing",
    "test_sync_generates_basemk_gitignore_and_makefile",
    "test_sync_github_workflows_apply_writes_ci_files_and_report",
    "test_sync_github_workflows_prunes_noncanonical_files",
    "test_sync_github_workflows_reports_create_operations",
    "test_sync_is_idempotent_on_second_run",
    "test_sync_regenerates_project_makefile_without_legacy_passthrough",
    "test_sync_workspace_returns_sync_result",
    "test_sync_workspace_root_also_syncs_child_projects",
    "test_tty_with_dumb_or_empty_term_disables_color",
    "test_tty_with_xterm_enables_color",
    "test_typealias_conversion_preserves_used_typing_siblings",
    "test_utf8_locale_enables_unicode",
    "test_utilities_family_allows_utilities_target",
    "test_workflows_subcommand_applies_templates",
    "test_workspace_check_main_returns_error_without_projects",
    "test_workspace_main_detect_accepts_explicit_workspace_root",
    "test_workspace_main_orchestrate_returns_failure_for_unknown_verb",
    "test_workspace_main_sync_runs_public_command",
    "test_workspace_main_without_command_returns_failure",
    "test_workspace_makefile_dry_run_fmt_respects_project_selection",
    "test_workspace_makefile_dry_run_gen_forwards_selection",
    "test_workspace_makefile_dry_run_mod_respects_project_selection",
    "test_workspace_makefile_dry_run_mod_without_selection_uses_workspace_scope",
    "test_workspace_makefile_dry_run_sync_respects_project_selection",
    "test_workspace_makefile_dry_run_up_forwards_selection_to_mod",
    "test_workspace_makefile_generator_declares_canonical_workspace_variables",
    "test_workspace_makefile_generator_declares_workspace_boot_separation",
    "test_workspace_makefile_generator_does_not_persist_external_project_names",
    "test_workspace_makefile_generator_emits_parseable_discovery_commands",
    "test_workspace_makefile_generator_limits_absolute_path_scan_to_sources",
    "test_workspace_makefile_generator_reuses_mod_and_boot_feedback",
    "test_workspace_makefile_generator_sanitizes_orchestrator_env",
    "test_workspace_makefile_generator_uses_check_only_for_maintenance_validation",
    "tool_config_document",
    "v",
    "workspace_main",
]
