# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Unit package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import install_lazy_exports, merge_lazy_imports

if _t.TYPE_CHECKING:
    import tests.unit._utilities as _tests_unit__utilities

    _utilities = _tests_unit__utilities
    import tests.unit.basemk as _tests_unit_basemk
    from tests.unit._utilities import (
        TestDiscoveryDiscoverProjects,
        TestDiscoveryFindAllPyprojectFiles,
        TestDiscoveryIterPythonFiles,
        TestDiscoveryProjectRoots,
        TestFormattingRunRuffFix,
        TestSafetyCheckpoint,
        TestSafetyRollback,
        TestScanModels,
        test_discovery_consolidated,
        test_formatting,
        test_iteration,
        test_rope_hooks,
        test_run_rope_post_hooks_applies_mro_migration,
        test_run_rope_post_hooks_dry_run_is_non_mutating,
        test_safety,
        test_scanning,
    )

    basemk = _tests_unit_basemk
    import tests.unit.check as _tests_unit_check
    from tests.unit.basemk import (
        TestFlextInfraBaseMk,
        basemk_main,
        test_basemk_build_config_with_none,
        test_basemk_build_config_with_project_name,
        test_basemk_cli_generate_to_file,
        test_basemk_cli_generate_to_stdout,
        test_basemk_engine_execute_calls_render_all,
        test_basemk_engine_render_all_handles_template_error,
        test_basemk_engine_render_all_returns_string,
        test_basemk_engine_render_all_with_valid_config,
        test_basemk_main_ensures_structlog_configured,
        test_basemk_main_output_to_stdout,
        test_basemk_main_rejects_apply_flag,
        test_basemk_main_with_generate_command,
        test_basemk_main_with_generation_failure,
        test_basemk_main_with_help,
        test_basemk_main_with_invalid_command,
        test_basemk_main_with_no_command,
        test_basemk_main_with_none_argv,
        test_basemk_main_with_output_file,
        test_basemk_main_with_project_name,
        test_basemk_main_with_write_failure,
        test_engine,
        test_generator,
        test_generator_edge_cases,
        test_generator_execute_returns_generated_content,
        test_generator_fails_for_invalid_make_syntax,
        test_generator_generate_propagates_render_failure,
        test_generator_generate_with_basemk_config_object,
        test_generator_generate_with_dict_config,
        test_generator_generate_with_invalid_dict_config,
        test_generator_generate_with_none_config_uses_default,
        test_generator_initializes_with_custom_engine,
        test_generator_initializes_with_default_engine,
        test_generator_normalize_config_with_basemk_config,
        test_generator_normalize_config_with_dict,
        test_generator_normalize_config_with_invalid_dict,
        test_generator_normalize_config_with_none,
        test_generator_renders_with_config_override,
        test_generator_validate_generated_output_handles_oserror,
        test_generator_write_creates_parent_directories,
        test_generator_write_fails_without_output_or_stream,
        test_generator_write_handles_file_permission_error,
        test_generator_write_saves_output_file,
        test_generator_write_to_file,
        test_generator_write_to_stream,
        test_generator_write_to_stream_handles_oserror,
        test_init,
        test_main,
        test_make_boot_works_without_existing_venv_in_workspace_mode,
        test_make_check_fast_path_check_only_suppresses_fix_writes,
        test_make_check_file_scope_rejects_unsupported_gates,
        test_make_check_file_scope_runs_mypy,
        test_make_check_file_scope_unsets_python_path_env,
        test_make_check_full_run_forwards_fix_and_tool_args,
        test_make_check_full_run_unsets_python_path_env,
        test_make_contract,
        test_make_help_lists_supported_options,
        test_render_all_declares_and_documents_runtime_options,
        test_render_all_exposes_canonical_public_targets,
        test_render_all_generates_large_makefile,
        test_render_all_has_no_scripts_path_references,
        test_rendered_base_mk_declares_cli_group_roots,
        test_rendered_base_mk_forwards_canonical_root_in_workspace_preflight,
    )

    check = _tests_unit_check
    import tests.unit.codegen as _tests_unit_codegen
    from tests.unit.check import (
        GateClass,
        RunProjectsMock,
        Spy,
        TestCheckIssueFormatted,
        TestCheckMainEntryPoint,
        TestCheckProjectRunners,
        TestCollectMarkdownFiles,
        TestConfigFixerEnsureProjectExcludes,
        TestConfigFixerExecute,
        TestConfigFixerFindPyprojectFiles,
        TestConfigFixerFixSearchPaths,
        TestConfigFixerPathResolution,
        TestConfigFixerProcessFile,
        TestConfigFixerRemoveIgnoreSubConfig,
        TestConfigFixerRun,
        TestConfigFixerRunMethods,
        TestConfigFixerRunWithVerbose,
        TestConfigFixerToArray,
        TestErrorReporting,
        TestFixPyrelfyCLI,
        TestFlextInfraCheck,
        TestFlextInfraConfigFixer,
        TestFlextInfraWorkspaceChecker,
        TestGoFmtEmptyLinesInOutput,
        TestJsonWriteFailure,
        TestLintAndFormatPublicMethods,
        TestMarkdownReportEmptyGates,
        TestMypyEmptyLinesInOutput,
        TestProcessFileReadError,
        TestProjectResultProperties,
        TestRuffFormatDuplicateFiles,
        TestRunBandit,
        TestRunCLIExtended,
        TestRunCommand,
        TestRunGo,
        TestRunMarkdown,
        TestRunMypy,
        TestRunProjectFixMode,
        TestRunProjectsBehavior,
        TestRunProjectsReports,
        TestRunProjectsValidation,
        TestRunPyrefly,
        TestRunPyright,
        TestRunPyrightArgs,
        TestRunRuffFormat,
        TestRunRuffLint,
        TestRunSingleProject,
        TestWorkspaceCheckCLI,
        TestWorkspaceCheckerBuildGateResult,
        TestWorkspaceCheckerCollectMarkdownFiles,
        TestWorkspaceCheckerDirsWithPy,
        TestWorkspaceCheckerErrorSummary,
        TestWorkspaceCheckerExecute,
        TestWorkspaceCheckerExistingCheckDirs,
        TestWorkspaceCheckerInitialization,
        TestWorkspaceCheckerInitOSError,
        TestWorkspaceCheckerParseGateCSV,
        TestWorkspaceCheckerResolveGates,
        TestWorkspaceCheckerResolveWorkspaceRootFallback,
        TestWorkspaceCheckerRunBandit,
        TestWorkspaceCheckerRunCommand,
        TestWorkspaceCheckerRunGo,
        TestWorkspaceCheckerRunMarkdown,
        TestWorkspaceCheckerRunMypy,
        TestWorkspaceCheckerRunPyright,
        cli_tests,
        create_check_project_iter_stub,
        create_check_project_stub,
        create_checker_project,
        create_fake_run_projects,
        create_fake_run_raw,
        create_gate_context,
        create_gate_execution,
        extended_cli_entry_tests,
        extended_config_fixer_errors_tests,
        extended_config_fixer_tests,
        extended_error_reporting_tests,
        extended_gate_bandit_markdown_tests,
        extended_gate_go_cmd_tests,
        extended_gate_mypy_pyright_tests,
        extended_models_tests,
        extended_project_runners_tests,
        extended_projects_tests,
        extended_resolve_gates_tests,
        extended_run_projects_tests,
        extended_runners_extra_tests,
        extended_runners_go_tests,
        extended_runners_ruff_tests,
        extended_runners_tests,
        extended_workspace_init_tests,
        fix_pyrefly_config_tests,
        init_tests,
        main_tests,
        make_issue,
        make_project,
        patch_gate_run,
        patch_gate_run_sequence,
        patch_python_dir_detection,
        pyrefly_tests,
        run_command_failure_check,
        run_gate_check,
        test_check_main_executes_real_cli,
        test_fix_pyrefly_config_main_executes_real_cli_help,
        test_resolve_gates_maps_type_alias,
        test_run_cli_rejects_shared_dry_run_flag,
        test_run_cli_run_forwards_fix_and_tool_args,
        test_run_cli_run_returns_one_for_fail,
        test_run_cli_run_returns_two_for_error,
        test_run_cli_run_returns_zero_for_pass,
        test_run_cli_with_fail_fast_flag,
        test_run_cli_with_multiple_projects,
        test_workspace_check_main_returns_error_without_projects,
        workspace_check_tests,
        workspace_tests,
    )

    codegen = _tests_unit_codegen
    import tests.unit.container as _tests_unit_container
    from tests.unit.codegen import (
        FlextInfraCodegenTestProjectFactory,
        TestAllDirectoriesScanned,
        TestBuildSiblingExportIndex,
        TestCheckOnlyMode,
        TestEdgeCases,
        TestExcludedDirectories,
        TestExtractExports,
        TestExtractVersionExports,
        TestFlextInfraCodegenLazyInit,
        TestGeneratedClassNamingConvention,
        TestGeneratedFilesAreValidPython,
        TestGenerateFile,
        TestGenerateTypeChecking,
        TestInferPackage,
        TestMergeChildExports,
        TestProcessDirectory,
        TestReadExistingDocstring,
        TestResolveAliases,
        TestRunRuffFix,
        TestScanPublicDefs,
        TestShouldBubbleUp,
        autofix_workspace_tests,
        census_models_tests,
        census_tests,
        constants_quality_gate_tests,
        lazy_init_generation_tests,
        lazy_init_helpers_tests,
        lazy_init_process_tests,
        lazy_init_service_tests,
        lazy_init_tests,
        lazy_init_transforms_tests,
        pipeline_tests,
        scaffolder_naming_tests,
        scaffolder_tests,
        test_codegen_init_getattr_raises_attribute_error,
    )

    container = _tests_unit_container
    import tests.unit.deps as _tests_unit_deps
    from tests.unit.container import (
        TestInfraContainerFunctions,
        TestInfraMroPattern,
        TestInfraServiceRetrieval,
        test_infra_container,
    )

    deps = _tests_unit_deps
    import tests.unit.discovery as _tests_unit_discovery
    from tests.unit.deps import (
        TestBuildProjectReport,
        TestClassifyIssues,
        TestCollectInternalDeps,
        TestCollectInternalDepsEdgeCases,
        TestConsolidateGroupsPhase,
        TestConstants,
        TestDetectionUncoveredLines,
        TestDetectMode,
        TestDetectorReportFlags,
        TestDetectorRunFailures,
        TestEnsureCheckout,
        TestEnsureCheckoutEdgeCases,
        TestEnsureCoverageConfigPhase,
        TestEnsureFormattingToolingPhase,
        TestEnsureMypyConfigPhase,
        TestEnsureNamespaceToolingPhase,
        TestEnsurePydanticMypyConfigPhase,
        TestEnsurePyreflyConfigPhase,
        TestEnsurePyrightConfigPhase,
        TestEnsurePytestConfigPhase,
        TestEnsureRuffConfigPhase,
        TestEnsureSymlink,
        TestEnsureSymlinkEdgeCases,
        TestFlextInfraDependencyDetectionModels,
        TestFlextInfraDependencyDetectionService,
        TestFlextInfraDependencyDetectorModels,
        TestFlextInfraDependencyPathSync,
        TestFlextInfraDeps,
        TestFlextInfraExtraPathsManager,
        TestFlextInfraInternalDependencySyncService,
        TestFlextInfraPyprojectModernizer,
        TestFlextInfraRuntimeDevDependencyDetectorInit,
        TestFlextInfraRuntimeDevDependencyDetectorRunDetect,
        TestFlextInfraRuntimeDevDependencyDetectorRunReport,
        TestFlextInfraRuntimeDevDependencyDetectorRunTypings,
        TestGetDepPaths,
        TestInferOwnerFromOrigin,
        TestInjectCommentsPhase,
        TestIsInternalPathDep,
        TestIsRelativeTo,
        TestIsWorkspaceMode,
        TestLoadDependencyLimits,
        TestMainDelegation,
        TestMainEdgeCases,
        TestMainExceptionHandling,
        TestMainFunction,
        TestMainHelpAndErrors,
        TestMainModuleImport,
        TestMainReturnValues,
        TestMainSubcommandDispatch,
        TestMainSysArgvModification,
        TestModernizerEdgeCases,
        TestModernizerRunAndMain,
        TestModernizerUncoveredLines,
        TestModuleAndTypingsFlow,
        TestOwnerFromRemoteUrl,
        TestParseGitmodules,
        TestParser,
        TestParseRepoMap,
        TestPathDepPathsPep621,
        TestPathDepPathsPoetry,
        TestPathSyncEdgeCases,
        TestReadDoc,
        TestResolveRef,
        TestRewriteDepPaths,
        TestRewritePep621,
        TestRewritePoetry,
        TestRunDeptry,
        TestRunMypyStubHints,
        TestRunPipCheck,
        TestSubcommandMapping,
        TestSync,
        TestSyncMethodEdgeCases,
        TestSyncMethodEdgeCasesMore,
        TestSyncOne,
        TestSynthesizedRepoMap,
        TestToInfraValue,
        TestValidateGitRefEdgeCases,
        TestWorkspaceRootFromEnv,
        TestWorkspaceRootFromParents,
        doc,
        extract_dep_name,
        manager,
        pyright_content,
        rewrite_dep_paths,
        test_array,
        test_as_string_list,
        test_as_string_list_toml_item,
        test_canonical_dev_dependencies,
        test_consolidate_groups_phase_apply_removes_old_groups,
        test_consolidate_groups_phase_apply_with_empty_poetry_group,
        test_declared_dependency_names_collects_all_supported_groups,
        test_dedupe_specs,
        test_dep_name,
        test_detect_mode_with_nonexistent_path,
        test_detect_mode_with_path_object,
        test_detection_classify,
        test_detection_deptry,
        test_detection_discover,
        test_detection_models,
        test_detection_pip_check,
        test_detection_typings,
        test_detection_typings_flow,
        test_detection_uncovered,
        test_detector_detect,
        test_detector_detect_failures,
        test_detector_init,
        test_detector_main,
        test_detector_models,
        test_detector_report,
        test_detector_report_flags,
        test_ensure_pyrefly_config_phase_apply_errors,
        test_ensure_pyrefly_config_phase_apply_ignore_errors,
        test_ensure_pyrefly_config_phase_apply_python_version,
        test_ensure_pyrefly_config_phase_apply_search_path,
        test_ensure_pyrefly_config_phase_is_idempotent,
        test_ensure_table,
        test_extra_paths_manager,
        test_extra_paths_pep621,
        test_extra_paths_sync,
        test_extract_dep_name,
        test_extract_requirement_name,
        test_flext_infra_pyproject_modernizer_find_pyproject_files,
        test_flext_infra_pyproject_modernizer_process_file_invalid_toml,
        test_helpers_alias_is_reachable_helpers,
        test_helpers_alias_is_reachable_project_obj,
        test_inject_comments_phase_apply_banner,
        test_inject_comments_phase_apply_broken_group_section,
        test_inject_comments_phase_apply_markers,
        test_inject_comments_phase_apply_with_optional_dependencies_dev,
        test_inject_comments_phase_deduplicates_family_markers,
        test_inject_comments_phase_marks_pytest_and_coverage_subtables,
        test_inject_comments_phase_removes_auto_banner_and_auto_marker,
        test_inject_comments_phase_repositions_marker_before_section,
        test_internal_sync_discovery,
        test_internal_sync_discovery_edge,
        test_internal_sync_main,
        test_internal_sync_resolve,
        test_internal_sync_sync,
        test_internal_sync_sync_edge,
        test_internal_sync_sync_edge_more,
        test_internal_sync_update,
        test_internal_sync_update_checkout_edge,
        test_internal_sync_validation,
        test_internal_sync_workspace,
        test_main_discovery_failure,
        test_main_dispatch,
        test_main_no_changes_needed,
        test_main_project_invalid_toml,
        test_main_project_no_name,
        test_main_project_non_string_name,
        test_main_project_obj_not_dict_first_loop,
        test_main_project_obj_not_dict_second_loop,
        test_main_success_modes,
        test_main_sync_failure,
        test_main_with_changes_and_dry_run,
        test_main_with_changes_no_dry_run,
        test_modernizer_comments,
        test_modernizer_consolidate,
        test_modernizer_coverage,
        test_modernizer_helpers,
        test_modernizer_main,
        test_modernizer_main_extra,
        test_modernizer_mypy,
        test_modernizer_pyrefly,
        test_modernizer_pyright,
        test_modernizer_pytest,
        test_modernizer_tooling,
        test_modernizer_workspace,
        test_path_sync_helpers,
        test_path_sync_init,
        test_path_sync_main,
        test_path_sync_main_edges,
        test_path_sync_main_more,
        test_path_sync_main_project_obj,
        test_path_sync_rewrite_deps,
        test_path_sync_rewrite_pep621,
        test_path_sync_rewrite_poetry,
        test_project_dev_groups,
        test_project_dev_groups_missing_sections,
        test_pyrefly_search_paths_include_workspace_declared_dev_dependencies,
        test_rewrite_dep_paths_dry_run,
        test_rewrite_dep_paths_read_failure,
        test_rewrite_dep_paths_with_internal_names,
        test_rewrite_dep_paths_with_no_deps,
        test_rewrite_pep621_invalid_path_dep_regex,
        test_rewrite_pep621_no_project_table,
        test_rewrite_pep621_non_string_item,
        test_rewrite_poetry_no_poetry_table,
        test_rewrite_poetry_no_tool_table,
        test_rewrite_poetry_with_non_dict_value,
        test_string_zero_return_value,
        test_sync_extra_paths_missing_root_pyproject,
        test_sync_extra_paths_success_modes,
        test_sync_extra_paths_sync_failure,
        test_sync_one_edge_cases,
        test_target_path,
        test_unwrap_item,
        test_unwrap_item_toml_item,
        test_workspace_root_doc_construction,
        test_workspace_root_fallback,
    )

    discovery = _tests_unit_discovery
    import tests.unit.docs as _tests_unit_docs
    from tests.unit.discovery import (
        TestFlextInfraDiscoveryServiceUncoveredLines,
        test_infra_discovery,
        test_infra_discovery_edge_cases,
    )

    docs = _tests_unit_docs
    import tests.unit.github as _tests_unit_github
    from tests.unit.docs import (
        TestAdrHelpers,
        TestAuditorBrokenLinks,
        TestAuditorCore,
        TestAuditorForbiddenTerms,
        TestAuditorMainCli,
        TestAuditorNormalize,
        TestAuditorScope,
        TestAuditorScopeFailure,
        TestAuditorToMarkdown,
        TestBuilderCore,
        TestBuilderScope,
        TestBuildScopes,
        TestFixerCore,
        TestFixerProcessFile,
        TestFixerScope,
        TestFixerToc,
        TestFlextInfraDocs,
        TestFlextInfraDocScope,
        TestGeneratorCore,
        TestGeneratorHelpers,
        TestGeneratorScope,
        TestIterMarkdownFiles,
        TestLoadAuditBudgets,
        TestMainRouting,
        TestMainWithFlags,
        TestMaybeWriteTodo,
        TestRunAudit,
        TestRunBuild,
        TestRunFix,
        TestRunGenerate,
        TestRunValidate,
        TestSelectedProjectNames,
        TestValidateCore,
        TestValidateReport,
        TestValidateScope,
        TestWriteJson,
        TestWriteMarkdown,
        auditor,
        auditor_budgets_tests,
        auditor_cli_tests,
        auditor_links_tests,
        auditor_scope_tests,
        auditor_tests,
        builder,
        builder_scope_tests,
        builder_tests,
        fixer,
        fixer_internals_tests,
        fixer_tests,
        gen,
        generator_internals_tests,
        generator_tests,
        is_external,
        main_commands_tests,
        main_entry_tests,
        normalize_link,
        shared_iter_tests,
        shared_tests,
        shared_write_tests,
        should_skip_target,
        validator,
        validator_internals_tests,
        validator_tests,
    )

    github = _tests_unit_github
    import tests.unit.io as _tests_unit_io
    from tests.unit.github import (
        StubCommandOutput,
        StubJsonIo,
        StubLinter,
        StubPrManager,
        StubProjectInfo,
        StubReporting,
        StubRunner,
        StubSelector,
        StubSyncer,
        StubTemplates,
        StubUtilities,
        StubVersioning,
        StubWorkspaceManager,
        TestMain,
        TestRunLint,
        TestRunPr,
        TestRunPrWorkspace,
        TestRunWorkflows,
        main_cli_tests,
        main_dispatch_tests,
        main_integration_tests,
        test_main_returns_nonzero_on_unknown,
        test_main_returns_zero_on_help,
        test_pr_workspace_accepts_repeated_project_options,
    )

    io = _tests_unit_io
    import tests.unit.refactor as _tests_unit_refactor
    from tests.unit.io import (
        SampleModel,
        TestFlextInfraJsonService,
        TestShouldUseColor,
        TestShouldUseUnicode,
        test_infra_json_io,
        test_infra_terminal_detection,
    )

    refactor = _tests_unit_refactor
    import tests.unit.release as _tests_unit_release
    from tests.unit.refactor import (
        FAMILY_FILE_MAP,
        FAMILY_SUFFIX_MAP,
        EngineSafetyStub,
        conftest,
        refactor_main,
        rope_project,
        test_all_three_capabilities_in_one_pass,
        test_class_reconstructor_reorders_each_contiguous_method_block,
        test_class_reconstructor_reorders_methods_by_config,
        test_class_reconstructor_skips_interleaved_non_method_members,
        test_converts_multiple_aliases,
        test_converts_typealias_to_pep695,
        test_detects_attribute_base_class,
        test_detects_basemodel_in_non_model_file,
        test_detects_missing_local_composition_base,
        test_detects_multiple_models,
        test_detects_only_wrong_alias_in_mixed_import,
        test_detects_same_project_submodule_alias_import,
        test_detects_wrong_source_m_import,
        test_detects_wrong_source_u_import,
        test_engine_always_enables_class_nesting_file_rule,
        test_ensure_future_annotations_after_docstring,
        test_ensure_future_annotations_moves_existing_import_to_top,
        test_import_alias_detector_skips_facade_and_subclass_files,
        test_import_alias_detector_skips_nested_private_and_as_renames,
        test_import_alias_detector_skips_private_and_class_imports,
        test_import_modernizer_adds_c_when_existing_c_is_aliased,
        test_import_modernizer_does_not_rewrite_function_parameter_shadow,
        test_import_modernizer_does_not_rewrite_rebound_local_name_usage,
        test_import_modernizer_partial_import_keeps_unmapped_symbols,
        test_import_modernizer_partial_import_with_asname_keeps_unmapped_alias,
        test_import_modernizer_skips_rewrite_when_runtime_alias_shadowed_in_function,
        test_import_modernizer_skips_when_runtime_alias_name_is_blocked,
        test_import_modernizer_updates_aliased_symbol_usage,
        test_infra_refactor_class_and_propagation,
        test_infra_refactor_class_placement,
        test_infra_refactor_engine,
        test_infra_refactor_import_modernizer,
        test_infra_refactor_legacy_and_annotations,
        test_infra_refactor_mro_completeness,
        test_infra_refactor_mro_import_rewriter,
        test_infra_refactor_namespace_aliases,
        test_infra_refactor_namespace_source,
        test_infra_refactor_pattern_corrections,
        test_infra_refactor_project_classifier,
        test_infra_refactor_safety,
        test_infra_refactor_typing_unifier,
        test_injects_t_import_when_needed,
        test_lazy_import_rule_hoists_import_to_module_level,
        test_lazy_import_rule_uses_fix_action_for_hoist,
        test_legacy_import_bypass_collapses_to_primary_import,
        test_legacy_rule_uses_fix_action_remove_for_aliases,
        test_legacy_wrapper_forwarding_keywords_is_inlined_as_alias,
        test_legacy_wrapper_forwarding_varargs_is_inlined_as_alias,
        test_legacy_wrapper_function_is_inlined_as_alias,
        test_legacy_wrapper_non_passthrough_is_not_inlined,
        test_main_cli,
        test_migrate_workspace_applies_consumer_rewrites,
        test_migrate_workspace_dry_run_preserves_files,
        test_namespace_rewriter_keeps_contextual_alias_subset,
        test_namespace_rewriter_only_rewrites_runtime_alias_imports,
        test_namespace_rewriter_skips_facade_and_subclass_files,
        test_namespace_rewriter_skips_nested_private_as_rename_and_duplicates,
        test_no_duplicate_t_import_when_t_from_project_package,
        test_non_pydantic_class_not_flagged,
        test_noop_clean_module,
        test_pattern_rule_converts_dict_annotations_to_mapping,
        test_pattern_rule_keeps_dict_param_when_copy_used,
        test_pattern_rule_keeps_dict_param_when_subscript_mutated,
        test_pattern_rule_keeps_type_cast_when_not_nested_object_cast,
        test_pattern_rule_optionally_converts_return_annotations_to_mapping,
        test_pattern_rule_removes_configured_redundant_casts,
        test_pattern_rule_removes_nested_type_object_cast_chain,
        test_pattern_rule_skips_overload_signatures,
        test_preserves_annotated_in_function_params,
        test_preserves_non_matching_unions,
        test_preserves_override_in_method,
        test_preserves_protocol_and_runtime_checkable,
        test_preserves_type_checking_import,
        test_preserves_typealias_import_when_class_level_usage_exists,
        test_preserves_used_imports_when_import_precedes_usage,
        test_preserves_used_typing_imports,
        test_project_without_alias_facade_has_no_violation,
        test_read_project_metadata_preserves_pep621_dependency_order,
        test_read_project_metadata_preserves_poetry_dependency_order,
        test_refactor_census_accepts_apply_before_subcommand,
        test_refactor_centralize_accepts_apply_before_subcommand,
        test_refactor_files_skips_non_python_inputs,
        test_refactor_project_integrates_safety_manager,
        test_refactor_project_scans_tests_and_scripts_dirs,
        test_refactor_runtime_alias_imports_accepts_aliases_and_project,
        test_removes_all_imports_when_none_used_import_first,
        test_removes_all_unused_typing_imports,
        test_removes_dead_typealias_import,
        test_removes_typealias_import_only_when_all_usages_converted,
        test_removes_unused_preserves_used_when_import_precedes_usage,
        test_replaces_container_union,
        test_replaces_numeric_union,
        test_replaces_primitives_union,
        test_replaces_scalar_union,
        test_replaces_subset_union_with_none,
        test_rewriter_adds_missing_base_and_formats,
        test_rewriter_namespace_source_is_idempotent_with_ruff,
        test_rewriter_preserves_non_alias_symbols,
        test_rewriter_splits_mixed_imports_correctly,
        test_rule_dispatch_fails_on_invalid_pattern_rule_config,
        test_rule_dispatch_fails_on_unknown_rule_mapping,
        test_rule_dispatch_keeps_legacy_id_fallback_mapping,
        test_rule_dispatch_prefers_fix_action_metadata,
        test_runtime_alias_migrator_merges_local_imports_in_src,
        test_runtime_alias_migrator_merges_local_imports_in_tests,
        test_runtime_alias_migrator_skips_unsafe_local_cycle,
        test_signature_propagation_removes_and_adds_keywords,
        test_signature_propagation_renames_call_keyword,
        test_skips_definition_files,
        test_skips_facade_declaration_files,
        test_skips_import_as_rename,
        test_skips_init_file,
        test_skips_models_directory,
        test_skips_models_file,
        test_skips_non_alias_symbols,
        test_skips_non_facade_files,
        test_skips_private_candidate_classes,
        test_skips_private_class,
        test_skips_protected_files,
        test_skips_r_alias_universal_exception,
        test_skips_same_project_private_submodule,
        test_skips_same_project_submodule_class_import,
        test_skips_settings_file,
        test_skips_when_candidate_is_already_in_facade_bases,
        test_symbol_propagation_keeps_alias_reference_when_asname_used,
        test_symbol_propagation_renames_import_and_local_references,
        test_symbol_propagation_updates_mro_base_references,
        test_typealias_conversion_preserves_used_typing_siblings,
    )

    release = _tests_unit_release
    import tests.unit.test_infra_constants_core as _tests_unit_test_infra_constants_core
    from tests.unit.release import (
        FakeReporting,
        FakeSelection,
        FakeSubprocess,
        FakeUtilsNamespace,
        FakeVersioning,
        TestBuildTargets,
        TestBumpNextDev,
        TestCollectChanges,
        TestCreateBranches,
        TestCreateTag,
        TestDispatchPhase,
        TestGenerateNotes,
        TestPhaseBuild,
        TestPhasePublish,
        TestPhaseValidate,
        TestPhaseVersion,
        TestPreviousTag,
        TestPushRelease,
        TestReleaseInit,
        TestReleaseMainFlow,
        TestReleaseMainParsing,
        TestReleaseMainTagResolution,
        TestReleaseMainVersionResolution,
        TestReleaseOrchestratorExecute,
        TestResolveVersionInteractive,
        TestRunMake,
        TestUpdateChangelog,
        TestVersionFiles,
        flow_tests,
        orchestrator_git_tests,
        orchestrator_helpers_tests,
        orchestrator_phases_tests,
        orchestrator_publish_tests,
        orchestrator_tests,
        release_init_tests,
        version_resolution_tests,
        workspace_root,
    )

    test_infra_constants_core = _tests_unit_test_infra_constants_core
    import tests.unit.test_infra_constants_extra as _tests_unit_test_infra_constants_extra
    from tests.unit.test_infra_constants_core import (
        TestFlextInfraConstantsExcludedNamespace,
        TestFlextInfraConstantsFilesNamespace,
        TestFlextInfraConstantsGatesNamespace,
        TestFlextInfraConstantsPathsNamespace,
        TestFlextInfraConstantsStatusNamespace,
    )

    test_infra_constants_extra = _tests_unit_test_infra_constants_extra
    import tests.unit.test_infra_git as _tests_unit_test_infra_git
    from tests.unit.test_infra_constants_extra import (
        TestFlextInfraConstantsAlias,
        TestFlextInfraConstantsCheckNamespace,
        TestFlextInfraConstantsConsistency,
        TestFlextInfraConstantsEncodingNamespace,
        TestFlextInfraConstantsGithubNamespace,
        TestFlextInfraConstantsImmutability,
    )

    test_infra_git = _tests_unit_test_infra_git
    import tests.unit.test_infra_init_lazy_core as _tests_unit_test_infra_init_lazy_core
    from tests.unit.test_infra_git import (
        TestFlextInfraGitService,
        TestGitPush,
        TestGitTagOperations,
        TestRemovedCompatibilityMethods,
        git_repo,
    )

    test_infra_init_lazy_core = _tests_unit_test_infra_init_lazy_core
    import tests.unit.test_infra_init_lazy_submodules as _tests_unit_test_infra_init_lazy_submodules
    from tests.unit.test_infra_init_lazy_core import TestFlextInfraInitLazyLoading

    test_infra_init_lazy_submodules = _tests_unit_test_infra_init_lazy_submodules
    import tests.unit.test_infra_main as _tests_unit_test_infra_main
    from tests.unit.test_infra_init_lazy_submodules import (
        TestFlextInfraSubmoduleInitLazyLoading,
    )

    test_infra_main = _tests_unit_test_infra_main
    import tests.unit.test_infra_maintenance_cli as _tests_unit_test_infra_maintenance_cli
    from tests.unit.test_infra_main import (
        test_main_all_groups_defined,
        test_main_group_descriptions_are_present,
        test_main_help_flag_returns_zero,
        test_main_returns_error_when_no_args,
        test_main_unknown_group_returns_error,
    )

    test_infra_maintenance_cli = _tests_unit_test_infra_maintenance_cli
    import tests.unit.test_infra_maintenance_init as _tests_unit_test_infra_maintenance_init
    from tests.unit.test_infra_maintenance_cli import (
        test_maintenance_rejects_apply_flag,
    )

    test_infra_maintenance_init = _tests_unit_test_infra_maintenance_init
    import tests.unit.test_infra_maintenance_main as _tests_unit_test_infra_maintenance_main
    from tests.unit.test_infra_maintenance_init import TestFlextInfraMaintenance

    test_infra_maintenance_main = _tests_unit_test_infra_maintenance_main
    import tests.unit.test_infra_maintenance_python_version as _tests_unit_test_infra_maintenance_python_version
    from tests.unit.test_infra_maintenance_main import (
        TestMaintenanceMainEnforcer,
        TestMaintenanceMainSuccess,
        main,
    )

    test_infra_maintenance_python_version = (
        _tests_unit_test_infra_maintenance_python_version
    )
    import tests.unit.test_infra_paths as _tests_unit_test_infra_paths
    from tests.unit.test_infra_maintenance_python_version import (
        TestDiscoverProjects,
        TestEnforcerExecute,
        TestEnsurePythonVersionFile,
        TestReadRequiredMinor,
        TestWorkspaceRoot,
    )

    test_infra_paths = _tests_unit_test_infra_paths
    import tests.unit.test_infra_patterns_core as _tests_unit_test_infra_patterns_core
    from tests.unit.test_infra_paths import TestFlextInfraPathResolver

    test_infra_patterns_core = _tests_unit_test_infra_patterns_core
    import tests.unit.test_infra_patterns_extra as _tests_unit_test_infra_patterns_extra
    from tests.unit.test_infra_patterns_core import (
        TestFlextInfraPatternsMarkdown,
        TestFlextInfraPatternsTooling,
    )

    test_infra_patterns_extra = _tests_unit_test_infra_patterns_extra
    import tests.unit.test_infra_protocols as _tests_unit_test_infra_protocols
    from tests.unit.test_infra_patterns_extra import (
        TestFlextInfraPatternsEdgeCases,
        TestFlextInfraPatternsPatternTypes,
    )

    test_infra_protocols = _tests_unit_test_infra_protocols
    import tests.unit.test_infra_reporting_core as _tests_unit_test_infra_reporting_core
    from tests.unit.test_infra_protocols import TestFlextInfraProtocolsImport

    test_infra_reporting_core = _tests_unit_test_infra_reporting_core
    import tests.unit.test_infra_reporting_extra as _tests_unit_test_infra_reporting_extra
    from tests.unit.test_infra_reporting_core import TestFlextInfraReportingServiceCore

    test_infra_reporting_extra = _tests_unit_test_infra_reporting_extra
    import tests.unit.test_infra_selection as _tests_unit_test_infra_selection
    from tests.unit.test_infra_reporting_extra import (
        TestFlextInfraReportingServiceExtra,
    )

    test_infra_selection = _tests_unit_test_infra_selection
    import tests.unit.test_infra_subprocess_core as _tests_unit_test_infra_subprocess_core
    from tests.unit.test_infra_selection import TestFlextInfraUtilitiesSelection

    test_infra_subprocess_core = _tests_unit_test_infra_subprocess_core
    import tests.unit.test_infra_subprocess_extra as _tests_unit_test_infra_subprocess_extra
    from tests.unit.test_infra_subprocess_core import (
        runner,
        test_capture_cases,
        test_run_cases,
        test_run_raw_cases,
    )

    test_infra_subprocess_extra = _tests_unit_test_infra_subprocess_extra
    import tests.unit.test_infra_typings as _tests_unit_test_infra_typings
    from tests.unit.test_infra_subprocess_extra import TestFlextInfraCommandRunnerExtra

    test_infra_typings = _tests_unit_test_infra_typings
    import tests.unit.test_infra_utilities as _tests_unit_test_infra_utilities
    from tests.unit.test_infra_typings import TestFlextInfraTypesImport

    test_infra_utilities = _tests_unit_test_infra_utilities
    import tests.unit.test_infra_version_core as _tests_unit_test_infra_version_core
    from tests.unit.test_infra_utilities import TestFlextInfraUtilitiesImport

    test_infra_version_core = _tests_unit_test_infra_version_core
    import tests.unit.test_infra_version_extra as _tests_unit_test_infra_version_extra
    from tests.unit.test_infra_version_core import TestFlextInfraVersionClass

    test_infra_version_extra = _tests_unit_test_infra_version_extra
    import tests.unit.test_infra_versioning as _tests_unit_test_infra_versioning
    from tests.unit.test_infra_version_extra import (
        TestFlextInfraVersionModuleLevel,
        TestFlextInfraVersionPackageInfo,
    )

    test_infra_versioning = _tests_unit_test_infra_versioning
    import tests.unit.test_infra_workspace_cli as _tests_unit_test_infra_workspace_cli
    from tests.unit.test_infra_versioning import (
        service,
        test_bump_version_invalid,
        test_bump_version_result_type,
        test_bump_version_valid,
        test_current_workspace_version,
        test_parse_semver_invalid,
        test_parse_semver_result_type,
        test_parse_semver_valid,
        test_replace_project_version,
    )

    test_infra_workspace_cli = _tests_unit_test_infra_workspace_cli
    import tests.unit.test_infra_workspace_detector as _tests_unit_test_infra_workspace_detector
    from tests.unit.test_infra_workspace_cli import (
        test_workspace_cli_accepts_default_dry_run_for_detect,
        test_workspace_cli_migrate_command,
        test_workspace_cli_migrate_output_contains_summary,
    )

    test_infra_workspace_detector = _tests_unit_test_infra_workspace_detector
    import tests.unit.test_infra_workspace_init as _tests_unit_test_infra_workspace_init
    from tests.unit.test_infra_workspace_detector import (
        TestDetectorBasicDetection,
        TestDetectorGitRunScenarios,
        TestDetectorRepoNameExtraction,
        detector,
    )

    test_infra_workspace_init = _tests_unit_test_infra_workspace_init
    import tests.unit.test_infra_workspace_main as _tests_unit_test_infra_workspace_main
    from tests.unit.test_infra_workspace_init import TestFlextInfraWorkspace

    test_infra_workspace_main = _tests_unit_test_infra_workspace_main
    import tests.unit.test_infra_workspace_migrator as _tests_unit_test_infra_workspace_migrator
    from tests.unit.test_infra_workspace_main import (
        TestMainCli,
        TestRunDetect,
        TestRunMigrate,
        TestRunOrchestrate,
        TestRunSync,
        workspace_main,
    )

    test_infra_workspace_migrator = _tests_unit_test_infra_workspace_migrator
    import tests.unit.test_infra_workspace_migrator_deps as _tests_unit_test_infra_workspace_migrator_deps
    from tests.unit.test_infra_workspace_migrator import (
        test_migrator_apply_updates_project_files,
        test_migrator_discovery_failure,
        test_migrator_dry_run_reports_changes_without_writes,
        test_migrator_execute_returns_failure,
        test_migrator_handles_missing_pyproject_gracefully,
        test_migrator_no_changes_needed,
        test_migrator_preserves_custom_makefile_content,
        test_migrator_workspace_root_not_exists,
        test_migrator_workspace_root_project_detection,
    )

    test_infra_workspace_migrator_deps = _tests_unit_test_infra_workspace_migrator_deps
    import tests.unit.test_infra_workspace_migrator_dryrun as _tests_unit_test_infra_workspace_migrator_dryrun
    from tests.unit.test_infra_workspace_migrator_deps import (
        test_migrate_makefile_not_found_non_dry_run,
        test_migrate_pyproject_flext_core_non_dry_run,
        test_migrator_has_flext_core_dependency_in_poetry,
        test_migrator_has_flext_core_dependency_poetry_deps_not_table,
        test_migrator_has_flext_core_dependency_poetry_table_missing,
        test_workspace_migrator_error_handling_on_invalid_workspace,
        test_workspace_migrator_makefile_not_found_dry_run,
        test_workspace_migrator_makefile_read_error,
        test_workspace_migrator_pyproject_write_error,
    )

    test_infra_workspace_migrator_dryrun = (
        _tests_unit_test_infra_workspace_migrator_dryrun
    )
    import tests.unit.test_infra_workspace_migrator_errors as _tests_unit_test_infra_workspace_migrator_errors
    from tests.unit.test_infra_workspace_migrator_dryrun import (
        test_migrator_flext_core_dry_run,
        test_migrator_flext_core_project_skipped,
        test_migrator_gitignore_already_normalized_dry_run,
        test_migrator_makefile_not_found_dry_run,
        test_migrator_makefile_read_failure,
        test_migrator_pyproject_not_found_dry_run,
    )

    test_infra_workspace_migrator_errors = (
        _tests_unit_test_infra_workspace_migrator_errors
    )
    import tests.unit.test_infra_workspace_migrator_internal as _tests_unit_test_infra_workspace_migrator_internal

    test_infra_workspace_migrator_internal = (
        _tests_unit_test_infra_workspace_migrator_internal
    )
    import tests.unit.test_infra_workspace_migrator_pyproject as _tests_unit_test_infra_workspace_migrator_pyproject

    test_infra_workspace_migrator_pyproject = (
        _tests_unit_test_infra_workspace_migrator_pyproject
    )
    import tests.unit.test_infra_workspace_orchestrator as _tests_unit_test_infra_workspace_orchestrator

    test_infra_workspace_orchestrator = _tests_unit_test_infra_workspace_orchestrator
    import tests.unit.test_infra_workspace_sync as _tests_unit_test_infra_workspace_sync
    from tests.unit.test_infra_workspace_orchestrator import (
        TestOrchestratorBasic,
        TestOrchestratorFailures,
        TestOrchestratorGateNormalization,
        orchestrator,
    )

    test_infra_workspace_sync = _tests_unit_test_infra_workspace_sync
    import tests.unit.validate as _tests_unit_validate
    from tests.unit.test_infra_workspace_sync import (
        SetupFn,
        svc,
        test_atomic_write_fail,
        test_atomic_write_ok,
        test_cli_forwards_canonical_root,
        test_cli_result_by_project_root,
        test_gitignore_entry_scenarios,
        test_gitignore_sync_failure,
        test_gitignore_write_failure,
        test_sync_basemk_scenarios,
        test_sync_error_scenarios,
        test_sync_regenerates_project_makefile_without_legacy_passthrough,
        test_sync_root_validation,
        test_sync_success_scenarios,
        test_sync_updates_project_makefile_for_standalone_project,
        test_sync_updates_workspace_makefile_for_workspace_root,
        test_workspace_makefile_generator_declares_canonical_workspace_variables,
        test_workspace_makefile_generator_reuses_mod_and_boot_feedback,
        test_workspace_makefile_generator_sanitizes_orchestrator_env,
    )

    validate = _tests_unit_validate
    from tests.unit.validate import (
        basemk_validator_tests,
        inventory_tests,
        pytest_diag,
        scanner_tests,
        skill_validator_tests,
        stub_chain_tests,
        test_stub_validate_help_returns_zero,
        test_stub_validate_uses_all_flag,
    )

    from flext_core.constants import FlextConstants as c
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.models import FlextModels as m
    from flext_core.protocols import FlextProtocols as p
    from flext_core.result import FlextResult as r
    from flext_core.service import FlextService as s
    from flext_core.typings import FlextTypes as t
    from flext_core.utilities import FlextUtilities as u
_LAZY_IMPORTS = merge_lazy_imports(
    (
        "tests.unit._utilities",
        "tests.unit.basemk",
        "tests.unit.check",
        "tests.unit.codegen",
        "tests.unit.container",
        "tests.unit.deps",
        "tests.unit.discovery",
        "tests.unit.docs",
        "tests.unit.github",
        "tests.unit.io",
        "tests.unit.refactor",
        "tests.unit.release",
        "tests.unit.validate",
    ),
    {
        "SetupFn": "tests.unit.test_infra_workspace_sync",
        "TestDetectorBasicDetection": "tests.unit.test_infra_workspace_detector",
        "TestDetectorGitRunScenarios": "tests.unit.test_infra_workspace_detector",
        "TestDetectorRepoNameExtraction": "tests.unit.test_infra_workspace_detector",
        "TestDiscoverProjects": "tests.unit.test_infra_maintenance_python_version",
        "TestEnforcerExecute": "tests.unit.test_infra_maintenance_python_version",
        "TestEnsurePythonVersionFile": "tests.unit.test_infra_maintenance_python_version",
        "TestFlextInfraCommandRunnerExtra": "tests.unit.test_infra_subprocess_extra",
        "TestFlextInfraConstantsAlias": "tests.unit.test_infra_constants_extra",
        "TestFlextInfraConstantsCheckNamespace": "tests.unit.test_infra_constants_extra",
        "TestFlextInfraConstantsConsistency": "tests.unit.test_infra_constants_extra",
        "TestFlextInfraConstantsEncodingNamespace": "tests.unit.test_infra_constants_extra",
        "TestFlextInfraConstantsExcludedNamespace": "tests.unit.test_infra_constants_core",
        "TestFlextInfraConstantsFilesNamespace": "tests.unit.test_infra_constants_core",
        "TestFlextInfraConstantsGatesNamespace": "tests.unit.test_infra_constants_core",
        "TestFlextInfraConstantsGithubNamespace": "tests.unit.test_infra_constants_extra",
        "TestFlextInfraConstantsImmutability": "tests.unit.test_infra_constants_extra",
        "TestFlextInfraConstantsPathsNamespace": "tests.unit.test_infra_constants_core",
        "TestFlextInfraConstantsStatusNamespace": "tests.unit.test_infra_constants_core",
        "TestFlextInfraGitService": "tests.unit.test_infra_git",
        "TestFlextInfraInitLazyLoading": "tests.unit.test_infra_init_lazy_core",
        "TestFlextInfraMaintenance": "tests.unit.test_infra_maintenance_init",
        "TestFlextInfraPathResolver": "tests.unit.test_infra_paths",
        "TestFlextInfraPatternsEdgeCases": "tests.unit.test_infra_patterns_extra",
        "TestFlextInfraPatternsMarkdown": "tests.unit.test_infra_patterns_core",
        "TestFlextInfraPatternsPatternTypes": "tests.unit.test_infra_patterns_extra",
        "TestFlextInfraPatternsTooling": "tests.unit.test_infra_patterns_core",
        "TestFlextInfraProtocolsImport": "tests.unit.test_infra_protocols",
        "TestFlextInfraReportingServiceCore": "tests.unit.test_infra_reporting_core",
        "TestFlextInfraReportingServiceExtra": "tests.unit.test_infra_reporting_extra",
        "TestFlextInfraSubmoduleInitLazyLoading": "tests.unit.test_infra_init_lazy_submodules",
        "TestFlextInfraTypesImport": "tests.unit.test_infra_typings",
        "TestFlextInfraUtilitiesImport": "tests.unit.test_infra_utilities",
        "TestFlextInfraUtilitiesSelection": "tests.unit.test_infra_selection",
        "TestFlextInfraVersionClass": "tests.unit.test_infra_version_core",
        "TestFlextInfraVersionModuleLevel": "tests.unit.test_infra_version_extra",
        "TestFlextInfraVersionPackageInfo": "tests.unit.test_infra_version_extra",
        "TestFlextInfraWorkspace": "tests.unit.test_infra_workspace_init",
        "TestGitPush": "tests.unit.test_infra_git",
        "TestGitTagOperations": "tests.unit.test_infra_git",
        "TestMainCli": "tests.unit.test_infra_workspace_main",
        "TestMaintenanceMainEnforcer": "tests.unit.test_infra_maintenance_main",
        "TestMaintenanceMainSuccess": "tests.unit.test_infra_maintenance_main",
        "TestOrchestratorBasic": "tests.unit.test_infra_workspace_orchestrator",
        "TestOrchestratorFailures": "tests.unit.test_infra_workspace_orchestrator",
        "TestOrchestratorGateNormalization": "tests.unit.test_infra_workspace_orchestrator",
        "TestReadRequiredMinor": "tests.unit.test_infra_maintenance_python_version",
        "TestRemovedCompatibilityMethods": "tests.unit.test_infra_git",
        "TestRunDetect": "tests.unit.test_infra_workspace_main",
        "TestRunMigrate": "tests.unit.test_infra_workspace_main",
        "TestRunOrchestrate": "tests.unit.test_infra_workspace_main",
        "TestRunSync": "tests.unit.test_infra_workspace_main",
        "TestWorkspaceRoot": "tests.unit.test_infra_maintenance_python_version",
        "_utilities": "tests.unit._utilities",
        "basemk": "tests.unit.basemk",
        "c": ("flext_core.constants", "FlextConstants"),
        "check": "tests.unit.check",
        "codegen": "tests.unit.codegen",
        "container": "tests.unit.container",
        "d": ("flext_core.decorators", "FlextDecorators"),
        "deps": "tests.unit.deps",
        "detector": "tests.unit.test_infra_workspace_detector",
        "discovery": "tests.unit.discovery",
        "docs": "tests.unit.docs",
        "e": ("flext_core.exceptions", "FlextExceptions"),
        "git_repo": "tests.unit.test_infra_git",
        "github": "tests.unit.github",
        "h": ("flext_core.handlers", "FlextHandlers"),
        "io": "tests.unit.io",
        "m": ("flext_core.models", "FlextModels"),
        "main": "tests.unit.test_infra_maintenance_main",
        "orchestrator": "tests.unit.test_infra_workspace_orchestrator",
        "p": ("flext_core.protocols", "FlextProtocols"),
        "r": ("flext_core.result", "FlextResult"),
        "refactor": "tests.unit.refactor",
        "release": "tests.unit.release",
        "runner": "tests.unit.test_infra_subprocess_core",
        "s": ("flext_core.service", "FlextService"),
        "service": "tests.unit.test_infra_versioning",
        "svc": "tests.unit.test_infra_workspace_sync",
        "t": ("flext_core.typings", "FlextTypes"),
        "test_atomic_write_fail": "tests.unit.test_infra_workspace_sync",
        "test_atomic_write_ok": "tests.unit.test_infra_workspace_sync",
        "test_bump_version_invalid": "tests.unit.test_infra_versioning",
        "test_bump_version_result_type": "tests.unit.test_infra_versioning",
        "test_bump_version_valid": "tests.unit.test_infra_versioning",
        "test_capture_cases": "tests.unit.test_infra_subprocess_core",
        "test_cli_forwards_canonical_root": "tests.unit.test_infra_workspace_sync",
        "test_cli_result_by_project_root": "tests.unit.test_infra_workspace_sync",
        "test_current_workspace_version": "tests.unit.test_infra_versioning",
        "test_gitignore_entry_scenarios": "tests.unit.test_infra_workspace_sync",
        "test_gitignore_sync_failure": "tests.unit.test_infra_workspace_sync",
        "test_gitignore_write_failure": "tests.unit.test_infra_workspace_sync",
        "test_infra_constants_core": "tests.unit.test_infra_constants_core",
        "test_infra_constants_extra": "tests.unit.test_infra_constants_extra",
        "test_infra_git": "tests.unit.test_infra_git",
        "test_infra_init_lazy_core": "tests.unit.test_infra_init_lazy_core",
        "test_infra_init_lazy_submodules": "tests.unit.test_infra_init_lazy_submodules",
        "test_infra_main": "tests.unit.test_infra_main",
        "test_infra_maintenance_cli": "tests.unit.test_infra_maintenance_cli",
        "test_infra_maintenance_init": "tests.unit.test_infra_maintenance_init",
        "test_infra_maintenance_main": "tests.unit.test_infra_maintenance_main",
        "test_infra_maintenance_python_version": "tests.unit.test_infra_maintenance_python_version",
        "test_infra_paths": "tests.unit.test_infra_paths",
        "test_infra_patterns_core": "tests.unit.test_infra_patterns_core",
        "test_infra_patterns_extra": "tests.unit.test_infra_patterns_extra",
        "test_infra_protocols": "tests.unit.test_infra_protocols",
        "test_infra_reporting_core": "tests.unit.test_infra_reporting_core",
        "test_infra_reporting_extra": "tests.unit.test_infra_reporting_extra",
        "test_infra_selection": "tests.unit.test_infra_selection",
        "test_infra_subprocess_core": "tests.unit.test_infra_subprocess_core",
        "test_infra_subprocess_extra": "tests.unit.test_infra_subprocess_extra",
        "test_infra_typings": "tests.unit.test_infra_typings",
        "test_infra_utilities": "tests.unit.test_infra_utilities",
        "test_infra_version_core": "tests.unit.test_infra_version_core",
        "test_infra_version_extra": "tests.unit.test_infra_version_extra",
        "test_infra_versioning": "tests.unit.test_infra_versioning",
        "test_infra_workspace_cli": "tests.unit.test_infra_workspace_cli",
        "test_infra_workspace_detector": "tests.unit.test_infra_workspace_detector",
        "test_infra_workspace_init": "tests.unit.test_infra_workspace_init",
        "test_infra_workspace_main": "tests.unit.test_infra_workspace_main",
        "test_infra_workspace_migrator": "tests.unit.test_infra_workspace_migrator",
        "test_infra_workspace_migrator_deps": "tests.unit.test_infra_workspace_migrator_deps",
        "test_infra_workspace_migrator_dryrun": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_infra_workspace_migrator_errors": "tests.unit.test_infra_workspace_migrator_errors",
        "test_infra_workspace_migrator_internal": "tests.unit.test_infra_workspace_migrator_internal",
        "test_infra_workspace_migrator_pyproject": "tests.unit.test_infra_workspace_migrator_pyproject",
        "test_infra_workspace_orchestrator": "tests.unit.test_infra_workspace_orchestrator",
        "test_infra_workspace_sync": "tests.unit.test_infra_workspace_sync",
        "test_main_all_groups_defined": "tests.unit.test_infra_main",
        "test_main_group_descriptions_are_present": "tests.unit.test_infra_main",
        "test_main_help_flag_returns_zero": "tests.unit.test_infra_main",
        "test_main_returns_error_when_no_args": "tests.unit.test_infra_main",
        "test_main_unknown_group_returns_error": "tests.unit.test_infra_main",
        "test_maintenance_rejects_apply_flag": "tests.unit.test_infra_maintenance_cli",
        "test_migrate_makefile_not_found_non_dry_run": "tests.unit.test_infra_workspace_migrator_deps",
        "test_migrate_pyproject_flext_core_non_dry_run": "tests.unit.test_infra_workspace_migrator_deps",
        "test_migrator_apply_updates_project_files": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_discovery_failure": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_dry_run_reports_changes_without_writes": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_execute_returns_failure": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_flext_core_dry_run": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_migrator_flext_core_project_skipped": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_migrator_gitignore_already_normalized_dry_run": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_migrator_handles_missing_pyproject_gracefully": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_has_flext_core_dependency_in_poetry": "tests.unit.test_infra_workspace_migrator_deps",
        "test_migrator_has_flext_core_dependency_poetry_deps_not_table": "tests.unit.test_infra_workspace_migrator_deps",
        "test_migrator_has_flext_core_dependency_poetry_table_missing": "tests.unit.test_infra_workspace_migrator_deps",
        "test_migrator_makefile_not_found_dry_run": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_migrator_makefile_read_failure": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_migrator_no_changes_needed": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_preserves_custom_makefile_content": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_pyproject_not_found_dry_run": "tests.unit.test_infra_workspace_migrator_dryrun",
        "test_migrator_workspace_root_not_exists": "tests.unit.test_infra_workspace_migrator",
        "test_migrator_workspace_root_project_detection": "tests.unit.test_infra_workspace_migrator",
        "test_parse_semver_invalid": "tests.unit.test_infra_versioning",
        "test_parse_semver_result_type": "tests.unit.test_infra_versioning",
        "test_parse_semver_valid": "tests.unit.test_infra_versioning",
        "test_replace_project_version": "tests.unit.test_infra_versioning",
        "test_run_cases": "tests.unit.test_infra_subprocess_core",
        "test_run_raw_cases": "tests.unit.test_infra_subprocess_core",
        "test_sync_basemk_scenarios": "tests.unit.test_infra_workspace_sync",
        "test_sync_error_scenarios": "tests.unit.test_infra_workspace_sync",
        "test_sync_regenerates_project_makefile_without_legacy_passthrough": "tests.unit.test_infra_workspace_sync",
        "test_sync_root_validation": "tests.unit.test_infra_workspace_sync",
        "test_sync_success_scenarios": "tests.unit.test_infra_workspace_sync",
        "test_sync_updates_project_makefile_for_standalone_project": "tests.unit.test_infra_workspace_sync",
        "test_sync_updates_workspace_makefile_for_workspace_root": "tests.unit.test_infra_workspace_sync",
        "test_workspace_cli_accepts_default_dry_run_for_detect": "tests.unit.test_infra_workspace_cli",
        "test_workspace_cli_migrate_command": "tests.unit.test_infra_workspace_cli",
        "test_workspace_cli_migrate_output_contains_summary": "tests.unit.test_infra_workspace_cli",
        "test_workspace_makefile_generator_declares_canonical_workspace_variables": "tests.unit.test_infra_workspace_sync",
        "test_workspace_makefile_generator_reuses_mod_and_boot_feedback": "tests.unit.test_infra_workspace_sync",
        "test_workspace_makefile_generator_sanitizes_orchestrator_env": "tests.unit.test_infra_workspace_sync",
        "test_workspace_migrator_error_handling_on_invalid_workspace": "tests.unit.test_infra_workspace_migrator_deps",
        "test_workspace_migrator_makefile_not_found_dry_run": "tests.unit.test_infra_workspace_migrator_deps",
        "test_workspace_migrator_makefile_read_error": "tests.unit.test_infra_workspace_migrator_deps",
        "test_workspace_migrator_pyproject_write_error": "tests.unit.test_infra_workspace_migrator_deps",
        "u": ("flext_core.utilities", "FlextUtilities"),
        "validate": "tests.unit.validate",
        "workspace_main": "tests.unit.test_infra_workspace_main",
        "x": ("flext_core.mixins", "FlextMixins"),
    },
)
_ = _LAZY_IMPORTS.pop("cleanup_submodule_namespace", None)
_ = _LAZY_IMPORTS.pop("install_lazy_exports", None)
_ = _LAZY_IMPORTS.pop("lazy_getattr", None)
_ = _LAZY_IMPORTS.pop("merge_lazy_imports", None)
_ = _LAZY_IMPORTS.pop("output", None)
_ = _LAZY_IMPORTS.pop("output_reporting", None)

__all__ = [
    "FAMILY_FILE_MAP",
    "FAMILY_SUFFIX_MAP",
    "EngineSafetyStub",
    "FakeReporting",
    "FakeSelection",
    "FakeSubprocess",
    "FakeUtilsNamespace",
    "FakeVersioning",
    "FlextInfraCodegenTestProjectFactory",
    "GateClass",
    "RunProjectsMock",
    "SampleModel",
    "SetupFn",
    "Spy",
    "StubCommandOutput",
    "StubJsonIo",
    "StubLinter",
    "StubPrManager",
    "StubProjectInfo",
    "StubReporting",
    "StubRunner",
    "StubSelector",
    "StubSyncer",
    "StubTemplates",
    "StubUtilities",
    "StubVersioning",
    "StubWorkspaceManager",
    "TestAdrHelpers",
    "TestAllDirectoriesScanned",
    "TestAuditorBrokenLinks",
    "TestAuditorCore",
    "TestAuditorForbiddenTerms",
    "TestAuditorMainCli",
    "TestAuditorNormalize",
    "TestAuditorScope",
    "TestAuditorScopeFailure",
    "TestAuditorToMarkdown",
    "TestBuildProjectReport",
    "TestBuildScopes",
    "TestBuildSiblingExportIndex",
    "TestBuildTargets",
    "TestBuilderCore",
    "TestBuilderScope",
    "TestBumpNextDev",
    "TestCheckIssueFormatted",
    "TestCheckMainEntryPoint",
    "TestCheckOnlyMode",
    "TestCheckProjectRunners",
    "TestClassifyIssues",
    "TestCollectChanges",
    "TestCollectInternalDeps",
    "TestCollectInternalDepsEdgeCases",
    "TestCollectMarkdownFiles",
    "TestConfigFixerEnsureProjectExcludes",
    "TestConfigFixerExecute",
    "TestConfigFixerFindPyprojectFiles",
    "TestConfigFixerFixSearchPaths",
    "TestConfigFixerPathResolution",
    "TestConfigFixerProcessFile",
    "TestConfigFixerRemoveIgnoreSubConfig",
    "TestConfigFixerRun",
    "TestConfigFixerRunMethods",
    "TestConfigFixerRunWithVerbose",
    "TestConfigFixerToArray",
    "TestConsolidateGroupsPhase",
    "TestConstants",
    "TestCreateBranches",
    "TestCreateTag",
    "TestDetectMode",
    "TestDetectionUncoveredLines",
    "TestDetectorBasicDetection",
    "TestDetectorGitRunScenarios",
    "TestDetectorRepoNameExtraction",
    "TestDetectorReportFlags",
    "TestDetectorRunFailures",
    "TestDiscoverProjects",
    "TestDiscoveryDiscoverProjects",
    "TestDiscoveryFindAllPyprojectFiles",
    "TestDiscoveryIterPythonFiles",
    "TestDiscoveryProjectRoots",
    "TestDispatchPhase",
    "TestEdgeCases",
    "TestEnforcerExecute",
    "TestEnsureCheckout",
    "TestEnsureCheckoutEdgeCases",
    "TestEnsureCoverageConfigPhase",
    "TestEnsureFormattingToolingPhase",
    "TestEnsureMypyConfigPhase",
    "TestEnsureNamespaceToolingPhase",
    "TestEnsurePydanticMypyConfigPhase",
    "TestEnsurePyreflyConfigPhase",
    "TestEnsurePyrightConfigPhase",
    "TestEnsurePytestConfigPhase",
    "TestEnsurePythonVersionFile",
    "TestEnsureRuffConfigPhase",
    "TestEnsureSymlink",
    "TestEnsureSymlinkEdgeCases",
    "TestErrorReporting",
    "TestExcludedDirectories",
    "TestExtractExports",
    "TestExtractVersionExports",
    "TestFixPyrelfyCLI",
    "TestFixerCore",
    "TestFixerProcessFile",
    "TestFixerScope",
    "TestFixerToc",
    "TestFlextInfraBaseMk",
    "TestFlextInfraCheck",
    "TestFlextInfraCodegenLazyInit",
    "TestFlextInfraCommandRunnerExtra",
    "TestFlextInfraConfigFixer",
    "TestFlextInfraConstantsAlias",
    "TestFlextInfraConstantsCheckNamespace",
    "TestFlextInfraConstantsConsistency",
    "TestFlextInfraConstantsEncodingNamespace",
    "TestFlextInfraConstantsExcludedNamespace",
    "TestFlextInfraConstantsFilesNamespace",
    "TestFlextInfraConstantsGatesNamespace",
    "TestFlextInfraConstantsGithubNamespace",
    "TestFlextInfraConstantsImmutability",
    "TestFlextInfraConstantsPathsNamespace",
    "TestFlextInfraConstantsStatusNamespace",
    "TestFlextInfraDependencyDetectionModels",
    "TestFlextInfraDependencyDetectionService",
    "TestFlextInfraDependencyDetectorModels",
    "TestFlextInfraDependencyPathSync",
    "TestFlextInfraDeps",
    "TestFlextInfraDiscoveryServiceUncoveredLines",
    "TestFlextInfraDocScope",
    "TestFlextInfraDocs",
    "TestFlextInfraExtraPathsManager",
    "TestFlextInfraGitService",
    "TestFlextInfraInitLazyLoading",
    "TestFlextInfraInternalDependencySyncService",
    "TestFlextInfraJsonService",
    "TestFlextInfraMaintenance",
    "TestFlextInfraPathResolver",
    "TestFlextInfraPatternsEdgeCases",
    "TestFlextInfraPatternsMarkdown",
    "TestFlextInfraPatternsPatternTypes",
    "TestFlextInfraPatternsTooling",
    "TestFlextInfraProtocolsImport",
    "TestFlextInfraPyprojectModernizer",
    "TestFlextInfraReportingServiceCore",
    "TestFlextInfraReportingServiceExtra",
    "TestFlextInfraRuntimeDevDependencyDetectorInit",
    "TestFlextInfraRuntimeDevDependencyDetectorRunDetect",
    "TestFlextInfraRuntimeDevDependencyDetectorRunReport",
    "TestFlextInfraRuntimeDevDependencyDetectorRunTypings",
    "TestFlextInfraSubmoduleInitLazyLoading",
    "TestFlextInfraTypesImport",
    "TestFlextInfraUtilitiesImport",
    "TestFlextInfraUtilitiesSelection",
    "TestFlextInfraVersionClass",
    "TestFlextInfraVersionModuleLevel",
    "TestFlextInfraVersionPackageInfo",
    "TestFlextInfraWorkspace",
    "TestFlextInfraWorkspaceChecker",
    "TestFormattingRunRuffFix",
    "TestGenerateFile",
    "TestGenerateNotes",
    "TestGenerateTypeChecking",
    "TestGeneratedClassNamingConvention",
    "TestGeneratedFilesAreValidPython",
    "TestGeneratorCore",
    "TestGeneratorHelpers",
    "TestGeneratorScope",
    "TestGetDepPaths",
    "TestGitPush",
    "TestGitTagOperations",
    "TestGoFmtEmptyLinesInOutput",
    "TestInferOwnerFromOrigin",
    "TestInferPackage",
    "TestInfraContainerFunctions",
    "TestInfraMroPattern",
    "TestInfraServiceRetrieval",
    "TestInjectCommentsPhase",
    "TestIsInternalPathDep",
    "TestIsRelativeTo",
    "TestIsWorkspaceMode",
    "TestIterMarkdownFiles",
    "TestJsonWriteFailure",
    "TestLintAndFormatPublicMethods",
    "TestLoadAuditBudgets",
    "TestLoadDependencyLimits",
    "TestMain",
    "TestMainCli",
    "TestMainDelegation",
    "TestMainEdgeCases",
    "TestMainExceptionHandling",
    "TestMainFunction",
    "TestMainHelpAndErrors",
    "TestMainModuleImport",
    "TestMainReturnValues",
    "TestMainRouting",
    "TestMainSubcommandDispatch",
    "TestMainSysArgvModification",
    "TestMainWithFlags",
    "TestMaintenanceMainEnforcer",
    "TestMaintenanceMainSuccess",
    "TestMarkdownReportEmptyGates",
    "TestMaybeWriteTodo",
    "TestMergeChildExports",
    "TestModernizerEdgeCases",
    "TestModernizerRunAndMain",
    "TestModernizerUncoveredLines",
    "TestModuleAndTypingsFlow",
    "TestMypyEmptyLinesInOutput",
    "TestOrchestratorBasic",
    "TestOrchestratorFailures",
    "TestOrchestratorGateNormalization",
    "TestOwnerFromRemoteUrl",
    "TestParseGitmodules",
    "TestParseRepoMap",
    "TestParser",
    "TestPathDepPathsPep621",
    "TestPathDepPathsPoetry",
    "TestPathSyncEdgeCases",
    "TestPhaseBuild",
    "TestPhasePublish",
    "TestPhaseValidate",
    "TestPhaseVersion",
    "TestPreviousTag",
    "TestProcessDirectory",
    "TestProcessFileReadError",
    "TestProjectResultProperties",
    "TestPushRelease",
    "TestReadDoc",
    "TestReadExistingDocstring",
    "TestReadRequiredMinor",
    "TestReleaseInit",
    "TestReleaseMainFlow",
    "TestReleaseMainParsing",
    "TestReleaseMainTagResolution",
    "TestReleaseMainVersionResolution",
    "TestReleaseOrchestratorExecute",
    "TestRemovedCompatibilityMethods",
    "TestResolveAliases",
    "TestResolveRef",
    "TestResolveVersionInteractive",
    "TestRewriteDepPaths",
    "TestRewritePep621",
    "TestRewritePoetry",
    "TestRuffFormatDuplicateFiles",
    "TestRunAudit",
    "TestRunBandit",
    "TestRunBuild",
    "TestRunCLIExtended",
    "TestRunCommand",
    "TestRunDeptry",
    "TestRunDetect",
    "TestRunFix",
    "TestRunGenerate",
    "TestRunGo",
    "TestRunLint",
    "TestRunMake",
    "TestRunMarkdown",
    "TestRunMigrate",
    "TestRunMypy",
    "TestRunMypyStubHints",
    "TestRunOrchestrate",
    "TestRunPipCheck",
    "TestRunPr",
    "TestRunPrWorkspace",
    "TestRunProjectFixMode",
    "TestRunProjectsBehavior",
    "TestRunProjectsReports",
    "TestRunProjectsValidation",
    "TestRunPyrefly",
    "TestRunPyright",
    "TestRunPyrightArgs",
    "TestRunRuffFix",
    "TestRunRuffFormat",
    "TestRunRuffLint",
    "TestRunSingleProject",
    "TestRunSync",
    "TestRunValidate",
    "TestRunWorkflows",
    "TestSafetyCheckpoint",
    "TestSafetyRollback",
    "TestScanModels",
    "TestScanPublicDefs",
    "TestSelectedProjectNames",
    "TestShouldBubbleUp",
    "TestShouldUseColor",
    "TestShouldUseUnicode",
    "TestSubcommandMapping",
    "TestSync",
    "TestSyncMethodEdgeCases",
    "TestSyncMethodEdgeCasesMore",
    "TestSyncOne",
    "TestSynthesizedRepoMap",
    "TestToInfraValue",
    "TestUpdateChangelog",
    "TestValidateCore",
    "TestValidateGitRefEdgeCases",
    "TestValidateReport",
    "TestValidateScope",
    "TestVersionFiles",
    "TestWorkspaceCheckCLI",
    "TestWorkspaceCheckerBuildGateResult",
    "TestWorkspaceCheckerCollectMarkdownFiles",
    "TestWorkspaceCheckerDirsWithPy",
    "TestWorkspaceCheckerErrorSummary",
    "TestWorkspaceCheckerExecute",
    "TestWorkspaceCheckerExistingCheckDirs",
    "TestWorkspaceCheckerInitOSError",
    "TestWorkspaceCheckerInitialization",
    "TestWorkspaceCheckerParseGateCSV",
    "TestWorkspaceCheckerResolveGates",
    "TestWorkspaceCheckerResolveWorkspaceRootFallback",
    "TestWorkspaceCheckerRunBandit",
    "TestWorkspaceCheckerRunCommand",
    "TestWorkspaceCheckerRunGo",
    "TestWorkspaceCheckerRunMarkdown",
    "TestWorkspaceCheckerRunMypy",
    "TestWorkspaceCheckerRunPyright",
    "TestWorkspaceRoot",
    "TestWorkspaceRootFromEnv",
    "TestWorkspaceRootFromParents",
    "TestWriteJson",
    "TestWriteMarkdown",
    "_utilities",
    "auditor",
    "auditor_budgets_tests",
    "auditor_cli_tests",
    "auditor_links_tests",
    "auditor_scope_tests",
    "auditor_tests",
    "autofix_workspace_tests",
    "basemk",
    "basemk_main",
    "basemk_validator_tests",
    "builder",
    "builder_scope_tests",
    "builder_tests",
    "c",
    "census_models_tests",
    "census_tests",
    "check",
    "cli_tests",
    "codegen",
    "conftest",
    "constants_quality_gate_tests",
    "container",
    "create_check_project_iter_stub",
    "create_check_project_stub",
    "create_checker_project",
    "create_fake_run_projects",
    "create_fake_run_raw",
    "create_gate_context",
    "create_gate_execution",
    "d",
    "deps",
    "detector",
    "discovery",
    "doc",
    "docs",
    "e",
    "extended_cli_entry_tests",
    "extended_config_fixer_errors_tests",
    "extended_config_fixer_tests",
    "extended_error_reporting_tests",
    "extended_gate_bandit_markdown_tests",
    "extended_gate_go_cmd_tests",
    "extended_gate_mypy_pyright_tests",
    "extended_models_tests",
    "extended_project_runners_tests",
    "extended_projects_tests",
    "extended_resolve_gates_tests",
    "extended_run_projects_tests",
    "extended_runners_extra_tests",
    "extended_runners_go_tests",
    "extended_runners_ruff_tests",
    "extended_runners_tests",
    "extended_workspace_init_tests",
    "extract_dep_name",
    "fix_pyrefly_config_tests",
    "fixer",
    "fixer_internals_tests",
    "fixer_tests",
    "flow_tests",
    "gen",
    "generator_internals_tests",
    "generator_tests",
    "git_repo",
    "github",
    "h",
    "init_tests",
    "inventory_tests",
    "io",
    "is_external",
    "lazy_init_generation_tests",
    "lazy_init_helpers_tests",
    "lazy_init_process_tests",
    "lazy_init_service_tests",
    "lazy_init_tests",
    "lazy_init_transforms_tests",
    "m",
    "main",
    "main_cli_tests",
    "main_commands_tests",
    "main_dispatch_tests",
    "main_entry_tests",
    "main_integration_tests",
    "main_tests",
    "make_issue",
    "make_project",
    "manager",
    "normalize_link",
    "orchestrator",
    "orchestrator_git_tests",
    "orchestrator_helpers_tests",
    "orchestrator_phases_tests",
    "orchestrator_publish_tests",
    "orchestrator_tests",
    "p",
    "patch_gate_run",
    "patch_gate_run_sequence",
    "patch_python_dir_detection",
    "pipeline_tests",
    "pyrefly_tests",
    "pyright_content",
    "pytest_diag",
    "r",
    "refactor",
    "refactor_main",
    "release",
    "release_init_tests",
    "rewrite_dep_paths",
    "rope_project",
    "run_command_failure_check",
    "run_gate_check",
    "runner",
    "s",
    "scaffolder_naming_tests",
    "scaffolder_tests",
    "scanner_tests",
    "service",
    "shared_iter_tests",
    "shared_tests",
    "shared_write_tests",
    "should_skip_target",
    "skill_validator_tests",
    "stub_chain_tests",
    "svc",
    "t",
    "test_all_three_capabilities_in_one_pass",
    "test_array",
    "test_as_string_list",
    "test_as_string_list_toml_item",
    "test_atomic_write_fail",
    "test_atomic_write_ok",
    "test_basemk_build_config_with_none",
    "test_basemk_build_config_with_project_name",
    "test_basemk_cli_generate_to_file",
    "test_basemk_cli_generate_to_stdout",
    "test_basemk_engine_execute_calls_render_all",
    "test_basemk_engine_render_all_handles_template_error",
    "test_basemk_engine_render_all_returns_string",
    "test_basemk_engine_render_all_with_valid_config",
    "test_basemk_main_ensures_structlog_configured",
    "test_basemk_main_output_to_stdout",
    "test_basemk_main_rejects_apply_flag",
    "test_basemk_main_with_generate_command",
    "test_basemk_main_with_generation_failure",
    "test_basemk_main_with_help",
    "test_basemk_main_with_invalid_command",
    "test_basemk_main_with_no_command",
    "test_basemk_main_with_none_argv",
    "test_basemk_main_with_output_file",
    "test_basemk_main_with_project_name",
    "test_basemk_main_with_write_failure",
    "test_bump_version_invalid",
    "test_bump_version_result_type",
    "test_bump_version_valid",
    "test_canonical_dev_dependencies",
    "test_capture_cases",
    "test_check_main_executes_real_cli",
    "test_class_reconstructor_reorders_each_contiguous_method_block",
    "test_class_reconstructor_reorders_methods_by_config",
    "test_class_reconstructor_skips_interleaved_non_method_members",
    "test_cli_forwards_canonical_root",
    "test_cli_result_by_project_root",
    "test_codegen_init_getattr_raises_attribute_error",
    "test_consolidate_groups_phase_apply_removes_old_groups",
    "test_consolidate_groups_phase_apply_with_empty_poetry_group",
    "test_converts_multiple_aliases",
    "test_converts_typealias_to_pep695",
    "test_current_workspace_version",
    "test_declared_dependency_names_collects_all_supported_groups",
    "test_dedupe_specs",
    "test_dep_name",
    "test_detect_mode_with_nonexistent_path",
    "test_detect_mode_with_path_object",
    "test_detection_classify",
    "test_detection_deptry",
    "test_detection_discover",
    "test_detection_models",
    "test_detection_pip_check",
    "test_detection_typings",
    "test_detection_typings_flow",
    "test_detection_uncovered",
    "test_detector_detect",
    "test_detector_detect_failures",
    "test_detector_init",
    "test_detector_main",
    "test_detector_models",
    "test_detector_report",
    "test_detector_report_flags",
    "test_detects_attribute_base_class",
    "test_detects_basemodel_in_non_model_file",
    "test_detects_missing_local_composition_base",
    "test_detects_multiple_models",
    "test_detects_only_wrong_alias_in_mixed_import",
    "test_detects_same_project_submodule_alias_import",
    "test_detects_wrong_source_m_import",
    "test_detects_wrong_source_u_import",
    "test_discovery_consolidated",
    "test_engine",
    "test_engine_always_enables_class_nesting_file_rule",
    "test_ensure_future_annotations_after_docstring",
    "test_ensure_future_annotations_moves_existing_import_to_top",
    "test_ensure_pyrefly_config_phase_apply_errors",
    "test_ensure_pyrefly_config_phase_apply_ignore_errors",
    "test_ensure_pyrefly_config_phase_apply_python_version",
    "test_ensure_pyrefly_config_phase_apply_search_path",
    "test_ensure_pyrefly_config_phase_is_idempotent",
    "test_ensure_table",
    "test_extra_paths_manager",
    "test_extra_paths_pep621",
    "test_extra_paths_sync",
    "test_extract_dep_name",
    "test_extract_requirement_name",
    "test_fix_pyrefly_config_main_executes_real_cli_help",
    "test_flext_infra_pyproject_modernizer_find_pyproject_files",
    "test_flext_infra_pyproject_modernizer_process_file_invalid_toml",
    "test_formatting",
    "test_generator",
    "test_generator_edge_cases",
    "test_generator_execute_returns_generated_content",
    "test_generator_fails_for_invalid_make_syntax",
    "test_generator_generate_propagates_render_failure",
    "test_generator_generate_with_basemk_config_object",
    "test_generator_generate_with_dict_config",
    "test_generator_generate_with_invalid_dict_config",
    "test_generator_generate_with_none_config_uses_default",
    "test_generator_initializes_with_custom_engine",
    "test_generator_initializes_with_default_engine",
    "test_generator_normalize_config_with_basemk_config",
    "test_generator_normalize_config_with_dict",
    "test_generator_normalize_config_with_invalid_dict",
    "test_generator_normalize_config_with_none",
    "test_generator_renders_with_config_override",
    "test_generator_validate_generated_output_handles_oserror",
    "test_generator_write_creates_parent_directories",
    "test_generator_write_fails_without_output_or_stream",
    "test_generator_write_handles_file_permission_error",
    "test_generator_write_saves_output_file",
    "test_generator_write_to_file",
    "test_generator_write_to_stream",
    "test_generator_write_to_stream_handles_oserror",
    "test_gitignore_entry_scenarios",
    "test_gitignore_sync_failure",
    "test_gitignore_write_failure",
    "test_helpers_alias_is_reachable_helpers",
    "test_helpers_alias_is_reachable_project_obj",
    "test_import_alias_detector_skips_facade_and_subclass_files",
    "test_import_alias_detector_skips_nested_private_and_as_renames",
    "test_import_alias_detector_skips_private_and_class_imports",
    "test_import_modernizer_adds_c_when_existing_c_is_aliased",
    "test_import_modernizer_does_not_rewrite_function_parameter_shadow",
    "test_import_modernizer_does_not_rewrite_rebound_local_name_usage",
    "test_import_modernizer_partial_import_keeps_unmapped_symbols",
    "test_import_modernizer_partial_import_with_asname_keeps_unmapped_alias",
    "test_import_modernizer_skips_rewrite_when_runtime_alias_shadowed_in_function",
    "test_import_modernizer_skips_when_runtime_alias_name_is_blocked",
    "test_import_modernizer_updates_aliased_symbol_usage",
    "test_infra_constants_core",
    "test_infra_constants_extra",
    "test_infra_container",
    "test_infra_discovery",
    "test_infra_discovery_edge_cases",
    "test_infra_git",
    "test_infra_init_lazy_core",
    "test_infra_init_lazy_submodules",
    "test_infra_json_io",
    "test_infra_main",
    "test_infra_maintenance_cli",
    "test_infra_maintenance_init",
    "test_infra_maintenance_main",
    "test_infra_maintenance_python_version",
    "test_infra_paths",
    "test_infra_patterns_core",
    "test_infra_patterns_extra",
    "test_infra_protocols",
    "test_infra_refactor_class_and_propagation",
    "test_infra_refactor_class_placement",
    "test_infra_refactor_engine",
    "test_infra_refactor_import_modernizer",
    "test_infra_refactor_legacy_and_annotations",
    "test_infra_refactor_mro_completeness",
    "test_infra_refactor_mro_import_rewriter",
    "test_infra_refactor_namespace_aliases",
    "test_infra_refactor_namespace_source",
    "test_infra_refactor_pattern_corrections",
    "test_infra_refactor_project_classifier",
    "test_infra_refactor_safety",
    "test_infra_refactor_typing_unifier",
    "test_infra_reporting_core",
    "test_infra_reporting_extra",
    "test_infra_selection",
    "test_infra_subprocess_core",
    "test_infra_subprocess_extra",
    "test_infra_terminal_detection",
    "test_infra_typings",
    "test_infra_utilities",
    "test_infra_version_core",
    "test_infra_version_extra",
    "test_infra_versioning",
    "test_infra_workspace_cli",
    "test_infra_workspace_detector",
    "test_infra_workspace_init",
    "test_infra_workspace_main",
    "test_infra_workspace_migrator",
    "test_infra_workspace_migrator_deps",
    "test_infra_workspace_migrator_dryrun",
    "test_infra_workspace_migrator_errors",
    "test_infra_workspace_migrator_internal",
    "test_infra_workspace_migrator_pyproject",
    "test_infra_workspace_orchestrator",
    "test_infra_workspace_sync",
    "test_init",
    "test_inject_comments_phase_apply_banner",
    "test_inject_comments_phase_apply_broken_group_section",
    "test_inject_comments_phase_apply_markers",
    "test_inject_comments_phase_apply_with_optional_dependencies_dev",
    "test_inject_comments_phase_deduplicates_family_markers",
    "test_inject_comments_phase_marks_pytest_and_coverage_subtables",
    "test_inject_comments_phase_removes_auto_banner_and_auto_marker",
    "test_inject_comments_phase_repositions_marker_before_section",
    "test_injects_t_import_when_needed",
    "test_internal_sync_discovery",
    "test_internal_sync_discovery_edge",
    "test_internal_sync_main",
    "test_internal_sync_resolve",
    "test_internal_sync_sync",
    "test_internal_sync_sync_edge",
    "test_internal_sync_sync_edge_more",
    "test_internal_sync_update",
    "test_internal_sync_update_checkout_edge",
    "test_internal_sync_validation",
    "test_internal_sync_workspace",
    "test_iteration",
    "test_lazy_import_rule_hoists_import_to_module_level",
    "test_lazy_import_rule_uses_fix_action_for_hoist",
    "test_legacy_import_bypass_collapses_to_primary_import",
    "test_legacy_rule_uses_fix_action_remove_for_aliases",
    "test_legacy_wrapper_forwarding_keywords_is_inlined_as_alias",
    "test_legacy_wrapper_forwarding_varargs_is_inlined_as_alias",
    "test_legacy_wrapper_function_is_inlined_as_alias",
    "test_legacy_wrapper_non_passthrough_is_not_inlined",
    "test_main",
    "test_main_all_groups_defined",
    "test_main_cli",
    "test_main_discovery_failure",
    "test_main_dispatch",
    "test_main_group_descriptions_are_present",
    "test_main_help_flag_returns_zero",
    "test_main_no_changes_needed",
    "test_main_project_invalid_toml",
    "test_main_project_no_name",
    "test_main_project_non_string_name",
    "test_main_project_obj_not_dict_first_loop",
    "test_main_project_obj_not_dict_second_loop",
    "test_main_returns_error_when_no_args",
    "test_main_returns_nonzero_on_unknown",
    "test_main_returns_zero_on_help",
    "test_main_success_modes",
    "test_main_sync_failure",
    "test_main_unknown_group_returns_error",
    "test_main_with_changes_and_dry_run",
    "test_main_with_changes_no_dry_run",
    "test_maintenance_rejects_apply_flag",
    "test_make_boot_works_without_existing_venv_in_workspace_mode",
    "test_make_check_fast_path_check_only_suppresses_fix_writes",
    "test_make_check_file_scope_rejects_unsupported_gates",
    "test_make_check_file_scope_runs_mypy",
    "test_make_check_file_scope_unsets_python_path_env",
    "test_make_check_full_run_forwards_fix_and_tool_args",
    "test_make_check_full_run_unsets_python_path_env",
    "test_make_contract",
    "test_make_help_lists_supported_options",
    "test_migrate_makefile_not_found_non_dry_run",
    "test_migrate_pyproject_flext_core_non_dry_run",
    "test_migrate_workspace_applies_consumer_rewrites",
    "test_migrate_workspace_dry_run_preserves_files",
    "test_migrator_apply_updates_project_files",
    "test_migrator_discovery_failure",
    "test_migrator_dry_run_reports_changes_without_writes",
    "test_migrator_execute_returns_failure",
    "test_migrator_flext_core_dry_run",
    "test_migrator_flext_core_project_skipped",
    "test_migrator_gitignore_already_normalized_dry_run",
    "test_migrator_handles_missing_pyproject_gracefully",
    "test_migrator_has_flext_core_dependency_in_poetry",
    "test_migrator_has_flext_core_dependency_poetry_deps_not_table",
    "test_migrator_has_flext_core_dependency_poetry_table_missing",
    "test_migrator_makefile_not_found_dry_run",
    "test_migrator_makefile_read_failure",
    "test_migrator_no_changes_needed",
    "test_migrator_preserves_custom_makefile_content",
    "test_migrator_pyproject_not_found_dry_run",
    "test_migrator_workspace_root_not_exists",
    "test_migrator_workspace_root_project_detection",
    "test_modernizer_comments",
    "test_modernizer_consolidate",
    "test_modernizer_coverage",
    "test_modernizer_helpers",
    "test_modernizer_main",
    "test_modernizer_main_extra",
    "test_modernizer_mypy",
    "test_modernizer_pyrefly",
    "test_modernizer_pyright",
    "test_modernizer_pytest",
    "test_modernizer_tooling",
    "test_modernizer_workspace",
    "test_namespace_rewriter_keeps_contextual_alias_subset",
    "test_namespace_rewriter_only_rewrites_runtime_alias_imports",
    "test_namespace_rewriter_skips_facade_and_subclass_files",
    "test_namespace_rewriter_skips_nested_private_as_rename_and_duplicates",
    "test_no_duplicate_t_import_when_t_from_project_package",
    "test_non_pydantic_class_not_flagged",
    "test_noop_clean_module",
    "test_parse_semver_invalid",
    "test_parse_semver_result_type",
    "test_parse_semver_valid",
    "test_path_sync_helpers",
    "test_path_sync_init",
    "test_path_sync_main",
    "test_path_sync_main_edges",
    "test_path_sync_main_more",
    "test_path_sync_main_project_obj",
    "test_path_sync_rewrite_deps",
    "test_path_sync_rewrite_pep621",
    "test_path_sync_rewrite_poetry",
    "test_pattern_rule_converts_dict_annotations_to_mapping",
    "test_pattern_rule_keeps_dict_param_when_copy_used",
    "test_pattern_rule_keeps_dict_param_when_subscript_mutated",
    "test_pattern_rule_keeps_type_cast_when_not_nested_object_cast",
    "test_pattern_rule_optionally_converts_return_annotations_to_mapping",
    "test_pattern_rule_removes_configured_redundant_casts",
    "test_pattern_rule_removes_nested_type_object_cast_chain",
    "test_pattern_rule_skips_overload_signatures",
    "test_pr_workspace_accepts_repeated_project_options",
    "test_preserves_annotated_in_function_params",
    "test_preserves_non_matching_unions",
    "test_preserves_override_in_method",
    "test_preserves_protocol_and_runtime_checkable",
    "test_preserves_type_checking_import",
    "test_preserves_typealias_import_when_class_level_usage_exists",
    "test_preserves_used_imports_when_import_precedes_usage",
    "test_preserves_used_typing_imports",
    "test_project_dev_groups",
    "test_project_dev_groups_missing_sections",
    "test_project_without_alias_facade_has_no_violation",
    "test_pyrefly_search_paths_include_workspace_declared_dev_dependencies",
    "test_read_project_metadata_preserves_pep621_dependency_order",
    "test_read_project_metadata_preserves_poetry_dependency_order",
    "test_refactor_census_accepts_apply_before_subcommand",
    "test_refactor_centralize_accepts_apply_before_subcommand",
    "test_refactor_files_skips_non_python_inputs",
    "test_refactor_project_integrates_safety_manager",
    "test_refactor_project_scans_tests_and_scripts_dirs",
    "test_refactor_runtime_alias_imports_accepts_aliases_and_project",
    "test_removes_all_imports_when_none_used_import_first",
    "test_removes_all_unused_typing_imports",
    "test_removes_dead_typealias_import",
    "test_removes_typealias_import_only_when_all_usages_converted",
    "test_removes_unused_preserves_used_when_import_precedes_usage",
    "test_render_all_declares_and_documents_runtime_options",
    "test_render_all_exposes_canonical_public_targets",
    "test_render_all_generates_large_makefile",
    "test_render_all_has_no_scripts_path_references",
    "test_rendered_base_mk_declares_cli_group_roots",
    "test_rendered_base_mk_forwards_canonical_root_in_workspace_preflight",
    "test_replace_project_version",
    "test_replaces_container_union",
    "test_replaces_numeric_union",
    "test_replaces_primitives_union",
    "test_replaces_scalar_union",
    "test_replaces_subset_union_with_none",
    "test_resolve_gates_maps_type_alias",
    "test_rewrite_dep_paths_dry_run",
    "test_rewrite_dep_paths_read_failure",
    "test_rewrite_dep_paths_with_internal_names",
    "test_rewrite_dep_paths_with_no_deps",
    "test_rewrite_pep621_invalid_path_dep_regex",
    "test_rewrite_pep621_no_project_table",
    "test_rewrite_pep621_non_string_item",
    "test_rewrite_poetry_no_poetry_table",
    "test_rewrite_poetry_no_tool_table",
    "test_rewrite_poetry_with_non_dict_value",
    "test_rewriter_adds_missing_base_and_formats",
    "test_rewriter_namespace_source_is_idempotent_with_ruff",
    "test_rewriter_preserves_non_alias_symbols",
    "test_rewriter_splits_mixed_imports_correctly",
    "test_rope_hooks",
    "test_rule_dispatch_fails_on_invalid_pattern_rule_config",
    "test_rule_dispatch_fails_on_unknown_rule_mapping",
    "test_rule_dispatch_keeps_legacy_id_fallback_mapping",
    "test_rule_dispatch_prefers_fix_action_metadata",
    "test_run_cases",
    "test_run_cli_rejects_shared_dry_run_flag",
    "test_run_cli_run_forwards_fix_and_tool_args",
    "test_run_cli_run_returns_one_for_fail",
    "test_run_cli_run_returns_two_for_error",
    "test_run_cli_run_returns_zero_for_pass",
    "test_run_cli_with_fail_fast_flag",
    "test_run_cli_with_multiple_projects",
    "test_run_raw_cases",
    "test_run_rope_post_hooks_applies_mro_migration",
    "test_run_rope_post_hooks_dry_run_is_non_mutating",
    "test_runtime_alias_migrator_merges_local_imports_in_src",
    "test_runtime_alias_migrator_merges_local_imports_in_tests",
    "test_runtime_alias_migrator_skips_unsafe_local_cycle",
    "test_safety",
    "test_scanning",
    "test_signature_propagation_removes_and_adds_keywords",
    "test_signature_propagation_renames_call_keyword",
    "test_skips_definition_files",
    "test_skips_facade_declaration_files",
    "test_skips_import_as_rename",
    "test_skips_init_file",
    "test_skips_models_directory",
    "test_skips_models_file",
    "test_skips_non_alias_symbols",
    "test_skips_non_facade_files",
    "test_skips_private_candidate_classes",
    "test_skips_private_class",
    "test_skips_protected_files",
    "test_skips_r_alias_universal_exception",
    "test_skips_same_project_private_submodule",
    "test_skips_same_project_submodule_class_import",
    "test_skips_settings_file",
    "test_skips_when_candidate_is_already_in_facade_bases",
    "test_string_zero_return_value",
    "test_stub_validate_help_returns_zero",
    "test_stub_validate_uses_all_flag",
    "test_symbol_propagation_keeps_alias_reference_when_asname_used",
    "test_symbol_propagation_renames_import_and_local_references",
    "test_symbol_propagation_updates_mro_base_references",
    "test_sync_basemk_scenarios",
    "test_sync_error_scenarios",
    "test_sync_extra_paths_missing_root_pyproject",
    "test_sync_extra_paths_success_modes",
    "test_sync_extra_paths_sync_failure",
    "test_sync_one_edge_cases",
    "test_sync_regenerates_project_makefile_without_legacy_passthrough",
    "test_sync_root_validation",
    "test_sync_success_scenarios",
    "test_sync_updates_project_makefile_for_standalone_project",
    "test_sync_updates_workspace_makefile_for_workspace_root",
    "test_target_path",
    "test_typealias_conversion_preserves_used_typing_siblings",
    "test_unwrap_item",
    "test_unwrap_item_toml_item",
    "test_workspace_check_main_returns_error_without_projects",
    "test_workspace_cli_accepts_default_dry_run_for_detect",
    "test_workspace_cli_migrate_command",
    "test_workspace_cli_migrate_output_contains_summary",
    "test_workspace_makefile_generator_declares_canonical_workspace_variables",
    "test_workspace_makefile_generator_reuses_mod_and_boot_feedback",
    "test_workspace_makefile_generator_sanitizes_orchestrator_env",
    "test_workspace_migrator_error_handling_on_invalid_workspace",
    "test_workspace_migrator_makefile_not_found_dry_run",
    "test_workspace_migrator_makefile_read_error",
    "test_workspace_migrator_pyproject_write_error",
    "test_workspace_root_doc_construction",
    "test_workspace_root_fallback",
    "u",
    "validate",
    "validator",
    "validator_internals_tests",
    "validator_tests",
    "version_resolution_tests",
    "workspace_check_tests",
    "workspace_main",
    "workspace_root",
    "workspace_tests",
    "x",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
