# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_infra._constants.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".adapters": ("FlextInfraConstantsAdapters",),
    ".base": ("FlextInfraConstantsBase",),
    ".basemk": ("FlextInfraConstantsBasemk",),
    ".census": ("FlextInfraConstantsCensus",),
    ".check": ("FlextInfraConstantsCheck",),
    ".cli": ("FlextInfraConstantsCli",),
    ".cli_routes": (
        "CODEGEN_ROUTES",
        "VALIDATE_ROUTES",
        "WORKSPACE_ROUTES",
    ),
    ".cli_routes_validate_commands": ("VALIDATE_COMMAND_ROUTES",),
    ".codegen": ("FlextInfraConstantsCodegen",),
    ".codegen_detection": ("FlextInfraConstantsCodegenDetection",),
    ".codegen_lazy": ("FlextInfraConstantsCodegenLazy",),
    ".codegen_project": ("FlextInfraConstantsCodegenProject",),
    ".codegen_render_names": ("FlextInfraConstantsCodegenRenderNames",),
    ".deps": ("FlextInfraConstantsDeps",),
    ".detectors": ("FlextInfraConstantsDetectors",),
    ".docs": ("FlextInfraConstantsDocs",),
    ".github": ("FlextInfraConstantsGithub",),
    ".make": ("FlextInfraConstantsMake",),
    ".namespace": ("FlextInfraConstantsNamespace",),
    ".refactor": ("FlextInfraConstantsRefactor",),
    ".release": ("FlextInfraConstantsRelease",),
    ".rope": ("FlextInfraConstantsRope",),
    ".source_code": ("FlextInfraConstantsSourceCode",),
    ".validate": ("FlextInfraConstantsSharedInfra",),
    ".workspace": ("FlextInfraConstantsWorkspace",),
}

LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}
CHILD_MODULE_PATHS: tuple[str, ...] = ()
EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()

PUBLIC_EXPORTS: tuple[str, ...] = (
    "CODEGEN_ROUTES",
    "FlextInfraConstantsAdapters",
    "FlextInfraConstantsBase",
    "FlextInfraConstantsBasemk",
    "FlextInfraConstantsCensus",
    "FlextInfraConstantsCheck",
    "FlextInfraConstantsCli",
    "FlextInfraConstantsCodegen",
    "FlextInfraConstantsCodegenDetection",
    "FlextInfraConstantsCodegenLazy",
    "FlextInfraConstantsCodegenProject",
    "FlextInfraConstantsCodegenRenderNames",
    "FlextInfraConstantsDeps",
    "FlextInfraConstantsDetectors",
    "FlextInfraConstantsDocs",
    "FlextInfraConstantsGithub",
    "FlextInfraConstantsMake",
    "FlextInfraConstantsNamespace",
    "FlextInfraConstantsRefactor",
    "FlextInfraConstantsRelease",
    "FlextInfraConstantsRope",
    "FlextInfraConstantsSharedInfra",
    "FlextInfraConstantsSourceCode",
    "FlextInfraConstantsWorkspace",
    "VALIDATE_COMMAND_ROUTES",
    "VALIDATE_ROUTES",
    "WORKSPACE_ROUTES",
)
