"""Source code and detection constants for flext-infra project.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import re
from typing import Final

from flext_infra import t


class FlextInfraConstantsSourceCode:
    """Source code patterns, exclusion sets, and detection constants."""

    # --- Directory exclusion sets (was: class Excluded) ---
    COMMON_EXCLUDED_DIRS: Final[frozenset[str]] = frozenset({
        ".git",
        ".venv",
        "node_modules",
        "__pycache__",
        "dist",
        "dist-packages",
        "build",
        ".reports",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "site-packages",
        "venv",
    })
    "Common directories to exclude from analysis across all scripts."
    PYTHON_DISCOVERY_SKIP_DIRS: Final[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "legado",
        "vendor",
    }
    "Non-productive roots excluded while discovering Python analyzer surfaces."
    DOC_EXCLUDED_DIRS: Final[frozenset[str]] = COMMON_EXCLUDED_DIRS | {"site"}
    "Directories to exclude when analyzing documentation."
    PYPROJECT_SKIP_DIRS: Final[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".claude.disabled",
        "context_test",
        "rope_ws",
        "tmp_flow_test",
        "tests",
        "examples",
        "legado",
    }
    "Directories to skip when scanning pyproject.toml files."
    CHECK_EXCLUDED_DIRS: Final[frozenset[str]] = COMMON_EXCLUDED_DIRS | {"reports"}
    "Directories to exclude during quality checks."
    ITERATION_EXCLUDED_PARTS: Final[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "dist-packages",
        "site-packages",
        "vendor",
        "venv",
    }
    "Path parts to skip during file iteration (superset of COMMON_EXCLUDED_DIRS)."
    VALIDATION_CLONE_EXCLUDES: Final[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".ropeproject",
        "htmlcov",
    }
    "Directories excluded when cloning a project tree for post-apply validation."

    # --- Encoding (was: class Encoding) ---
    ENCODING_DEFAULT: Final[str] = "utf-8"
    "Default text encoding for file operations."

    # --- Source code template constants and parsing patterns
    # (was: class SourceCode) ---
    TOC_START: Final[str] = "<!-- TOC START -->"
    "Marker for table of contents start."
    TOC_END: Final[str] = "<!-- TOC END -->"
    "Marker for table of contents end."
    GENERATED_HEADER: Final[str] = "<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->"
    "Header for markdown auto-generated content."
    GENERATED_SHELL_HEADER: Final[str] = "# Generated by {source} - DO NOT EDIT\n"
    "Header for shell auto-generated content."
    # NOTE (multi-agent, mro-wkii.17.26.2): generated and handwritten Python
    # modules share one mandatory copyright notice.
    PYTHON_COPYRIGHT_NOTICE: Final[str] = (
        "Copyright (c) 2025 FLEXT Team. All rights reserved.\n"
        "SPDX-License-Identifier: MIT"
    )
    "Canonical copyright notice embedded in Python module docstrings."
    FUTURE_ANNOTATIONS: Final[str] = "from __future__ import annotations"
    "Standard future annotations import line."
    ENCODING_COOKIE_RE: Final[t.RegexPattern] = re.compile(
        r"^[ \t\f]*#.*?coding[:=][ \t]*[-\w.]+"
    )
    "Regex: Python source encoding cookie on a header line."
    IMPORT_RE: Final[t.RegexPattern] = re.compile(r"^import\s+(.+)", re.MULTILINE)
    "Regex: ``import <module>``."
    DEF_CLASS_RE: Final[t.RegexPattern] = re.compile(
        r"^(?:def|async\s+def|class)\s+(\w+)", re.MULTILINE
    )
    "Regex: ``def/async def/class <name>``."
    CLASS_NAME_RE: Final[t.RegexPattern] = re.compile(r"^class\s+(\w+)", re.MULTILINE)
    "Regex: any class definition — captures name only."
    CLASS_WITH_BASES_RE: Final[t.RegexPattern] = re.compile(
        r"^class\s+(\w+)\s*\(([^)]*)\)\s*:", re.MULTILINE
    )
    "Regex: ``class <name>(<bases>):`` — requires parentheses, captures bases."
    ASSIGN_RE: Final[t.RegexPattern] = re.compile(r"^(\w+)\s*(?::.*)?=", re.MULTILINE)
    "Regex: ``<name> [: ...] = ...`` assignment."
    FUNC_PARAM_RE: Final[t.RegexPattern] = re.compile(
        r"^(?:def|async\s+def)\s+\w+\s*\(([^)]*)\)", re.MULTILINE | re.DOTALL
    )
    "Regex: function parameter list."
    BARE_IMPORT_FROM_RE: Final[t.RegexPattern] = re.compile(
        r"^\s*from\s+import\s", re.MULTILINE
    )
    "Regex: malformed ``from import ...`` (missing module)."
    IMPORT_LINE_RE: Final[t.RegexPattern] = re.compile(
        r"^\s*(?:from\s+\S+\s+import\s|import\s)", re.MULTILINE
    )
    "Regex: any import line (from or import)."
    FUTURE_IMPORT_RE: Final[t.RegexPattern] = re.compile(
        r"^\s*from\s+__future__\s+import\s"
    )
    "Regex: future import line."
    FROM_IMPORT_RE: Final[t.RegexPattern] = re.compile(
        r"^\s*from\s+([\w.]+)\s+import\s+(.+?)(?:\s*#.*)?$", re.MULTILINE
    )
    "Regex: from-import with optional trailing comment."
    FROM_IMPORT_BLOCK_RE: Final[t.RegexPattern] = re.compile(
        r"^\s*from\s+([\w.]+)\s+import\s*\((.*?)\)", re.MULTILINE | re.DOTALL
    )
    "Regex: multiline from-import block."
    DOCSTRING_RE: Final[t.RegexPattern] = re.compile(r"""^\s*(?:'''|\"\"\"|\"|')""")
    "Regex: docstring opening (single/triple quote)."
    CONSTANT_NAME_RE: Final[t.RegexPattern] = re.compile(r"^_?[A-Z][A-Z0-9_]*$")
    "Regex: constant name pattern (UPPER_CASE with optional leading underscore)."
    FINAL_ASSIGN_RE: Final[t.RegexPattern] = re.compile(
        r"^(_?[A-Z][A-Z0-9_]*)\s*:\s*(?:Final|typing\.Final)(?:\[.*?\])?\s*=",
        re.MULTILINE,
    )
    "Regex: Final-annotated assignment (captures constant name)."
    DEPRECATED_RE: Final[t.RegexPattern] = re.compile(
        r"^@deprecated.*\n(?:class|def)\s+(\w+).*?(?=\n(?:class |def |@|\Z))",
        re.MULTILINE | re.DOTALL,
    )
    "Regex: @deprecated decorated class/function block."
    REQUIRES_PYTHON_RE: Final[t.RegexPattern] = re.compile(
        r'requires-python\s*=\s*"[>!=]*(\d+)\.(\d+)'
    )
    'Regex: ``requires-python = ">=3.X"`` — captures major and minor.'
    DEPENDENCY_VERSION_OP_RE: Final[t.RegexPattern] = re.compile(r"[<>=!~]")
    "Regex: dependency version operator characters (used to split a name+spec)."

    REGEX_ERROR: Final[type[Exception]] = re.error
    "Centralized alias for ``re.error`` so consumers needn't import ``re``."
    IDENTIFIER_RE: Final[t.RegexPattern] = re.compile(r"\b([A-Za-z_]\w*)\b")
    "Regex: Python identifier — captures the bare name token."
    DECORATOR_RE: Final[t.RegexPattern] = re.compile(r"@\w+")
    "Regex: ``@<name>`` decorator usage."

    DICT_STR_JSONVALUE_RE: Final[t.RegexPattern] = re.compile(
        r"\b(?:dict|Dict)\[str,\s*t\.JsonValue\]"
    )
    "Regex: ``dict[str, t.JsonValue]`` / ``Dict[str, t.JsonValue]`` annotation."
    DICT_GENERIC_RE: Final[t.RegexPattern] = re.compile(r"\b(?:dict|Dict)\[")
    "Regex: opening of any ``dict[...]`` / ``Dict[...]`` annotation."
    ANCHOR_NON_ALNUM_RE: Final[t.RegexPattern] = re.compile(r"[^a-z0-9\s-]")
    "Regex: characters to strip when generating an anchor slug."
    ANCHOR_WHITESPACE_RE: Final[t.RegexPattern] = re.compile(r"\s+")
    "Regex: any run of whitespace (collapsed to single hyphen in anchors)."
    ANCHOR_DASH_COLLAPSE_RE: Final[t.RegexPattern] = re.compile(r"-+")
    "Regex: collapse consecutive hyphens to one in anchor slugs."
    TOC_BLOCK_RE: Final[t.RegexPattern] = re.compile(
        r"<!-- TOC START -->.*?<!-- TOC END -->", re.DOTALL
    )
    "Regex: TOC marker block (start..end), DOTALL."
    DUNDER_ALL_SINGLE_LINE_RE: Final[t.RegexPattern] = re.compile(
        r"^(?P<prefix>__all__(?:\s*:\s*[^\n=]+)?\s*=\s*)\[(?P<body>[^\[\]\n]*)\]",
        re.MULTILINE,
    )
    "Regex: single-line ``__all__ = [...]`` declaration."
    DUNDER_ALL_MULTI_LINE_RE: Final[t.RegexPattern] = re.compile(
        r"^(?P<prefix>__all__(?:\s*:\s*[^\n=]+)?\s*=\s*)\[(?P<body>[^\[\]]*?)\]",
        re.MULTILINE | re.DOTALL,
    )
    "Regex: multi-line ``__all__ = [...]`` declaration (DOTALL body)."
    BLANK_LINE_RUN_RE: Final[t.RegexPattern] = re.compile(r"\n{4,}")
    "Regex: 4+ consecutive newlines — collapsed to triple newline."
    LEGACY_TYPEALIAS_RE: Final[t.RegexPattern] = re.compile(
        r"^(\w+)\s*:\s*TypeAlias\s*=\s*(.+)$", re.MULTILINE
    )
    "Regex: legacy ``X: TypeAlias = expr`` (rewritten to PEP 695 ``type X = ...``)."
    T_IMPORT_RE: Final[t.RegexPattern] = re.compile(
        r"^from\s+\S+\s+import\s+.*\bt\b", re.MULTILINE
    )
    "Regex: any ``from X import ... t ...`` line (canonical t import detector)."
    IMPORT_LINE_ANCHORED_RE: Final[t.RegexPattern] = re.compile(
        r"^(?:from\s+\S+\s+import\s+.+|import\s+.+)$", re.MULTILINE
    )
    "Regex: any anchored import line (used to find the insertion offset)."
    IMPORT_PAREN_CLOSE_RE: Final[t.RegexPattern] = re.compile(r"^\)\s*$", re.MULTILINE)
    "Regex: closing ``)`` of a parenthesized import block, anchored at line start."

    @staticmethod
    def compile_multiline(pattern: str) -> t.RegexPattern:
        """Compile a user-supplied pattern with ``re.MULTILINE`` (centralized)."""
        return re.compile(pattern, re.MULTILINE)

    @staticmethod
    def compile_word(name: str) -> t.RegexPattern:
        r"""Compile ``\b<escaped name>\b`` for word-boundary matching."""
        return re.compile(rf"\b{re.escape(name)}\b")

    @staticmethod
    def compile_bare_reference_rename(name: str) -> t.RegexPattern:
        """Compile a "bare reference" pattern excluding imports/defs/assignments."""
        return re.compile(
            rf"(?<!import\s)(?<!\.)(?<!class\s)(?<!def\s)"
            rf"\b{re.escape(name)}\b"
            rf"(?!\s*=)"
        )

    @staticmethod
    def compile_from_module_rename(old_module: str) -> t.RegexPattern:
        r"""Compile ``(from )<old_module>(\s+import\s)`` for module rename."""
        return re.compile(rf"(from\s+){re.escape(old_module)}(\s+import\s)")

    @staticmethod
    def compile_import_symbol_rename(
        target_module: str, old_name: str
    ) -> t.RegexPattern:
        r"""Compile ``(from <target_module> import .*?)\b<old_name>\b`` rename."""
        return re.compile(
            rf"(from\s+{re.escape(target_module)}\s+import\s+.*?)"
            rf"\b{re.escape(old_name)}\b"
        )

    @staticmethod
    def compile(pattern: str, *, multiline: bool = False) -> t.RegexPattern:
        """Compile an arbitrary pattern (centralized so consumers needn't import re)."""
        return re.compile(pattern, re.MULTILINE if multiline else 0)

    @staticmethod
    def compile_class_base_with_generic(name: str) -> t.RegexPattern:
        r"""Compile ``<escaped name>(?:\[.*\])?`` for class-base + generic match."""
        return re.compile(rf"{re.escape(name)}(?:\[.*\])?")

    @staticmethod
    def compile_keyword_argument(name: str) -> t.RegexPattern:
        r"""Compile ``\b<name>\s*=`` to find a keyword-argument occurrence."""
        return re.compile(rf"\b{re.escape(name)}(\s*=)")

    BARE_ALIAS_LINE_RE: Final[t.RegexPattern] = re.compile(
        r"^([A-Za-z_]\w*)\s*=\s*([A-Za-z_]\w*)\s*$"
    )
    "Regex: ``X = Y`` bare alias on a single stripped line (no leading indent)."

    @staticmethod
    def compile_helper_call_site(name: str) -> t.RegexPattern:
        """Compile a free-call detection regex."""
        return re.compile(rf"(?<!\.)(?<!class\s)(?<!def\s)\b{re.escape(name)}\s*\(")

    @staticmethod
    def compile_function_signature(name: str) -> t.RegexPattern:
        r"""Compile ``def\s+<name>\s*\(([^)]*)\)`` (DOTALL) for signature capture."""
        return re.compile(rf"def\s+{re.escape(name)}\s*\(([^)]*)\)", re.DOTALL)

    @staticmethod
    def compile_class_header_with_bases_for(name: str) -> t.RegexPattern:
        """Compile a multiline class-header capture regex."""
        return re.compile(
            rf"^(\s*class\s+{re.escape(name)})\s*\([^)]*\)\s*:", re.MULTILINE
        )

    FLEXT_CORE_DIRECT_SUBMODULE_RE: Final[t.RegexPattern] = re.compile(
        r"^from\s+(flext_core\.\S+)\s+import"
    )
    (
        "Regex: ``from flext_core.<sub> import`` direct-submodule import "
        "(captures full path)."
    )

    @staticmethod
    def escape(literal: str) -> str:
        """Escape ``literal`` for inclusion in a regex (centralized re.escape)."""
        return re.escape(literal)

    @staticmethod
    def compile_from_module_paren_open(module_name: str) -> t.RegexPattern:
        """Compile a parenthesized-import detection regex."""
        return re.compile(rf"^from\s+{re.escape(module_name)}\s+import\s+\(")

    @staticmethod
    def compile_from_module_import_line(module_name: str) -> t.RegexPattern:
        """Compile a multiline whole-import replacement regex."""
        return re.compile(
            rf"^from\s+{re.escape(module_name)}\s+import\s+.+$", re.MULTILINE
        )

    @staticmethod
    def compile_class_header_match(class_name: str) -> t.RegexPattern:
        r"""Compile ``^class <class_name>\b`` for header equality check."""
        return re.compile(rf"^class\s+{re.escape(class_name)}\b")

    @staticmethod
    def compile_class_header_search(class_name: str) -> t.RegexPattern:
        r"""Compile ``^class <class_name>\b`` (MULTILINE) for full-source search."""
        return re.compile(rf"^class\s+{re.escape(class_name)}\b", re.MULTILINE)

    @staticmethod
    def compile_attr_access(name: str) -> t.RegexPattern:
        r"""Compile ``\b<name>\.(\w+)`` for one-level attribute access detection."""
        return re.compile(rf"\b{re.escape(name)}\.(\w+)")

    @staticmethod
    def compile_double_attr_access(name: str) -> t.RegexPattern:
        r"""Compile ``\b<name>\.(\w+)\.(\w+)`` for two-level attribute access."""
        return re.compile(rf"\b{re.escape(name)}\.(\w+)\.(\w+)")

    @staticmethod
    def compile_from_import_paren_open(module_name: str) -> t.RegexPattern:
        """Compile an unanchored parenthesized-import regex."""
        return re.compile(rf"from\s+{re.escape(module_name)}\s+import\s*\(")

    FROM_IMPORT_CAPTURE_PAREN_OPEN_RE: Final[t.RegexPattern] = re.compile(
        r"from\s+([\w.]+)\s+import\s*\("
    )
    "Regex: ``from <module> import (`` capturing the module name."

    @staticmethod
    def compile_mro_import_rewrite(module_name: str, old_symbol: str) -> t.RegexPattern:
        r"""Compile ``(from <module> import )(\b<old>\b)`` — captures both groups."""
        return re.compile(
            rf"(from\s+{re.escape(module_name)}\s+import\s+)"
            rf"(\b{re.escape(old_symbol)}\b)"
        )

    @staticmethod
    def compile_mro_bare_qualify(old_symbol: str) -> t.RegexPattern:
        """Compile the MRO propagator bare-symbol qualification regex."""
        escaped = re.escape(old_symbol)
        return re.compile(
            rf"(?<!class\s)(?<!def\s)(?<!\.)(?<!import\s)"
            rf"\b{escaped}\b"
            rf"(?!\s*[=:](?!=))(?!\s*\()"
        )

    @staticmethod
    def compile_mro_prefixed_annotation(prefix: str, old_symbol: str) -> t.RegexPattern:
        """Compile an annotation-prefixed qualification regex."""
        escaped_prefix = re.escape(prefix)
        return re.compile(rf"({escaped_prefix}[ \t]*)\b{re.escape(old_symbol)}\b")

    @staticmethod
    def compile_import_namespace_rewrite(old_name: str) -> t.RegexPattern:
        """Compile a namespace-import rewrite regex."""
        return re.compile(
            rf"(from\s+\S+\s+import\s+(?:.*?,\s*)?)"
            rf"\b{re.escape(old_name)}\b"
            rf"((?:\s*,.*)?)"
        )

    @staticmethod
    def compile_import_alias_finder(old_name: str) -> t.RegexPattern:
        """Compile an alias-binding finder regex."""
        return re.compile(
            rf"from\s+\S+\s+import\s+[^\n]*\b{re.escape(old_name)}\b\s+as\s+"
            rf"([A-Za-z_]\w*)"
        )

    @staticmethod
    def compile_bare_qualify_allowing_call(old_name: str) -> t.RegexPattern:
        """Compile bare-symbol qualification while allowing call sites."""
        escaped = re.escape(old_name)
        return re.compile(
            rf"(?<!class\s)(?<!def\s)(?<!\.)(?<!import\s)"
            rf"\b{escaped}\b"
            rf"(?!\s*[=:](?!=))"
        )

    @staticmethod
    def compile_alias_qualify(alias_name: str) -> t.RegexPattern:
        """Compile a bare-alias qualification regex."""
        escaped = re.escape(alias_name)
        return re.compile(
            rf"(?<!class\s)(?<!def\s)(?<!\.)(?<!import\s)(?<!as\s)"
            rf"\b{escaped}\b"
            rf"(?!\s*[=:](?!=))"
        )

    @staticmethod
    def compile_assign_or_annotation_start(name: str) -> t.RegexPattern:
        """Compile a line-start annotation or assignment regex."""
        return re.compile(rf"^{re.escape(name)}\s*(:|==?)\s*")

    @staticmethod
    def compile_facade_alias_assignment(
        family_alias: str, class_suffix: str
    ) -> t.RegexPattern:
        """Compile a multiline facade-alias detection regex."""
        return re.compile(
            rf"^{re.escape(family_alias)}\s*=\s*([A-Za-z_]\w*{re.escape(class_suffix)})\b",
            re.MULTILINE,
        )

    @staticmethod
    def compile_class_with_suffix(class_suffix: str) -> t.RegexPattern:
        """Compile a multiline suffixed-class header regex."""
        return re.compile(
            rf"^class\s+([A-Za-z_]\w*{re.escape(class_suffix)})\b", re.MULTILINE
        )

    @staticmethod
    def compile_class_header_with_bases(name: str) -> t.RegexPattern:
        """Compile a class-bases capture regex."""
        return re.compile(
            rf"^class\s+{re.escape(name)}(?:\[[^\]]+\])?\s*\((?P<bases>.*)\)\s*:"
        )

    @staticmethod
    def compile_attribute_qualify(old_name: str) -> t.RegexPattern:
        r"""Compile ``(\w+)\.\b<old>\b`` to qualify attribute-style references."""
        return re.compile(rf"(\w+)\.\b{re.escape(old_name)}\b")

    @staticmethod
    def compile_function_def_block(name: str) -> t.RegexPattern:
        """Compile a regex matching the full def block of ``name`` (with decorators)."""
        return re.compile(
            rf"^((?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"def\s+{re.escape(name)}\s*\([^)]*\)[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*)",
            re.MULTILINE,
        )

    @staticmethod
    def compile_class_def_block(name: str) -> t.RegexPattern:
        """Compile a regex matching a decorated class block for ``name``."""
        return re.compile(
            rf"^((?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"class\s+{re.escape(name)}\b[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*)",
            re.MULTILINE,
        )

    @staticmethod
    def compile_function_def_remove(name: str) -> t.RegexPattern:
        """Compile a function-block removal regex without an outer capture."""
        return re.compile(
            rf"^(?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"def\s+{re.escape(name)}\s*\([^)]*\)[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*",
            re.MULTILINE,
        )

    @staticmethod
    def compile_class_def_remove(name: str) -> t.RegexPattern:
        """Compile a class-block removal regex without an outer capture."""
        return re.compile(
            rf"^(?:@\w[\w.]*(?:\([^)]*\))?\n)*"
            rf"class\s+{re.escape(name)}\b[^\n]*\n"
            rf"(?:(?:[ \t]+[^\n]*|[ \t]*)\n)*",
            re.MULTILINE,
        )

    # --- Single-line patterns shared across consumers ---
    CLASS_HEADER_ANY_RE: Final[t.RegexPattern] = re.compile(r"^class\s+\w+")
    "Regex: any class header at start of line (no MULTILINE — matches single line)."
    DUNDER_ALL_DECL_RE: Final[t.RegexPattern] = re.compile(r"^__all__\s*:")
    "Regex: ``__all__: ...`` declaration line."
    MODULE_ALIAS_RE: Final[t.RegexPattern] = re.compile(
        r"^([A-Za-z_]\w*)\s*=\s*([A-Za-z_]\w*)\s*$"
    )
    "Regex: module-level ``X = Y`` identity-alias line."
    MODULE_ASSIGNMENT_RE: Final[t.RegexPattern] = re.compile(
        r"^([A-Za-z_]\w*)\s*(?::\s*[^=]+)?=\s*(.+)$"
    )
    "Regex: module-level ``X [: T] = value`` assignment (captures name, value)."
    CAST_CALL_RE: Final[t.RegexPattern] = re.compile(
        r"\bcast\s*\(\s*[^,]+\s*,\s*([^)]+)\s*\)"
    )
    "Regex: ``cast(Type, value)`` call — captures the value to retain."
    AS_KEYWORD_RE: Final[t.RegexPattern] = re.compile(r"\s+as\s+")
    "Regex: ``<sp>as<sp>`` keyword for splitting import-as forms."
    FROM_IMPORT_SIMPLE_RE: Final[t.RegexPattern] = re.compile(
        r"^from\s+([\w.]+)\s+import\s+(.+?)$", re.MULTILINE
    )
    "Regex: simple from-import line (no trailing-comment strip)."
    FROM_IMPORT_LINE_TRIM_RE: Final[t.RegexPattern] = re.compile(
        r"from\s+([\w.]+)\s+import\s+(.+?)(?:\s*#.*)?$"
    )
    "Regex: from-import line with optional trailing comment (no anchor)."

    # --- Pytest log parsing patterns ---
    PYTEST_SLOWEST_HEADER_RE: Final[t.RegexPattern] = re.compile(
        r"^=+ slowest durations =+"
    )
    "Regex: pytest 'slowest durations' section header."
    PYTEST_SECTION_DIVIDER_RE: Final[t.RegexPattern] = re.compile(r"^=+")
    "Regex: pytest section divider line (``===...``)."
    PYTEST_WARNINGS_HEADER_RE: Final[t.RegexPattern] = re.compile(
        r"^=+ warnings summary =+"
    )
    "Regex: pytest 'warnings summary' section header."
    PYTEST_DOCS_FOOTER_RE: Final[t.RegexPattern] = re.compile(
        r"^-- Docs: https://docs.pytest.org/"
    )
    "Regex: pytest warnings-section docs footer."
    PYTEST_KNOWN_WARNINGS_RE: Final[t.RegexPattern] = re.compile(
        r"CoverageWarning|PytestCollectionWarning|DeprecationWarning|UserWarning|RuntimeWarning"
    )
    "Regex: known pytest warning class names."
    PYTEST_FAILED_LINE_RE: Final[t.RegexPattern] = re.compile(
        r"(^FAILED |::.* FAILED( |$))"
    )
    "Regex: pytest FAILED status line."
    PYTEST_SKIPPED_LINE_RE: Final[t.RegexPattern] = re.compile(
        r"(^SKIPPED |::.* SKIPPED( |$))"
    )
    "Regex: pytest SKIPPED status line."
    PYTEST_FAILURES_OR_ERRORS_RE: Final[t.RegexPattern] = re.compile(
        r"^=+ (FAILURES|ERRORS) =+"
    )
    "Regex: pytest FAILURES/ERRORS section header."
    PYTEST_BLOCK_END_RE: Final[t.RegexPattern] = re.compile(
        r"^=+ (short test summary info|warnings summary|.+ in [0-9.]+s) =+"
    )
    "Regex: pytest block-end markers (summary/warnings/timing)."

    # mro-r3r8: analyzers cover production; pytest owns executable test validation.
    CHECK_DIRS_SUBPROJECT: Final[t.StrSequence] = ("src",)
    "Productive Python root passed positionally to subproject analyzers."

    GITHUB_REPO_URL: Final[str] = "https://github.com/flext-sh/flext"
    "Official GitHub repository URL for the FLEXT project."
    GITHUB_REPO_NAME: Final[str] = "flext-sh/flext"
    "GitHub repository name in owner/repo format."

    # --- Log parsing constants (was: class LogParser) ---
    LOG_TAIL_LINES: Final[int] = 50
    "Number of tail lines to extract from log output."
    LOG_ERROR_PATTERNS: Final[tuple[t.RegexPattern, ...]] = (
        re.compile(r"^\s*\S+\.py:\d+"),
        re.compile(r"^ERROR:", re.IGNORECASE),
        re.compile(r"^\s+\[B\d+\]"),
        re.compile(r"^FAIL:", re.IGNORECASE),
        re.compile(r"^error:", re.IGNORECASE),
        re.compile(r"^E\s+\w"),
        re.compile(r"^FAILED\s"),
    )
    "Regex patterns for identifying error lines in logs."
    LOG_NOISE_PATTERNS: Final[tuple[t.RegexPattern, ...]] = (
        re.compile(r"^make\["),
        re.compile(r"warning:\s+(overriding|ignoring)"),
        re.compile(r"^(Total|Success|Failed|Skipped):"),
        re.compile(r"^──\s"),
        re.compile(r"^INFO:"),
    )
    "Regex patterns for identifying noise lines in logs."

    # --- Class placement detection (was: class ClassPlacement) ---
    PLACEMENT_PYDANTIC_BASE_NAMES: Final[frozenset[str]] = frozenset({
        "BaseModel",
        "FrozenModel",
        "ArbitraryTypesModel",
        "ContractModel",
        "FrozenValueModel",
        "TimestampedModel",
    })
    "Pydantic model base class names for placement detection."
    PLACEMENT_PROTOCOL_BASE_NAMES: Final[frozenset[str]] = frozenset({"Protocol"})
    "Protocol base class names for placement detection."
    PLACEMENT_ENUM_BASE_NAMES: Final[frozenset[str]] = frozenset({
        "StrEnum",
        "IntEnum",
        "Enum",
    })
    "Enum base class names for placement detection."
    PLACEMENT_UTILITY_NAME_SUFFIXES: Final[frozenset[str]] = frozenset({
        "Utilities",
        "Utility",
    })
    "Class-name suffixes that identify a utility class for placement detection."
    PLACEMENT_CANONICAL_MODEL_FILES: Final[frozenset[str]] = frozenset({"models.py"})
    "Canonical file names where Pydantic models should live."
    PLACEMENT_CANONICAL_PROTOCOL_FILES: Final[frozenset[str]] = frozenset({
        "protocols.py"
    })
    "Canonical file names where Protocol classes should live."
    PLACEMENT_CANONICAL_CONSTANTS_FILES: Final[frozenset[str]] = frozenset({
        "constants.py"
    })
    "Canonical file names where Enum constants should live."
    PLACEMENT_CANONICAL_UTILITY_FILES: Final[frozenset[str]] = frozenset({
        "utilities.py"
    })
    "Canonical file names where utility classes should live."
    PLACEMENT_CANONICAL_MODEL_DIRS: Final[frozenset[str]] = frozenset({
        "_models",
        "models",
    })
    "Canonical directory names where Pydantic models should live."
    PLACEMENT_CANONICAL_PROTOCOL_DIRS: Final[frozenset[str]] = frozenset({"_protocols"})
    "Canonical directory names where Protocol classes should live."
    PLACEMENT_CANONICAL_CONSTANTS_DIRS: Final[frozenset[str]] = frozenset({
        "_constants"
    })
    "Canonical directory names where Enum constants should live."
    PLACEMENT_CANONICAL_UTILITY_DIRS: Final[frozenset[str]] = frozenset({"_utilities"})
    "Canonical directory names where utility classes should live."
    PLACEMENT_CANONICAL_TYPING_FILES: Final[frozenset[str]] = frozenset({"typings.py"})
    "Canonical file names where type aliases should live."
    PLACEMENT_CANONICAL_TYPING_DIRS: Final[frozenset[str]] = frozenset({"_typings"})
    "Canonical directory names where type aliases should live."

    # --- Shared threshold constants (was: class Thresholds) ---
    MIN_UNION_MEMBERS: Final[int] = 2
    "Minimum members for a union type to be normalizable."

    # --- Combined import detection (from + bare import) ---
    COMBINED_IMPORT_RE: Final[t.RegexPattern] = re.compile(
        r"^(?:from\s+([\w.]+)\s+import\s+(.+)|import\s+([\w.]+)(?:\s+as\s+(\w+))?)$",
        re.MULTILINE,
    )
    "Regex: matches both 'from X import Y' and 'import X [as Z]' forms."
    FUNCTION_DEF_SIMPLE_RE: Final[t.RegexPattern] = re.compile(
        r"^def\s+(\w+)\s*\(", re.MULTILINE
    )
    "Regex: simple function definition (def name(), captures name only)."

    # --- Lint output parsing patterns ---
    LINE_COL_RE: Final[t.RegexPattern] = re.compile(r":\d+(?::\d+)?")
    "Regex: line:col or line:col:col reference in lint output."
    CODE_FRAME_RE: Final[t.RegexPattern] = re.compile(r"^\s*\d+\s+\|")
    "Regex: code frame lines (e.g. '  5 | ...' from ruff output)."
    CODE_FRAME_BODY_RE: Final[t.RegexPattern] = re.compile(r"^\s*\|")
    "Regex: code frame continuation lines."
    UNUSED_IMPORT_RE: Final[t.RegexPattern] = re.compile(
        r"`([^`]+)` imported but unused"
    )
    "Regex: ruff F401 unused import message, capturing the import name."
    LINT_SUMMARY_RE: Final[t.RegexPattern] = re.compile(
        r"^(Found \d+ errors?\.|\[\*\] \d+ fixable .*)$"
    )
    "Regex: ruff summary line (Found N errors / N fixable)."

    # --- Semantic versioning (was: class Versioning) ---
    SEMVER_PROJECT_SECTION: Final[str] = "[project]"
    "TOML section header for project metadata."
    SEMVER_RE: Final[t.RegexPattern] = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:-dev)?$")
    "Regex pattern for parsing semantic version strings."
    # --- Reporting paths (was: class Reporting) ---
    REPORTS_DIR_NAME: Final[str] = ".reports"
    "Standard directory name for report output."


__all__: list[str] = ["FlextInfraConstantsSourceCode"]
