"""Source code and detection constants for flext-infra project.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, ClassVar

if TYPE_CHECKING:
    from flext_infra import t


class FlextInfraConstantsSourceCode:
    """Source code patterns, exclusion sets, and detection constants."""

    MERGE_CONFLICT_CONTROLS: ClassVar[t.VariadicTuple[t.Pair[str, str]]] = (
        ("current", "<<<<<<< "),
        ("ancestor", "||||||| "),
        ("separator", "======="),
        ("incoming", ">>>>>>> "),
    )
    "Git merge-control kinds and their immutable protocol tokens."
    TOML_MULTILINE_QUOTE_LENGTH: ClassVar[int] = 3
    "Length of the multiline string delimiter in the TOML protocol."
    TOML_SECTION_HEADER_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^\s*\[\[?([^\[\]]+)\]\]?\s*(?:#.*)?$",
    )
    "Regex: one complete TOML table header with an optional comment."

    # --- Directory exclusion sets (was: class Excluded) ---
    COMMON_EXCLUDED_DIRS: ClassVar[frozenset[str]] = frozenset({
        ".git",
        ".agents-sync-home",
        ".test-tmp",
        ".venv",
        ".worktrees",
        "node_modules",
        "__pycache__",
        "dist",
        "dist-packages",
        "build",
        ".reports",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "site-packages",
        "venv",
    })
    "Common directories to exclude from analysis across all scripts."
    PYTHON_DISCOVERY_SKIP_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "vendor",
    }
    "Non-productive roots excluded while discovering Python analyzer surfaces."
    DOC_EXCLUDED_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "crg-reports",
        "incoming",
        "legado",
        "site",
    }
    "Live docs exclude generated sites and immutable or historical evidence roots."
    PYPROJECT_SKIP_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".claude.disabled",
        "context_test",
        "rope_ws",
        "tmp_flow_test",
        "tests",
        "examples",
        "legado",
    }
    "Directories to skip when scanning pyproject.toml files."
    CHECK_EXCLUDED_DIRS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".archive",
        ".claude",
        ".codex",
        ".cursor",
        ".gemini",
        ".opencode",
        ".beads",
        "reports",
        ".agents",
        # Runtime tool state (Serena memories, Kilo plans): regenerated caches,
        # never governed source — excluded from every quality-check surface.
        ".serena",
        ".kilo",
        ".omo",
        ".tmp",
        ".snapshots",
        ".benchmarks",
        ".hypothesis",
        ".vscode",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".pyrefly_cache",
        "htmlcov",
        "legado",
        "site",
        "target",
    }
    "Directories to exclude during quality checks."
    GITHUB_AGENT_PROJECTION_DIRS: ClassVar[frozenset[str]] = frozenset({
        "agents",
        "hooks",
        "instructions",
        "skills",
    })
    "GitHub provider directories owned by the agentsctl projection."
    ITERATION_EXCLUDED_PARTS: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        "dist-packages",
        "site-packages",
        "vendor",
        "venv",
    }
    "Path parts to skip during file iteration (superset of COMMON_EXCLUDED_DIRS)."
    TRANSIENT_PYTEST_SCRATCH_PART: ClassVar[t.RegexPattern] = re.compile(
        r"^\.flext-.+\.pytest-scratch\.",
    )
    "Transient per-run pytest basetemp directories the runners create inside"
    " the repository; analyzers must never descend into them."
    VALIDATION_CLONE_EXCLUDES: ClassVar[frozenset[str]] = COMMON_EXCLUDED_DIRS | {
        ".archive",
        ".ropeproject",
        "htmlcov",
    }
    "Directories excluded when cloning a project tree for post-apply validation."
    WORKTREE_TRANSACTION_EXCLUDED_DIRS: ClassVar[frozenset[str]] = (
        COMMON_EXCLUDED_DIRS | {".pyrefly_cache", ".cache"}
    )
    "Cache directories excluded from isolated worktree transaction deltas."

    # --- Encoding (was: class Encoding) ---
    ENCODING_DEFAULT: ClassVar[str] = "utf-8"
    "Default text encoding for file operations."

    # --- Source code template constants/parsing patterns (was: class SourceCode) ---
    TOC_START: ClassVar[str] = "<!-- TOC START -->"
    "Marker for table of contents start."
    TOC_END: ClassVar[str] = "<!-- TOC END -->"
    "Marker for table of contents end."
    GENERATED_HEADER: ClassVar[str] = "<!-- AUTO-GENERATED — DO NOT EDIT MANUALLY -->"
    "Header for markdown auto-generated content."
    GENERATED_SHELL_HEADER: ClassVar[str] = "# Generated by {source} - DO NOT EDIT\n"
    "Header for shell auto-generated content."
    FUTURE_ANNOTATIONS: ClassVar[str] = "from __future__ import annotations"
    "Standard future annotations import line."
    RUNTIME_MODEL_BASES: ClassVar[frozenset[str]] = frozenset({
        "BaseModel",
        "BaseSettings",
        "FlextModelsBase",
    })
    "Pydantic bases that resolve class-body annotations at runtime, not statically."
    PROTOCOL_BASE: ClassVar[str] = "Protocol"
    "typing base that must stay last in a protocol class's base list."
    ENCODING_COOKIE_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^[ \t\f]*#.*?coding[:=][ \t]*[-\w.]+",
    )
    "Regex: Python source encoding cookie on a header line."
    CLASS_WITH_BASES_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^class\s+(\w+)\s*\(([^)]*)\)\s*:",
        re.MULTILINE,
    )
    "Regex: ``class <name>(<bases>):`` — requires parentheses, captures bases."
    FROM_IMPORT_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^\s*from\s+([\w.]+)\s+import\s+(.+?)(?:\s*#.*)?$",
        re.MULTILINE,
    )
    "Regex: from-import with optional trailing comment."
    FROM_IMPORT_BLOCK_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^\s*from\s+([\w.]+)\s+import\s*\((.*?)\)",
        re.MULTILINE | re.DOTALL,
    )
    "Regex: multiline from-import block."
    REQUIRES_PYTHON_RE: ClassVar[t.RegexPattern] = re.compile(
        r'requires-python\s*=\s*"[>!=]*(\d+)\.(\d+)',
    )
    'Regex: ``requires-python = ">=3.X"`` — captures major and minor.'
    DEPENDENCY_VERSION_OP_RE: ClassVar[t.RegexPattern] = re.compile(r"[<>=!~]")
    "Regex: dependency version operator characters (used to split a name+spec)."

    REGEX_ERROR: ClassVar[type[Exception]] = re.error
    "Centralized alias for ``re.error`` so consumers needn't import ``re``."

    TOC_BLOCK_RE: ClassVar[t.RegexPattern] = re.compile(
        r"<!-- TOC START -->.*?<!-- TOC END -->",
        re.DOTALL,
    )
    "Regex: TOC marker block (start..end), DOTALL."
    DUNDER_ALL_SINGLE_LINE_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(?P<prefix>__all__(?:\s*:\s*[^\n=]+)?\s*=\s*)\[(?P<body>[^\[\]\n]*)\]",
        re.MULTILINE,
    )
    "Regex: single-line ``__all__ = [...]`` declaration."
    DUNDER_ALL_MULTI_LINE_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(?P<prefix>__all__(?:\s*:\s*[^\n=]+)?\s*=\s*)\[(?P<body>[^\[\]]*?)\]",
        re.MULTILINE | re.DOTALL,
    )
    "Regex: multi-line ``__all__ = [...]`` declaration (DOTALL body)."
    BLANK_LINE_RUN_RE: ClassVar[t.RegexPattern] = re.compile(r"\n{4,}")
    "Regex: 4+ consecutive newlines — collapsed to triple newline."
    LEGACY_TYPEALIAS_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(\w+)\s*:\s*TypeAlias\s*=\s*(.+)$",
        re.MULTILINE,
    )
    "Regex: legacy ``X: TypeAlias = expr`` (rewritten to PEP 695 ``type X = ...``)."

    @staticmethod
    def compile_multiline(pattern: str) -> t.RegexPattern:
        """Compile a user-supplied pattern with ``re.MULTILINE`` (centralized).

        Returns:
            The resulting ``t.RegexPattern``.

        """
        return re.compile(pattern, re.MULTILINE)

    @staticmethod
    def compile(pattern: str, *, multiline: bool = False) -> t.RegexPattern:
        """Compile an arbitrary pattern (centralized so consumers needn't import re).

        Returns:
            The resulting ``t.RegexPattern``.

        """
        return re.compile(pattern, re.MULTILINE if multiline else 0)

    @staticmethod
    def compile_class_base_with_generic(name: str) -> t.RegexPattern:
        r"""Compile ``<escaped name>(?:\[.*\])?`` for class-base + generic match.

        Returns:
            The resulting ``t.RegexPattern``.

        """
        return re.compile(rf"{re.escape(name)}(?:\[.*\])?")

    @staticmethod
    def escape(literal: str) -> str:
        """Escape ``literal`` for inclusion in a regex (centralized re.escape).

        Returns:
            The resulting ``str``.

        """
        return re.escape(literal)

    @staticmethod
    def compile_from_module_paren_open(module_name: str) -> t.RegexPattern:
        """Compile ``^from <module_name> import (`` for parenthesized-import detection.

        Returns:
            The resulting ``t.RegexPattern``.

        """
        return re.compile(rf"^from\s+{re.escape(module_name)}\s+import\s+\(")

    @staticmethod
    def compile_from_module_import_line(module_name: str) -> t.RegexPattern:
        """Compile ``^from <module_name> import .+$`` (MULTILINE) for line replace.

        Returns:
            The resulting ``t.RegexPattern``.

        """
        return re.compile(
            rf"^from\s+{re.escape(module_name)}\s+import\s+.+$",
            re.MULTILINE,
        )

    GITHUB_REPO_URL: ClassVar[str] = "https://github.com/flext-sh/flext"
    "Official GitHub repository URL for the FLEXT project."
    GITHUB_REPO_NAME: ClassVar[str] = "flext-sh/flext"
    "GitHub repository name in owner/repo format."

    # --- Shared threshold constants (was: class Thresholds) ---
    MIN_UNION_MEMBERS: ClassVar[int] = 2
    "Minimum members for a union type to be normalizable."

    # --- Lint output parsing patterns ---
    LINE_COL_RE: ClassVar[t.RegexPattern] = re.compile(r":\d+(?::\d+)?")
    "Regex: line:col or line:col:col reference in lint output."
    CODE_FRAME_RE: ClassVar[t.RegexPattern] = re.compile(r"^\s*\d+\s*[|+-]")
    "Regex: code/suggestion frame lines ('5 | code', '5 + added', '5 - removed')."
    CODE_FRAME_BODY_RE: ClassVar[t.RegexPattern] = re.compile(r"^\s*\|")
    "Regex: code frame continuation lines."
    UNUSED_IMPORT_RE: ClassVar[t.RegexPattern] = re.compile(
        r"`([^`]+)` imported but unused",
    )
    "Regex: ruff F401 unused import message, capturing the import name."
    LINT_SUMMARY_RE: ClassVar[t.RegexPattern] = re.compile(
        r"^(Found \d+ errors?\.|\[\*\] \d+ fixable .*)$",
    )
    "Regex: ruff summary line (Found N errors / N fixable)."

    # --- Semantic versioning (was: class Versioning) ---
    SEMVER_PROJECT_SECTION: ClassVar[str] = "[project]"
    "TOML section header for project metadata."
    # --- Reporting paths (was: class Reporting) ---
    REPORTS_DIR_NAME: ClassVar[str] = ".reports"
    "Standard directory name for report output."


__all__: list[str] = ["FlextInfraConstantsSourceCode"]
