"""Centralized constants for the workspace subpackage.

Copyright (c) 2026 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from enum import StrEnum, unique
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, Literal

from flext_infra._constants import FlextInfraConstantsBase as cb
from flext_infra._constants import FlextInfraConstantsCodegenProject
from flext_infra._constants import FlextInfraConstantsSharedInfra

if TYPE_CHECKING:
    from flext_infra import t


class FlextInfraConstantsWorkspace:
    """Workspace infrastructure constants."""

    @unique
    class BeadIssueStatus(StrEnum):
        """Beads issue status values."""

        OPEN = "open"
        IN_PROGRESS = "in_progress"
        BLOCKED = "blocked"
        DEFERRED = "deferred"
        CLOSED = "closed"

    @unique
    class WorktreeOperation(StrEnum):
        """Private Git worktree primitives composed by the worktree service."""

        LIST = "list"
        ADD = "add"
        UPDATE = "update"
        REMOVE = "remove"

    PERSISTENT_STATE_ARTIFACT_NAMES: ClassVar[frozenset[str]] = frozenset({".serena"})
    "Persistent-state artifact basenames owned by the local repository."

    # NOTE: the .gitignore body is derived from the artifact SSOT
    # (config/codegen.yaml artifacts -> CodegenConfigSpec.gitignore_sections)
    # and written only by codegen conform; the old REQUIRED_GITIGNORE_ENTRIES,
    # GITIGNORE_REMOVE_EXACT and GITIGNORE_MANAGED_HEADER append-paths were
    # removed with the migrator/sync parallel writers.
    WORKTREES_DIRNAME: ClassVar[str] = ".worktrees"
    WORKTREE_NAMESPACE_DIGEST_LENGTH: ClassVar[int] = 12
    VSCODE_DIRNAME: ClassVar[str] = ".vscode"
    VSCODE_SETTINGS_FILENAME: ClassVar[str] = "settings.json"
    VSCODE_PYTHON_ENVS_SEARCH_PATHS_KEY: ClassVar[str] = (
        "python-envs.workspaceSearchPaths"
    )
    CODEGEN_OWNER_VSCODE: ClassVar[str] = "vscode"
    # Canonical VS Code settings content lives in config/codegen.yaml (vscode:).
    # Recursive "**" venv search globs are forbidden: they make the Python
    # Environments locator (pet) walk entire trees and hang discovery.
    MAKEFILE_GENERATED_MARKER: ClassVar[str] = (
        "# @generated by: flext_infra codegen conform"
    )
    "Comment marker inserted into generated Makefiles."
    TEMPLATE_GENERATED_MARKERS: ClassVar[t.StrSequence] = (
        "Generated by flext_infra codegen",
        "@generated by flext_infra codegen",
        "@flext-generated:",
        "Generated by `flext_infra codegen conform`",
    )
    "Canonical and historical ownership markers emitted by project codegen."
    MAKEFILE_CUSTOM_INCLUDE: ClassVar[str] = (
        f"-include {FlextInfraConstantsCodegenProject.CUSTOM_MAKE_FILENAME}"
    )
    "Makefile include for user customization overrides."

    # Workspace environment sync owns .envrc only. Conform is the sole writer
    # of .mise.toml; the old marker remains readable for migration evidence.
    ENVRC_FILENAME: ClassVar[str] = ".envrc"
    ENVRC_LOCAL_RELPATH: ClassVar[str] = ".envrc.local"
    MISE_TOML_FILENAME: ClassVar[str] = ".mise.toml"
    WORKSPACE_ENV_FILES: ClassVar[t.StrSequence] = (ENVRC_FILENAME,)
    WORKSPACE_ENV_GENERATED_MARKERS: ClassVar[t.StrSequence] = (
        "# @generated by: flext_infra workspace sync",
        "# Generated by `flext-infra codegen conform`.",
        "# Generated by `flext_infra codegen conform`.",
    )
    # Local overrides carry operator customization only. Beads activation is a
    # generated property of `.envrc`; any of these tokens here is a second
    # activation owner whose drift already diverged (historical jq conditions
    # differed), so their presence in `.envrc.local` is a contract violation.
    ENVRC_LOCAL_FORBIDDEN_VARS: ClassVar[t.StrSequence] = (
        "AGENTS_GAS_CITY_ROOT",
        "GT_ROOT",
        "GT_TOWN_ROOT",
        "BEADS_DIR",
        "BEADS_DOLT_",
    )
    "Beads activation tokens forbidden in ``.envrc.local`` overrides."
    ENVIRONMENT_DIRECTORY: ClassVar[str] = ".venv"
    "Python environment directory owned by the runtime checkout (D-VENV)."
    ENVIRONMENT_METADATA: ClassVar[str] = "pyvenv.cfg"
    "Interpreter metadata identifying a provisioned virtual environment."
    DISTRIBUTION_DIRECT_URL_FILE: ClassVar[str] = "direct_url.json"
    "PEP 610 installer receipt recording a distribution's direct-reference origin."
    BINDING_RESOLUTION_FILES: ClassVar[t.VariadicTuple[t.StrPair]] = (
        ("--overrides", "overrides.txt"),
        ("--constraints", "constraints.txt"),
    )
    "UV resolution inputs written only inside the consumer environment."
    BINDING_MARKER_SCRIPT: ClassVar[str] = """import json, os, platform, sys
version = sys.implementation.version
implementation_version = '.'.join(str(part) for part in version[:3])
if version.releaselevel != 'final':
    implementation_version += version.releaselevel[0] + str(version.serial)
print(json.dumps({
    'prefix': sys.prefix,
    'implementation_name': sys.implementation.name,
    'implementation_version': implementation_version,
    'os_name': os.name,
    'platform_machine': platform.machine(),
    'platform_release': platform.release(),
    'platform_system': platform.system(),
    'platform_version': platform.version(),
    'platform_python_implementation': platform.python_implementation(),
    'python_full_version': platform.python_version(),
    'python_version': '.'.join(platform.python_version_tuple()[:2]),
    'sys_platform': sys.platform,
}))
"""
    "Standard-library probe for complete PEP 508 marker facts and environment identity."

    SCRATCH_IDENTITY_SEGMENT_ALIASES: ClassVar[t.VariadicTuple[t.StrPair]] = (
        (FlextInfraConstantsSharedInfra.GIT_DIR, "_git"),
    )
    "Checkout path segments renamed when mirrored into the scratch identity."

    PROPAGATION_BRANCH: ClassVar[str] = "propagation/flext-infra"
    "One lane per member carries the workspace's flext-infra projections."
    PROPAGATION_COMMIT_SUBJECT: ClassVar[str] = (
        "chore(infra): propagate the workspace flext-infra"
    )
    PROPAGATION_REPORT_KEY: ClassVar[str] = "propagation"
    "Report directory holding each member lane's pull-request body."

    FLEET_GAPS_ROUTE_NAME: ClassVar[str] = "fleet-gaps"
    "Canonical workspace CLI verb that reports per-repository fleet gaps."
    LIFECYCLE_VERBS: ClassVar[t.StrSequence] = (
        "setup",
        "gen",
        "upg",
        "setup",
        "gen",
        "gen",
    )
    "Fixed serial lifecycle, including the post-upgrade generation fixed point."
    LIFECYCLE_REPORT_RELATIVE_PATH: ClassVar[Path] = (
        Path(cb.REPORTS_DIR_NAME) / "validate-lifecycle.json"
    )
    "Typed receipts for the invoking workspace root and governed members."
    FLEET_GAPS_REPORT_RELATIVE_PATH: ClassVar[Path] = (
        Path(cb.REPORTS_DIR_NAME) / "fleet-gaps.json"
    )
    "Canonical single-file receipt for the latest fleet-gaps report."
    FLEET_GAPS_REPORT_SCHEMA_VERSION: ClassVar[Literal[1]] = 1
    "Exact structured fleet-gaps report schema version."
    AGENTS_DOC_FILENAME: ClassVar[str] = "AGENTS.md"
    "Repository-local governance law file every governed checkout declares."
    SKILLS_STAMP_RELPATH: ClassVar[Path] = (
        Path(".agents") / "skills" / ".flext-stamp.json"
    )
    "Repository-local skills provisioning stamp observed by the gaps report."
    SKILLS_STAMP_DISTRIBUTION_VERSION_KEY: ClassVar[str] = "distribution_version"
    "Stamp field carrying the provisioned skills distribution version."
    BEADS_RUNTIME_CONFIG_RELPATH: ClassVar[Path] = Path(".beads") / "config.yaml"
    "Repository-local Beads runtime identity every participating checkout holds."


__all__: list[str] = ["FlextInfraConstantsWorkspace"]
