"""Centralized constants for the workspace subpackage."""

from __future__ import annotations

from enum import StrEnum, unique
from typing import ClassVar, TYPE_CHECKING

from .codegen_project import FlextInfraConstantsCodegenProject
from .validate import FlextInfraConstantsSharedInfra

if TYPE_CHECKING:
    from flext_infra import t


class FlextInfraConstantsWorkspace:
    """Workspace infrastructure constants."""

    @unique
    class WorktreeOperation(StrEnum):
        """Private Git worktree primitives composed by the work saga."""

        LIST = "list"
        ADD = "add"
        UPDATE = "update"
        REMOVE = "remove"

    @unique
    class WorkOperation(StrEnum):
        """Retained lane metadata operation values."""

        START = "start"
        STATUS = "status"
        LAND = "land"
        FINISH = "finish"

    @unique
    class WorkKind(StrEnum):
        """GitFlow lane kinds owned by configuration policy."""

        EPIC = "epic"
        FEATURE = "feature"
        BUGFIX = "bugfix"
        HOTFIX = "hotfix"
        RELEASE = "release"

    @unique
    class WorkBranchNamespace(StrEnum):
        EPIC = "epic"
        FEATURE = "feature"
        BUGFIX = "bugfix"
        HOTFIX = "hotfix"
        RELEASE = "release"

    @unique
    class WorkLaneRole(StrEnum):
        """Topology role one registered lane holds inside an epic program."""

        PLAIN = "plain"
        EPIC = "epic"
        CHILD = "child"

    @unique
    class WorkProvisioningState(StrEnum):
        """Lifecycle state persisted for one work-lane reservation."""

        PENDING = "pending"
        READY = "ready"
        FAILED = "failed"

    @unique
    class WorkRecoveryCategory(StrEnum):
        """Recovery action supported for a failed work-lane reservation."""

        RETRY_SETUP = "retry-setup"

    @unique
    class WorkProvisioningError(StrEnum):
        """Provisioning stage that failed after lane reservation."""

        SETUP = "setup"

    WORK_FORBIDDEN_SLUGS: ClassVar[frozenset[str]] = frozenset({
        "teste",
        "ajuste",
        "correcao",
        "temp",
        "nova-branch",
    })

    EXTERNAL_WORKSPACE_SIBLING_PATTERNS: ClassVar[t.StrSequence] = (
        ".ai-hub",
        "algar-*",
        "gruponos-*",
    )
    "Sibling directory patterns for FLEXT-managed external workspaces."

    PERSISTENT_STATE_ARTIFACT_NAMES: ClassVar[frozenset[str]] = frozenset({".serena"})
    "Persistent-state artifact basenames owned by the local repository."

    # NOTE (flext-jnm1.2): the .gitignore body is derived from the artifact SSOT
    # (config/codegen.yaml artifacts -> CodegenConfigSpec.gitignore_sections)
    # and written only by codegen conform; the old REQUIRED_GITIGNORE_ENTRIES,
    # GITIGNORE_REMOVE_EXACT and GITIGNORE_MANAGED_HEADER append-paths were
    # removed with the migrator/sync parallel writers.
    WORKTREES_DIRNAME: ClassVar[str] = ".worktrees"
    WORKTREE_NAMESPACE_DIGEST_LENGTH: ClassVar[int] = 12
    VSCODE_DIRNAME: ClassVar[str] = ".vscode"
    VSCODE_SETTINGS_FILENAME: ClassVar[str] = "settings.json"
    VSCODE_PYTHON_ENVS_SEARCH_PATHS_KEY: ClassVar[str] = "python-envs.workspaceSearchPaths"
    CODEGEN_OWNER_VSCODE: ClassVar[str] = "vscode"
    # Canonical VS Code settings content lives in config/codegen.yaml (vscode:).
    # Recursive "**" venv search globs are forbidden: they make the Python
    # Environments locator (pet) walk entire trees and hang discovery.
    MAKEFILE_GENERATED_MARKER: ClassVar[str] = (
        "# @generated by: flext_infra codegen conform"
    )
    "Comment marker inserted into generated Makefiles."
    TEMPLATE_GENERATED_MARKERS: ClassVar[t.StrSequence] = (
        "Generated by flext_infra codegen",
        "@generated by flext_infra codegen",
        "@flext-generated:",
        "Generated by `flext_infra codegen conform`",
    )
    "Canonical and historical ownership markers emitted by project codegen."
    MAKEFILE_CUSTOM_INCLUDE: ClassVar[str] = (
        f"-include {FlextInfraConstantsCodegenProject.CUSTOM_MAKE_FILENAME}"
    )
    "Makefile include for user customization overrides."

    # Workspace environment sync owns .envrc only. Conform is the sole writer
    # of .mise.toml; the old marker remains readable for migration evidence.
    ENVRC_FILENAME: ClassVar[str] = ".envrc"
    ENVRC_LOCAL_RELPATH: ClassVar[str] = ".envrc.local"
    MISE_TOML_FILENAME: ClassVar[str] = ".mise.toml"
    WORKSPACE_ENV_FILES: ClassVar[t.StrSequence] = (ENVRC_FILENAME,)
    WORKSPACE_ENV_GENERATED_MARKERS: ClassVar[t.StrSequence] = (
        "# @generated by: flext_infra workspace sync",
        "# Generated by `flext-infra codegen conform`.",
        "# Generated by `flext_infra codegen conform`.",
    )
    # Scratch mirrors the absolute checkout path below the home scratch root. A
    # checkout nested in a VCS directory (submodule worktrees under
    # .git/modules) reproduced that directory in the mirror, so every process
    # whose TMPDIR lived there discovered a config-less repository.
    SCRATCH_IDENTITY_SEGMENT_ALIASES: ClassVar[t.VariadicTuple[t.StrPair]] = (
        (FlextInfraConstantsSharedInfra.GIT_DIR, "_git"),
    )
    "Checkout path segments renamed when mirrored into the scratch identity."


__all__: list[str] = ["FlextInfraConstantsWorkspace"]
